### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by BurningTheSky** [clinton-hall/nzbToMedia#1008]
I recently changed Sonarr to run under the local user account rather than a privileged one and I am now getting this error in the script. Any idea what's causing it?

[08:20:57] [INFO]::MAIN: Loading config from [/Users/user/SABnzbd/scripts/nzbToMedia/autoProcessMedia.cfg]
[08:20:57] [INFO]::MAIN: Checking database structure...
[08:20:57] [INFO]::MAIN: Checking if git needs an update
[08:20:59] [INFO]::MAIN: There is a newer version available  (you're 29 commits behind)
[08:20:59] [INFO]::MAIN: Auto-Updating nzbToMedia, Please wait ...
[08:21:02] [ERROR]::MAIN: Update wasn't successful, not restarting. Check your log for more information.
[08:21:02] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Darwin 15.4.0)
[08:21:02] [WARNING]::MAIN: Failed to locate 7zip. Transcosing of disk images and extraction of .7z files will not be possible!
[08:21:02] [INFO]::MAIN: #########################################################
[08:21:02] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[08:21:02] [INFO]::MAIN: #########################################################
[08:21:02] [INFO]::MAIN: Script triggered from SABnzbd
Traceback (most recent call last):
  File "/Users/user/SABnzbd/scripts/nzbToMedia/nzbToNzbDrone.py", line 236, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/Users/user/SABnzbd/scripts/nzbToMedia/nzbToMedia.py", line 712, in main
    download_id='')
  File "/Users/user/SABnzbd/scripts/nzbToMedia/nzbToMedia.py", line 522, in process
    download_id = get_nzoid(inputName) 
  File "/Users/user/SABnzbd/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 838, in get_nzoid
    r = requests.get(url, params=params, verify=False, timeout=(30, 120))
  File "/Users/user/SABnzbd/scripts/nzbToMedia/libs/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/user/SABnzbd/scripts/nzbToMedia/libs/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/user/SABnzbd/scripts/nzbToMedia/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/user/SABnzbd/scripts/nzbToMedia/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/Users/user/SABnzbd/scripts/nzbToMedia/libs/requests/adapters.py", line 431, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=9095): Read timed out. (read timeout=120)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x106af8998>> ignored

**Comment by BurningTheSky** [comment]
Could have been due to sab updating and script being out of date, updated and testing now

**Comment by BurningTheSky** [comment]
So the issue has come back, I'm not sure what's causing it but I am having file permission problems on my NAS, could it be linked?

**Comment by clinton-hall** [comment]
what port is SABnzbd running on?

**Comment by BurningTheSky** [comment]
9095

**Comment by clinton-hall** [comment]
Vis http or https?

**Comment by BurningTheSky** [comment]
HTTPS

**Comment by clinton-hall** [comment]
what do you have in autoProcessMedia.cfg
```
[Nzb]
    sabnzbd_host
```

**Comment by clinton-hall** [comment]
try setting this to
`    sabnzbd_host = https://localhost`

**Comment by BurningTheSky** [comment]
That seemed to work, thanks!
