### ISSUE TITLE
transcode failure concat message?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1036]
I've been noticing a lot of this lately specifically with TV shows that are being postproc'ed 

Full log session here https://gist.github.com/mgaulton/9747797c44458fc369240681f79c27ab

[09:45:16] [INFO]::MAIN: Checking for files to be transcoded
[09:45:16] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /home/@send/TV/Elementary/Elementary.-.S04E22.-.480p.WEB.DL.nSD.x264-NhaNc3-Chamele0n.mkv
Traceback (most recent call last):
  File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 807, in <module>
    exit(main(sys.argv))
  File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 719, in main
    download_id='')
  File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 605, in process
    download_id, inputCategory, failureLink)
  File "/opt/Sick-Beard/autoProcessTV/core/autoProcess/autoProcessTV.py", line 196, in processEpisode
    result, newDirName = transcoder.Transcode_directory(dirName)
  File "/opt/Sick-Beard/autoProcessTV/core/transcoder/transcoder.py", line 708, in Transcode_directory
    command = buildCommands(file, newDir, movieName, bitbucket)
  File "/opt/Sick-Beard/autoProcessTV/core/transcoder/transcoder.py", line 422, in buildCommands
    video_cmd.extend(['-vf', 'subtitles=' + inputFile + ":si=" + subloc])
TypeError: cannot concatenate 'str' and 'int' objects
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7fd75818d7e8>> ignored
Elementary S04E16 480p WEB DL nSD x264-NhaNc3-Chamele0nclose

**Comment by clinton-hall** [comment]
please update to latest nightly branch and see if this works.

**Comment by mgaulton** [comment]
Trying that now.
