### ISSUE TITLE
Mysterious failures ( TypeError: 'NoneType' object is not itterable )

### ISSUE THREAD

**Issue by aaronkuchma** [clinton-hall/nzbToMedia#1038]
I have the latest stable version of nzbToMedia.

Sometimes, something goes awry and nzbToMedia dies everywhere.

SAB and Deluge both stop having their items processed, because the script always errors out with the 'NoneType' message.

E.g.

```
2016-05-18 11:11:05 INFO    ::MAIN: #########################################################
2016-05-18 11:11:05 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2016-05-18 11:11:05 INFO    ::MAIN: #########################################################
2016-05-18 11:11:05 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
2016-05-18 11:11:05 INFO    ::MAIN: Searching /home/rt/done/movies for mediafiles to post-process ...
2016-05-18 11:11:05 INFO    ::MAIN: Searching /home/rt/extract/movies for mediafiles to post-process ...
2016-05-18 11:11:05 INFO    ::MAIN: Starting manual run for CouchPotato:movies - Folder:/home/rt/extract/movies/Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:11:05 INFO    ::MAIN: Checking database for download info for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD ...
2016-05-18 11:11:05 INFO    ::MAIN: Unable to locate download info for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD, continuing to try and process this release ...
2016-05-18 11:11:05 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2016-05-18 11:11:05 INFO    ::MAIN: Calling CouchPotato:movies to post-process:Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:11:05 INFO    ::MAIN: Attemping imdbID lookup for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:11:05 INFO    ::MAIN: Searching folder and file names for imdbID ...
2016-05-18 11:11:05 INFO    ::MAIN: Searching IMDB for imdbID ...
2016-05-18 11:11:06 WARNING ::MAIN: Unable to find a imdbID for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:12:39 INFO    ::MAIN: Loading config from [/apps/sabToSick/autoProcessMedia.cfg]
2016-05-18 11:12:39 INFO    ::MAIN: Checking database structure...
2016-05-18 11:12:39 INFO    ::MAIN: Checking if git needs an update
2016-05-18 11:12:39 INFO    ::MAIN: No update needed
2016-05-18 11:12:39 INFO    ::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Linux 3.10.0-327.13.1.el7.x86_64)
2016-05-18 11:12:39 WARNING ::MAIN: Failed to locate ffmpeg. Transcoding disabled!
2016-05-18 11:12:39 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2016-05-18 11:12:39 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2016-05-18 11:12:39 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2016-05-18 11:12:39 INFO    ::MAIN: #########################################################
2016-05-18 11:12:39 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2016-05-18 11:12:39 INFO    ::MAIN: #########################################################
2016-05-18 11:12:39 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
2016-05-18 11:12:39 INFO    ::MAIN: Searching /home/rt/done/movies for mediafiles to post-process ...
2016-05-18 11:12:39 INFO    ::MAIN: Searching /home/rt/extract/movies for mediafiles to post-process ...
2016-05-18 11:12:39 INFO    ::MAIN: Starting manual run for CouchPotato:movies - Folder:/home/rt/extract/movies/Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:12:39 INFO    ::MAIN: Checking database for download info for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD ...
2016-05-18 11:12:40 INFO    ::MAIN: Unable to locate download info for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD, continuing to try and process this release ...
2016-05-18 11:12:40 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2016-05-18 11:12:40 INFO    ::MAIN: Calling CouchPotato:movies to post-process:Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:12:40 INFO    ::MAIN: Attemping imdbID lookup for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:12:40 INFO    ::MAIN: Searching folder and file names for imdbID ...
2016-05-18 11:12:40 INFO    ::MAIN: Searching IMDB for imdbID ...
2016-05-18 11:12:40 WARNING ::MAIN: Unable to find a imdbID for Ghost.in.the.Shell.The.New.Movie.2015.BRRip.XviD
2016-05-18 11:13:35 INFO    ::MAIN: Loading config from [/apps/sabToSick/autoProcessMedia.cfg]
2016-05-18 11:13:35 INFO    ::MAIN: Checking database structure...
2016-05-18 11:13:35 INFO    ::MAIN: Checking if git needs an update
2016-05-18 11:13:35 INFO    ::MAIN: No update needed
2016-05-18 11:13:35 INFO    ::MAIN: nzbToMedia Version:c50957d0b4683a125df039329d8f90df630d4e28 Branch:master (Linux 3.10.0-327.13.1.el7.x86_64)
2016-05-18 11:13:35 WARNING ::MAIN: Failed to locate ffmpeg. Transcoding disabled!
2016-05-18 11:13:35 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2016-05-18 11:13:35 WARNING ::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
2016-05-18 11:13:35 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2016-05-18 11:13:35 INFO    ::MAIN: #########################################################
2016-05-18 11:13:35 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2016-05-18 11:13:35 INFO    ::MAIN: #########################################################
2016-05-18 11:13:35 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
2016-05-18 11:13:35 INFO    ::MAIN: Searching /home/rt/done/movies for mediafiles to post-process ...
2016-05-18 11:13:35 INFO    ::MAIN: Searching /home/rt/extract/movies for mediafiles to post-process ...
2016-05-18 11:13:35 INFO    ::MAIN: Starting manual run for CouchPotato:movies - Folder:/home/rt/done/movies/Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1)
2016-05-18 11:13:35 INFO    ::MAIN: Checking database for download info for Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1) ...
2016-05-18 11:13:35 INFO    ::MAIN: Unable to locate download info for Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1), continuing to try and process this release ...
2016-05-18 11:13:35 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2016-05-18 11:13:35 INFO    ::MAIN: Calling CouchPotato:movies to post-process:Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1)
2016-05-18 11:13:35 INFO    ::MAIN: Attemping imdbID lookup for Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1)
2016-05-18 11:13:35 INFO    ::MAIN: Searching folder and file names for imdbID ...
2016-05-18 11:13:35 INFO    ::MAIN: Searching IMDB for imdbID ...
2016-05-18 11:13:36 WARNING ::MAIN: Unable to find a imdbID for Disney's Snow Buddies 2008 DvdRip (ENG) (lcfc1)
```

When debugging is enabled, it very clearly dies immediately after calling couch potato.

Couch potato logs show:

```
05-18 11:37:08 ERROR [to.core.media._base.media] Media with id "f353b88ede76454285899e27b7977e56" not found
05-18 11:37:09 ERROR [ couchpotato.core.event] Error in event "quality.single", that wasn't caught: 
Traceback (most recent call last): 
    File "/apps/couchpotatoserver/couchpotato/core/event.py", line 15, in runHandler 
        return handler(*args, **kwargs) 
    File "/apps/couchpotatoserver/couchpotato/core/plugins/quality/main.py", line 117, in single
        quality = db.get('quality', identifier, with_doc = True)['doc'] 
    File "/apps/couchpotatoserver/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
         res = f(*args, **kwargs) 
    File "/apps/couchpotatoserver/libs/CodernityDB/database.py", line 944, in get
        raise RecordNotFound("Not found") 
RecordNotFound: Not found encoding=UTF-8 debug=True args=['--daemon', '--data_dir=/apps/data/.couchpotatoserver', '--config_file=/apps/data/.couchpotatoserver/couchpotatoserver_config.ini', '--quiet'] app_dir=/apps/couchpotatoserver data_dir=/apps/data/.couchpotatoserver desktop=None options=Namespace(config_file='/apps/data/.couchpotatoserver/couchpotatoserver_config.ini', console_log=False, daemon=True, data_dir='/apps/data/.couchpotatoserver', debug=False, pid_file='/apps/data/.couchpotatoserver/couchpotato.pid', quiet=True)
```

I renamed ghost in the machine to "Ghost in the Machine (2015).avi" (both directory and file were renamed) and it went on to complain about Disney's Snow Buddies. Of course, it seems to be going down the list based on age of folder, since I didn't see any mention of Ghost in the Machine being processed, so no telling if the rename helps.

Any chance you can help me figure it out? Anything I can do to make debugging easier?

[autoProcessMedia.cfg.zip](https://github.com/clinton-hall/nzbToMedia/files/270829/autoProcessMedia.cfg.zip)

**Comment by clinton-hall** [comment]
Ok. try opening log files in wordpad (not notepad) or some program that can correctly display this without running the log lines together... this is very hard to read as it is.

The errors in CouchPotato are concerning. There are several issues reported around this, but I have not seen if this has been tracked down over at CouchPotato yet.

As far as the script goes the key I see here is that this being run as a manual run and therefore doesn't have a lot of information that should be passed from the downloader, and will try to process an entire directory.
To be able to track this down I really would like to see the log when this is called from the downloader (deluge/sabnzbd)

**Comment by aaronkuchma** [comment]
I can almost confirm its a bad response from couch potato causing problems.

When I shut down couch potato server the script managed to skip the movie
processing and processed TV.

I haven't looked at any code though, so I'm unsure if there are steps after
no response is received from Couch Potato that get skipped.
