### ISSUE TITLE
Couchpotato post processing not working

### ISSUE THREAD

**Issue by kireol** [clinton-hall/nzbToMedia#1071]
Everything was running fine for a few years.  Then I updated.

Ubuntu system.

```
[18:24:33] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder:/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[18:24:33] [INFO]::MAIN: Checking database for download info for Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865) ...
[18:24:33] [INFO]::MAIN: Unable to locate download info for Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865), continuing to try and process this release ...
Traceback (most recent call last):
  File "/home/sabnzbdplus/sabnzbd/scripts/nzbToCouchPotato.py", line 251, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/home/sabnzbdplus/.sabnzbd/scripts/nzbToMedia.py", line 759, in main
    clientAgent = text_type(core.DOWNLOADINFO[0].get('client_agent', ''))
IndexError: list index out of range
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fa1ce898f10>> ignored
```

# nzbToMedia Configuration
# For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki

```
[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 0
    # Set to the full path to the git executable
    git_path = /usr/bin/git
    # GitHUB user for repo
    git_user = kireol
    # GitHUB branch for repo
    git_branch = master
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 1
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 1
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 0
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 0
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 0
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = /usr/bin/ffmpeg
    # Enable/Disable media file checking using ffprobe.
    check_media = 1
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1

[Posix]
    ### Process priority setting for External commands (Extractor and Transcoder) on Posix (Unix/Linux/OSX) systems.
    # Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
    niceness = 0
    # Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
    ionice_class = 0
    # Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
    ionice_classdata = 0

[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movie]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 5050
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
    [[movies]]
        enabled = 1
        apikey = myapikey
        host = localhost
        port = 8082
        ssl = 0
        web_root = ""
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        minSize = 300
        delete_ignored = 0
        remote_path = 0
        watch_dir = /home/sabnzbdplus/Downloads/complete/movies/

[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 0
        host = localhost
        port = 8081
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage to delete all source files after processing.
        delete_on = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 50
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = /home/sabnzbdplus/Downloads/complete/tvshows/

[NzbDrone]
    #### autoProcessing for TV Series
    #### ndCategory - category that gets called for post-processing with NzbDrone
    [[tv]]
        enabled = 0
        apikey = myapikey
        host = localhost
        port = 8989
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        nzbExtractionBy = Downloader
        wait_for = 3
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 50
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if NzbDrone is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = /home/sabnzbdplus/Downloads/complete/tvshows/

[HeadPhones]
    #### autoProcessing for Music
    #### music - category that gets called for post-processing with HP
    [[music]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8181
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        wait_for = 2
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if HeadPhones is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Mylar]
    #### autoProcessing for Comics
    #### comics - category that gets called for post-processing with Mylar
    [[comics]]
        enabled = 0
        host = localhost
        port = 8090
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Mylar is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Gamez]
    #### autoProcessing for Games
    #### games - category that gets called for post-processing with Gamez
    [[games]]
        enabled = 0
        apikey = ""
        host = localhost
        port = 8085
        ###### 
        library = Set to path where you want the processed games to be moved to.
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Gamez is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[Network]
    # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
    # e.g. MountPoints = /volume1/Public/,E:\|/volume2/share/,\\NAS\
    mount_points = ""

[Nzb]
    ###### clientAgent - Supported clients: sabnzbd, nzbget
    clientAgent = sabnzbd
    ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
    sabnzbd_host = http://localhost
    sabnzbd_port = 8080
    sabnzbd_apikey = ""
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
    default_downloadDirectory = ""

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = other
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
    useLink = hard
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = /home/sabnzbdplus/Downloads/complete/
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = /home/sabnzbdplus/Downloads/complete/
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = movies, tvshows
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = pictures, manual
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8090/gui/
    uTorrentUSR = your username
    uTorrentPWD = your password
    ###### Transmission (You must edit this if your using TorrentToMedia.py with Transmission)
    TransmissionHost = http://192.168.1.72:9025/transmission/web/
    TransmissionPort = 9025
    TransmissionUSR = transuser
    TransmissionPWD = transpass
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = your username
    DelugePWD = your password
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 0
    chmodDirectory = 1
    resume = 1
    resumeOnFailure = 1

[Extensions]
    compressedExtensions = .zip, .rar, .7z, .gz, .bz, .tar, .arj, .1, .01, .001
    mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg, .vob, .iso, .m4v, .ts
    audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
    metaExtensions = .nfo, .sub, .srt, .jpg, .gif

[Plex]
    # Only enter these details if you want to update plex library after processing.
    # Do not enter these details if you send the plex notifications from Sickbeard/CouchPotato.
    plex_host = localhost
    plex_port = 32400
    plex_token = myplextoken
    plex_ssl = 0
    # Enter Plex category to section mapping as Category,section and separate each pair with '|'
    # e.g. plex_sections = movie,3|tv,4
    plex_sections = Movies|TV Shows

[Transcoder]
    # getsubs. enable to download subtitles.
    getSubs = 0
    # subLanguages. create a list of languages in the order you want them in your subtitles. 
    subLanguages = eng
    # transcode. enable to use transcoder
    transcode = 0
    ###### duplicate =1 will create a new file. =0 will replace the original
    duplicate = 1
    # concat. joins cd1 cd2 etc into a single video.
    concat = 1
    # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
    ignoreExtensions = .avi, .mkv, .mp4
    # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
    outputFastStart = 0
    # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
    outputQualityPercent = 0
    # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
    outputVideoPath = ""
    # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
    processOutput = 0
    # audioLanguage. set the 3 letter language code you want as your primary audio track.
    audioLanguage = eng
    # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
    allAudioLanguages = 0
    # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
    allSubLanguages = 0
    # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
    embedSubs = 1
    # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
    burnInSubtitle = 0
    # extractSubs. 1 will extract subs from the video file and save these as external srt files.
    extractSubs = 0
    # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
    externalSubDir = ""
    # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
    hwAccel = 0
    # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
    generalOptions = ""
    # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
    # If you want to use your own profile, leave this blank and set the remaining options below.
    # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
    outputDefault = ""
    #### Define custom settings below.
    outputVideoExtension = .mp4
    outputVideoCodec = libx264
    VideoCodecAllow = ""
    outputVideoPreset = medium
    outputVideoResolution = 1920:1080
    outputVideoFramerate = 24
    outputVideoBitrate = 800000
    outputVideoCRF = 19
    outputVideoLevel = 3.1
    outputAudioCodec = ac3
    AudioCodecAllow = ""
    outputAudioChannels = 6
    outputAudioBitrate = 640k
    outputAudioTrack2Codec = libfaac
    AudioCodec2Allow = ""
    outputAudioTrack2Channels = 2
    outputAudioTrack2Bitrate = 128000
    outputAudioOtherCodec = libmp3lame
    AudioOtherCodecAllow = ""
    outputAudioOtherChannels = ""
    outputAudioOtherBitrate = 128000
    outputSubtitleCodec = ""

[WakeOnLan]
    ###### set wake = 1 to send WOL broadcast to the mac and test the server (e.g. xbmc) the host and port specified.
    wake = 0
    host = 192.168.1.37
    port = 80
    mac = 00:01:2e:2D:64:e1

[UserScript]
    #Use user_script for uncategorized downloads
    #Set the categories to use external script.
    #Use "UNCAT" to process non-category downloads, and "ALL" for all defined categories.
    [[UNCAT]]
        #Enable/Disable this subsection category
        enabled = 0
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 192.168.1.37
        #Enable if you are sending commands to a remote server for this category
        remote_path = 0
        #What extension do you want to process? Specify all the extension, or use "ALL" to process all files.
        user_script_mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg
        #Specify the path to your custom script. Use "None" if you wish to link this category, but NOT run any external script.
        user_script_path = /nzbToMedia/userscripts/script.sh
        #Specify the argument(s) passed to script, comma separated in order.
        #for example FP,FN,DN, TN, TL for file path (absolute file name with path), file name, absolute directory name (with path), Torrent Name, Torrent Label/Category.
        #So the result is /media/test/script/script.sh FP FN DN TN TL. Add other arguments as needed eg -f, -r
        user_script_param = FN
        #Set user_script_runOnce = 0 to run for each file, or 1 to only run once (presumably on the entire directory).
        user_script_runOnce = 0
        #Specify the successcodes returned by the user script as a comma separated list. Linux default is 0
        user_script_successCodes = 0
        #Clean after? Note that delay function is used to prevent possible mistake :) Delay is intended as seconds
        user_script_clean = 1
        delay = 120
        #Unique path (directory) created for every download. set 0 to disable.
        unique_path = 1
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""

[ASCII]
    #Set convert =1 if you want to convert any "foreign" characters to ASCII (UTF8) before passing to SB/CP etc. Default is disabled (0).
    convert = 0

[passwords]
    # enter the full path to a text file containing passwords to be used for extraction attempts.
    # In the passwords file, every password should be on a new line
    PassWordFile = ""

[Custom]
    # enter a list (comma separated) of Group Tags you want removed from filenames to help with subtitle matching.
    # e.g remove_group = [rarbag],-NZBgeek
    # be careful if your "group" is a common "real" word. Please report if you have any group replacements that would fall in this category.
    remove_group = ""
```

**Comment by labrys** [comment]
@kireol Are you on master, dev, or nightly?

**Comment by labrys** [comment]
@kireol Fix is in nightly if you wouldn't mind checking it out and letting us know.

**Comment by kireol** [comment]
Yup.  I was on nightly.  I git pulled and it's working now.


While that bug was fixed, none of the movies are processing.  Should I open a new bug?

[07:37:10] [INFO]::MAIN: Checking database for download info for Cell.2016.HDRip.XViD-ETRG ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for Cell.2016.HDRip.XViD-ETRG, continuing to try and process this release ...
[07:37:10] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /home/sabnzbdplus/Downloads/complete/movies/Operator.2015.720p.BluRay.x264.YIFY.cp(tt3849692)
[07:37:10] [INFO]::MAIN: Checking database for download info for Operator.2015.720p.BluRay.x264.YIFY.cp(tt3849692) ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for Operator.2015.720p.BluRay.x264.YIFY.cp(tt3849692), continuing to try and process this release ...
[07:37:10] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /home/sabnzbdplus/Downloads/complete/movies/The Darkness 2016 720p BrRip x264 - CM
[07:37:10] [INFO]::MAIN: Checking database for download info for The Darkness 2016 720p BrRip x264 - CM ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for The Darkness 2016 720p BrRip x264 - CM, continuing to try and process this release ...
[07:37:10] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /home/sabnzbdplus/Downloads/complete/movies/Robocop 2014.720p Web-DL.cp(tt1234721)
[07:37:10] [INFO]::MAIN: Checking database for download info for Robocop 2014.720p Web-DL.cp(tt1234721) ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for Robocop 2014.720p Web-DL.cp(tt1234721), continuing to try and process this release ...
[07:37:10] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /home/sabnzbdplus/Downloads/complete/movies/Hello.My.Name.Is.Doris.2015.Multi.1080p.BluRay.x264-VENUE.cp(tt3766394)
[07:37:10] [INFO]::MAIN: Checking database for download info for Hello.My.Name.Is.Doris.2015.Multi.1080p.BluRay.x264-VENUE.cp(tt3766394) ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for Hello.My.Name.Is.Doris.2015.Multi.1080p.BluRay.x264-VENUE.cp(tt3766394), continuing to try and process this release ...
[07:37:10] [INFO]::MAIN: Starting manual run for CouchPotato:movies - Folder: /home/sabnzbdplus/Downloads/complete/movies/Jaws.The.Revenge.1987.720p.HDTV.x264.DD2.0-FGT
[07:37:10] [INFO]::MAIN: Checking database for download info for Jaws.The.Revenge.1987.720p.HDTV.x264.DD2.0-FGT ...
[07:37:10] [INFO]::MAIN: Unable to locate download info for Jaws.The.Revenge.1987.720p.HDTV.x264.DD2.0-FGT, continuing to try and process this release ...

**Comment by clinton-hall** [comment]
Is that log from a manual run?
Does it print anything to terminal (not shown in logs?)

**Comment by kireol** [comment]
Hi.

Yes, that's from a manual run.  On the nightly build with a fresh git
pull.  It flies through a folder of 131 movies in around 2 seconds, as it's
not doing anything.

Of note, if I check out master, it seems to work.

With master checked out.


[08:25:23] [INFO]::MAIN:
#########################################################
[08:25:23] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[08:25:23] [INFO]::MAIN:
#########################################################
[08:25:23] [DEBUG]::MAIN: Options passed into nzbToMedia:
['/home/sabnzbdplus/sabnzbd/scripts/nzbToCouchPotato.py']
[08:25:23] [WARNING]::MAIN: Invalid number of arguments received from
client, Switching to manual run mode ...
[08:25:23] [INFO]::MAIN: Searching
/home/sabnzbdplus/Downloads/complete/movies/ for mediafiles to post-process
...
[08:25:23] [INFO]::MAIN: Starting manual run for CouchPotato:movies -
Folder:/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:23] [INFO]::MAIN: Checking database for download info for
Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865) ...
[08:25:23] [INFO]::MAIN: Unable to locate download info for
Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865), continuing
to try and process this release ...
[08:25:23] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[08:25:23] [DEBUG]::MAIN: Checking for archives to extract in directory:
/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:23] [INFO]::MAIN: Calling CouchPotato:movies to
post-process:Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:23] [INFO]::MAIN: Attemping imdbID lookup for
Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:23] [INFO]::MAIN: Searching folder and file names for imdbID ...
[08:25:23] [INFO]::MAIN: Found imdbID [tt0084865]
[08:25:23] [DEBUG]::MAIN: Opening URL:
http://localhost:8082/api/ac5b161ae603448da06538ae63142404/media.get with
PARAMS: {'id': 'tt0084865'}
[08:25:23] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet
-print_format json -show_format -show_streams -show_error
/home/sabnzbdplus/.sabnzbd/scripts/tests/test.mp4
[08:25:23] [INFO]::TRANSCODER: Checking
[Victor.Victoria.1982.DVDRip.x264-PHOBOS.mkv] for corruption, please stand
by ...
[08:25:23] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet
-print_format json -show_format -show_streams -show_error
/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)/Victor.Victoria.1982.DVDRip.x264-PHOBOS.mkv
[08:25:24] [INFO]::TRANSCODER: SUCCESS:
[Victor.Victoria.1982.DVDRip.x264-PHOBOS.mkv] has no corruption.
[08:25:24] [DEBUG]::COUCHPOTATO: Opening URL:
http://localhost:8082/api/ac5b161ae603448da06538ae63142404/renamer.scan
with PARAMS: {'media_folder':
'/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)'}
[08:25:24] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for
Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:24] [POSTPROCESS]::COUCHPOTATO: SUCCESS: Finished renamer scan for
folder
/home/sabnzbdplus/Downloads/complete/movies/Victor.Victoria.1982.iNTERNAL.DVDRip.x264-PHOBOS.cp(tt0084865)
[08:25:24] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please
stand by ...
[08:25:24] [DEBUG]::MAIN: Opening URL:
http://localhost:8082/api/ac5b161ae603448da06538ae63142404/media.get with
PARAMS: {'id': 'tt0084865'}
[08:25:44] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please
stand by ...

**Comment by clinton-hall** [comment]
Ok, so the issue here is in the auto detection section. In master the next line is 
    
    MAIN: Auto-detected SECTION:CouchPotato

But in nightly it just moves on to the next download found...
