### ISSUE TITLE
IMDB for imdbID not found

### ISSUE THREAD

**Issue by LennyM8472** [clinton-hall/nzbToMedia#1080]
Hi,

the postprocessing script for couchpotato/sabnzbd was running great for years, but now it seems that the script is unable to find a imbdID (this error appears on every movie now) resulting that the scripts encounters errors.

Below the error and the log.

best regards
Lenny

**script error within sabnzbd**
`Exit(1) Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0xf... <a href="./scriptlog?name=SABnzbd_nzo_85iuWv">`

**nzbToMedia log**
`2016-07-19 17:36:01 INFO    ::MAIN: Loading config from [/share/MD0_DATA/Applications/nzbToMedia/autoProcessMedia.cfg]
2016-07-19 17:36:01 INFO    ::MAIN: Checking database structure...
2016-07-19 17:36:01 INFO    ::MAIN: Checking if git needs an update
2016-07-19 17:36:03 INFO    ::MAIN: No update needed
2016-07-19 17:36:03 INFO    ::MAIN: nzbToMedia Version:2d770510a284fadc6b44628626f5769789086dbb Branch:master (Linux 3.12.6)
2016-07-19 17:36:03 INFO    ::MAIN: #########################################################
2016-07-19 17:36:03 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2016-07-19 17:36:03 INFO    ::MAIN: #########################################################
2016-07-19 17:36:03 INFO    ::MAIN: Script triggered from SABnzbd
2016-07-19 17:36:05 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2016-07-19 17:36:05 INFO    ::MAIN: Calling CouchPotato:movie to post-process:XXX.2015.BDRip.x264-GECKOS.nzb
2016-07-19 17:36:05 INFO    ::MAIN: Attemping imdbID lookup for XXX.2015.BDRip.x264-GECKOS.nzb
2016-07-19 17:36:05 INFO    ::MAIN: Searching folder and file names for imdbID ...
2016-07-19 17:36:05 INFO    ::MAIN: Searching IMDB for imdbID ...
2016-07-19 17:36:05 WARNING ::MAIN: Unable to find a imdbID for XXX.BDRip.x264-GECKOS.nzb`

**Comment by LennyM8472** [comment]
the search for the imdbID looks to work again, might have been an api provider problem.

**Comment by LennyM8472** [comment]
It seems to me that the IMDB-ID lookup works when triggered by couchpotato, but when movie is added to sabnzbd and the script is being run from there the IMDB-ID is never being found and results in the error.

`[08:54:42] [INFO]::MAIN: Loading config from [/share/MD0_DATA/Applications/nzbToMedia/autoProcessMedia.cfg]
[08:54:42] [INFO]::MAIN: Checking database structure...
[08:54:42] [INFO]::MAIN: Checking if git needs an update
[08:54:42] [INFO]::MAIN: No update needed
[08:54:42] [INFO]::MAIN: nzbToMedia Version:2d770510a284fadc6b44628626f5769789086dbb Branch:master (Linux 3.12.6)
[08:54:42] [INFO]::MAIN: #########################################################
[08:54:42] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[08:54:42] [INFO]::MAIN: #########################################################
[08:54:42] [INFO]::MAIN: Script triggered from SABnzbd
[08:54:43] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[08:54:43] [INFO]::MAIN: Calling CouchPotato:movie to post-process:in.the.name.of.ben.hur.2016.bdrip.x264-rusted.nzb
[08:54:43] [INFO]::MAIN: Attemping imdbID lookup for in.the.name.of.ben.hur.2016.bdrip.x264-rusted.nzb
[08:54:43] [INFO]::MAIN: Searching folder and file names for imdbID ...
[08:54:43] [INFO]::MAIN: Searching IMDB for imdbID ...
[08:54:44] [WARNING]::MAIN: Unable to find a imdbID for in.the.name.of.ben.hur.2016.bdrip.x264-rusted.nzb
Traceback (most recent call last):
  File "/share/MD0_DATA/Applications/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/share/MD0_DATA/Applications/nzbToMedia/nzbToMedia.py", line 719, in main
    download_id='')
  File "/share/MD0_DATA/Applications/nzbToMedia/nzbToMedia.py", line 602, in process
    inputCategory, failureLink)
  File "/share/MD0_DATA/Applications/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 138, in process
    release = self.get_release(baseURL, imdbid, download_id)
  File "/share/MD0_DATA/Applications/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 67, in get_release
    for release in releases:
TypeError: 'NoneType' object is not iterable
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0xf61094cc>> ignored`

**Comment by clinton-hall** [comment]
Please test the latest nightly build to see if this now works.
