### ISSUE TITLE
CouchPotato returned the following non-json data

### ISSUE THREAD

**Issue by chadnauman** [clinton-hall/nzbToMedia#1086]
getting the above error when using nzbToMedia script to post-process. Was working and then something went wrong with CP, so reinstalled from scratch and now can't get the two (nzbget and CP to play nice). I've confirmed that the apiKey is correct and it's a single server setup.

here's my log file for the post-process issue.
[_nzblog.txt](https://github.com/clinton-hall/nzbToMedia/files/398159/_nzblog.txt)

System: Ubuntu 14

What else do you need to assist?

Thanks!

**Comment by depasseg** [comment]
I'm seeing this same thing running on Master.

Here's the output from sabnzbd:
`[11:51:08] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[11:51:08] [INFO]::MAIN: Checking database structure...
[11:51:08] [INFO]::MAIN: Checking if git needs an update
[11:51:09] [INFO]::MAIN: No update needed
[11:51:09] [INFO]::MAIN: nzbToMedia Version:2d770510a284fadc6b44628626f5769789086dbb Branch:master (FreeBSD 9.1-RELEASE)
[11:51:09] [ERROR]::MAIN: Failed to connect to Transmission
[11:51:09] [INFO]::MAIN: #########################################################
[11:51:09] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[11:51:09] [INFO]::MAIN: #########################################################
[11:51:09] [INFO]::MAIN: Script triggered from SABnzbd
[11:51:09] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[11:51:09] [INFO]::MAIN: Calling CouchPotato:movie to post-process:taken.blah.blah.blah.cp(tt2446042).nzb
[11:51:09] [INFO]::MAIN: Attemping imdbID lookup for taken.blah.blah.blah.cp(tt2446042).nzb
[11:51:09] [INFO]::MAIN: Searching folder and file names for imdbID ...
[11:51:09] [INFO]::MAIN: Found imdbID [tt2446042]
[11:51:09] [ERROR]::MAIN: CouchPotato returned the following non-json data
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <!doctype html>
[11:51:09] [ERROR]::MAIN: <html class="">
[11:51:09] [ERROR]::MAIN: <head>
[11:51:09] [ERROR]::MAIN: <title>CouchPotato</title>
[11:51:09] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[11:51:09] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes" />
[11:51:09] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes" />
[11:51:09] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-tap-highlight" content="no" />
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <link rel="apple-touch-icon-precomposed" href="/static/images/icons/ios.png" />
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <link rel="icon" type="image/png" href="/static/images/icons/android.png" sizes="192x192">
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-TileColor" content="#ac0000">
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-TileImage" content="/static/images/icons/windows.png">
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-square70x70logo" content="/static/images/icons/windows.png">
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-square150x150logo" content="/static/images/icons/windows.png">
[11:51:09] [ERROR]::MAIN: <meta name="msapplication-square310x310logo" content="/static/images/icons/windows.png">
[11:51:09] [ERROR]::MAIN: <link href="/static/images/icons/favicon.ico" rel="icon" type="image/x-icon" />
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.vendor.min.js?1473165689"></script>
[11:51:09] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.base.min.js?1473165689"></script>
[11:51:09] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.plugins.min.js?1473165689"></script>
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <script type="text/javascript">
[11:51:09] [ERROR]::MAIN: window.addEvent('domready', function() {
[11:51:09] [ERROR]::MAIN: new Uniform();
[11:51:09] [ERROR]::MAIN: Api.setup({
[11:51:09] [ERROR]::MAIN: 'url': "/api/01a67c20d3b84b148865223b698dac74/",
[11:51:09] [ERROR]::MAIN: 'path_sep': "/",
[11:51:09] [ERROR]::MAIN: 'is_remote': false
[11:51:09] [ERROR]::MAIN: });
[11:51:09] [ERROR]::MAIN: $(document.body).set('data-api', window.location.protocol + '//' + window.location.host + Api.createUrl().replace('/default/', '/'));
[11:51:09] [ERROR]::MAIN: // Catch errors
[11:51:09] [ERROR]::MAIN: var dev = false;
[11:51:09] [ERROR]::MAIN: if(!dev){
[11:51:09] [ERROR]::MAIN: window.onerror = function(message, file, line){
[11:51:09] [ERROR]::MAIN: p(message, file, line);
[11:51:09] [ERROR]::MAIN: Api.request('logging.log', {
[11:51:09] [ERROR]::MAIN: 'data': {
[11:51:09] [ERROR]::MAIN: 'type': 'error',
[11:51:09] [ERROR]::MAIN: 'message': Browser.name + ' ' + Browser.version + ': \n' + message,
[11:51:09] [ERROR]::MAIN: 'page': window.location.href.replace(window.location.host, 'HOST'),
[11:51:09] [ERROR]::MAIN: 'file': file.replace(window.location.host, 'HOST'),
[11:51:09] [ERROR]::MAIN: 'line': line
[11:51:09] [ERROR]::MAIN: }
[11:51:09] [ERROR]::MAIN: });
[11:51:09] [ERROR]::MAIN: return true;
[11:51:09] [ERROR]::MAIN: }
[11:51:09] [ERROR]::MAIN: }
[11:51:09] [ERROR]::MAIN: Quality.setup({
[11:51:09] [ERROR]::MAIN: 'profiles': [{"core": false, "_rev": "000cfa7a", "finish": [true, true, true, false, true], "qualities": ["720p", "1080p", "brrip", "dvdrip", ""], "_id": "f61eee8dab3b4e718a41b0dc54d6aa4f", "_t": "profile", "label": "Best", "minimum_score": 1, "stop_after": [120, 120, 120, 120, 120], "wait_for": [3, 3, 3, 3, 3], "order": 0, "3d": [0, 0, 0, 0, 0]}, {"_rev": "0001e2b9", "finish": [true, true], "qualities": ["720p", "1080p"], "_id": "e4b8fe3356254bcc87f18fa254e5e9c9", "_t": "profile", "label": "HD", "minimum_score": 1, "stop_after": [0, 0], "wait_for": [0, 0], "order": 1, "3d": [false, false]}, {"_rev": "0001e9b6", "finish": [true, true], "qualities": ["dvdrip", "dvdr"], "_id": "5d67559a75f94c3a9554f55f5b9bcce5", "_t": "profile", "label": "SD", "minimum_score": 1, "stop_after": [0, 0], "wait_for": [0, 0], "order": 2, "3d": [false, false]}, {"_rev": "0001bcb1", "finish": [true, true, true, true], "qualities": ["1080p", "720p", "720p", "1080p"], "_id": "f6d82735572a45ba97b84d2d75930a14", "_t": "profile", "label": "Prefer 3D HD", "minimum_score": 1, "stop_after": [0, 0, 0, 0], "wait_for": [0, 0, 0, 0], "order": 3, "3d": [true, true, false, false]}, {"_rev": "0001f684", "finish": [true, true], "qualities": ["1080p", "720p"], "_id": "13da79ed95c3401d94643ffb6c1d1636", "_t": "profile", "label": "3D HD", "minimum_score": 1, "stop_after": [0, 0], "wait_for": [0, 0], "order": 4, "3d": [true, true]}, {"core": true, "_rev": "000159a8", "finish": [true], "_id": "535d143d6c2d41bc8312cb5142c4db95", "_t": "profile", "label": "BR-Disk", "qualities": ["bd50"], "wait_for": [0], "order": 20}, {"core": true, "_rev": "000164dc", "finish": [true], "_id": "1445eacbb1364e2da2d773a6c0185a1f", "_t": "profile", "label": "2160p", "qualities": ["2160p"], "wait_for": [0], "order": 20}, {"core": true, "_rev": "0001bc83", "finish": [true], "_id": "5ac8ecdb96a744fd950bc0f2906cdcbc", "_t": "profile", "label": "1080p", "qualities": ["1080p"], "wait_for": [0], "order": 21}, {"core": true, "_rev": "0001e163", "finish": [true], "_id": "b2dd9c71496843bb97a944cb07c0cb63", "_t": "profile", "label": "720p", "qualities": ["720p"], "wait_for": [0], "order": 22}, {"core": true, "_rev": "00013737", "finish": [true], "_id": "10d3e573822c4b88b641a2cf82331d0b", "_t": "profile", "label": "BR-Rip", "qualities": ["brrip"], "wait_for": [0], "order": 23}, {"core": true, "_rev": "0001d5b7", "finish": [true], "_id": "8071741a426f4234ac7cf6aff4fa1cde", "_t": "profile", "label": "DVD-R", "qualities": ["dvdr"], "wait_for": [0], "order": 24}, {"core": true, "_rev": "00019052", "finish": [true], "_id": "d756bee55d194be189bf749638c49f0b", "_t": "profile", "label": "DVD-Rip", "qualities": ["dvdrip"], "wait_for": [0], "order": 25}, {"core": true, "_rev": "00017b57", "finish": [true], "_id": "3f385f30476c4f98ac403364ac1e6abb", "_t": "profile", "label": "Screener", "qualities": ["scr"], "wait_for": [0], "order": 26}, {"core": true, "_rev": "00015000", "finish": [true], "_id": "2fcb89b5cdb94f9f99dfde2b00bcf352", "_t": "profile", "label": "R5", "qualities": ["r5"], "wait_for": [0], "order": 27}, {"core": true, "_rev": "000135c2", "finish": [true], "_id": "eb5fd498bacb4573b95654d66421cb14", "_t": "profile", "label": "TeleCine", "qualities": ["tc"], "wait_for": [0], "order": 28}, {"core": true, "_rev": "0001a252", "finish": [true], "_id": "3f8ef0363d4042f88a28267b96236325", "_t": "profile", "label": "TeleSync", "qualities": ["ts"], "wait_for": [0], "order": 29}, {"core": true, "_rev": "0001cc07", "finish": [true], "_id": "db457ac9cc6b434fbd6a345fe75f1432", "_t": "profile", "label": "Cam", "qualities": ["cam"], "wait_for": [0], "order": 30}],
[11:51:09] [ERROR]::MAIN: 'qualities': [{"_rev": "0001b972", "identifier": "2160p", "size_min": 10000, "tags": ["x264", "h264", "2160"], "_id": "bb323208ecba47fc9302c23ddcf3c9b9", "_t": "quality", "size_max": 650000, "label": "2160p", "height": 2160, "order": 0, "width": 3840, "ext": ["mkv"], "is_3d": false, "allow": [], "alternative": [], "allow_3d": true, "median_size": 20000, "hd": true, "size": [10000, 650000]}, {"_id": "8f26a171aa034c5caa1bd44c43b662b5", "tags": ["bdmv", "certificate", ["complete", "bluray"], "avc", "mvc"], "_rev": "000238b4", "_t": "quality", "size_max": 60000, "size_min": 20000, "label": "BR-Disk", "order": 1, "ext": ["iso", "img"], "is_3d": false, "allow_3d": true, "allow": ["1080p"], "alternative": ["bd25", ["br", "disk"]], "identifier": "bd50", "median_size": 40000, "hd": true, "size": [20000, 60000]}, {"_rev": "000210d9", "identifier": "1080p", "size_min": 4000, "tags": ["m2ts", "x264", "h264", "1080"], "_id": "87bb8c30121b479ba341b79b559f2321", "_t": "quality", "size_max": 20000, "label": "1080p", "height": 1080, "order": 2, "width": 1920, "ext": ["mkv", "m2ts", "ts"], "is_3d": false, "allow": [], "alternative": [], "allow_3d": true, "median_size": 10000, "hd": true, "size": [4000, 20000]}, {"_rev": "0002c48f", "identifier": "720p", "size_min": 3000, "tags": ["x264", "h264", "720"], "_id": "b498c20a3f454a37b20d5601a4db963b", "_t": "quality", "size_max": 10000, "label": "720p", "height": 720, "order": 3, "width": 1280, "ext": ["mkv", "ts"], "is_3d": false, "allow": [], "alternative": [], "allow_3d": true, "median_size": 5500, "hd": true, "size": [3000, 10000]}, {"_id": "ec4cd5fcc4dc4aa5974f770d8dce767a", "tags": ["webdl", ["web", "dl"]], "_rev": "0002a49d", "_t": "quality", "size_max": 7000, "size_min": 700, "label": "BR-Rip", "order": 4, "ext": ["mp4", "avi"], "is_3d": false, "allow_3d": true, "allow": ["720p", "1080p"], "alternative": ["bdrip", ["br", "rip"], "hdtv", "hdrip"], "identifier": "brrip", "median_size": 2000, "hd": true, "size": [700, 7000]}, {"_id": "9f04afc7de544e909837f6490c44bfa1", "tags": ["pal", "ntsc", "video_ts", "audio_ts", ["dvd", "r"], "dvd9"], "_rev": "0002fa90", "_t": "quality", "size_max": 10000, "size_min": 3000, "label": "DVD-R", "order": 5, "ext": ["iso", "img", "vob"], "is_3d": false, "allow": [], "alternative": ["br2dvd", ["dvd", "r"]], "identifier": "dvdr", "median_size": 4500, "size": [3000, 10000]}, {"_id": "ad53178bd8f24ca0ad59772d7032472e", "tags": [["dvd", "rip"], ["dvd", "xvid"], ["dvd", "divx"]], "_rev": "0002df1e", "_t": "quality", "size_max": 2400, "size_min": 600, "label": "DVD-Rip", "order": 6, "width": 720, "ext": ["avi"], "is_3d": false, "allow": [], "alternative": [["dvd", "rip"]], "identifier": "dvdrip", "median_size": 1500, "size": [600, 2400]}, {"_id": "83c12a4722574008a11d3717b245943e", "tags": [], "_rev": "00027c07", "_t": "quality", "size_max": 1600, "size_min": 600, "label": "Screener", "order": 7, "ext": [], "is_3d": false, "allow": ["dvdr", "dvdrip", "720p", "1080p"], "alternative": ["screener", "dvdscr", "ppvrip", "dvdscreener", "hdscr", "webrip", ["web", "rip"]], "identifier": "scr", "median_size": 700, "size": [600, 1600]}, {"_rev": "0002b3b7", "order": 8, "size_min": 600, "is_3d": false, "alternative": ["r6"], "size": [600, 1000], "identifier": "r5", "_t": "quality", "size_max": 1000, "label": "R5", "ext": [], "allow": ["dvdr", "720p", "1080p"], "_id": "0514ac56739d482ab025b51676a34707", "median_size": 700}, {"_rev": "0002cf47", "order": 9, "size_min": 600, "alternative": ["telecine"], "size": [600, 1000], "identifier": "tc", "_t": "quality", "size_max": 1000, "label": "TeleCine", "ext": [], "allow": ["720p", "1080p"], "_id": "adb4b6d3db764b6b8f7877338b396449", "median_size": 700}, {"_rev": "0002cd19", "order": 10, "size_min": 600, "is_3d": false, "alternative": ["telesync", "hdts"], "size": [600, 1000], "identifier": "ts", "_t": "quality", "size_max": 1000, "label": "TeleSync", "ext": [], "allow": ["720p", "1080p"], "_id": "cc94aea704964827813449d7dc21875d", "median_size": 700}, {"_rev": "00028930", "order": 11, "size_min": 600, "is_3d": false, "alternative": ["camrip", "hdcam"], "size": [600, 1000], "identifier": "cam", "_t": "quality", "size_max": 1000, "label": "Cam", "ext": [], "allow": ["720p", "1080p"], "_id": "4314f69997c74f65a1f4ceb3a9009aa0", "median_size": 700}]
[11:51:09] [ERROR]::MAIN: });
[11:51:09] [ERROR]::MAIN: CategoryList.setup([]);
[11:51:09] [ERROR]::MAIN: App.setup({
[11:51:09] [ERROR]::MAIN: 'dev': dev,
[11:51:09] [ERROR]::MAIN: 'base_url': "/",
[11:51:09] [ERROR]::MAIN: 'dereferer': "http://www.dereferer.org/?",
[11:51:09] [ERROR]::MAIN: 'args': "['--data_dir', '/var/db/couchpotato', '--pid_file', '/var/run/couchpotato/couchpotato.pid', '--daemon']",
[11:51:09] [ERROR]::MAIN: 'options': "Namespace(config_file='/var/db/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/var/db/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=False)",
[11:51:09] [ERROR]::MAIN: 'app_dir': "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer",
[11:51:09] [ERROR]::MAIN: 'data_dir': "/var/db/couchpotato",
[11:51:09] [ERROR]::MAIN: 'pid': "25880 ",
[11:51:09] [ERROR]::MAIN: 'userscript_version': 34,
[11:51:09] [ERROR]::MAIN: 'webui_feature': {
[11:51:09] [ERROR]::MAIN: 'hide_about_dirs' : false,
[11:51:09] [ERROR]::MAIN: 'hide_menuitem_update' : false,
[11:51:09] [ERROR]::MAIN: 'hide_about_update' : false,
[11:51:09] [ERROR]::MAIN: }
[11:51:09] [ERROR]::MAIN: });
[11:51:09] [ERROR]::MAIN: })
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: </script>
[11:51:09] [ERROR]::MAIN: 
[11:51:09] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1473165689" rel="stylesheet" href="/static/style/combined.min.css?1473165689" type="text/css">
[11:51:09] [ERROR]::MAIN: </head>
[11:51:09] [ERROR]::MAIN: <body></body>
[11:51:09] [ERROR]::MAIN: </html>
[11:51:09] [INFO]::TRANSCODER: Message contains non-utf-8 string
[11:51:09] [INFO]::TRANSCODER: Message contains non-utf-8 string
[11:51:09] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for taken.blah.blah.blah.cp(tt2446042).nzb
Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 719, in main
    download_id='')
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 602, in process
    inputCategory, failureLink)
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 246, in process
    result = r.json()
  File "/usr/local/share/nzbToMedia/libs/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x80797e878>> ignored`

**Comment by clinton-hall** [comment]
@MacChad 
In your log file, it shows this error twice, then works correctly, then showed a migration error.

So what is the current status? CP is working correctly at my end with these scripts.

@depasseg 
What is the current status for you?

**Comment by MacChad** [comment]
Seems to be working fine now. I re-installed nzbget. And CP is all good now.

**Comment by depasseg** [comment]
I'm still getting the "CouchPotato returned the following non-json data".  and then a traceback and the file move fails.

**Comment by clinton-hall** [comment]
@depasseg 
Can you please post the full log/traceback here?

**Comment by depasseg** [comment]
My apologies for what may be a newb question, but is that a different log than what I posted above?

**Comment by clinton-hall** [comment]
Sorry, are you able to repeat this with 
```
[General]
    log_debug = 1
```
Then post the new logs.


Have you checked the api in CouchPotato Settings, General (show advanced) and verified this is the same as you have entered in
```
[CouchPotato]
    [[movie]]
        apikey = 
```

**Comment by depasseg** [comment]
Thanks for the help.  Yes, the correct API key from CP is in autoProcessMedia.cfg [coucpotato][[movie]]apikey section.

I enabled debug and ran nzbToMedia.py from the command line.
[nzbtomedia-debug.txt](https://github.com/clinton-hall/nzbToMedia/files/487412/nzbtomedia-debug.txt)

**Comment by clinton-hall** [comment]
ok... you have 
```
[CouchPotato]
    [[movie]]
        web_root = couchpotato
```
Are you behind a reverse proxy? do you have this same web_root set in CouchPotato?

What happens if you just set this to
```
[CouchPotato]
    [[movie]]
        web_root = ""
```

**Comment by depasseg** [comment]
It is setup with a reverse proxy.  I followed the steps on Joshua's blog (I'm also running this on FreeNAS)..  It was working flawlessly until a couple months ago.  I think a CouchPotato update broke something, but that's only a guess.
https://www.jruehlig.com/wordpress/installation-configuration-of-freenas-plugins/

**Comment by depasseg** [comment]
Thanks for the nudge in the right direction.  I guess something's out of whack on the reverse proxy.  I removed that web_root, and it's working now.  Thanks for the help!
