### ISSUE TITLE
autoProcessMedia.cfg gets overwritten?

### ISSUE THREAD

**Issue by nucce1** [clinton-hall/nzbToMedia#1103]
Hi.

I'm trying to get Nzbtomedia up and running, I have some small errors but the main-issue is that everytime I tweak my autoProcessMedia.cfg in someway it just get overwritten next time nzbTo*.py  is executed.

My logfile aint saying anything all regarding this but ill add the output anyway:
```
2016-09-17 15:49:53 INFO    ::MAIN: Loading config from [/home/nucce/.nzbtomedia/autoProcessMedia.cfg]
2016-09-17 15:49:53 INFO    ::MAIN: Checking database structure...
2016-09-17 15:49:53 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2016-09-17 15:49:53 DEBUG   ::MAIN: InitialSchema upgrade not required
2016-09-17 15:49:53 DEBUG   ::MAIN: Checking if we can use git commands: "/usr/lib/git-core/git" version
2016-09-17 15:49:53 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" version with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:53 DEBUG   ::MAIN: "/usr/lib/git-core/git" version : returned successful
2016-09-17 15:49:53 DEBUG   ::MAIN: Using: "/usr/lib/git-core/git"
2016-09-17 15:49:53 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" symbolic-ref -q HEAD with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:53 DEBUG   ::MAIN: "/usr/lib/git-core/git" symbolic-ref -q HEAD : returned successful
2016-09-17 15:49:53 INFO    ::MAIN: Checking if git needs an update
2016-09-17 15:49:53 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" rev-parse HEAD with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:53 DEBUG   ::MAIN: "/usr/lib/git-core/git" rev-parse HEAD : returned successful
2016-09-17 15:49:53 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" fetch origin with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:54 DEBUG   ::MAIN: "/usr/lib/git-core/git" fetch origin : returned successful
2016-09-17 15:49:54 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" rev-parse --verify --quiet "@{upstream}" with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:54 DEBUG   ::MAIN: "/usr/lib/git-core/git" rev-parse --verify --quiet "@{upstream}" : returned successful
2016-09-17 15:49:54 DEBUG   ::MAIN: Executing "/usr/lib/git-core/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /home/nucce/.nzbtomedia
2016-09-17 15:49:54 DEBUG   ::MAIN: "/usr/lib/git-core/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
2016-09-17 15:49:54 DEBUG   ::MAIN: cur_commit = 2d770510a284fadc6b44628626f5769789086dbb % (newest_commit)= 2d770510a284fadc6b44628626f5769789086dbb, num_commits_behind = 0, num_commits_ahead = 0
2016-09-17 15:49:54 INFO    ::MAIN: No update needed
2016-09-17 15:49:54 INFO    ::MAIN: nzbToMedia Version:2d770510a284fadc6b44628626f5769789086dbb Branch:master (Linux 4.4.0-36-generic)
```

I'm running Nzbtomedia on a Ubuntu Server, installed from git.

Filestructure:
```
-rw-rw-r--  1 nucce nucce 13720 sep 17 15:49 autoProcessMedia.cfg
-rw-rw-r--  1 nucce nucce 13714 sep 17 14:26 autoProcessMedia.cfg.150917
-rw-------  1 nucce nucce 13263 sep 17 15:49 autoProcessMedia.cfg.old
-rw-rw-r--  1 nucce nucce 13576 sep 16 19:48 autoProcessMedia.cfg.spec
-rw-rw-r--  1 nucce nucce 21203 sep 14 00:01 changelog.txt
drwxrwxr-x 10 nucce nucce  4096 sep 16 19:48 core/
drwxr-xr-x 19 nucce nucce  4096 sep 14 23:40 FFmpeg/
-rwxrwxr-x  1 nucce nucce   504 sep 14 00:01 getffmpeg.sh*
drwxrwxr-x  8 nucce nucce  4096 sep 17 10:48 .git/
-rw-rw-r--  1 nucce nucce   555 sep 14 00:01 .gitattributes
-rw-rw-r--  1 nucce nucce    74 sep 14 00:01 .gitignore
drwxrwxr-x 19 nucce nucce  4096 sep 16 19:48 libs/
-rw-rw-r--  1 nucce nucce 35127 sep 14 00:01 license.txt
drwxrwxr-x  2 nucce nucce  4096 sep 17 15:41 logs/
-rwxrwxr-x  1 nucce nucce  6783 sep 14 00:01 nzbToCouchPotato.py*
-rwxrwxr-x  1 nucce nucce  2702 sep 14 00:01 nzbToGamez.py*
-rwxrwxr-x  1 nucce nucce  3119 sep 14 00:01 nzbToHeadPhones.py*
-rw-r--r--  1 nucce nucce  4096 sep 16 19:48 nzbtomedia.db
-rw-rw-r--  1 nucce nucce 10793 sep 17 15:35 nzbtomediaprocess.log
-rwxrwxr-x  1 nucce nucce 26602 sep 14 00:01 nzbToMedia.py*
-rw-rw-r--  1 nucce nucce  9103 sep 16 19:48 nzbToMedia.pyc
-rwxrwxr-x  1 nucce nucce  3070 sep 14 00:01 nzbToMylar.py*
-rwxrwxr-x  1 nucce nucce  6386 sep 14 00:01 nzbToNzbDrone.py*
-rwxrwxr-x  1 nucce nucce  6708 sep 14 00:01 nzbToSickBeard.py*
-rw-rw-r--  1 nucce nucce  5042 sep 14 00:01 README.md
drwxrwxr-x  2 nucce nucce  4096 sep 14 00:01 tests/
-rwxrwxr-x  1 nucce nucce 15953 sep 14 00:01 TorrentToMedia.py*
```

The reason that I try to edit the file is because nzbto* failing to take care of job sent from sabnzbd(its strange that the output data of this errors dont end up in nzbtomedia.log, but it can be found inside sabnzbd):
```
[15:49:53] [INFO]::MAIN: Loading config from [/home/nucce/.nzbtomedia/autoProcessMedia.cfg]
[15:49:53] [INFO]::MAIN: Checking database structure...
[15:49:53] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[15:49:53] [DEBUG]::MAIN: InitialSchema upgrade not required
[15:49:53] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/lib/git-core/git" version
[15:49:53] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" version with your shell in /home/nucce/.nzbtomedia
[15:49:53] [DEBUG]::MAIN: "/usr/lib/git-core/git" version : returned successful
[15:49:53] [DEBUG]::MAIN: Using: "/usr/lib/git-core/git"
[15:49:53] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" symbolic-ref -q HEAD with your shell in /home/nucce/.nzbtomedia
[15:49:53] [DEBUG]::MAIN: "/usr/lib/git-core/git" symbolic-ref -q HEAD : returned successful
[15:49:53] [INFO]::MAIN: Checking if git needs an update
[15:49:53] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" rev-parse HEAD with your shell in /home/nucce/.nzbtomedia
[15:49:53] [DEBUG]::MAIN: "/usr/lib/git-core/git" rev-parse HEAD : returned successful
[15:49:53] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" fetch origin with your shell in /home/nucce/.nzbtomedia
[15:49:54] [DEBUG]::MAIN: "/usr/lib/git-core/git" fetch origin : returned successful
[15:49:54] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" rev-parse --verify --quiet "@{upstream}" with your shell in /home/nucce/.nzbtomedia
[15:49:54] [DEBUG]::MAIN: "/usr/lib/git-core/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[15:49:54] [DEBUG]::MAIN: Executing "/usr/lib/git-core/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /home/nucce/.nzbtomedia
[15:49:54] [DEBUG]::MAIN: "/usr/lib/git-core/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[15:49:54] [DEBUG]::MAIN: cur_commit = 2d770510a284fadc6b44628626f5769789086dbb % (newest_commit)= 2d770510a284fadc6b44628626f5769789086dbb, num_commits_behind = 0, num_commits_ahead = 0
[15:49:54] [INFO]::MAIN: No update needed
[15:49:54] [INFO]::MAIN: nzbToMedia Version:2d770510a284fadc6b44628626f5769789086dbb Branch:master (Linux 4.4.0-36-generic)
Traceback (most recent call last):
  File "/home/nucce/.nzbtomedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/home/nucce/.nzbtomedia/nzbToMedia.py", line 633, in main
    core.initialize(section)
  File "/home/nucce/.nzbtomedia/core/__init__.py", line 356, in initialize
    TRANSMISSIONPORT = int(CFG["Torrent"]["TransmissionPort"])
TypeError: int() argument must be a string or a number, not 'Section'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x7f70efe33560>> ignored
```

Any ideas?

Full Regards

**Comment by nucce1** [comment]
I got this under control now, after I edit autoProcessMedia.cfg I must simply run the command python nzbToMedia.py.
