### ISSUE TITLE
Importerror No module named core

### ISSUE THREAD

**Issue by wigwam12** [clinton-hall/nzbToMedia#1122]
Hi

Xpenology DSM5.2-5592 update 4 on an HP Gen 8 Microserver

After some previous frustrations I had my Sab/SR working just fine
I then foolishly clicked on the upgrade button for Sab and after updating it wouldn't start so I was forced to uninstall and reinstall. Lost all my settings.
I worked my through them.
The scripts is the main remaining issue - they just won't work for SR

I created a new folder in usr/local/sabnzb/var/scripts and copied across the contents of the nzbtomedia folder I had an offline copy of which used to work
I have screenshotted it (called scripts permission)
I have a feeling permissions might be a problem here but I am getting the following error for ALL SR tv programmes:
Importerror: No module named core
Traceback (most recent call last):
  File "/usr/local/sabnzbd/var/scripts/nzbToSickBeard.py", line 249, in <module>
    import nzbToMedia
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia.py", line 503, in <module>
    import core
ImportError: No module named core

I have also screen-shotted the volume1/@appstore etc folder 

I would appreciate advice on how I go about fixing (please be gentle I am a novice here)
I have noticed that in the sickbeard-custom version of the contrib/nzbtomedia folder there are other folders called logs, libs, core etc that I don't have in my sabnzbtomedia folder......?

![scripts permissions](https://cloud.githubusercontent.com/assets/15263597/19833637/eb3795ee-9e40-11e6-9538-ca59f85e8d0e.jpg)

![scripts appstore folder](https://cloud.githubusercontent.com/assets/15263597/19833638/eb38e99e-9e40-11e6-9c40-082a6bd65e66.jpg)

![sickbeard contrib nzbtomedia folder](https://cloud.githubusercontent.com/assets/15263597/19833652/c6496112-9e41-11e6-8e73-ef78086a84e3.jpg)

**Comment by clinton-hall** [comment]
Yeah, the scripts folder is missing those necessary folders.

You could just change SABnzbd scripts folder to point to /usr/local/sickbeard-custom/var/SickBeard/contrib/nzbToMedia

or delete the files in /usr/local/sabnzbd/var/scripts
then re-clone
`git clone https://github.com/clinton-hall/nzbToMedia.git`

**Comment by wigwam12** [comment]
Thanks
I did that but now I am seeing this error:
Processing failed: File is locked for reading/writing]

**Comment by wigwam12** [comment]
here is the log:
[03:42:51] [INFO]::MAIN: Loading config from [/volume1/@appstore/sickbeard-custom/var/SickBeard/contrib/nzbToMedia/autoProcessMedia.cfg]
[03:42:51] [INFO]::MAIN: Checking database structure...
[03:42:51] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[03:42:51] [DEBUG]::MAIN: InitialSchema upgrade not required
[03:42:51] [INFO]::MAIN: Checking if source needs an update
[03:42:51] [DEBUG]::MAIN: cur_commit = None % (newest_commit)= 26957918e562918c653292d33e2c11206ce6ccb9, num_commits_behind = 0
[03:42:51] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[03:42:51] [INFO]::MAIN: nzbToMedia Version:10.14 Branch:master (Linux 3.10.35)
[03:42:52] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[03:42:52] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[03:42:52] [DEBUG]::MAIN: Connecting to transmission: http://192.168.0.20:9091
[03:42:52] [INFO]::MAIN: #########################################################
[03:42:52] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[03:42:52] [INFO]::MAIN: #########################################################
[03:42:52] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/sickbeard-custom/var/SickBeard/contrib/nzbToMedia/nzbToSickBeard.py', '/volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION', 'Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.nzb', 'Lucifer.S02E07.1080p.HDTV.X264-DIMENSION', '', 'tv', 'alt.binaries.teevee', '0', 'h', 't', 't', 'p', 's', ':', '/', '/', 'n', 'z', 'b', '.', 'i', 's', '/', 'f', 'a', 'i', 'l', 'e', 'd', '/', '?', 'g', 'u', 'i', 'd', '=', '8', 'f', 'b', 'a', '6', '5', 'b', '3', 'f', '2', '0', '8', '8', '7', 'b', '1', 'a', '1', '9', '8', '0', '3', 'd', '2', '7', '8', '5', '0', 'b', '8', 'd', 'f', '8', '6', 'f', '7', '2', 'f', 'd', '7', '&', 'u', 's', 'e', 'r', 'i', 'd', '=', '4', '8', '1', '7', '0', '&', 'r', 's', 's', 't', 'o', 'k', 'e', 'n', '=', 'c', '8', 'b', '0', '0', '8', '2', 'd', 'b', 'e', 'd', '2', '0', '6', '1', '4', 'd', '0', 'f', '7', 'b', '7', '2', '6', '6', 'a', '3', '3', '4', '2', '4', '6']
[03:42:52] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[03:42:52] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[03:42:52] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_s9Dn5U
[03:42:52] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION to database
[03:42:52] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[03:42:52] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r02
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r06
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r11
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r03
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r01
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r12
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r05
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r04
/usr/syno/bin/7z
[03:42:52] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .r07
/usr/syno/bin/7z
[03:42:52] [INFO]::MAIN: Extracting /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/morning.star.207.1080-dimension.rar to /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:42:52] [DEBUG]::MAIN: Extracting ['unrar', 'x', '-o+', '-y'] /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/morning.star.207.1080-dimension.rar /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:43:32] [INFO]::MAIN: EXTRACTOR: Extraction was successful for /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/morning.star.207.1080-dimension.rar to /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:43:35] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r02 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:36] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r06 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:37] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r11 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:38] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r03 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:39] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r01 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:40] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r12 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:41] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r05 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:42] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r04 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:43] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r07 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:44] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.rar from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:45] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r21 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:46] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r22 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:47] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r10 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:48] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r23 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:49] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r14 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:50] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r13 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:51] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r25 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:52] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r26 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:54] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r15 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:55] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r16 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:56] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r00 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:57] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r28 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:58] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r17 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:43:59] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r08 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:00] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r30 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:01] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r19 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:02] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r20 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:03] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r32 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:04] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r34 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:05] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r24 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:06] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r35 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:07] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r38 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:08] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r36 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:09] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r39 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:10] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r27 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:11] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r29 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:12] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r42 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:13] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r31 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:14] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r45 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:15] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r18 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:16] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r37 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:17] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r09 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:18] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r40 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:19] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r41 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:20] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r43 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:21] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r44 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:22] [INFO]::MAIN: Removing extracted archive morning.star.207.1080-dimension.r33 from folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION ...
[03:44:23] [INFO]::MAIN: Calling SickBeard:tv to post-process:Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.nzb
[03:44:23] [INFO]::MAIN: SickBeard:tv fork set to sickrage
[03:44:23] [INFO]::MAIN: FLATTEN: Flattening directory: /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [DEBUG]::MAIN: Checking for empty folders in:/volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[03:44:23] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8899/home/postprocess/processEpisode with params: {'nzbName': 'Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.nzb', 'quiet': 1, 'failed': '0', 'dir': '/volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION'}
[03:44:23] [POSTPROCESS]::SICKBEARD: Processing folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing Path: /volume1/Downloads/complete/tv
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing Dirs: [u'Lucifer.S02E07.1080p.HDTV.X264-DIMENSION']
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing Files: []
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing VideoFiles: []
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing RarContent: []
[03:44:23] [POSTPROCESS]::SICKBEARD: PostProcessing VideoInRar: []
[03:44:23] [POSTPROCESS]::SICKBEARD: Processing folder Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [POSTPROCESS]::SICKBEARD: Processing folder /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [POSTPROCESS]::SICKBEARD: Found unwanted files: ['lucifer.207.1080-dimension.nfo', 'morning.star.207.1080-dimension.sfv', 'morning.star.207.1080-dimension.srr', 'morning.star.207.1080-dimension.sample.mkv']
[03:44:23] [POSTPROCESS]::SICKBEARD: Processing /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.mkv (Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.nzb)
[03:44:23] [POSTPROCESS]::SICKBEARD: Retrieving episode object for 2x7
[03:44:23] [POSTPROCESS]::SICKBEARD: Snatch history had a quality in it, using that: 1080p HDTV
[03:44:23] [POSTPROCESS]::SICKBEARD: SR snatched this episode and it is not processed before
[03:44:23] [POSTPROCESS]::SICKBEARD: Is ep a priority download: True
[03:44:23] [POSTPROCESS]::SICKBEARD: There is no existing file so there's no worries about replacing it
[03:44:23] [POSTPROCESS]::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
[03:44:23] [POSTPROCESS]::SICKBEARD: Unable to determine needed filespace as the source file is locked for access
[03:44:23] [POSTPROCESS]::SICKBEARD: Found release name Lucifer.S02E07.1080p.HDTV.X264-DIMENSION
[03:44:23] [POSTPROCESS]::SICKBEARD: Destination folder for this episode: /volume1/video/tv/Lucifer/Season 02
[03:44:23] [POSTPROCESS]::SICKBEARD: Processing failed for /volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.mkv: File is locked for reading/writing
[03:44:23] [POSTPROCESS]::SICKBEARD: Problem(s) during processing, failed the following files/folders:  
[03:44:23] [POSTPROCESS]::SICKBEARD: [/volume1/Downloads/complete/tv/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION/Lucifer.S02E07.1080p.HDTV.X264-DIMENSION.mkv : Processing failed: File is locked for reading/writing]
[03:44:23] [ERROR]::MAIN: A problem was reported in the /usr/local/sickbeard-custom/var/SickBeard/contrib/nzbToMedia/nzbToSickBeard.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected

**Comment by clinton-hall** [comment]
why is nzbToMedia doing the extraction? does SABnzbd not extract these already?

In SABnzbd, for the category `tv` set the post processing option to `delete`

see here: https://sabnzbd.org/wiki/extra/job-options

**Comment by wigwam12** [comment]
Okay thanks Ive done that and will see what happens now.

**Comment by wigwam12** [comment]
I've now tried a belts and braces approach of moving the whole contrib folder to a new "scripts" folder I have created in Downloads and given it permissions
Let's see what happens tonight with the relevant shows....

**Comment by wigwam12** [comment]
That sorted it.
Thanks again for your help
