### ISSUE TITLE
Post-Processing Failure

### ISSUE THREAD

**Issue by thamilton91** [clinton-hall/nzbToMedia#1128]
Clean install of NZBGET, COUCHPOTATO and NZBTOMEDIA

I'm receiving the following within NZBGET logs.

<img width="1418" alt="screen shot 2016-11-03 at 9 32 37 pm" src="https://cloud.githubusercontent.com/assets/5624324/19991805/fc9a2c12-a20e-11e6-980e-64f909c96739.png">

**Comment by clinton-hall** [comment]
What system is this on?
This looks like missing libs in your Python install.

**Comment by thamilton91** [comment]
This is running on a dedi stream server through bytesized hosting. I dont have root access so I'd need to open a ticket to install things.

**Comment by thamilton91** [comment]
What should I ask the system administrator try?

**Comment by clinton-hall** [comment]
can you check the contents of the following directory?
`/home/hd1/hamflix/apps/nzbToMedia/libs/bs4/builder`

**Comment by thamilton91** [comment]
![screen sharing picture november 7 2016 at 10 03 44 am est](https://cloud.githubusercontent.com/assets/5624324/20062393/8e04a334-a4d1-11e6-8350-d7633a6627fe.png)

Also, i'll say that everything was functioning fine up until about a week ago.

**Comment by clinton-hall** [comment]
So a week ago these libs were all updated, but there is nothing in the traceback to indicate why this couldn't be imported...

can you please try the following via ssh?
```
cd /home/hd1/hamflix/apps/nzbToMedia
rm -rf *.pyc
git reset --hard
git pull
```
Then try running the script again.

Also, can you post the output of calling the script manually via ssh?
```
cd /home/hd1/hamflix/apps/nzbToMedia
./nzbToMedia.py
```

**Comment by thamilton91** [comment]
![screen shot 2016-11-08 at 9 26 22 pm](https://cloud.githubusercontent.com/assets/5624324/20125205/08b1ff04-a5fa-11e6-9987-79713fbe15c2.png)

**Comment by clinton-hall** [comment]
Can you show the output of `pyhton -V` and `python2 -V`

**Comment by clinton-hall** [comment]
Please update to latest nightly and test... I just updated BS4

**Comment by thamilton91** [comment]
Ran the manual script again on the nightly, it appears to have worked.
![screen shot 2016-11-09 at 9 52 39 pm](https://cloud.githubusercontent.com/assets/5624324/20163002/f2c8533c-a6c6-11e6-82e3-ea55ac67ec07.png)

**Comment by thamilton91** [comment]
Just ran it through on NZBGET and all is working smoothly.

What did it come down to being?

**Comment by clinton-hall** [comment]
I don't understand exactly what changed fixed this in bs4 but I updated Beautifulsoup (bs4) to the latest version and that worked...
I had read some issues with bs4 on different platforms, so can only assume they fixed this issue and it just needed to be updated internally.

What caused this to break in my script was when I updated Subsonic, it actually made a different call to bs4 (which worked on my system, but not on yours, using the old version)

**Comment by ladude626** [comment]
Hi. I just moved to a shared seedbox and having similar issue running the latest nightly getting this error:

	2016-11-20 21:23:45 INFO    ::MAIN: Loading config from [/mnt/mpathac/asnguy01/opt/nzbtomedia/autoProcessMedia.cfg]
	2016-11-20 21:23:45 INFO    ::MAIN: Checking database structure...
	2016-11-20 21:23:45 DEBUG   ::MAIN: Checking Initial Schema database upgrade
	2016-11-20 21:23:45 DEBUG   ::MAIN: InitialSchema upgrade not required
	2016-11-20 21:23:45 DEBUG   ::MAIN: Checking if we can use git commands: git version
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git version with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git version : returned successful
	2016-11-20 21:23:45 DEBUG   ::MAIN: Using: git
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
	2016-11-20 21:23:45 INFO    ::MAIN: Checking if git needs an update
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git fetch origin with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git fetch origin : returned successful
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
	2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
	2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
	2016-11-20 21:23:45 DEBUG   ::MAIN: cur_commit = 4b90a2cc197b5321041a937ceabfb15ba824fe5a % (newest_commit)= 4b90a2cc197b5321041a937ceabfb15ba824fe5a, num_commits_behind = 0, num_commits_ahead = 0
	2016-11-20 21:23:45 INFO    ::MAIN: No update needed
	2016-11-20 21:23:45 INFO    ::MAIN: nzbToMedia Version:4b90a2cc197b5321041a937ceabfb15ba824fe5a Branch:nightly (Linux 4.7.10-hardened-r2-whatbox)
	Traceback (most recent call last):
	  File "./nzbToMedia.py", line 817, in <module>
	    exit(main(sys.argv))
	  File "./nzbToMedia.py", line 649, in main
	    core.initialize(section)
	  File "/mnt/mpathac/asnguy01/opt/nzbtomedia/core/__init__.py", line 394, in initialize
	    REMOTEPATHS]  # strip trailing and leading whitespaces
	ValueError: need more than 1 value to unpack
	Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fae141db250>> ignored   

Here's what my Python version: Python 2.7.12

**Comment by clinton-hall** [comment]
What do you have for [Network] mount_points?

Sent from my iPhone

On 21 Nov. 2016, at 7:57 am, ladude626 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi. I just moved to a shared seedbox and having similar issue running the latest nightly getting this error:

2016-11-20 21:23:45 INFO    ::MAIN: Loading config from [/mnt/mpathac/asnguy01/opt/nzbtomedia/autoProcessMedia.cfg]
2016-11-20 21:23:45 INFO    ::MAIN: Checking database structure...
2016-11-20 21:23:45 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2016-11-20 21:23:45 DEBUG   ::MAIN: InitialSchema upgrade not required
2016-11-20 21:23:45 DEBUG   ::MAIN: Checking if we can use git commands: git version
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git version with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git version : returned successful
2016-11-20 21:23:45 DEBUG   ::MAIN: Using: git
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
2016-11-20 21:23:45 INFO    ::MAIN: Checking if git needs an update
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git fetch origin with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git fetch origin : returned successful
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
2016-11-20 21:23:45 DEBUG   ::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /mnt/mpathac/asnguy01/opt/nzbtomedia
2016-11-20 21:23:45 DEBUG   ::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2016-11-20 21:23:45 DEBUG   ::MAIN: cur_commit = 4b90a2cc197b5321041a937ceabfb15ba824fe5a % (newest_commit)= 4b90a2cc197b5321041a937ceabfb15ba824fe5a, num_commits_behind = 0, num_commits_ahead = 0
2016-11-20 21:23:45 INFO    ::MAIN: No update needed
2016-11-20 21:23:45 INFO    ::MAIN: nzbToMedia Version:4b90a2cc197b5321041a937ceabfb15ba824fe5a Branch:nightly (Linux 4.7.10-hardened-r2-whatbox)
Traceback (most recent call last):
  File "./nzbToMedia.py", line 817, in <module>
    exit(main(sys.argv))
  File "./nzbToMedia.py", line 649, in main
    core.initialize(section)
  File "/mnt/mpathac/asnguy01/opt/nzbtomedia/core/__init__.py", line 394, in initialize
    REMOTEPATHS]  # strip trailing and leading whitespaces
ValueError: need more than 1 value to unpack
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fae141db250>> ignored


Here's what my Python version: Python 2.7.12

-

**Comment by ladude626** [comment]
I did have something for mount_point. I got it working after removing that setting. What do you think the issue?

**Comment by clinton-hall** [comment]
The issue was with the formatting of mount point or the way it was loaded in. To know if this is a bug I need to know what you did have for mount_point.

Sent from my iPhone

On 21 Nov. 2016, at 9:38 am, ladude626 <notifications@github.com<mailto:notifications@github.com>> wrote:


I did have something for mount_point. I got it working after removing that setting. What do you think the issue?

-
