### ISSUE TITLE
Couchpotato error

### ISSUE THREAD

**Issue by Alexwijn** [clinton-hall/nzbToMedia#1134]
When trying to run it in combination with couchpotato I get the following error:

~~~
pi@raspberrypi:/opt/nzbToMedia $ ./TorrentToMedia.py
[17:08:39] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[17:08:39] [INFO]::MAIN: Checking database structure...
[17:08:39] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[17:08:39] [DEBUG]::MAIN: InitialSchema upgrade not required
[17:08:39] [DEBUG]::MAIN: Checking if we can use git commands: git version
[17:08:39] [DEBUG]::MAIN: Executing git version with your shell in /opt/nzbToMedia
[17:08:39] [DEBUG]::MAIN: git version : returned successful
[17:08:39] [DEBUG]::MAIN: Using: git
[17:08:39] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /opt/nzbToMedia
[17:08:39] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[17:08:39] [INFO]::MAIN: Checking if git needs an update
[17:08:39] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /opt/nzbToMedia
[17:08:39] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[17:08:39] [DEBUG]::MAIN: Executing git fetch origin with your shell in /opt/nzbToMedia
[17:08:41] [DEBUG]::MAIN: git fetch origin : returned successful
[17:08:41] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/nzbToMedia
[17:08:41] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[17:08:41] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/nzbToMedia
[17:08:41] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[17:08:41] [DEBUG]::MAIN: cur_commit = 26957918e562918c653292d33e2c11206ce6ccb9 % (newest_commit)= 26957918e562918c653292d33e2c11206ce6ccb9, num_commits_behind = 0, num_commits_ahead = 0
[17:08:41] [INFO]::MAIN: No update needed
[17:08:41] [INFO]::MAIN: nzbToMedia Version:26957918e562918c653292d33e2c11206ce6ccb9 Branch:master (Linux 4.4.32-v7+)
[17:08:41] [DEBUG]::MAIN: Connecting to transmission: http://localhost:9091
[17:08:41] [INFO]::MAIN: #########################################################
[17:08:41] [INFO]::MAIN: ## ..::[TorrentToMedia.py]::.. ##
[17:08:41] [INFO]::MAIN: #########################################################
[17:08:41] [DEBUG]::MAIN: Options passed into TorrentToMedia: ['./TorrentToMedia.py']
[17:08:41] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[17:08:48] [INFO]::MAIN: Searching /media/usb0/Downloads/Queue/Movies for mediafiles to post-process ...
[17:08:48] [INFO]::MAIN: Searching /media/usb0/Downloads/Processing/Movies for mediafiles to post-process ...
[17:08:48] [INFO]::MAIN: Starting manual run for CouchPotato:Movies - Folder:/media/usb0/Downloads/Processing/Movies/Chasing Liberty (2004)  DVDRip
[17:08:48] [INFO]::MAIN: Checking database for download info for Chasing Liberty (2004)  DVDRip ...
Traceback (most recent call last):
  File "./TorrentToMedia.py", line 363, in <module>
    exit(main(sys.argv))
  File "./TorrentToMedia.py", line 321, in main
    clientAgent = text_type(core.DOWNLOADINFO[0].get('client_agent', 'manual'))
AttributeError: 'sqlite3.Row' object has no attribute 'get'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x754d3370>> ignored
~~~

**Comment by clinton-hall** [comment]
So this is a manual run, after this movie has already been processed?

It looks like an issue with retrieving info from the database. I'll try and reproduce, but for now, just try deleting nzbtomedia.db

**Comment by Alexwijn** [comment]
It was just downloaded and I ran the command and this happened. I'll try to delete that file and get back to you.

**Comment by Alexwijn** [comment]
After deleting it I get the error: No media found. This is when it tries to call couchpotato.
