### ISSUE TITLE
QQ: manual notify SR of failed

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1141]
I have a script that goes through my utorrent list and cleans out blacklisted downloads, certain sized/category combinations and the like and currently it just nuked the torrent. I was wondering if there was a way to have it call nzbToMedia for TV or Movies and appropriately notify CP or SR that it needs to consider that a failed download and move on to the next. I'm not quite sure if nTM can do this or it needs a manual SR / CP api call. Looking for thoughts.

**Comment by clinton-hall** [comment]
You could have it call nTM or TTM.

The command to call depends on your downloader. 

In the following, this is for utorrent:

autoProcessmedia.cfg
```
[Torrent]
     clientAgent = utorrent
```

Then have your script call
`TorrentToMedia.py <Directoy> <Name> <Label> <Hash>`

when the script finds no media in the directory this will set the status to failed and let CP/SR know...

The same can be done for other torrent clients... for Transmission you need to export the environment variables.

Calling nzbToMedia may be easier in that you can pass in the status as failed.. but if this looks for a snatched release (in CP) it won't find a match as it is for a different download client...

**Comment by mgaulton** [comment]
giving this a shot.

**Comment by mgaulton** [comment]
So since the torrent doesn't finish, it doesn't move the data from /home/processing (incomplete) to /home/processed (complete) so the destination directory doesn't actually exist. Should I pass the path of the incomplete location?

Removing broken torrent: Bottle Shock 2008 720p BRRip x264-MgB=16
[08:56:27] [INFO]::MAIN: Loading config from [/opt/Sick-Beard/autoProcessTV/autoProcessMedia.cfg]
[08:56:27] [INFO]::MAIN: Checking database structure...
[08:56:27] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[08:56:27] [DEBUG]::MAIN: InitialSchema upgrade not required
[08:56:27] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[08:56:27] [DEBUG]::MAIN: Using: "/usr/bin/git"
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[08:56:27] [INFO]::MAIN: Checking if git needs an update
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[08:56:27] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[08:56:27] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[08:56:27] [DEBUG]::MAIN: cur_commit = 66abb2d562aa9491c5c5fad0c228e20a05982fd7 % (newest_commit)= 66abb2d562aa9491c5c5fad0c228e20a05982fd7, num_commits_behind = 0, num_commits_ahead = 0
[08:56:27] [INFO]::MAIN: No update needed
[08:56:27] [INFO]::MAIN: nzbToMedia Version:66abb2d562aa9491c5c5fad0c228e20a05982fd7 Branch:master (Linux 4.1.34-33-default)
[08:56:27] [DEBUG]::MAIN: Connecting to utorrent: http://localhost:8087/gui/
[08:56:27] [INFO]::MAIN: #########################################################
[08:56:27] [INFO]::MAIN: ## ..::[TorrentToMedia.py]::.. ##
[08:56:27] [INFO]::MAIN: #########################################################
[08:56:27] [DEBUG]::MAIN: Options passed into TorrentToMedia: ['/opt/Sick-Beard/autoProcessTV/TorrentToMedia.py', '/home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB', 'Bottle Shock 2008 720p BRRip x264-MgB', 'Movies', '7D3BDFAB76BBE367C5205DD364EE239CA2C5AC73']
[08:56:27] [DEBUG]::MAIN: Adding TORRENT download info for directory /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB to database
[08:56:27] [DEBUG]::MAIN: Received Directory: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB | Name: Bottle Shock 2008 720p BRRip x264-MgB | Category: Movies
[08:56:27] [DEBUG]::MAIN: SEARCH: Found the Category: Movies in directory structure
[08:56:27] [INFO]::MAIN: SEARCH: Found a unique directory Bottle Shock 2008 720p BRRip x264-MgB in the category directory
[08:56:27] [DEBUG]::MAIN: Determined Directory: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB | Name: Bottle Shock 2008 720p BRRip x264-MgB | Category: Movies
[08:56:27] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[08:56:27] [DEBUG]::MAIN: Stopping torrent Bottle Shock 2008 720p BRRip x264-MgB in utorrent while processing
[08:56:27] [WARNING]::MAIN: Failed to stop torrent Bottle Shock 2008 720p BRRip x264-MgB in utorrent
[08:56:27] [INFO]::MAIN: Output directory set to: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [DEBUG]::MAIN: Scanning files in directory: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [DEBUG]::MAIN: Found 0 files in /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [INFO]::MAIN: FLATTEN: Flattening directory: /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [WARNING]::MAIN: Found no media files in /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [INFO]::MAIN: Calling CouchPotato:Movies to post-process:Bottle Shock 2008 720p BRRip x264-MgB
[08:56:27] [INFO]::MAIN: Changing file mode of /home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB to 0777
Traceback (most recent call last):
  File "/opt/Sick-Beard/autoProcessTV/TorrentToMedia.py", line 363, in <module>
    exit(main(sys.argv))
  File "/opt/Sick-Beard/autoProcessTV/TorrentToMedia.py", line 304, in main
    result = processTorrent(inputDirectory, inputName, inputCategory, inputHash, inputID, clientAgent)
  File "/opt/Sick-Beard/autoProcessTV/TorrentToMedia.py", line 223, in processTorrent
    core.rchmod(outputDestination, core.TORRENT_CHMOD_DIRECTORY)
  File "/opt/Sick-Beard/autoProcessTV/core/__init__.py", line 842, in rchmod
    os.chmod(path, mod)
OSError: [Errno 2] No such file or directory: '/home/processed/Movies/Bottle Shock 2008 720p BRRip x264-MgB'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f5f8c62e8d0>> ignored

**Comment by clinton-hall** [comment]
Yes, pass in the incomplete directory for that download.
