### ISSUE TITLE
Add Medusa support

### ISSUE THREAD

**Issue by OmgImAlexis** [clinton-hall/nzbToMedia#1152]
Hey, I'm one of the devs from the sickrage fork Medusa and I just thought I'd let you know we're adding in a new API that may help this project out. If there's anything specific that this needs please let me know and I'll try to add it as soon as possible.

For now just try to keep an eye on [our wiki](https://github.com/pymedusa/Medusa/wiki/API-v2) for updates. 😃

**Comment by clinton-hall** [comment]
Thanks for the info.
Is there a list of available api calls and parameters to be passed?

**Comment by OmgImAlexis** [comment]
At the moment we're still working on the API so we haven't finished everything. We do have an apiary page though which we'll be updating as it changes. All of the changes for current routes should be locked down by January.

http://docs.medusaapi.apiary.io/

**Comment by clinton-hall** [comment]
Thanks for that.
As far as nzbToMedia's integration, given the current setup, the only direct interface used is the manual post-process where we pass the following params:
`proc_dir, failed, process_method, force, delete_on, ignore_subs`

If this were available through api, potentially with some return data to confirm the status of the renaming, then I could switch this over to api. Currently nzbToMedia just logs in with the user/pass and then does the manual post-process through the web-ui.

**Comment by OmgImAlexis** [comment]
Post processing will now be on my TODO list, completely forgot that would be something we needed with the API. I'll try and add something in the next week and let you know.

**Comment by clinton-hall** [comment]
Thanks,

When available (and time permitting) I'll try and update this project to work with the api.

**Comment by jackalblood** [comment]
i greatly look forward to word on this also as NZBtoMedia is the only thing stopping me from switching

**Comment by labrys** [comment]
@jackalblood Medusa already supports NZBtoMedia.  I'm one of the Medusa devs and use it currently.  Configuration is no different than for any other Sick* fork.  Our v2 API though will be different than the other forks, thus the reason for this.

**Comment by udochrist** [comment]
i ran into issues with medusa 0.2.8 (released 27/7/18) and the fork autodetection.
for fork = auto i get
```
[17:58:19] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
  File "./nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/volume1/Download/SABnzbd/scripts/nzbToMedia/nzbToMedia.py", line 832, in main
    download_id='')
  File "/volume1/Download/SABnzbd/scripts/nzbToMedia/nzbToMedia.py", line 717, in process
    download_id, inputCategory, failureLink)
  File "/volume1/Download/SABnzbd/scripts/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
    fork, fork_params = autoFork(section, inputCategory)
  File "/volume1/Download/SABnzbd/scripts/nzbToMedia/core/nzbToMediaAutoFork.py", line 84, in autoFork
    if param not in r.json()['data']['optionalParameters'].keys():
KeyError: 'optionalParameters'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f81ef223e10>> ignored
```
and with fork set to medusa the postprocess will still not work since in core.FORKS[FORK_MEDUSA] proc_dir is used where medusa expects 'path' to be sent.

**Comment by clinton-hall** [comment]
Currently the code at nzbToMedia doesn't use api to interface with medusa, so in autoProcessMEdia.cfg remove the api key from the appropriate category.
```
[SickBeard]
    [tv]
        apikey = ""
```
and set the user and pass details only for the medusa webui.

The changes was introduced in nzbToMedia where 1 of the other SickBeard forms has now implemented api functionality and an internal check there fails with other branches... I will try and fix this is due course.

As far the `proc_dir` vs `path` I am not sure when this was introducted in medusa, but I can make this change. Can you please make the changes suggested above (removing apikey) and set back to autofork? This should then detect as a "custom" form and will confirm the parameter names. Please show the logs from this test.
