### ISSUE TITLE
Error With Master Branch

### ISSUE THREAD

**Issue by HPMSGEN8** [clinton-hall/nzbToMedia#1188]
Hi,

I am getting this when i am using master:

`[03:14:23] [INFO]::MAIN: Loading config from [/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/autoProcessMedia.cfg]
[03:14:23] [INFO]::MAIN: Checking database structure...
[03:14:23] [INFO]::MAIN: Checking if git needs an update
[03:14:23] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[03:14:23] [INFO]::MAIN: No update needed
[03:14:23] [INFO]::MAIN: nzbToMedia Version:11.03 Branch:master (Linux 3.10.77)
[03:14:23] [INFO]::MAIN: #########################################################
[03:14:23] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[03:14:23] [INFO]::MAIN: #########################################################
[03:14:23] [INFO]::MAIN: Script triggered from SABnzbd
[03:14:25] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[03:14:25] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Manchester.by.the.Sea.2016.1080p.BluRay.x264-GECKOS.nzb
[03:14:25] [INFO]::MAIN: Attemping imdbID lookup for Manchester.by.the.Sea.2016.1080p.BluRay.x264-GECKOS.nzb
[03:14:25] [INFO]::MAIN: Searching folder and file names for imdbID ...
[03:14:25] [INFO]::MAIN: Searching IMDB for imdbID ...
Traceback (most recent call last):
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/nzbToCouchPotato.py", line 257, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/nzbToMedia.py", line 732, in main
    download_id='')
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/nzbToMedia.py", line 618, in process
    inputCategory, failureLink)
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 131, in process
    imdbid = find_imdbid(dirName, inputName)
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/core/nzbToMediaUtil.py", line 1072, in find_imdbid
    results = r.json()
  File "/volumeX/Downloads/103 NZB/Scripts/nzbToMedia/libs/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fd04db59d90>> ignored
Manchester by the Sea 2016 1080p BluRay x264-GECKOSimage 1 of 49nextpreviousclose`

**Comment by clinton-hall** [comment]
please update to nightly branch... there is an issue with omdb api site that is currently causing issues.
```
cd /volumeX/Downloads/103 NZB/Scripts/nzbToMedia
git checkout nightly
git pull
```

**Comment by HPMSGEN8** [comment]
Yes that is want i did and it works :)
