### ISSUE TITLE
nzbtoMedia should be updated to support new SAB path references

### ISSUE THREAD

**Issue by gerbil42** [clinton-hall/nzbToMedia#1189]
I'm filing this issue on the request of one of the sabnzbd devs.

I'm running from nzbtomedia nightly branch with auto-update turned on.
Yesterday I hit an issue after updating to the latest SAB develop commit where the calls to nzbtosickbeard.py resulted in a Windows Error and no actual execution of the nzbtomedia processing scripts.  

```
[12:19:33] [INFO]::MAIN: Auto-detected SECTION:SickBeard
Traceback (most recent call last):
  File "D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "D:\SickRage\contrib\nzbToMedia\nzbToMedia.py", line 732, in main
    download_id='')
  File "D:\SickRage\contrib\nzbToMedia\nzbToMedia.py", line 612, in process
    extractFiles(inputDirectory)
  File "D:\SickRage\contrib\nzbToMedia\core\nzbToMediaUtil.py", line 1097, in extractFiles
    for inputFile in listMediaFiles(src, media=False, audio=False, meta=False, archives=True):
  File "D:\SickRage\contrib\nzbToMedia\core\nzbToMediaUtil.py", line 997, in listMediaFiles
    for curFile in os.listdir(path):
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: '\\\\?\\D:\\sabnzbd\\Downloads\\complete\\tv\\Black Mirror S03 COMPLETE 720p WEBRip X264-DEFLATE/*.*'
```
I rolled back to their Master branch, 1.2.0 to confirm that the issue was related to sabnzbd, not nzbtomedia.

I filed the issue with them and they're going to revert the change that causes the label syntax error for Sab 1.2.1 Final, but sab vnext (2.0) is going to use it to work around Windows path length issues.

I'm not sure hot link this issue to that one, but the link is here:
https://github.com/sabnzbd/sabnzbd/issues/815

And here's the quote:

> We will change this back for 1.2.1 final. But can you submit an issue with nzbToMedia?
Because for 2.0.0 (next release) we will be switching to long path (the \\?\ at the start) on Windows.
Otherwise if the extraction path is longer than 250 characters, it will fail on Windows.
I think all he needs to do is use os.path.join when adding that *. * at the end. Because now the slash at the end is the wrong way for Windows.

**Comment by clinton-hall** [comment]
are you able to test this (latest nightly)?

**Comment by gerbil42** [comment]
I've switched sabnzbd back to develop and forced a pull of nzbtomedia nightly.  Trying to find something I want to test with now.

**Comment by gerbil42** [comment]
Clinton,

One thing I've noticed, after running this for a couple days now, is that the completed folders are not being cleaned up, post-processing.  Everything that has been post-processed by nzbtomedia since the listdir changes has been successful, but it leaves behind the folder with .nfo and sample files.

**Comment by clinton-hall** [comment]
Are you able to post logs from such an event?
There haven't been any other changes that should impact this, but if I can see what sections of the code are bing logged etc, I can hopefully narrow in on the appropriate section and test some longs paths etc...

**Comment by gerbil42** [comment]
Here's one log snippet.  All 12 are like this.  These were all normal discovery and snatched by SickRage.

```
2017-02-12 21:01:27 INFO    ::MAIN: Loading config from [D:\SickRage\contrib\nzbToMedia\autoProcessMedia.cfg]
2017-02-12 21:01:27 INFO    ::MAIN: Checking database structure...
2017-02-12 21:01:27 INFO    ::MAIN: Checking if git needs an update
2017-02-12 21:01:28 INFO    ::MAIN: No update needed
2017-02-12 21:01:28 INFO    ::MAIN: nzbToMedia Version:e0594a6e5196adc6d351959e5626109aafa56b95 Branch:nightly (Windows 10)
2017-02-12 21:01:28 WARNING ::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
2017-02-12 21:01:28 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2017-02-12 21:01:28 INFO    ::MAIN: #########################################################
2017-02-12 21:01:28 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
2017-02-12 21:01:28 INFO    ::MAIN: #########################################################
2017-02-12 21:01:28 INFO    ::MAIN: Script triggered from SABnzbd 0.7.17+
2017-02-12 21:01:30 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2017-02-12 21:01:30 INFO    ::MAIN: Calling SickBeard:tv to post-process:Last.Week.Tonight.with.John.Oliver.S04E01.720p.HDTV.x264-BRISK.nzb
2017-02-12 21:01:31 INFO    ::MAIN: Attempting to auto-detect tv fork
2017-02-12 21:01:33 INFO    ::MAIN: SickBeard:tv fork auto-detection successful ...
2017-02-12 21:01:33 INFO    ::MAIN: SickBeard:tv fork set to sickrage
2017-02-12 21:01:33 INFO    ::MAIN: FLATTEN: Flattening directory: \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:33 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Processing folder \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Processing folder \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Found unwanted files: [u'last.week.tonight.with.john.oliver.s04e01.720p.hdtv.x264-brisk.nfo', u'last.week.tonight.with.john.oliver.s04e01.720p.hdtv.x264-brisk.sample.mkv']
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Processing \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT\Last.Week.Tonight.With.John.Oliver.S04E01.720p.HDTV.x264-BRISK.mkv (Last.Week.Tonight.with.John.Oliver.S04E01.720p.HDTV.x264-BRISK.nzb)
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Retrieving episode object for 4x1
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Snatch history had a quality in it, using that: 720p HDTV
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: SR snatched this episode and it is not processed before
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Is ep a priority download: True
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: There is no existing file so there's no worries about replacing it
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Found release name Last.Week.Tonight.with.John.Oliver.S04E01.720p.HDTV.x264-BRISK
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Destination folder for this episode: D:\ServerFolders\Videos\TV\Last Week Tonight with John Oliver\Season 04
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Moving file from \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT\Last.Week.Tonight.With.John.Oliver.S04E01.720p.HDTV.x264-BRISK.mkv to D:\ServerFolders\Videos\TV\Last Week Tonight with John Oliver\Season 04\Last Week Tonight with John Oliver - S04E01 - 720p HDTV.mkv
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Processing succeeded for \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT\Last.Week.Tonight.With.John.Oliver.S04E01.720p.HDTV.x264-BRISK.mkv
2017-02-12 21:01:38 POSTPROCESS::SICKBEARD: Successfully processed
2017-02-12 21:01:39 INFO    ::CLEANDIR: Doing Forceful Clean of \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:39 INFO    ::MAIN: Deleting \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:39 ERROR   ::MAIN: Unable to delete folder \\?\D:\sabnzbd\Downloads\complete\tv\Last Week Tonight with John Oliver S04E01 720p HDT
2017-02-12 21:01:39 INFO    ::MAIN: The D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py script completed successfully.
```

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/blob/nightly/core/nzbToMediaUtil.py#L731
ok... so it appears shutil.rmtree fails with long-paths/unicode..
I'll try some tests and see what I can come up with. In theory it shouldn't be too hard to fix.

**Comment by clinton-hall** [comment]
so shutil.rmtree calls the same os.listdir.... same fix works here :)
Please update to latest nightly and test.

**Comment by gerbil42** [comment]
Looks like the download that happened at 3am picked up the nightly update automatically and everything worked.  Thanks for the quick fix.

```
[03:01:28] [POSTPROCESS]::SICKBEARD: Moving file from \\?\D:\sabnzbd\Downloads\complete\tv\At Midnight 2017 02 13 Tom Lennon 720p WEB x264-HE\at.midnight.2017.02.13.tom.lennon.720p.web.x264-heat.mkv to D:\ServerFolders\Videos\TV\@midnight\Season 2017\@midnight - 2017.02.13 - Kyle Kinane, Tom Lennon, Milana Vayntrub.mkv
[03:01:28] [POSTPROCESS]::SICKBEARD: Processing succeeded for \\?\D:\sabnzbd\Downloads\complete\tv\At Midnight 2017 02 13 Tom Lennon 720p WEB x264-HE\at.midnight.2017.02.13.tom.lennon.720p.web.x264-heat.mkv
[03:01:28] [POSTPROCESS]::SICKBEARD: Successfully processed
[03:01:29] [INFO]::CLEANDIR: Doing Forceful Clean of \\?\D:\sabnzbd\Downloads\complete\tv\At Midnight 2017 02 13 Tom Lennon 720p WEB x264-HE
[03:01:29] [INFO]::MAIN: Deleting \\?\D:\sabnzbd\Downloads\complete\tv\At Midnight 2017 02 13 Tom Lennon 720p WEB x264-HE
[03:01:29] [INFO]::MAIN: The D:\SickRage\contrib\nzbToMedia\nzbToSickBeard.py script completed successfully.
SickBeard: Successfully post-processed @midnight - 2017.02.13 - Kyle Kinane, Tom Lennon, Milana Vayntrub.mkv!
```

**Comment by clinton-hall** [comment]
Yes.. great news.
