### ISSUE TITLE
nzbtomedia problem post-process

### ISSUE THREAD

**Issue by fontes31** [clinton-hall/nzbToMedia#1191]
Hi,
Iam using nzbtomedia processo on my freenas to post-process from sabnzbd (1.2.0) to sickrage. I have this error:

[11:42:40] [INFO]::TRANSCODER: SUCCESS: [the.bl.web.h264-jawn-BUYMORE.2.mkv] has no corruption.
Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 732, in main
    download_id='')
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 621, in process
    download_id, inputCategory, failureLink)
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessTV.py", line 183, in processEpisode
    fork_params['quiet'] = 1
TypeError: list indices must be integers, not str
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x80831dd10>> ignored

**Comment by fontes31** [comment]
on the autoprocessmedia.cfg the force_clean must be 1 or 0 ?

**Comment by clinton-hall** [comment]
Yes, force_clean must be 1 or 0.

Can youi show the full logs. I can't figure out how it gets to this particular error, so I need to see how this is being called.
Are you using master or nightly branch?

**Comment by fontes31** [comment]
Iam using master branch.
Full logs on sab (where the error happens):

[13:35:56] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[13:35:56] [INFO]::MAIN: Checking database structure...
[13:35:56] [INFO]::MAIN: Checking if git needs an update
[13:35:57] [INFO]::MAIN: No update needed
[13:35:57] [INFO]::MAIN: nzbToMedia Version:ad1017712d72970b02f133dbfd7710c18cc3ec37 Branch:nightly (FreeBSD 10.3-RELEASE)
[13:35:57] [INFO]::MAIN: #########################################################
[13:35:57] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[13:35:57] [INFO]::MAIN: #########################################################
[13:35:57] [INFO]::MAIN: Script triggered from SABnzbd
[13:35:57] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[13:35:57] [INFO]::MAIN: Calling SickBeard:tv to post-process:Suits.S06E13.1080p.WEB-DL.DD5.1.H264-RARBG-Obfuscated.nzb
[13:35:57] [INFO]::MAIN: No SickBeard username or Sonarr apikey entered. Performing transcoder functions only
[13:35:57] [INFO]::MAIN: FLATTEN: Flattening directory: /mnt/media/downloads/sabnzbd/complete/tv/Suits.S06E13.1080p.WEB-DL.DD5.1.H264-RARBG-Obfuscated
[13:35:58] [INFO]::TRANSCODER: Checking [Suits.S06E13.1080p.WEB-DL.DD5.1.H264-RARBG-Obfuscated.mkv] for corruption, please stand by ...
[13:35:58] [INFO]::TRANSCODER: SUCCESS: [Suits.S06E13.1080p.WEB-DL.DD5.1.H264-RARBG-Obfuscated.mkv] has no corruption.
Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 732, in main
    download_id='')
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 621, in process
    download_id, inputCategory, failureLink)
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessTV.py", line 183, in processEpisode
    fork_params['quiet'] = 1
TypeError: list indices must be integers, not str
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x80831cd10>> ignored

**Comment by fontes31** [comment]
I have the following in autoprocesstv.py:

     if not username and not apikey:
            logger.info('No SickBeard username or Sonarr apikey entered. Performing transcoder functions only')
            fork, fork_params = "None", []
        elif server_responding("{0}{1}:{2}{3}".format(protocol, host, port, web_root)):
            # auto-detect correct fork
            fork, fork_params = autoFork(section, inputCategory)
        else:
            logger.error("Server did not respond. Exiting", section)
            return [1, "{0}: Failed to post-process - {1} did not respond.".format(section, section)]

Should edit like you said? 

-            fork, fork_params = "None", []
+            fork, fork_params = "None", {}

{} instead of [] ?

**Comment by clinton-hall** [comment]
Please update to latest nightly (do a git pull).

That should apply the `{}` instead of `[]`

**Comment by fontes31** [comment]
ok. did this:

root@sabnzbd_1:/usr/local/share/nzbToMedia # git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From git://github.com/clinton-hall/nzbToMedia
   ad10177..e0594a6  nightly    -> origin/nightly
Updating ad10177..e0594a6
Fast-forward
 core/autoProcess/autoProcessTV.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
root@sabnzbd_1:/usr/local/share/nzbToMedia #


2017-02-12 11:16 GMT+00:00 Clinton Hall <notifications@github.com>:

**Comment by clinton-hall** [comment]
great.. hopefully this works for you now.

**Comment by fontes31** [comment]
i have this error now:

[03:58:41] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[03:58:41] [INFO]::MAIN: Checking database structure...
[03:58:41] [INFO]::MAIN: Checking if git needs an update
[03:58:43] [INFO]::MAIN: No update needed
[03:58:43] [INFO]::MAIN: nzbToMedia Version:e0594a6e5196adc6d351959e5626109aafa56b95 Branch:nightly (FreeBSD 10.3-RELEASE)
[03:58:43] [INFO]::MAIN: #########################################################
[03:58:43] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[03:58:43] [INFO]::MAIN: #########################################################
[03:58:43] [INFO]::MAIN: Script triggered from SABnzbd
[03:58:43] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[03:58:43] [INFO]::MAIN: Calling SickBeard:tv to post-process:the.blacklist.s04e13.1080p.web.h264-jawn-BUYMORE.nzb
[03:58:43] [INFO]::MAIN: No SickBeard username or Sonarr apikey entered. Performing transcoder functions only
[03:58:43] [INFO]::MAIN: FLATTEN: Flattening directory: /mnt/media/downloads/sabnzbd/complete/tv/the.blacklist.s04e13.1080p.web.h264-jawn-BUYMORE.3
[03:58:44] [INFO]::TRANSCODER: Checking [the.blacklist.s04e13.1080p.web.h264-jawn-BUYMORE.3.mkv] for corruption, please stand by ...
[03:58:44] [INFO]::TRANSCODER: SUCCESS: [the.blacklist.s04e13.1080p.web.h264-jawn-BUYMORE.3.mkv] has no corruption.
[03:58:44] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[03:58:44] [ERROR]::SICKBEARD: Server returned status 404
[03:58:44] [ERROR]::MAIN: A problem was reported in the /usr/local/share/nzbToMedia/nzbToSickBeard.py script.
SickBeard: Failed to post-process - Server returned status 404!

**Comment by clinton-hall** [comment]
No SickBeard username or Sonarr apikey entered. Performing transcoder functions only

Are you actually using SickBeard? If so add the username and password in the .cfg

**Comment by fontes31** [comment]
Iam using sickrage, i never had user and pass



No dia 12/02/2017, às 12:13, Clinton Hall <notifications@github.com> escreveu:

**Comment by clinton-hall** [comment]
please update to latest nightly and test again.

**Comment by IngoVals** [comment]
I had the same issue, never used a user and pass. Went into Settings > Help & Info and notice that my synology sickrage package automatically sets a username, tried setting it in the autoProcessMedia.cfg, just username no pass and it seemed to do the trick.
