### ISSUE TITLE
failing to work :(

### ISSUE THREAD

**Issue by ch1p2014** [clinton-hall/nzbToMedia#1196]
hi getting this mad error recently - running nightly build

:29] [INFO]::MAIN: Attemping imdbID lookup for Saw.2004. 720p BRRIP X264 finny
[19:56:29] [INFO]::MAIN: Searching folder and file names for imdbID ...
[19:56:29] [INFO]::MAIN: Searching IMDB for imdbID ...
[19:56:29] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
Traceback (most recent call last):
  File "/scripts/nzbToMedia/TorrentToMedia.py", line 363, in <module>
    exit(main(sys.argv))
  File "/scripts/nzbToMedia/TorrentToMedia.py", line 348, in main
    clientAgent)
  File "/scripts/nzbToMedia/TorrentToMedia.py", line 231, in processTorrent
    status, clientAgent, inputHash, inputCategory)
  File "/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 131, in process
    imdbid = find_imdbid(dirName, inputName)
  File "/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 1072, in find_imdbid
    results = r.json()
  File "/scripts/nzbToMedia/libs/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7100787d8350>> ignored

**Comment by clinton-hall** [comment]
can you check that you have updated to latest nightly? this issue should have been fixed.
Try a manual git pull.

**Comment by ch1p2014** [comment]
getting this now : - 

Already on 'nightly'
Your branch is up-to-date with 'origin/nightly'.
root@ns3032073:/scripts/nzbToMedia# /scripts/nzbToMedia/TorrentToMedia.py
Traceback (most recent call last):
  File "/scripts/nzbToMedia/TorrentToMedia.py", line 6, in <module>
    import core
  File "/scripts/nzbToMedia/core/__init__.py", line 38, in <module>
    from core.autoProcess.autoProcessMusic import autoProcessMusic
ImportError: No module named autoProcessMusic

**Comment by clinton-hall** [comment]
That makes no sense...

backup your autoProcessMedia.cfg, then delete the nzbToMedia folder and re-clone. (then switch to nightly)
Place your saved .cfg back onto the new clone and try.

**Comment by ch1p2014** [comment]
thanx buddy ill give it a go shortly
