### ISSUE TITLE
TypeError: 'NoneType' error with transcoding enabled on nightly

### ISSUE THREAD

**Issue by natoriousbigg** [clinton-hall/nzbToMedia#1210]
I haven't used nzbtomedia for awhile and decided to use it again with the nightly build. Getting this weird error with transcoding enable. I modified autoProcessMedia.cfg from scratch and only modified a few parameters.

    ./nzbToRadarr.py
    [10:34:01] [INFO]::MAIN: Loading config from [/data/postprocess/nzbtomedia-movies/autoProcessMedia.cfg]
    [10:34:01] [INFO]::MAIN: Checking database structure...
    [10:34:01] [DEBUG]::MAIN: Checking Initial Schema database upgrade
    [10:34:01] [DEBUG]::MAIN: InitialSchema upgrade not required
    [10:34:01] [DEBUG]::MAIN: Checking if we can use git commands: git version
    [10:34:01] [DEBUG]::MAIN: Executing git version with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:01] [DEBUG]::MAIN: git version : returned successful
    [10:34:01] [DEBUG]::MAIN: Using: git
    [10:34:01] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:01] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
    [10:34:01] [INFO]::MAIN: Checking if git needs an update
    [10:34:01] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:01] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
    [10:34:01] [DEBUG]::MAIN: Executing git fetch origin with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:02] [DEBUG]::MAIN: git fetch origin : returned successful
    [10:34:02] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:02] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
    [10:34:02] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /data/postprocess/nzbtomedia-movies
    [10:34:02] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
    [10:34:02] [DEBUG]::MAIN: cur_commit = 346c0952e179b7253d90cc1c91c552579d73baca % (newest_commit)= 346c0952e179b7253d90cc1c91c552579d73baca, num_commits_behind = 0, num_commits_ahead = 0
    [10:34:02] [INFO]::MAIN: No update needed
    [10:34:02] [INFO]::MAIN: nzbToMedia Version:346c0952e179b7253d90cc1c91c552579d73baca Branch:nightly (Linux 4.4.0-59-generic)
    [10:34:02] [INFO]::MAIN: #########################################################
    [10:34:02] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
    [10:34:02] [INFO]::MAIN: #########################################################
    [10:34:02] [DEBUG]::MAIN: Options passed into nzbToMedia: ['./nzbToRadarr.py']
    [10:34:02] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
    [10:34:02] [INFO]::MAIN: Searching /data/media/downloads/movies for mediafiles to post-process ...
    [10:34:02] [INFO]::MAIN: Starting manual run for Radarr:movies - Folder: /data/media/downloads/movies/MOVIE
    [10:34:02] [INFO]::MAIN: Checking database for download info for MOVIE ...
    [10:34:02] [INFO]::MAIN: Unable to locate download info for MOVIE, continuing to try and process this release ...
    [10:34:02] [INFO]::MAIN: Auto-detected SECTION:Radarr
    [10:34:02] [INFO]::MAIN: Calling Radarr:movies to post-process:MOVIE
    [10:34:02] [INFO]::MAIN: Attemping imdbID lookup for MOVIE
    [10:34:02] [INFO]::MAIN: Searching folder and file names for imdbID ...
    [10:34:02] [INFO]::MAIN: Searching IMDB for imdbID ...
    [10:34:03] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
    [10:34:03] [INFO]::MAIN: Found imdbID [tt2468774]
    [10:34:03] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:7878/radarr/api/command
    [10:34:03] [DEBUG]::SERVER: Server responded at http://localhost:7878/radarr/api/command
    [10:34:03] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /data/postprocess/nzbtomedia-movies/tests/test.mp4
    [10:34:03] [INFO]::TRANSCODER: Checking [gimchi-confessionmurder2012.1080p.mkv] for corruption, please stand by ...
    [10:34:03] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /data/media/downloads/movies/MOVIE/gimchi-confessionmurder2012.1080p.mkv
    [10:34:03] [INFO]::TRANSCODER: SUCCESS: [gimchi-confessionmurder2012.1080p.mkv] has no corruption.
    [10:34:03] [INFO]::MAIN: Checking for files to be transcoded
    [10:34:03] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /data/media/downloads/movies/MOVIE/gimchi-confessionmurder2012.1080p.mkv
    Traceback (most recent call last):
      File "./nzbToRadarr.py", line 244, in <module>
        result = nzbToMedia.main(sys.argv, section)
      File "/data/postprocess/nzbtomedia-movies/nzbToMedia.py", line 837, in main
        download_id=download_id or None, inputCategory=subsection)
      File "/data/postprocess/nzbtomedia-movies/nzbToMedia.py", line 661, in process
        inputCategory, failureLink)
      File "/data/postprocess/nzbtomedia-movies/core/autoProcess/autoProcessMovie.py", line 245, in process
        result, newDirName = transcoder.Transcode_directory(dirName)
      File "/data/postprocess/nzbtomedia-movies/core/transcoder/transcoder.py", line 753, in Transcode_directory
        command = buildCommands(file, newDir, movieName, bitbucket)
      File "/data/postprocess/nzbtomedia-movies/core/transcoder/transcoder.py", line 385, in buildCommands
        for audio in audioStreams.extend(commentary): #add commentry tracks back here.
    TypeError: 'NoneType' object is not iterable
    Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f3548b02e50>> ignored

config file:

        # nzbToMedia Configuration
        # For more information, visit https://github.com/clinton-hall/nzbToMedia/wiki

        [General]
            # Enable/Disable update notifications
            version_notify = 1
            # Enable/Disable automatic updates
            auto_update = 0
            # Set to the full path to the git executable
            git_path = ""
            # GitHUB user for repo
            git_user = ""
            # GitHUB branch for repo
            git_branch = nightly
            # Enable/Disable forceful cleaning of leftover files following postprocess 
            force_clean = 0
            # Enable/Disable logging debug messages to nzbtomedia.log
            log_debug = 1
            # Enable/Disable logging database messages to nzbtomedia.log
            log_db = 0
            # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
            log_env = 0
            # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
            log_git = 0
            # Set to the directory where your ffmpeg/ffprobe executables are located
            ffmpeg_path = ""
            # Enable/Disable media file checking using ffprobe.
            check_media = 1
            # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
            safe_mode = 1
            # Turn this on to disable additional extraction attempts for failed downloads. Default = 0 will attempt to extract and verify if media is present.
            no_extract_failed = 1

        [Posix]
            ### Process priority setting for External commands (Extractor and Transcoder) on Posix (Unix/Linux/OSX) systems.
            # Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
            niceness = 0
            # Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
            ionice_class = 0
            # Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
            ionice_classdata = 0

        [CouchPotato]
            #### autoProcessing for Movies
            #### movie - category that gets called for post-processing with CPS
            [[movie]]
                enabled = 0
                apikey = ""
                host = localhost
                port = 5050
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                ssl = 0
                web_root = ""
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                method = renamer
                delete_failed = 0
                wait_for = 2
                extract = 1
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if Couchpotato is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""
                ##### Set the recursive directory permissions to the following (0 to disable)
                chmodDirectory = 0

        [Radarr]
            #### autoProcessing for Movies
            #### raCategory - category that gets called for post-processing with Radarr
            [[movie]]
                enabled = 0
                apikey = ""
                host = localhost
                port = 7878
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                web_root = ""
                ssl = 0
                delete_failed = 0
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                nzbExtractionBy = Downloader
                wait_for = 6
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if NzbDrone is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""
            [[movies]]
                enabled = 1
                apikey = **API**
                host = localhost
                port = 7878
                web_root = /radarr
                ssl = 0
                delete_failed = 0
                Torrent_NoLink = 0
                keep_archive = 0
                extract = 0
                nzbExtractionBy = Downloader
                wait_for = 6
                minSize = 0
                delete_ignored = 1
                remote_path = 0
                watch_dir = /data/media/downloads/movies

        [SickBeard]
            #### autoProcessing for TV Series
            #### tv - category that gets called for post-processing with SB
            [[tv]]
                enabled = 0
                host = localhost
                port = 8081
                username = ""
                password = ""
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                web_root = ""
                ssl = 0
                fork = auto
                delete_failed = 0
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                process_method = ""
                # force processing of already processed content when running a manual scan.
                force = 0
                # tell SickRage/Medusa to delete all source files after processing.
                delete_on = 0
                # tell Medusa to ignore check for associated subtitle check when postponing release
                ignore_subs = 0
                extract = 1
                nzbExtractionBy = Downloader
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if SickBeard is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""
                ##### Set the recursive directory permissions to the following (0 to disable)
                chmodDirectory = 0

        [NzbDrone]
            #### Formerly known as NzbDrone this is now Sonarr
            #### autoProcessing for TV Series
            #### ndCategory - category that gets called for post-processing with NzbDrone/Sonarr
            [[tv]]
                enabled = 0
                apikey = ""
                host = localhost
                port = 8989
                username = ""
                password = ""
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                web_root = ""
                ssl = 0
                delete_failed = 0
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                nzbExtractionBy = Downloader
                wait_for = 6
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if NzbDrone is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""

        [HeadPhones]
            #### autoProcessing for Music
            #### music - category that gets called for post-processing with HP
            [[music]]
                enabled = 0
                apikey = ""
                host = localhost
                port = 8181
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                ssl = 0
                web_root = ""
                wait_for = 2
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if HeadPhones is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""

        [Mylar]
            #### autoProcessing for Comics
            #### comics - category that gets called for post-processing with Mylar
            [[comics]]
                enabled = 0
                host = localhost
                port = 8090
                username = ""
                password = ""
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                web_root = ""
                ssl = 0
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if Mylar is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""

        [Gamez]
            #### autoProcessing for Games
            #### games - category that gets called for post-processing with Gamez
            [[games]]
                enabled = 0
                apikey = ""
                host = localhost
                port = 8085
                ###### 
                library = Set to path where you want the processed games to be moved to.
                ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
                ssl = 0
                web_root = ""
                # Enable/Disable linking for Torrents
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                # Set this to minimum required size to consider a media file valid (in MB)
                minSize = 0
                # Enable/Disable deleting ignored files (samples and invalid media files)
                delete_ignored = 0
                ##### Enable if Gamez is on a remote server for this category
                remote_path = 0
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""

        [Network]
            # Enter Mount points as LocalPath,RemotePath and separate each pair with '|'
            # e.g. MountPoints = /volume1/Public/,E:\|/volume2/share/,\\NAS\
            mount_points = ""

        [Nzb]
            ###### clientAgent - Supported clients: sabnzbd, nzbget
            clientAgent = sabnzbd
            ###### SabNZBD (You must edit this if your using nzbToMedia.py with SabNZBD)
            sabnzbd_host = http://localhost
            sabnzbd_port = 8080
            sabnzbd_apikey = **API**
            ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode.
            default_downloadDirectory = /data/media/downloads

        [Torrent]
            ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
            clientAgent = other
            ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
            useLink = hard
            ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
            outputDirectory = /abs/path/to/complete/
            ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
            default_downloadDirectory = ""
            ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
            categories = music_videos, pictures, software, manual
            ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
            noFlatten = pictures, manual
            ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
            uTorrentWEBui = http://localhost:8090/gui/
            uTorrentUSR = your username
            uTorrentPWD = your password
            ###### Transmission (You must edit this if your using TorrentToMedia.py with Transmission)
            TransmissionHost = localhost
            TransmissionPort = 9091
            TransmissionUSR = your username
            TransmissionPWD = your password
            #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
            DelugeHost = localhost
            DelugePort = 58846
            DelugeUSR = your username
            DelugePWD = your password
            ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
            deleteOriginal = 0
            chmodDirectory = 0
            resume = 1
            resumeOnFailure = 1

        [Extensions]
            compressedExtensions = .zip, .rar, .7z, .gz, .bz, .tar, .arj, .1, .01, .001
            mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg, .vob, .iso, .m4v, .ts, .m4ts, .mts
            audioExtensions = .mp3, .aac, .ogg, .ape, .m4a, .asf, .wma, .flac
            metaExtensions = .srt, .ass, .ssa

        [Plex]
            # Only enter these details if you want to update plex library after processing.
            # Do not enter these details if you send the plex notifications from Sickbeard/CouchPotato.
            plex_host = localhost
            plex_port = 32400
            plex_token = ""
            plex_ssl = 0
            # Enter Plex category to section mapping as Category,section and separate each pair with '|'
            # e.g. plex_sections = movie,3|tv,4
            plex_sections = ""

        [Transcoder]
            # getsubs. enable to download subtitles.
            getSubs = 0
            # subLanguages. create a list of languages in the order you want them in your subtitles. 
            subLanguages = eng
            # transcode. enable to use transcoder
            transcode = 1
            ###### duplicate =1 will create a new file. =0 will replace the original
            duplicate = 0
            # concat. joins cd1 cd2 etc into a single video.
            concat = 1
            # IgnoreExtensions is a comma-separated list of extensions that will not be transcoded.
            ignoreExtensions = .mp4
            # outputFastStart. 1 will use -movflags + faststart. 0 will disable this from being used.
            outputFastStart = 1
            # outputQualityPercent. used as -q:a value. 0 will disable this from being used.
            outputQualityPercent = 0
            # outputVideoPath. Set path you want transcoded videos moved to. Leave blank to disable.
            outputVideoPath = ""
            # processOutput. 1 will send the outputVideoPath to SickBeard/CouchPotato. 0 will send original files.
            processOutput = 0
            # audioLanguage. set the 3 letter language code you want as your primary audio track.
            audioLanguage = eng
            # allAudioLanguages. 1 will keep all audio tracks (uses AudioCodec3) where available.
            allAudioLanguages = 1
            # allSubLanguages. 1 will keep all existing sub languages. 0 will discard those not in your list above.
            allSubLanguages = 0
            # embedSubs. 1 will embed external sub/srt subs into your video if this is supported.
            embedSubs = 0
            # burnInSubtitle. burns the default sub language into your video (needed for players that don't support subs)
            burnInSubtitle = 0
            # extractSubs. 1 will extract subs from the video file and save these as external srt files.
            extractSubs = 0
            # externalSubDir. set the directory where subs should be saved (if not the same directory as the video)
            externalSubDir = ""
            # hwAccel. 1 will set ffmpeg to enable hardware acceleration (this requires a recent ffmpeg)
            hwAccel = 0
            # generalOptions. Enter your additional ffmpeg options here with commas to separate each option/value (i.e replace spaces with commas).
            generalOptions = ""
            # outputDefault. Loads default configs for the selected device. The remaining options below are ignored.
            # If you want to use your own profile, leave this blank and set the remaining options below.
            # outputDefault profiles allowed: iPad, iPad-1080p, iPad-720p, Apple-TV2, iPod, iPhone, PS3, xbox, Roku-1080p, Roku-720p, Roku-480p, mkv, mp4-scene-release
            outputDefault = ""
            #### Define custom settings below.
            outputVideoExtension = .mp4
            outputVideoCodec = libx264
            VideoCodecAllow = "libx264,x264,h264,h.264,AVC,avc,mpeg4,MPEG-4,hevc,h265,x265,HEVC,mpeg4,MPEG-4,msmpeg4,MPEG-H,h.265"
            outputVideoPreset = ""
            outputVideoResolution = ""
            outputVideoFramerate = ""
            outputVideoBitrate = ""
            outputVideoCRF = ""
            outputVideoLevel = ""
            outputAudioCodec = libfdk_aac
            AudioCodecAllow = "aac,libfaac,libfdk_aac"
            outputAudioChannels = 2
            outputAudioBitrate = 160000
            outputAudioTrack2Codec = ac3
            AudioCodec2Allow = "ac3,dts,dca,aac,libfaac,libfdk_aac,truehd"
            outputAudioTrack2Channels = ""
            outputAudioTrack2Bitrate = ""
            outputAudioOtherCodec = libfdk_aac
            AudioOtherCodecAllow = "aac,libfaac,libfdk_aac"
            outputAudioOtherChannels = 2
            outputAudioOtherBitrate = 160000
            outputSubtitleCodec = mov_text

        [WakeOnLan]
            ###### set wake = 1 to send WOL broadcast to the mac and test the server (e.g. xbmc) the host and port specified.
            wake = 0
            host = 192.168.1.37
            port = 80
            mac = 00:01:2e:2D:64:e1

        [UserScript]
            #Use user_script for uncategorized downloads
            #Set the categories to use external script.
            #Use "UNCAT" to process non-category downloads, and "ALL" for all defined categories.
            [[UNCAT]]
                #Enable/Disable this subsection category
                enabled = 0
                Torrent_NoLink = 0
                keep_archive = 1
                extract = 1
                #Enable if you are sending commands to a remote server for this category
                remote_path = 0
                #What extension do you want to process? Specify all the extension, or use "ALL" to process all files.
                user_script_mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg
                #Specify the path to your custom script. Use "None" if you wish to link this category, but NOT run any external script.
                user_script_path = /nzbToMedia/userscripts/script.sh
                #Specify the argument(s) passed to script, comma separated in order.
                #for example FP,FN,DN, TN, TL for file path (absolute file name with path), file name, absolute directory name (with path), Torrent Name, Torrent Label/Category.
                #So the result is /media/test/script/script.sh FP FN DN TN TL. Add other arguments as needed eg -f, -r
                user_script_param = FN
                #Set user_script_runOnce = 0 to run for each file, or 1 to only run once (presumably on the entire directory).
                user_script_runOnce = 0
                #Specify the successcodes returned by the user script as a comma separated list. Linux default is 0
                user_script_successCodes = 0
                #Clean after? Note that delay function is used to prevent possible mistake :) Delay is intended as seconds
                user_script_clean = 1
                delay = 120
                #Unique path (directory) created for every download. set 0 to disable.
                unique_path = 1
                ##### Set to path where download client places completed downloads locally for this category
                watch_dir = ""

        [ASCII]
            #Set convert =1 if you want to convert any "foreign" characters to ASCII (UTF8) before passing to SB/CP etc. Default is disabled (0).
            convert = 0

        [passwords]
            # enter the full path to a text file containing passwords to be used for extraction attempts.
            # In the passwords file, every password should be on a new line
            PassWordFile = ""

        [Custom]
            # enter a list (comma separated) of Group Tags you want removed from filenames to help with subtitle matching.
            # e.g remove_group = [rarbag],-NZBgeek
            # be careful if your "group" is a common "real" word. Please report if you have any group replacements that would fall in this category.
            remove_group = ""

**Comment by clinton-hall** [comment]
Ok, just made a change. Can you please try again and see if this is fixed now?

**Comment by scoopydude2002** [comment]
Seems to work now but getting this error with failed download processing:

	[06:37:48] [INFO]::MAIN: Loading config from [/nzbtomedia/autoProcessMedia.cfg]
	[06:37:48] [INFO]::MAIN: Checking database structure...
	[06:37:48] [DEBUG]::MAIN: Checking Initial Schema database upgrade
	[06:37:48] [DEBUG]::MAIN: InitialSchema upgrade not required
	[06:37:48] [DEBUG]::MAIN: Checking if we can use git commands: git version
	[06:37:48] [DEBUG]::MAIN: Executing git version with your shell in /nzbtomedia
	[06:37:49] [DEBUG]::MAIN: Not using: git
	[06:37:49] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
	[06:37:49] [DEBUG]::MAIN: No git specified, can't use git commands
	[06:37:49] [INFO]::MAIN: Checking if git needs an update
	[06:37:49] [DEBUG]::MAIN: No git specified, can't use git commands
	[06:37:49] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
	[06:37:49] [INFO]::MAIN: No update needed
	[06:37:49] [INFO]::MAIN: nzbToMedia Version:11.03 Branch:nightly (Linux 4.4.0-59-generic)
	[06:37:49] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
	[06:37:49] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	[06:37:49] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
	[06:37:49] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
	[06:37:49] [INFO]::MAIN: #########################################################
	[06:37:49] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
	[06:37:49] [INFO]::MAIN: #########################################################
	[06:37:49] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/nzbtomedia/nzbToMedia.py', '/downloads/incomplete-nzb/MOVIES-NAME', 'MOVIES-NAME.nzb', 'MOVIES-NAME', '', 'movies', 'alt.binaries.dvdr', '3', '']
	[06:37:49] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
	[06:37:49] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
	[06:37:49] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_0sl6t0
	[06:37:49] [DEBUG]::MAIN: Adding NZB download info for directory /downloads/incomplete-nzb/MOVIES-NAME to database
	[06:37:49] [INFO]::MAIN: Auto-detected SECTION:Radarr
	[06:37:49] [INFO]::MAIN: Calling Radarr:movies to post-process:MOVIES-NAME.nzb
	[06:37:49] [INFO]::MAIN: Attemping imdbID lookup for MOVIES-NAME.nzb
	[06:37:49] [INFO]::MAIN: Searching folder and file names for imdbID ...
	[06:37:49] [INFO]::MAIN: Searching IMDB for imdbID ...
	[06:37:49] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
	[06:37:49] [INFO]::MAIN: Found imdbID [ttXXXXXXX]
	[06:37:49] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:7878/radarr/api/command
	[06:37:49] [DEBUG]::SERVER: Server responded at http://localhost:7878/radarr/api/command
	[06:37:49] [WARNING]::RADARR: No media files found in directory /downloads/incomplete-nzb/MOVIES-NAME. Processing this as a failed download
	[06:37:49] [POSTPROCESS]::RADARR: FAILED DOWNLOAD DETECTED FOR MOVIES-NAME.nzb
	 to end
	Traceback (most recent call last):
	  File "/nzbtomedia/nzbToMedia.py", line 862, in <module>
	    exit(main(sys.argv))
	  File "/nzbtomedia/nzbToMedia.py", line 792, in main
	    download_id='', failureLink=''.join(args[8:]))
	  File "/nzbtomedia/nzbToMedia.py", line 661, in process
	    inputCategory, failureLink)
	  File "/nzbtomedia/core/autoProcess/autoProcessMovie.py", line 330, in process
	    logger.postprocess("FAILED: The download failed. Sending failed download to {0} for CDH processing".format(fork), section)
	NameError: global name 'fork' is not defined
	Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fc794b9a510>> ignored

**Comment by clinton-hall** [comment]
thanks for reporting this. Please update and try again. hopefully fixed now.

**Comment by scoopydude2002** [comment]
Seems to be fixed now. Thanks!
