### ISSUE TITLE
Error calling nzbToMedia.py through Sabnzbd

### ISSUE THREAD

**Issue by louc918** [clinton-hall/nzbToMedia#1212]
I'm receiving the following error when I try to call nzbToMedia.py through Sabnzbd on my freeness box. 

`Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x8080f6710>> ignored`

I had this working on a previous installation, but had to rebuild the jails inside of freenas, and am not experiencing this error once Sabnzbd competes a download. 

Any assistance you can provide is appreciated.

**Comment by clinton-hall** [comment]
can you post the full log? this last line just means there was an error somewhere. I need to see where.

**Comment by louc918** [comment]
[13:21:30] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[13:21:30] [INFO]::MAIN: Checking database structure...
[13:21:30] [INFO]::MAIN: Database upgrade required: Initial Schema
[13:21:31] [INFO]::MAIN: Checking if git needs an update
[13:21:31] [INFO]::MAIN: No update needed
[13:21:31] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (FreeBSD 10.3-STABLE)
[13:21:31] [INFO]::MAIN: #########################################################
[13:21:31] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[13:21:31] [INFO]::MAIN: #########################################################
[13:21:31] [INFO]::MAIN: Script triggered from SABnzbd
[13:21:31] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[13:21:31] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
[13:21:31] [INFO]::MAIN: Attemping imdbID lookup for Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
[13:21:31] [INFO]::MAIN: Searching folder and file names for imdbID ...
[13:21:31] [INFO]::MAIN: Found imdbID [tt3741834]
[13:21:31] [ERROR]::MAIN: CouchPotato returned the following non-json data
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <!doctype html>
[13:21:31] [ERROR]::MAIN: <html class="">
[13:21:31] [ERROR]::MAIN: <head>
[13:21:31] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[13:21:31] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[13:21:31] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[13:21:31] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[13:21:31] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1455120825" rel="stylesheet" href="/couchpotato/static/style/combined.min.css?1455120825" type="text/css">
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.vendor.min.js?1455120825"></script>
[13:21:31] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.base.min.js?1455120825"></script>
[13:21:31] [ERROR]::MAIN: <link href="/couchpotato/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[13:21:31] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/couchpotato/static/images/homescreen.png" />
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <title>CouchPotato</title>
[13:21:31] [ERROR]::MAIN: </head>
[13:21:31] [ERROR]::MAIN: <body class="page login">
[13:21:31] [ERROR]::MAIN: <form action="" method="post">
[13:21:31] [ERROR]::MAIN: <h1>CouchPotato</h1>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder">
[13:21:31] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[13:21:31] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[13:21:31] [ERROR]::MAIN: </div>
[13:21:31] [ERROR]::MAIN: </form>
[13:21:31] [ERROR]::MAIN: </body>
[13:21:31] [ERROR]::MAIN: </html>
[13:21:31] [INFO]::TRANSCODER: Checking [Lion 2016 720p WEB-DL ShAaNiG.mkv] for corruption, please stand by ...
[13:21:31] [INFO]::TRANSCODER: SUCCESS: [Lion 2016 720p WEB-DL ShAaNiG.mkv] has no corruption.
[13:21:31] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToCouchPotato.py", line 257, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 732, in main
    download_id='')
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 618, in process
    inputCategory, failureLink)
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 243, in process
    result = r.json()
  File "/usr/local/share/nzbToMedia/libs/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x808970290>> ignored

**Comment by louc918** [comment]
`[13:21:30] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[13:21:30] [INFO]::MAIN: Checking database structure...
[13:21:30] [INFO]::MAIN: Database upgrade required: Initial Schema
[13:21:31] [INFO]::MAIN: Checking if git needs an update
[13:21:31] [INFO]::MAIN: No update needed
[13:21:31] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (FreeBSD 10.3-STABLE)
[13:21:31] [INFO]::MAIN: #########################################################
[13:21:31] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[13:21:31] [INFO]::MAIN: #########################################################
[13:21:31] [INFO]::MAIN: Script triggered from SABnzbd
[13:21:31] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[13:21:31] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
[13:21:31] [INFO]::MAIN: Attemping imdbID lookup for Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
[13:21:31] [INFO]::MAIN: Searching folder and file names for imdbID ...
[13:21:31] [INFO]::MAIN: Found imdbID [tt3741834]
[13:21:31] [ERROR]::MAIN: CouchPotato returned the following non-json data
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <!doctype html>
[13:21:31] [ERROR]::MAIN: <html class="">
[13:21:31] [ERROR]::MAIN: <head>
[13:21:31] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[13:21:31] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[13:21:31] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[13:21:31] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[13:21:31] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1455120825" rel="stylesheet" href="/couchpotato/static/style/combined.min.css?1455120825" type="text/css">
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.vendor.min.js?1455120825"></script>
[13:21:31] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.base.min.js?1455120825"></script>
[13:21:31] [ERROR]::MAIN: <link href="/couchpotato/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[13:21:31] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/couchpotato/static/images/homescreen.png" />
[13:21:31] [ERROR]::MAIN: 
[13:21:31] [ERROR]::MAIN: <title>CouchPotato</title>
[13:21:31] [ERROR]::MAIN: </head>
[13:21:31] [ERROR]::MAIN: <body class="page login">
[13:21:31] [ERROR]::MAIN: <form action="" method="post">
[13:21:31] [ERROR]::MAIN: <h1>CouchPotato</h1>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[13:21:31] [ERROR]::MAIN: <div class="ctrlHolder">
[13:21:31] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[13:21:31] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[13:21:31] [ERROR]::MAIN: </div>
[13:21:31] [ERROR]::MAIN: </form>
[13:21:31] [ERROR]::MAIN: </body>
[13:21:31] [ERROR]::MAIN: </html>
[13:21:31] [INFO]::TRANSCODER: Checking [Lion 2016 720p WEB-DL ShAaNiG.mkv] for corruption, please stand by ...
[13:21:31] [INFO]::TRANSCODER: SUCCESS: [Lion 2016 720p WEB-DL ShAaNiG.mkv] has no corruption.
[13:21:31] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Lion.2016.720p.WEB-DL.AAC2.0.x264-ShAaNiG.cp(tt3741834).nzb
Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToCouchPotato.py", line 257, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 732, in main
    download_id='')
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 618, in process
    inputCategory, failureLink)
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 243, in process
    result = r.json()
  File "/usr/local/share/nzbToMedia/libs/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x808970290>> ignored`

**Comment by clinton-hall** [comment]
This indicates that CouchPotato did not return a valid result from the api call.
Please check the CouchPotato settings (host, port, api) you have set in autoProcessMedia.cfg

**Comment by louc918** [comment]
I've checked and rechecked the settings in couchpotato and the autoProcessMedia.cfg file. 

I'm adding a screen shots to see if there's anything suggestions you have. 
[Uploading Screen Shot 2017-02-28 at 12.58.54 PM.pdf…]()

Here's the settings on my .cfg file. (I commented out some of the apikeys, but I've validated this number is correct several times. 

`[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movie]]
        enabled = 1
        apikey = XXXXXXXXXXXX509501d987784baae5f7
        host = localhost
        port = 5050
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = /couchpotato
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 1
        wait_for = 2
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0`

Interestingly enough, Sickrage is working fine, so I'm adding the settings for Sickrage too. 
`[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 8081
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = /sickrage
        ssl = 0
        fork = auto
        delete_failed = 1
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 0
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0`

**Comment by clinton-hall** [comment]
`web_root = /couchpotato`
Are you using reverse proxy or otherwise have the web_root set in CP?

Try enabling debug logging
```
[General]
    Log _debug = 1
```
then postprocess again... this will show the full URL that is being called.

**Comment by louc918** [comment]
"couchpotato" is set in the URL base field in CP Settings > General. Here is what I have in my nginx.conf file:
`    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /usr/local/www/nginx;
            index  index.html index.htm;

        location ^~ /sabnzbd {
           proxy_pass http://127.0.0.1:8080;
        }                                        

       location ^~ /transmission {
            proxy_pass http://127.0.0.1:9091;
        }

        location ^~ /sickrage {
            proxy_pass http://127.0.0.1:8081;
        }

        location ^~ /couchpotato {
            proxy_pass http://127.0.0.1:5050;
        }`

I tried another file with debugging on, here is the output: 
`2017-02-28 22:30:20 INFO    ::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
2017-02-28 22:30:20 INFO    ::MAIN: Checking database structure...
2017-02-28 22:30:20 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2017-02-28 22:30:20 DEBUG   ::MAIN: InitialSchema upgrade not required
2017-02-28 22:30:20 DEBUG   ::MAIN: Checking if we can use git commands: git version
2017-02-28 22:30:20 DEBUG   ::MAIN: Executing git version with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:20 DEBUG   ::MAIN: git version : returned successful
2017-02-28 22:30:20 DEBUG   ::MAIN: Using: git
2017-02-28 22:30:20 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:20 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
2017-02-28 22:30:20 INFO    ::MAIN: Checking if git needs an update
2017-02-28 22:30:20 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:20 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2017-02-28 22:30:20 DEBUG   ::MAIN: Executing git fetch origin with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:21 DEBUG   ::MAIN: git fetch origin : returned successful
2017-02-28 22:30:21 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:21 DEBUG   ::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-02-28 22:30:21 DEBUG   ::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /usr/local/share/nzbToMedia
2017-02-28 22:30:21 DEBUG   ::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-02-28 22:30:21 DEBUG   ::MAIN: cur_commit = 80c8ad58523ab99825c02f3855f9bd3dc9945d57 % (newest_commit)= 80c8ad58523ab99825c02f3855f9bd3dc9945d57, num_commits_behind = 0, num_commits_ahead = 0
2017-02-28 22:30:21 INFO    ::MAIN: No update needed
2017-02-28 22:30:21 INFO    ::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (FreeBSD 10.3-RELEASE)
2017-02-28 22:30:21 DEBUG   ::MAIN: Connecting to transmission: http://localhost:9091
2017-02-28 22:30:21 INFO    ::MAIN: #########################################################
2017-02-28 22:30:21 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
2017-02-28 22:30:21 INFO    ::MAIN: #########################################################
2017-02-28 22:30:21 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/usr/local/share/nzbToMedia/nzbToCouchPotato.py', '/mnt/media/downloads/sabnzbd/complete/movie/The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042)', 'T$
2017-02-28 22:30:21 INFO    ::MAIN: Script triggered from SABnzbd
2017-02-28 22:30:21 DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...
2017-02-28 22:30:21 DEBUG   ::MAIN: Found nzoid: SABnzbd_nzo_bIY_Qt
2017-02-28 22:30:21 DEBUG   ::MAIN: Adding NZB download info for directory /mnt/media/downloads/sabnzbd/complete/movie/The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042) to database
2017-02-28 22:30:21 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2017-02-28 22:30:21 DEBUG   ::MAIN: Checking for archives to extract in directory: /mnt/media/downloads/sabnzbd/complete/movie/The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042)
2017-02-28 22:30:21 INFO    ::MAIN: Calling CouchPotato:movie to post-process:The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042).nzb
2017-02-28 22:30:21 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:5050/couchpotato/api/***********b509501d987784baae5f7
2017-02-28 22:30:21 DEBUG   ::SERVER: Server responded at http://localhost:5050/couchpotato/api/**********8b509501d987784baae5f7
2017-02-28 22:30:21 INFO    ::MAIN: Attemping imdbID lookup for The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042).nzb
2017-02-28 22:30:21 INFO    ::MAIN: Searching folder and file names for imdbID ...
2017-02-28 22:30:21 INFO    ::MAIN: Found imdbID [tt2452042]
2017-02-28 22:30:21 DEBUG   ::MAIN: Opening URL: http://localhost:5050/couchpotato/api/**********8b509501d987784baae5f7/media.get with PARAMS: {'id': 'tt2452042'}
2017-02-28 22:30:21 ERROR   ::MAIN: CouchPotato returned the following non-json data
2017-02-28 22:30:21 ERROR   ::MAIN:
2017-02-28 22:30:21 ERROR   ::MAIN: <!doctype html>
2017-02-28 22:30:21 ERROR   ::MAIN: <html class="">
2017-02-28 22:30:21 ERROR   ::MAIN: <head>
2017-02-28 22:30:21 ERROR   ::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
2017-02-28 22:30:21 ERROR   ::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
2017-02-28 22:30:21 ERROR   ::MAIN: <meta name="mobile-web-app-capable" content="yes">
2017-02-28 22:30:21 ERROR   ::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
2017-02-28 22:30:21 ERROR   ::MAIN: <meta name="robots" content="noindex, nofollow" />
2017-02-28 22:30:21 ERROR   ::MAIN:
2017-02-28 22:30:21 ERROR   ::MAIN: <link data-url="static/style/combined.min.css?1455120825" rel="stylesheet" href="/couchpotato/static/style/combined.min.css?1455120825" type="text/css">
2017-02-28 22:30:21 ERROR   ::MAIN:
2017-02-28 22:30:21 ERROR   ::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.vendor.min.js?1455120825"></script>
2017-02-28 22:30:21 ERROR   ::MAIN: <script type="text/javascript" src="/couchpotato/static/scripts/combined.base.min.js?1455120825"></script>
2017-02-28 22:30:21 ERROR   ::MAIN: <link href="/couchpotato/static/images/favicon.ico" rel="icon" type="image/x-icon" />
2017-02-28 22:30:21 ERROR   ::MAIN: <link rel="apple-touch-icon" href="/couchpotato/static/images/homescreen.png" />
2017-02-28 22:30:21 ERROR   ::MAIN:
2017-02-28 22:30:21 ERROR   ::MAIN: <title>CouchPotato</title>
2017-02-28 22:30:21 ERROR   ::MAIN: </head>
2017-02-28 22:30:21 ERROR   ::MAIN: <body class="page login">
2017-02-28 22:30:21 ERROR   ::MAIN: <form action="" method="post">
2017-02-28 22:30:21 ERROR   ::MAIN: <h1>CouchPotato</h1>
2017-02-28 22:30:21 ERROR   ::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
2017-02-28 22:30:21 ERROR   ::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
2017-02-28 22:30:21 ERROR   ::MAIN: <div class="ctrlHolder">
2017-02-28 22:30:21 ERROR   ::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
2017-02-28 22:30:21 ERROR   ::MAIN: <input class="button" name="submit" type="submit" value="Login" />
2017-02-28 22:30:21 ERROR   ::MAIN: </div>
2017-02-28 22:30:21 ERROR   ::MAIN: </form>
2017-02-28 22:30:21 ERROR   ::MAIN: </body>
2017-02-28 22:30:21 ERROR   ::MAIN: </html>
2017-02-28 22:30:21 DEBUG   ::EXCEPTION: Replacing file name zQuTsfgaTto8OZnY with directory name The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042)
2017-02-28 22:30:21 DEBUG   ::EXCEPTION: Replacing file name /mnt/media/downloads/sabnzbd/complete/movie/The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042)/zQuTsfgaTto8OZnY.mkv with download name /mnt/media/downloads/sab$
2017-02-28 22:30:21 DEBUG   ::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /usr/local/share/nzbToMedia/tests/test.mp4
2017-02-28 22:30:46 INFO    ::TRANSCODER: Checking [The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042).mkv] for corruption, please stand by ...
2017-02-28 22:30:46 DEBUG   ::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /mnt/media/downloads/sabnzbd/complete/movie/The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-Vie$
2017-02-28 22:30:46 INFO    ::TRANSCODER: SUCCESS: [The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042).mkv] has no corruption.
2017-02-28 22:30:46 DEBUG   ::COUCHPOTATO: Opening URL: http://localhost:5050/couchpotato/api/**********b509501d987784baae5f7/renamer.scan with PARAMS: {'download_id': u'SABnzbd_nzo_bIY_Qt', 'media_folder': '/mnt/media/downloads/sabnzbd$
2017-02-28 22:30:46 POSTPROCESS::COUCHPOTATO: Starting renamer scan for The.Peanuts.Movie.2015.720p.BluRay.DTS-ES.x264-VietHD.cp(tt2452042).nzb`

**Comment by louc918** [comment]
I figured this out. I had the Sabnzbd API key in the CouchPotato API field in the scrip config. Thanks for you willingness to help.
