### ISSUE TITLE
QQ: why set mode on folder with no media?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1241]
when my UT restarts it will fire up unprocessed jobs for and i've noticed this a bunch of times. 

```
[12:11:35] [INFO]::MAIN: ## ..::[TorrentToMedia.py]::.. ##
[12:11:35] [INFO]::MAIN: #########################################################
[12:11:35] [DEBUG]::MAIN: Options passed into TorrentToMedia: ['/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py', '/home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]', 'Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]', 'TV', 'AE051AEC8472D165AF9D84A74FDF320F6A295541']
[12:11:35] [DEBUG]::MAIN: Adding TORRENT download info for directory /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] to database
[12:11:35] [DEBUG]::MAIN: Received Directory: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] | Name: Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] | Category: TV
[12:11:35] [DEBUG]::MAIN: SEARCH: Found the Category: TV in directory structure
[12:11:35] [INFO]::MAIN: SEARCH: Found a unique directory Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] in the category directory
[12:11:35] [DEBUG]::MAIN: Determined Directory: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] | Name: Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] | Category: TV
[12:11:35] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[12:11:35] [DEBUG]::MAIN: Stopping torrent Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] in utorrent while processing
[12:11:35] [WARNING]::MAIN: Failed to stop torrent Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] in utorrent
[12:11:35] [INFO]::MAIN: Output directory set to: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [DEBUG]::MAIN: Scanning files in directory: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [DEBUG]::MAIN: Found 0 files in /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [INFO]::MAIN: FLATTEN: Flattening directory: /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [WARNING]::MAIN: Found no media files in /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [INFO]::MAIN: Calling SickBeard:TV to post-process:Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]
[12:11:35] [INFO]::MAIN: Changing file mode of /home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ] to 0777
Traceback (most recent call last):
  File "/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py", line 363, in <module>
    exit(main(sys.argv))
  File "/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py", line 304, in main
    result = processTorrent(inputDirectory, inputName, inputCategory, inputHash, inputID, clientAgent)
  File "/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py", line 223, in processTorrent
    core.rchmod(outputDestination, core.TORRENT_CHMOD_DIRECTORY)
  File "/opt/nzbtomedia/nzbToMedia/core/__init__.py", line 842, in rchmod
    os.chmod(path, mod)
OSError: [Errno 2] No such file or directory: '/home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f8c38251b10>> ignored
```

**Comment by clinton-hall** [comment]
I can't figure out why the directory is found, but has no files in it, and then is determined to not be an existing directory.

Does the directory `/home/processed/TV/Mad.S01E10.HDTV.XviD-2HD [NO-RAR] - [ www.torrentday.com ]` exisit on your system?
