### ISSUE TITLE
Error (TypeError: "'NoneType' object is not callable" ) Just started

### ISSUE THREAD

**Issue by Toddler1984** [clinton-hall/nzbToMedia#1247]
Had to delete and reinstall CP, for some reason I'm getting this error now.. Any Ideas. Using Hall's QKPG

13:05:07] [INFO]::MAIN: #########################################################
[13:05:07] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[13:05:07] [INFO]::MAIN: #########################################################
[13:05:07] [INFO]::MAIN: Script triggered from SABnzbd
[13:05:09] [WARNING]::MAIN: Data from SABnzbd queue could not be parsed
[13:05:12] [WARNING]::MAIN: Data from SABnzbd history could not be parsed
[13:05:12] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[13:05:12] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Split.2016.1080p.BluRay.DTS.x264-TayTO.nzb
[13:05:12] [INFO]::MAIN: Attemping imdbID lookup for Split.2016.1080p.BluRay.DTS.x264-TayTO.nzb
[13:05:12] [INFO]::MAIN: Searching folder and file names for imdbID ...
[13:05:12] [INFO]::MAIN: Searching IMDB for imdbID ...
[13:05:12] [INFO]::MAIN: Found imdbID [tt4972582]
[13:05:12] [ERROR]::MAIN: CouchPotato returned the following non-json data
[13:05:12] [ERROR]::MAIN: 
[13:05:12] [ERROR]::MAIN: <!doctype html>
[13:05:12] [ERROR]::MAIN: <html class="">
[13:05:12] [ERROR]::MAIN: <head>
[13:05:12] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[13:05:12] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[13:05:12] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[13:05:12] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[13:05:12] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[13:05:12] [ERROR]::MAIN: 
[13:05:12] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1493662570" rel="stylesheet" href="/static/style/combined.min.css?1493662570" type="text/css">
[13:05:12] [ERROR]::MAIN: 
[13:05:12] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.vendor.min.js?1493662570"></script>
[13:05:12] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.base.min.js?1493662570"></script>
[13:05:12] [ERROR]::MAIN: <link href="/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[13:05:12] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/static/images/homescreen.png" />
[13:05:12] [ERROR]::MAIN: 
[13:05:12] [ERROR]::MAIN: <title>CouchPotato</title>
[13:05:12] [ERROR]::MAIN: </head>
[13:05:12] [ERROR]::MAIN: <body class="page login">
[13:05:12] [ERROR]::MAIN: <form action="" method="post">
[13:05:12] [ERROR]::MAIN: <h1>CouchPotato</h1>
[13:05:12] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" autofocus="autofocus" /></div>
[13:05:12] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[13:05:12] [ERROR]::MAIN: <div class="ctrlHolder">
[13:05:12] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[13:05:12] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[13:05:12] [ERROR]::MAIN: </div>
[13:05:12] [ERROR]::MAIN: </form>
[13:05:12] [ERROR]::MAIN: </body>
[13:05:12] [ERROR]::MAIN: </html>
[13:05:12] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Split.2016.1080p.BluRay.DTS.x264-TayTO.nzb
Traceback (most recent call last):
File "/share/Download/nzbToMedia/nzbToCouchPotato.py", line 257, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 732, in main
download_id='')
File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 618, in process
inputCategory, failureLink)
File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 243, in process
result = r.json()
File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/requests/models.py", line 805, in json
return complexjson.loads(self.text, **kwargs)
File "/opt/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/opt/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/opt/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x2828f80>> ignored

**Comment by clinton-hall** [comment]
Check the CouchPotato api key and the key set in autoProcessMedia.cfg 
```
[CouchPotato]
    [Movies]
        api_key
```

Also, try deleting all of the .pyc files from the nzbToMedia folder.
Also try enabling debug 
```
[General]
    log_debug = 1
```
as this will put more information into the logs.
