### ISSUE TITLE
Problem with xmlrpclib

### ISSUE THREAD

**Issue by eomacag** [clinton-hall/nzbToMedia#1256]
I have NZBGET running on QNAP TS-451+ , everything is working but the script. For all movies I get this message in the NZBGET logs

_**Post-process-script nzbToMedia.py for Before.the.Flood.2016.DOCU.1080p.WEBRip.x264.DD5.1-FGT failed (terminated with unknown status)
nzbToMedia: ImportError: No module named xmlrpclib**_

I am a Linux newbie so any help is appreciated. More info from my system:

NZBGet 18.0
Python 2.7.12  (python -V)

NzbToMedia is installed in :

[~] # find / -type f -name "nzbToMedia.py" -print
/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py

xmlrpclib as you can see is installed in many folders:

[~] # find / -type f -name "xmlrpclib.py" -print
/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/CloudLink/python/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/HD_Station/usr/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/XBMC/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/container-station/usr/local/container-station/python/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/QCouchPotato/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/HD_Station/usr/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/XBMC/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/container-station/usr/local/container-station/python/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/QCouchPotato/lib/python2.7/xmlrpclib.py
/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/xmlrpclib.py

**Comment by Kvothe1970** [comment]
I have the same issue: 

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToSickBeard.py", line 257, in <module>
    import nzbToMedia
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 520, in <module>
    import core
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/nzbToMediaUtil.py", line 19, in <module>
    import subliminal
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/subliminal/__init__.py", line 16, in <module>
    from .providers import Provider
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/subliminal/providers/__init__.py", line 5, in <module>
    from six.moves.xmlrpc_client import SafeTransport
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/libs/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named xmlrpclib

**Comment by phillipwei** [comment]
Thanks! Above was very helpful, and pointed me in the right direction. However, the location of the proper python path for me was at:

`/share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python` (2.7.12)

I'm not sure why the default environment's `/usr/local/python` was still pointing to 2.7.5
