### ISSUE TITLE
No module named cookielib ?

### ISSUE THREAD

**Issue by shadytree** [clinton-hall/nzbToMedia#1262]
Hi Clinton, hope you are well?

I've just migrated my QNAP and SABNZBD from Sickbeard to Sickrage and have been having a few teething issues getting the post processing scripts working smoothly.

Currently getting the following error message for nzbToSickbeard.py

`Traceback` (most recent call last):
  File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 257, in <module>
    import nzbToMedia
  File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 520, in <module>
    import core
  File "/share/MD0_DATA/Download/nzbToMedia/core/__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/share/MD0_DATA/Download/nzbToMedia/core/autoProcess/autoProcessComics.py", line 5, in <module>
    import requests
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/compat.py", line 39, in <module>
    import cookielib
ImportError: No module named cookielib``

Any wisdom much appreciated

**Comment by clinton-hall** [comment]
which python package is the script now using? cookielib should be a standard inclusion.

**Comment by shadytree** [comment]
FW 4.2.5 (2017/04/13)
QPKGs:
- Python 2.7.1
- Python 3.5.0.2
- SABnzbdplus 170529 V.2.01 Sherpa
- Sickrage v2017.05.23-1 
- SickBeard 141207 (retired)

**Comment by shadytree** [comment]
Also seeing the TV shows sitting in the TV download folder and not get moved properly to their respective series folders. So a bit confused what i've set incorrectly.

**Comment by shadytree** [comment]
Clinton, as regards the above issue. Are my Python versions correct ?

**Comment by clinton-hall** [comment]
The issue is the python installation. For some reason newer python qpkgs are missing some standard libraries.

Can you check to see if the cookielib files exist elsewhere on your system

```
find / -name "cookielib.py"
```

**Comment by shadytree** [comment]
nothing comes up when i run `find / -name "cookielib.py"`

Should I re-instal Python?

**Comment by clinton-hall** [comment]
Try installing QPython or one of the other python qpkgs and see if any of them include cookielib.

**Comment by shadytree** [comment]
I upgraded my Python to 2.7.13 and restarted.
Get the following script errors now
`
Convertig argument 0 to status.
Establishing http connection.
Handling request.
Traceback (most recent call last):
File "/share/Download/nzbToMedia/pushover.py", line 28, in <module>
}), { "Content-type": "application/x-www-form-urlencoded" })
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1001, in request
self._send_request(method, url, body, headers)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1035, in _send_request
self.endheaders(body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 997, in endheaders
self._send_output(message_body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 850, in _send_output
self.send(msg)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 812, in send
self.connect()
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1212, in connect
server_hostname=server_hostname)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 350, in wrap_socket
_context=self)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 566, in __init__
self.do_handshake()
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 788, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)`

**Comment by shadytree** [comment]
Tried numerous different scripts but still getting the same errors since upgrading to Sickrage. My post notification scripts haven't work properly.


Convertig argument 0 to status.
Establishing http connection.
Handling request.
Traceback (most recent call last):
File "/share/Download/nzbToMedia/pushover.py", line 28, in <module>
}), { "Content-type": "application/x-www-form-urlencoded" })
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1001, in request
self._send_request(method, url, body, headers)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1035, in _send_request
self.endheaders(body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 997, in endheaders
self._send_output(message_body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 850, in _send_output
self.send(msg)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 812, in send
self.connect()
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1212, in connect
server_hostname=server_hostname)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 350, in wrap_socket
_context=self)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 566, in __init__
self.do_handshake()
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/ssl.py", line 788, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by clinton-hall** [comment]
It looks like that version of Python is also broken and doesn't have pyOpenssl.

**Comment by shadytree** [comment]
I un-installed and re-installed Python and it seems to have fixed the SSL and cookielib errors.
Thanks again for your wise words and guidance Clinton

**Comment by shadytree** [comment]
ha, I spoke too soon. Now see this error

Convertig argument 0 to status.
Establishing http connection.
Handling request.
Traceback (most recent call last):
File "/share/Download/nzbToMedia/pushover.py", line 30, in <module>
}), { "Content-type": "application/x-www-form-urlencoded" })
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1001, in request
self._send_request(method, url, body, headers)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1035, in _send_request
self.endheaders(body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 997, in endheaders
self._send_output(message_body)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 850, in _send_output
self.send(msg)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 812, in send
self.connect()
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 1204, in connect
HTTPConnection.connect(self)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/httplib.py", line 793, in connect
self.timeout, self.source_address)
File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/socket.py", line 571, in create_connection
raise err
socket.error: [Errno 97] Address family not supported by protocol

**Comment by clinton-hall** [comment]
@krishna7233 
why are you posting here on an old issue with nothing new to add?
