### ISSUE TITLE
ImportError: Shared object "libffi.so.6" not found, required by "_ctypes.so"

### ISSUE THREAD

**Issue by ket0sully** [clinton-hall/nzbToMedia#1273]
For the past few days I am getting post processing errors on all downloads to CouchPotato and SickRage (see below). I've double checked all settings and everything looks ok. I have googled the heck out of this and am at an impasse. Any advice is greatly appreciated.

Traceback (most recent call last):
  File "/usr/local/share/nzbToMedia/nzbToCouchPotato.py", line 254, in <module>
    import nzbToMedia
  File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 520, in <module>
    import core
  File "/usr/local/share/nzbToMedia/core/__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/usr/local/share/nzbToMedia/core/nzbToMediaUtil.py", line 15, in <module>
    import beets
  File "/usr/local/share/nzbToMedia/libs/beets/__init__.py", line 20, in <module>
    from beets.util import confit
  File "/usr/local/share/nzbToMedia/libs/beets/util/__init__.py", line 29, in <module>
    from beets.util import hidden
  File "/usr/local/share/nzbToMedia/libs/beets/util/hidden.py", line 21, in <module>
    import ctypes
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: Shared object "libffi.so.6" not found, required by "_ctypes.so"

**Comment by c0m3d1an** [comment]
What linux are you using?   What does a python -V return?

**Comment by ket0sully** [comment]
FreeNAS 9.10.2
"python: Command not found."

**Comment by ket0sully** [comment]
I have resolved the problem by reinstalling the Headphones plugin which i had removed a few days ago.

**Comment by c0m3d1an** [comment]
Ahh good ol' BeaSDie.  I'm surprised you get "python: Command not found." and everything still works though!  Good catch on the Headphones thing!
