### ISSUE TITLE
Errors after fresh install

### ISSUE THREAD

**Issue by nishirux** [clinton-hall/nzbToMedia#1298]
Using NzbToMedia with Deluge to unpack rared torrents.

Getting python errors after fresh install of nzbtomedia on Windows 2016.
Prerequisites installed. PyWin32, Python 2.7. (tried both 32-bit & 64-bit for both applications)

Error message:
`[18:54:11] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[18:54:11] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[18:54:11] [INFO]::MAIN: Checking if git needs an update
[18:54:12] [INFO]::MAIN: No update needed
[18:54:12] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Windows 10)
Traceback (most recent call last):
  File "F:\Program\nzbToMedia\TorrentToMedia.py", line 363, in <module>
    exit(main(sys.argv))
  File "F:\Program\nzbToMedia\TorrentToMedia.py", line 282, in main
    core.initialize()
  File "F:\Program\nzbToMedia\core\__init__.py", line 345, in initialize
    if int(CFG["WakeOnLan"]["wake"]) == 1:
TypeError: int() argument must be a string or a number, not 'ConfigObj'
`

Anybody have any idea? 

This is my AutoProcessMedia.cfg
```
` [General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 1
    # Set to the full path to the git executable
    git_path = ""
    # GitHUB user for repo
    git_user = ""
    # GitHUB branch for repo
    git_branch = ""
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 1
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 0
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 1
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 1
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 1
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = ""
    # Enable/Disable media file checking using ffprobe.
    check_media = 0
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1
    # Turn this on to disable additional extraction attempts for failed downloads. Default = 0 will attempt to extract and verify if media is present.
    no_extract_failed = 0

[NzbDrone]
    #### autoProcessing for TV Series
    #### ndCategory - category that gets called for post-processing with NzbDrone
    [[tv]]
        enabled = 1
        apikey = <Removed>
        host = localhost
        port = 38084
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = /sonarr
        ssl = 0
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        extract = 1
        nzbExtractionBy = Downloader
        wait_for = 2
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if NzbDrone is on a remote server for this category
        remote_path = 1
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = F:\Torrents\Completed

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = deluge
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, move-sym to move and link back, and no to not use links (copy)
    useLink = hard
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = F:\Torrents\Upppackade
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = F:\Torrents\Completed
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = sonarr
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = ""
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = ""
    DelugePWD = ""
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 0 **ENSURE THIS IS 0, if not, once Sonarr post-processes the release, the torrent will fail.
    chmodDirectory = 0
    resume = 1
    resumeOnFailure = 1

[Extensions]
    compressedExtensions = .zip, .rar, .7z, .gz, .bz, .tar, .arj, .1, .01, .001
    mediaExtensions = .mkv, .avi, .divx, .xvid, .mov, .wmv, .mp4, .mpg, .mpeg, .vob, .iso, .m4v, .ts
    audioExtensions = ""
    metaExtensions = ""
```

`

**Comment by clinton-hall** [comment]
you seem to be missing a lot of extra information from your config. Did you cut some of it off?

when you set it up you need to COPY `autoProcessMedia.cfg.spec` to `autoProcessMedia.cfg` and then edit `autoProcessMedia.cfg` as per your requirements. `autoProcessMedia.cfg.spec` should be un-changed.
