### ISSUE TITLE
Mylar time out but UI works?

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1313]
So i recently realized that my Mylar integration from SAB to nTM to Mylar wasn't configured.
When I set it up ( ln -s nzbToMylar.py ComicRN.py, since SAB didn't seem to want to take the script from categories config) i get the below behaviour.
#### MYLAR
```
08-Nov-2017 12:12:10 - WARNING :: CP Server Thread-3 : ComicRN should be v1.01 and autoProcessComics.py should be v1.0, but they are not and are out of date. Post-Processing may or may not work.
08-Nov-2017 12:12:10 - INFO    :: CP Server Thread-3 : Starting postprocessing for : G.I.Joe.-.A.Real.American.Hero.245.2017.digital.Minutemen-Midas.1
08-Nov-2017 12:12:10 - ERROR   :: Post-Processing : [POST-PROCESSING] Unable to locate downloaded file within items I have snatched. Attempting to parse the filename directly and process.
08-Nov-2017 12:12:10 - INFO    :: Post-Processing : there are 1 files.
08-Nov-2017 12:12:10 - INFO    :: Post-Processing : [FILENAME]: G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:10 - INFO    :: Post-Processing : I have located 1 files that I should be able to post-process. Continuing...
08-Nov-2017 12:12:10 - INFO    :: Post-Processing : Series_Name: G I Joe - A Real American Hero --- WatchComic: G.I. Joe: A Real American Hero
08-Nov-2017 12:12:10 - INFO    :: Post-Processing : manual list: [{'ComicName': u'G.I. Joe: A Real American Hero', 'IssueID': u'634213', 'ComicLocation': u'/home/@send/comics/G I Joe - A Real American Hero 24
5 2017 digital Minutemen-Midas/G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr', 'One-Off': False, 'IssueNumber': u'245', 'ComicID': u'32910'}]
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : [DUPECHECK] Duplicate check for /home/@send/comics/G I Joe - A Real American Hero 245 2017 digital Minutemen-Midas/G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for G.I. Joe: A Real American Hero issue: 245
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : Filepath: /home/@send/comics/G I Joe - A Real American Hero 245 2017 digital Minutemen-Midas/G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : Filename: G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : New_Folder: /opt/mylar/mylar-master/cache/mylar_wiIRZL
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : New_Filepath: /opt/mylar/mylar-master/cache/mylar_wiIRZL/G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:19 - INFO    :: Post-Processing : Attempting to move: move
08-Nov-2017 12:12:28 - INFO    :: Post-Processing : [META-TAGGER] ComicRack tagging meta-tagging processing started.
08-Nov-2017 12:12:29 - WARNING :: Post-Processing : [META-TAGGER][COMIC-TAGGER] Unable to locate file: G.I. Joe - A Real American Hero 245 (2017) (digital) (Minutemen-Midas).cbr
08-Nov-2017 12:12:29 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar-master/mylar/logger.py", line 165, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar-master/mylar/PostProcessor.py", line 1376, in Process
    self.Process_next(comicid, issueid, issuenumOG, ml, stat)
  File "/opt/mylar/mylar-master/mylar/PostProcessor.py", line 2119, in Process_next
    filename_in_error = os.path.split(pcheck, '||')[1]
TypeError: split() takes exactly 1 argument (2 given)
```

####
NTM
```
[12:12:08] [INFO]::MAIN: Loading config from [/opt/Sick-Beard/autoProcessTV/autoProcessMedia.cfg]
[12:12:08] [INFO]::MAIN: Checking database structure...
[12:12:09] [INFO]::MAIN: Checking if git needs an update
[12:12:09] [INFO]::MAIN: No update needed
[12:12:09] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Linux 4.4.92-31-default)
[12:12:09] [ERROR]::MAIN: Failed to connect to uTorrent
[12:12:09] [INFO]::MAIN: #########################################################
[12:12:09] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[12:12:09] [INFO]::MAIN: #########################################################
[12:12:09] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[12:12:09] [INFO]::MAIN: Auto-detected SECTION:Mylar
[12:12:09] [INFO]::MAIN: Calling Mylar:comics to post-process:G.I.Joe.-.A.Real.American.Hero.245.2017.digital.Minutemen-Midas.1.nzb
Traceback (most recent call last):
File "/opt/Sick-Beard/autoProcessTV/nzbToMylar.py", line 123, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 747, in main
download_id='', failureLink=''.join(args[8:]))
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 626, in process
inputCategory)
File "/opt/Sick-Beard/autoProcessTV/core/autoProcess/autoProcessComics.py", line 51, in processEpisode
r = requests.get(url, auth=(username, password), params=params, stream=True, verify=False, timeout=(30, 300))
File "/opt/Sick-Beard/autoProcessTV/libs/requests/api.py", line 69, in get
return request('get', url, params=params, **kwargs)
File "/opt/Sick-Beard/autoProcessTV/libs/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/opt/Sick-Beard/autoProcessTV/libs/requests/sessions.py", line 469, in request
resp = self.send(prep, **send_kwargs)
File "/opt/Sick-Beard/autoProcessTV/libs/requests/sessions.py", line 577, in send
r = adapter.send(request, **kwargs)
File "/opt/Sick-Beard/autoProcessTV/libs/requests/adapters.py", line 431, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8090): Read timed out. (read timeout=300)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f41f1220890>> ignored
```

**Comment by clinton-hall** [comment]
this looks like an issue with Mylar.
```
File "/opt/mylar/mylar-master/mylar/PostProcessor.py", line 2119, in Process_next
filename_in_error = os.path.split(pcheck, '||')[1]
TypeError: split() takes exactly 1 argument (2 given)
```

they should not be doing `os.path.split(pcheck, '||')[1]` as `os.path.split` only accepts 1 argument.

**Comment by mgaulton** [comment]
Ahh ok, i'll bounce it over there. Thanks.

**Comment by mgaulton** [comment]
Migrated it over to mylar's github
