### ISSUE TITLE
Nonetype object is not callable?

### ISSUE THREAD

**Issue by Sarcas666** [clinton-hall/nzbToMedia#1337]
I've been using the scripts for years now, using SABnzbd, Couchpotato & Transmission. Rarely any problems. Lately the minority of my downloads seem to fail.
Downloading, unpacking, repairing etc takes one, two, three hours, and then I get this error "'Nonetype object' is not callable?".
I checked my categories, they are still the same i use for years (and not all downloads fail), even deleted the nzbtomedia.db. I just don't know what is going one.
The only change I made is that in Couchpotato I set the preferred quality to 4K UHD. Any ideas anyone?

Thx

Log:
```
[10:01:14] [INFO]::MAIN: Loading config from [/Applications/nzbToMedia/autoProcessMedia.cfg]
[10:01:14] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToCouchPotato.py
[10:01:14] [INFO]::ENVIRONMENT: SECURITYSESSIONID: 186a8
[10:01:14] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/par2/par2-sl64
[10:01:14] [INFO]::ENVIRONMENT: VERSIONER_PYTHON_PREFER_32_BIT: no
[10:01:14] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[10:01:14] [INFO]::ENVIRONMENT: PYTHONDONTWRITEBYTECODE: 1
[10:01:14] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[10:01:14] [INFO]::ENVIRONMENT: LOGNAME: myusername
[10:01:14] [INFO]::ENVIRONMENT: USER: myusername
[10:01:14] [INFO]::ENVIRONMENT: PATH: /usr/bin:/bin:/usr/sbin:/sbin
[10:01:14] [INFO]::ENVIRONMENT: HOME: /Users/myusername
[10:01:14] [INFO]::ENVIRONMENT: PYTHONUNBUFFERED: 1
[10:01:14] [INFO]::ENVIRONMENT: SAB_BYTES: 56125334835
[10:01:14] [INFO]::ENVIRONMENT: ARGVZERO: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[10:01:14] [INFO]::ENVIRONMENT: DISPLAY: /private/tmp/com.apple.launchd.53C3vc6pGa/org.macosforge.xquartz:0
[10:01:14] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[10:01:14] [INFO]::ENVIRONMENT: SAB_AGE: 4d
[10:01:14] [INFO]::ENVIRONMENT: Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.0FsmZStEWF/Render
[10:01:14] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[10:01:14] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[10:01:14] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_ZVG6b9
[10:01:14] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /Volumes/Media/Usenet incomplete/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)/__ADMIN__/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb.gz
[10:01:14] [INFO]::ENVIRONMENT: XPC_FLAGS: 0x0
[10:01:14] [INFO]::ENVIRONMENT: SAB_CAT: movies
[10:01:14] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)
[10:01:14] [INFO]::ENVIRONMENT: SSL_CERT_FILE: /Applications/SABnzbd.app/Contents/Resources/cacert.pem
[10:01:14] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[10:01:14] [INFO]::ENVIRONMENT: EXECUTABLEPATH: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[10:01:14] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[10:01:14] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/7zip/7za
[10:01:14] [INFO]::ENVIRONMENT: _PY2APP_LAUNCHED_: 1
[10:01:14] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 56125334835
[10:01:14] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[10:01:14] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 7163
[10:01:14] [INFO]::ENVIRONMENT: SAB_FILENAME: Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb
[10:01:14] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.flowed
[10:01:14] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 7283
[10:01:14] [INFO]::ENVIRONMENT: XPC_SERVICE_NAME: org.sabnzbd.team.22132
[10:01:14] [INFO]::ENVIRONMENT: SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.wy80MsASgu/Listeners
[10:01:14] [INFO]::ENVIRONMENT: SAB_PP: 3
[10:01:14] [INFO]::ENVIRONMENT: SHELL: /bin/bash
[10:01:14] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 53426652311
[10:01:14] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[10:01:14] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /Applications/SABnzbd.app/Contents/Resources
[10:01:14] [INFO]::ENVIRONMENT: LC_ALL: en_US.UTF-8
[10:01:14] [INFO]::ENVIRONMENT: SAB_URL: Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb
[10:01:14] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[10:01:14] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[10:01:14] [INFO]::ENVIRONMENT: TMPDIR: /var/folders/5w/r2d89fbn7j18rf4yv8p928zc0000gq/T/
[10:01:14] [INFO]::ENVIRONMENT: SAB_FAILURE_URL:
[10:01:14] [INFO]::ENVIRONMENT: SAB_PRIORITY: 0
[10:01:14] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[10:01:14] [INFO]::ENVIRONMENT: VERSIONER_PYTHON_VERSION: 2.7
[10:01:14] [INFO]::ENVIRONMENT: RESOURCEPATH: /Applications/SABnzbd.app/Contents/Resources
[10:01:14] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/unrar/unrar
[10:01:14] [INFO]::ENVIRONMENT: __CF_USER_TEXT_ENCODING: 0x1F7:0x0:0x5
[10:01:14] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[10:01:14] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.3Beta1
[10:01:14] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)
[10:01:14] [INFO]::MAIN: Checking database structure...
[10:01:14] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[10:01:14] [DEBUG]::MAIN: InitialSchema upgrade not required
[10:01:14] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[10:01:14] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /Applications/nzbToMedia
[10:01:14] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[10:01:14] [DEBUG]::MAIN: Using: "/usr/bin/git"
[10:01:14] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /Applications/nzbToMedia
[10:01:14] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[10:01:14] [INFO]::MAIN: Checking if git needs an update
[10:01:14] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /Applications/nzbToMedia
[10:01:14] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[10:01:14] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /Applications/nzbToMedia
[10:01:15] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[10:01:15] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /Applications/nzbToMedia
[10:01:15] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[10:01:15] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /Applications/nzbToMedia
[10:01:15] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[10:01:15] [DEBUG]::MAIN: cur_commit = 882cc81368c04febb406f4d3326590eece795ebf % (newest_commit)= 882cc81368c04febb406f4d3326590eece795ebf, num_commits_behind = 0, num_commits_ahead = 0
[10:01:15] [INFO]::MAIN: No update needed
[10:01:15] [INFO]::MAIN: nzbToMedia Version:882cc81368c04febb406f4d3326590eece795ebf Branch:OSX (Darwin 17.4.0)
[10:01:15] [WARNING]::MAIN: Failed to locate 7zip. Transcoding of disk images and extraction of .7z files will not be possible!
[10:01:15] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
[10:01:15] [DEBUG]::MAIN: Connecting to transmission: http://127.0.0.1:9091
[10:01:15] [INFO]::MAIN: #########################################################
[10:01:15] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[10:01:15] [INFO]::MAIN: #########################################################
[10:01:15] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/Applications/nzbToMedia/nzbToCouchPotato.py', '/Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)', 'Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb', 'Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)', '', 'movies', 'alt.binaries.flowed', '0', '']
[10:01:15] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[10:01:15] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[10:01:16] [ERROR]::MAIN: Unable to open URL
[10:01:16] [DEBUG]::MAIN: Adding NZB download info for directory /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362) to database
[10:01:16] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[10:01:16] [DEBUG]::MAIN: Checking for archives to extract in directory: /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)
[10:01:16] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb
[10:01:16] [INFO]::MAIN: Attemping imdbID lookup for Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb
[10:01:16] [INFO]::MAIN: Searching folder and file names for imdbID ...
[10:01:16] [INFO]::MAIN: Found imdbID [tt2283362]
[10:01:16] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:5050/api/myapikey/
[10:01:16] [DEBUG]::SERVER: Server responded at http://localhost:5050/api/myapikey/
[10:01:16] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/myapikey/media.get with PARAMS: {'id': 'tt2283362'}
[10:01:16] [DEBUG]::EXCEPTION: Replacing file name 0eb7d63755544c9492e4cbc7e030f4d1 with directory name Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)
[10:01:16] [DEBUG]::EXCEPTION: Replacing file name /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)/0eb7d63755544c9492e4cbc7e030f4d1.mkv with download name /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).mkv
[10:01:16] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /Applications/nzbToMedia/tests/test.mp4
[10:01:16] [INFO]::TRANSCODER: Checking [Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).mkv] for corruption, please stand by ...
[10:01:16] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).mkv
[10:01:16] [INFO]::TRANSCODER: SUCCESS: [Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).mkv] has no corruption.
[10:01:16] [INFO]::SUBTITLES: Attempting to download subtitles for /Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).mkv
[10:01:36] [DEBUG]::COUCHPOTATO: Opening URL: http://localhost:5050/api/myapikey/renamer.scan with PARAMS: {'media_folder': '/Volumes/Media/Downloads/movies/Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362)'}
[10:01:36] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Jumanji.Welcome.to.the.Jungle.2017.REMUX.2160p.10bit.BluRay.UHD.HDR.HEVC.DTS-HD.MA.7.1-LEGi0N.cp(tt2283362).nzb
Traceback (most recent call last):
File "/Applications/nzbToMedia/nzbToCouchPotato.py", line 262, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/Applications/nzbToMedia/nzbToMedia.py", line 802, in main
download_id='', failureLink=''.join(args[8:]))
File "/Applications/nzbToMedia/nzbToMedia.py", line 671, in process
inputCategory, failureLink)
File "/Applications/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 298, in process
r = requests.get(url, params=params, verify=False, timeout=(30, 1800))
File "/Applications/nzbToMedia/libs/requests/api.py", line 69, in get
return request('get', url, params=params, **kwargs)
File "/Applications/nzbToMedia/libs/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/Applications/nzbToMedia/libs/requests/sessions.py", line 469, in request
resp = self.send(prep, **send_kwargs)
File "/Applications/nzbToMedia/libs/requests/sessions.py", line 577, in send
r = adapter.send(request, **kwargs)
File "/Applications/nzbToMedia/libs/requests/adapters.py", line 431, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=5050): Read timed out. (read timeout=1800)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x10afe8cd0>> ignored
```

Part of my settings:
```
# nzbToMedia Configuration

[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 1
    # Set to the full path to the git executable
    git_path = /usr/bin/git
    # GitHUB user for repo
    git_user = ""
    # GitHUB branch for repo
    git_branch = OSX
    # Enable/Disable forceful cleaning of leftover files following postprocess 
    force_clean = 0
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 1
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 0
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 1
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 0
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = /usr/local/bin
    # Enable/Disable media file checking using ffprobe.
    check_media = 1
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1
    # Turn this on to disable additional extraction attempts for failed downloads. Default = 0 will attempt to extract and verify if media is present.
    no_extract_failed = 0

[Posix]
    ### Process priority setting for External commands (Extractor and Transcoder) on Posix (Unix/Linux/OSX) systems.
    # Set the Niceness value for the nice command. These range from -20 (most favorable to the process) to 19 (least favorable to the process).
    niceness = 0
    # Set the ionice scheduling class. 0 for none, 1 for real time, 2 for best-effort, 3 for idle.
    ionice_class = 0
    # Set the ionice scheduling class data. This defines the class data, if the class accepts an argument. For real time and best-effort, 0-7 is valid data.
    ionice_classdata = 0

[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movies]]
        enabled = 1
        apikey = myapikey
        host = localhost
        port = 5050
        ssl = 0
        web_root = ""
        omdbapikey = myapikey
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 1
        wait_for = 90
        extract = 1
        minSize = 0
        delete_ignored = 1
        remote_path = 0
        watch_dir = /Volumes/Media/Downloads/movies
        chmodDirectory = 0
```

**Comment by clinton-hall** [comment]
Look at CouchPotato logs at [10:01:36] 
The call to have CouchPotato do the renaming appears to time-out (although this should be caught and logged differently) so I want to see what is going wrong and preventing CouchPotato from returning status for this call.

**Comment by Sarcas666** [comment]
Thanks for your reply. Those CP logs are gone already, but I recognize what you say. When the files are being processed renaming can take 30-60 minutes, especially when SABnzdb is busy with expanding other files, verifying or repairing. This happens all on the same external drive. I tried setting timeouts in the config-files rather big, but I am not sure it helps. Is there anywhere I can increase this `read timeout=1800` setting I see mentioned?
I will keep an eye out for when it happens again and will get back to you with the logs.

**Comment by clinton-hall** [comment]
ok, this is interesting.
Previously the CouchPotato renamer was an instantaneous call, where is acknowledged the request and then slowly did it's renaming (where we use the "waif_for" timer to check that this completes.
If CP is not returning status of api call until renaming completes, then this needs to change.

To test, can you try editing https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMovie.py#L298
from
```
                    r = requests.get(url, params=params, verify=False, timeout=(30, 3600))
```
to
```
                    r = requests.get(url, params=params, verify=False, timeout=(30, 3600))
```
and let me know how this goes?
