### ISSUE TITLE
Postprocess fails after 1800 seconds

### ISSUE THREAD

**Issue by fooper** [clinton-hall/nzbToMedia#1349]
Hi

Recently starting to get below error on all TV downloads, seems the script runs for 1800 seconds and then fails. Sickrage is working and listening on port 8082, might be a problem with their postprocessing code but Im not sure and dont know where to look in Sickrage or nzbtomedia. Any help would be appreciated.

Server is Ubuntu 18.04 in a virtual environment. 

[00:20:27] [INFO]::MAIN: Loading config from [/home/User/sickrage/contrib/nzbToMedia/autoProcessMedia.cfg]
[00:20:27] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py
[00:20:27] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /usr/bin/par2
[00:20:27] [INFO]::ENVIRONMENT: AVAHI_COMPAT_NOWARN: 1
[00:20:27] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[00:20:27] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[00:20:27] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.2
[00:20:27] [INFO]::ENVIRONMENT: HOME: /home/User
[00:20:27] [INFO]::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[00:20:27] [INFO]::ENVIRONMENT: SAB_BYTES: 2492031994
[00:20:27] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[00:20:27] [INFO]::ENVIRONMENT: SAB_AGE: 1d
[00:20:27] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[00:20:27] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[00:20:27] [INFO]::ENVIRONMENT: LANGUAGE: en_US:en
[00:20:27] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[00:20:27] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_KfIIlV
[00:20:27] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /home/User/local/temp/SomeSerie-AMZN-group/__ADMIN__/SomeSerie-AMZN-group.nzb.gz
[00:20:27] [INFO]::ENVIRONMENT: SAB_CAT: tv
[00:20:27] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /home/User/local/complete/SomeSerie-AMZN-group
[00:20:27] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[00:20:27] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[00:20:27] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[00:20:27] [INFO]::ENVIRONMENT: INVOCATION_ID: 7c311b3e69e14141974283c7d2e4f1f1
[00:20:27] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 2492031994
[00:20:27] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND:
[00:20:27] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 8744
[00:20:27] [INFO]::ENVIRONMENT: SAB_FILENAME: SomeSerie-AMZN-group.nzb
[00:20:27] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.hdtv.x264
[00:20:27] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 249
[00:20:27] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 2238632782
[00:20:27] [INFO]::ENVIRONMENT: SAB_PP: 3
[00:20:27] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /usr/bin
[00:20:27] [INFO]::ENVIRONMENT: SAB_URL: http://192.168.1.133/getnzb/token
[00:20:27] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[00:20:27] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[00:20:27] [INFO]::ENVIRONMENT: SAB_FAILURE_URL: http://192.168.1.133/failed/?guidtoken
[00:20:27] [INFO]::ENVIRONMENT: SAB_PRIORITY: 1
[00:20:27] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[00:20:27] [INFO]::ENVIRONMENT: JOURNAL_STREAM: 9:27443
[00:20:27] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /usr/bin/unrar
[00:20:27] [INFO]::ENVIRONMENT: PWD: /
[00:20:27] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /usr/bin/7za
[00:20:27] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: SomeSerie-AMZN-group
[00:20:27] [INFO]::MAIN: Checking database structure...
[00:20:27] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[00:20:27] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[00:20:27] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[00:20:27] [DEBUG]::MAIN: InitialSchema upgrade not required
[00:20:27] [DEBUG]::MAIN: Checking if we can use git commands: git version
[00:20:27] [DEBUG]::MAIN: Executing git version with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:27] [DEBUG]::MAIN: git version : returned successful
[00:20:27] [DEBUG]::MAIN: Using: git
[00:20:27] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:27] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[00:20:27] [INFO]::MAIN: Checking if git needs an update
[00:20:27] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:27] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[00:20:27] [DEBUG]::MAIN: Executing git fetch origin with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:28] [DEBUG]::MAIN: git fetch origin : returned successful
[00:20:28] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:28] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[00:20:28] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /home/User/sickrage/contrib/nzbToMedia
[00:20:28] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[00:20:28] [DEBUG]::MAIN: cur_commit = ee243fbba51e66ed12ad17d57e016b4db5bdc720 % (newest_commit)= ee243fbba51e66ed12ad17d57e016b4db5bdc720, num_commits_behind = 0, num_commits_ahead = 0
[00:20:28] [INFO]::MAIN: No update needed
[00:20:28] [INFO]::MAIN: nzbToMedia Version:ee243fbba51e66ed12ad17d57e016b4db5bdc720 Branch:master (Linux 4.15.0-20-generic)
[00:20:28] [INFO]::MAIN: #########################################################
[00:20:28] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[00:20:28] [INFO]::MAIN: #########################################################
[00:20:28] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/home/User/sickrage/contrib/nzbToMedia/nzbToSickBeard.py', '/home/User/local/complete/SomeSerie-AMZN-group', 'SomeSerie-AMZN-group.nzb', 'SomeSerie-AMZN-group', '', 'tv', 'alt.binaries.hdtv.x264', '0', 'http://192.168.1.133/failed/?guid=token
[00:20:28] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[00:20:28] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[00:20:28] [ERROR]::MAIN: Unable to open URL
[00:20:28] [DEBUG]::MAIN: Adding NZB download info for directory /home/User/local/complete/SomeSerie-AMZN-group to database
[00:20:28] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 736826, u'None', u'None', u'SomeSerie-AMZN-group.nzb', u'/home/User/local/complete/SomeSerie-AMZN-group']
[00:20:28] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[00:20:28] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/User/local/complete/SomeSerie-AMZN-group
[00:20:28] [INFO]::MAIN: Calling SickBeard:tv to post-process:SomeSerie-AMZN-group.nzb
[00:20:28] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8082
[00:20:28] [DEBUG]::SERVER: Server responded at http://localhost:8082
[00:20:28] [INFO]::MAIN: Attempting to auto-detect tv fork
[00:20:28] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[00:20:28] [INFO]::MAIN: SickBeard:tv fork set to sickrage
[00:20:28] [INFO]::MAIN: FLATTEN: Flattening directory: /home/User/local/complete/SomeSerie-AMZN-group
[00:20:28] [DEBUG]::MAIN: Checking for empty folders in:/home/User/local/complete/SomeSerie-AMZN-group
[00:20:28] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /home/User/sickrage/contrib/nzbToMedia/tests/test.mp4
[00:20:28] [INFO]::TRANSCODER: Checking [SomeSerie-AMZN-group.mkv] for corruption, please stand by ...
[00:20:28] [DEBUG]::MAIN: calling command: /usr/local/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /home/User/local/complete/SomeSerie-AMZN-group/SomeSerie-AMZN-group.mkv
[00:20:28] [INFO]::TRANSCODER: SUCCESS: [SomeSerie-AMZN-group.mkv] has no corruption.
[00:20:28] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[00:20:28] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8082/home/postprocess/processEpisode with params: {'nzbName': 'SomeSerie-AMZN-group.nzb', 'quiet': 1, 'failed': '0', 'force_next': 1, 'proc_dir': '/home/User/local/complete/SomeSerie-AMZN-group', 'delete_on': 1}
Traceback (most recent call last):
File "/home/User/sickrage/contrib/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/home/User/sickrage/contrib/nzbToMedia/nzbToMedia.py", line 802, in main
download_id='', failureLink=''.join(args[8:]))
File "/home/User/sickrage/contrib/nzbToMedia/nzbToMedia.py", line 674, in process
download_id, inputCategory, failureLink)
File "/home/User/sickrage/contrib/nzbToMedia/core/autoProcess/autoProcessTV.py", line 274, in processEpisode
r = s.get(url, auth=(username, password), params=fork_params, stream=True, verify=False, timeout=(30, 1800))
File "/home/User/sickrage/contrib/nzbToMedia/libs/requests/sessions.py", line 481, in get
return self.request('GET', url, **kwargs)
File "/home/User/sickrage/contrib/nzbToMedia/libs/requests/sessions.py", line 469, in request
resp = self.send(prep, **send_kwargs)
File "/home/User/sickrage/contrib/nzbToMedia/libs/requests/sessions.py", line 577, in send
r = adapter.send(request, **kwargs)
File "/home/User/sickrage/contrib/nzbToMedia/libs/requests/adapters.py", line 431, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8082): Read timed out. (read timeout=1800)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fce58cf6850>> ignored

**Comment by clinton-hall** [comment]
Check SickRage logs at the time of a failure... i.e. `[00:20:28]`

How is SickRage set to process the downloads? Does it move (or copy) from 1 drive to another drive? Is it transferring across network mounts? These can cause delays in the processing, but still shouldn't be 30+ minutes (unless it is a really large file).

**Comment by fooper** [comment]
It is set to copy it from the host to the nas, had the same setup for years. Going to look in the logs if I can spot anything

**Comment by fooper** [comment]
Today everything works again. Haven't had time to look into it. Not sure what is going on.
