### ISSUE TITLE
error post processing

### ISSUE THREAD

**Issue by slayerXcore** [clinton-hall/nzbToMedia#1353]
Traceback (most recent call last):
File "C:\PythonApps\Sab-Scripts\nzbToMedia-master\nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "C:\PythonApps\Sab-Scripts\nzbToMedia-master\nzbToMedia.py", line 702, in main
core.initialize(section)
File "C:\PythonApps\Sab-Scripts\nzbToMedia-master\core\__init__.py", line 249, in initialize
MYAPP = RunningProcess()
File "C:\PythonApps\Sab-Scripts\nzbToMedia-master\core\nzbToMediaUtil.py", line 1251, in __init__
self.process = WindowsProcess()
File "C:\PythonApps\Sab-Scripts\nzbToMedia-master\core\nzbToMediaUtil.py", line 1266, in __init__
from win32event import CreateMutex
ImportError: DLL load failed: %1 is not a valid Win32 application.
Exception AttributeError: "'WindowsProcess' object has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <core.nzbToMediaUtil.WindowsProcess object at 0x00000000026DFBA8>> ignored

Win 10 x64 version 1803 build 17134.81
Python Version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)

**Comment by slayerXcore** [comment]
Seems my pywin32 got uninstalled when I updated things
