### ISSUE TITLE
missing global "delete_failed"

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1355]
I'm noticing PP from SAB for HP is failing, not sure when it started as I just noticed. 
I noticed many similar jobs doing the same thing, only HP seems affected.
Adding Delete_failed = 1 to the Music sections of the config didn't appear to make a difference.

[11:29:24] [INFO]::MAIN: Loading config from [/opt/Sick-Beard/autoProcessTV/autoProcessMedia.cfg]
[11:29:24] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToHeadPhones.py
[11:29:24] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /usr/local/bin/par2
[11:29:24] [INFO]::ENVIRONMENT: AVAHI_COMPAT_NOWARN: 1
[11:29:24] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[11:29:24] [INFO]::ENVIRONMENT: SAB_PP_STATUS: -1
[11:29:24] [INFO]::ENVIRONMENT: LOGNAME: root
[11:29:24] [INFO]::ENVIRONMENT: USER: root
[11:29:24] [INFO]::ENVIRONMENT: HOME: /opt
[11:29:24] [INFO]::ENVIRONMENT: PATH: /sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin
[11:29:24] [INFO]::ENVIRONMENT: SAB_BYTES: 0
[11:29:24] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 0
[11:29:24] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[11:29:24] [INFO]::ENVIRONMENT: SHELL: /bin/sh
[11:29:24] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[11:29:24] [INFO]::ENVIRONMENT: SAB_FAIL_MSG: Download failed - Not on your server(s) - https://sabnzbd.org/not-complete
[11:29:24] [INFO]::ENVIRONMENT: SHLVL: 3
[11:29:24] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[11:29:24] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_7O7idn
[11:29:24] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /home/@downloads/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT/__ADMIN__/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.nzb.gz
[11:29:24] [INFO]::ENVIRONMENT: SAB_CAT: music
[11:29:24] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /home/@send/Music/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.1
[11:29:24] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[11:29:24] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[11:29:24] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[11:29:24] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /usr/bin/7za
[11:29:24] [INFO]::ENVIRONMENT: SAB_AGE: 17710d
[11:29:24] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[11:29:24] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 0
[11:29:24] [INFO]::ENVIRONMENT: XDG_RUNTIME_DIR: /run/user/0
[11:29:24] [INFO]::ENVIRONMENT: SAB_FILENAME: Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT
[11:29:24] [INFO]::ENVIRONMENT: SAB_GROUP:
[11:29:24] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME:
[11:29:24] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 0
[11:29:24] [INFO]::ENVIRONMENT: LC_CTYPE: en_US.UTF-8
[11:29:24] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /opt/sabnzbd
[11:29:24] [INFO]::ENVIRONMENT: SAB_URL: /home/import2/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.nzb.gz
[11:29:24] [INFO]::ENVIRONMENT: XDG_SESSION_ID: 9987
[11:29:24] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[11:29:24] [INFO]::ENVIRONMENT: _: /usr/bin/python
[11:29:24] [INFO]::ENVIRONMENT: SAB_FAILURE_URL:
[11:29:24] [INFO]::ENVIRONMENT: SAB_PRIORITY: 1
[11:29:24] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[11:29:24] [INFO]::ENVIRONMENT: SAB_PP: 3
[11:29:24] [INFO]::ENVIRONMENT: OLDPWD: /opt/sabnzbd
[11:29:24] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /usr/bin/unrar
[11:29:24] [INFO]::ENVIRONMENT: PWD: /opt/sabnzbd
[11:29:24] [INFO]::ENVIRONMENT: SAB_VERSION: 2.4.0-develop
[11:29:24] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT
[11:29:24] [INFO]::MAIN: Checking database structure...
[11:29:24] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[11:29:24] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[11:29:24] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[11:29:24] [DEBUG]::MAIN: InitialSchema upgrade not required
[11:29:24] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output: git version 2.13.7
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[11:29:24] [DEBUG]::MAIN: Using: "/usr/bin/git"
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output: refs/heads/nightly
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[11:29:24] [INFO]::MAIN: Checking if git needs an update
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output: 58ee2b0d521d66713e33e351b623a387244599b0
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output:
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output: 58ee2b0d521d66713e33e351b623a387244599b0
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[11:29:24] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/Sick-Beard/autoProcessTV
[11:29:24] [DEBUG]::MAIN: git output:
[11:29:24] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[11:29:24] [DEBUG]::MAIN: cur_commit = 58ee2b0d521d66713e33e351b623a387244599b0 % (newest_commit)= 58ee2b0d521d66713e33e351b623a387244599b0, num_commits_behind = 0, num_commits_ahead = 0
[11:29:24] [INFO]::MAIN: No update needed
[11:29:24] [INFO]::MAIN: nzbToMedia Version:58ee2b0d521d66713e33e351b623a387244599b0 Branch:nightly (Linux 4.4.138-59-default)
[11:29:24] [INFO]::MAIN: #########################################################
[11:29:24] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[11:29:24] [INFO]::MAIN: #########################################################
[11:29:24] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/Sick-Beard/autoProcessTV/nzbToHeadPhones.py', '/home/@send/Music/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.1', 'Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT', 'Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT', '', 'music', 'None', '-1', '']
[11:29:24] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[11:29:24] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[11:29:25] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_7O7idn
[11:29:25] [DEBUG]::MAIN: Adding NZB download info for directory /home/@send/Music/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.1 to database
[11:29:25] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 736873, u'SABnzbd_nzo_7O7idn', u'SABnzbd_nzo_7O7idn', u'Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT', u'/home/@send/Music/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.1']
[11:29:25] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
[11:29:25] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/@send/Music/Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT.1
[11:29:25] [INFO]::MAIN: Calling HeadPhones:music to post-process:Ramones-End Of The Century (Deluxe Edition)-BONUS TRACKS-WEB-2005-ENTiTLED iNT
[11:29:25] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8181/api
[11:29:25] [DEBUG]::SERVER: Server responded at http://localhost:8181/api
[11:29:25] [WARNING]::HEADPHONES: FAILED DOWNLOAD DETECTED
Traceback (most recent call last):
File "/opt/Sick-Beard/autoProcessTV/nzbToHeadPhones.py", line 124, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 847, in main
download_id='', failureLink=''.join(args[8:]))
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 719, in process
result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
File "/opt/Sick-Beard/autoProcessTV/core/autoProcess/autoProcessMusic.py", line 256, in process
if delete_failed and os.path.isdir(dirName) and not os.path.dirname(dirName) == dirName:
NameError: global name 'delete_failed' is not defined
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f11a834c210>> ignored

**Comment by clinton-hall** [comment]
Just pushed a fix for this. When I added in the flow to support Lidarr (which isn't complete yet) I added the delete_failed option but no-one identified that this parameter wasn't read in for HP.

**Comment by mgaulton** [comment]
Awesome, thanks.

**Comment by MatthewYax** [comment]
Still getting an error - did a git pull, said I was up-to-date, 

NZBget error Below ------

NFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f6f9d3be590>> ignored
-- | -- | --
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: KeyError: 'delete_failed'
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: delete_failed = int(cfg["delete_failed"])
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: File "/opt/nzbtomedia/core/autoProcess/autoProcessMusic.py", line 124, in process
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: File "/opt/nzbtomedia/nzbToMedia.py", line 719, in process
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: failureLink=failureLink)
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: File "/opt/nzbtomedia/nzbToMedia.py", line 818, in main
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: result = nzbToMedia.main(sys.argv, section)
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: File "/opt/nzbtomedia/nzbToLidarr.py", line 244, in <module>
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: Traceback (most recent call last):
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: [19:38:52] [INFO]::MAIN: Calling HeadPhones:Music to post-process:Linkin Park-One More Light-CD-FLAC-2017-RiBS
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: [19:38:52] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: [19:38:52] [INFO]::MAIN: Script triggered from NZBGet Version 20.0.
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: [19:38:52] [INFO]::MAIN: #########################################################
INFO | Tue Aug 28 2018 19:38:52 | nzbToLidarr: [19:38:52] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##

**Comment by clinton-hall** [comment]
ok, Lidarr support isn't fully implemented yet, but in order to track down this issue, can you posy the config details under your `Lidarr` section?

**Comment by MatthewYax** [comment]
What config? Lidarr, nzbtomedia, nzbtolidar, nzbget... ???? its all basic except IP and API key.

**Comment by clinton-hall** [comment]
I was meaning /opt/nzbtomedia/autoProcessMedia.cfg
```
[Lidarr]
    [[Music]]
```
But I note you are using nzbget so the settings should be imported from the WebUI... 

I just made a change (nightly branch) so if you update to latest nightly that part should be fixed.

**Comment by clinton-hall** [comment]
yeah, this should be working now.
What do logs show when running latest nightly branch?

**Comment by foldingarmchair** [comment]
Installed Lidarr today and added api key to the nzbtomedia autoconfig.  Using radarr and sonarr successfully but sab gives me the following error when downloading and running the music category / script.

`NameError: global name 'download_id' is not defined
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fbf28329c10>> ignored`

as far as i can tell i'm on nightly
`
commit a63cf34a4a8bf0f51dd32180a66e69cdc89a44b3 (HEAD -> nightly, origin/nightly)
Author: clinton-hall <fock_wulf@hotmail.com>
Date:   Fri Aug 31 11:59:42 2018 +1200

    add better logging of movie name when added to CP. Fixes #1341

commit ca961e407e3fd02a0a34c1ac48bc3b6a144c408b
Author: clinton-hall <fock_wulf@hotmail.com>
Date:   Thu Aug 30 20:54:12 2018 +1200

    fix minor description error.

commit e5066cba0d79eb5d36484bb6da8c8d58ff429c47
Author: clinton-hall <fock_wulf@hotmail.com>
Date:   Thu Aug 30 20:42:20 2018 +1200

    improve logging for imdb id lookup. #1341

commit 01bb0b9bc195047627b712b0230ef466cc875f3b
Author: clinton-hall <fock_wulf@hotmail.com>
Date:   Thu Aug 30 08:01:00 2018 +1200

    Fixed NZBGet save of Lidarr config. Fixes #1355
`
