### ISSUE TITLE
Unable to manual process to sickrage: Server returned status 500

### ISSUE THREAD

**Issue by Sidhy** [clinton-hall/nzbToMedia#1356]
Not sure if this problem is sickrage related or caused by nzbToMedia

Here is all the info 
### ERROR
```
[13:23:27] [INFO]::MAIN: Starting manual run for SickBeard:tvshows - Folder: /mnt/Storage/Downloads/complete/tvshows/Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS
[13:23:27] [INFO]::MAIN: Checking database for download info for Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS ...
[13:23:27] [INFO]::MAIN: Unable to locate download info for Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS, continuing to try and process this release ...
[13:23:27] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[13:23:27] [INFO]::MAIN: Calling SickBeard:tvshows to post-process:Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS
[13:23:27] [INFO]::MAIN: Attempting to auto-detect tvshows fork
[13:23:27] [INFO]::MAIN: SickBeard:tvshows fork auto-detection failed
[13:23:27] [INFO]::MAIN: SickBeard:tvshows fork set to default
[13:23:27] [INFO]::MAIN: FLATTEN: Flattening directory: /mnt/Storage/Downloads/complete/tvshows/Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS
[13:23:27] [INFO]::TRANSCODER: Checking [Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS.mkv] for corruption, please stand by ...
[13:23:27] [INFO]::TRANSCODER: SUCCESS: [Law.&.Order.Special.Victims.Unit.S19E17.720p.HDTV.x264-AVS.mkv] has no corruption.
[13:23:27] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[13:23:27] [ERROR]::SICKBEARD: Server returned status 500
[13:23:27] [ERROR]::MAIN: A problem was reported when trying to perform a manual run for SickBeard:tvshows.
```

Link to sickrage issue: https://github.com/SickRage/SickRage/issues/4447#issuecomment-401599393

### INFO FROM SICKRAGE
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-6-amd64-x86_64-with-debian-9.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 2483, in processEpisode
    process_path = ss(kwargs.get('dir', xhtml_unescape(proc_dir)) or '')
  File "/opt/sickrage/lib/tornado/escape.py", line 68, in xhtml_unescape
    return re.sub(r"&(#?)(\w+?);", _convert_entity, _unicode(value))
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

```

**Comment by Sidhy** [comment]
### Additional Findings
After I manually removed the nzbtomedia.db file it does **not** error out anymore

### Log
```
SickBeard: Failed to post-process - Server returned status 500!
$ rm nzbtomedia.db
$ ./nzbToMedia.py
[13:55:51] [INFO]::MAIN: #########################################################
[13:55:51] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[13:55:51] [INFO]::MAIN: #########################################################
[13:55:51] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[13:55:51] [INFO]::MAIN: Searching /mnt/Storage/Downloads/complete/tvshows for mediafiles to post-process ...
[13:55:51] [INFO]::MAIN: Starting manual run for SickBeard:tvshows - Folder: /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p
[13:55:51] [INFO]::MAIN: Checking database for download info for Marvels.luke.Cage..s02e03..1080p ...
[13:55:51] [INFO]::MAIN: Unable to locate download info for Marvels.luke.Cage..s02e03..1080p, continuing to try and process this release ...
[13:55:51] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[13:55:51] [INFO]::MAIN: Calling SickBeard:tvshows to post-process:Marvels.luke.Cage..s02e03..1080p
[13:55:51] [INFO]::MAIN: Attempting to auto-detect tvshows fork
[13:55:51] [INFO]::MAIN: SickBeard:tvshows fork auto-detection successful ...
[13:55:51] [INFO]::MAIN: SickBeard:tvshows fork set to SickRage
[13:55:51] [INFO]::TRANSCODER: Checking [Marvels.luke.Cage..s02e03..1080p.mkv] for corruption, please stand by ...
[13:55:52] [INFO]::TRANSCODER: SUCCESS: [Marvels.luke.Cage..s02e03..1080p.mkv] has no corruption.
[13:55:52] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[13:56:08] [POSTPROCESS]::SICKBEARD: Processing in folder /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p
[13:56:08] [POSTPROCESS]::SICKBEARD: Processing /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p
[13:56:08] [POSTPROCESS]::SICKBEARD: Processing folder /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p
[13:56:08] [POSTPROCESS]::SICKBEARD: Processing /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p/Marvels.luke.Cage..s02e03..1080p.mkv (Marvels.luke.Cage..s02e03..1080p)
[13:56:08] [POSTPROCESS]::SICKBEARD: Retrieving episode object for 2x3
[13:56:08] [POSTPROCESS]::SICKBEARD: Looking up quality for name Marvels.luke.Cage..s02e03..1080p, got Unknown
[13:56:08] [POSTPROCESS]::SICKBEARD: Looking up quality for name Marvels.luke.Cage..s02e03..1080p, got Unknown
[13:56:08] [POSTPROCESS]::SICKBEARD: Looking up quality for name Marvels.luke.Cage..s02e03..1080p.mkv, got Unknown
[13:56:08] [POSTPROCESS]::SICKBEARD: Guessing quality for name Marvels.luke.Cage..s02e03..1080p.mkv, got 1080p HDTV
[13:56:08] [POSTPROCESS]::SICKBEARD: SR snatched this episode and it is not processed before
[13:56:08] [POSTPROCESS]::SICKBEARD: Is ep a priority download: True
[13:56:08] [POSTPROCESS]::SICKBEARD: There is no existing file so there's no worries about replacing it
[13:56:08] [POSTPROCESS]::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
[13:56:08] [POSTPROCESS]::SICKBEARD: Using original release name Marvels.luke.Cage..s02e03..1080p.mkv
[13:56:08] [POSTPROCESS]::SICKBEARD: Destination folder for this episode: /mnt/Storage/TVShows/Marvel's Luke Cage/Season 02
[13:56:08] [POSTPROCESS]::SICKBEARD: No associated files for /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p/Marvels.luke.Cage..s02e03..1080p.mkv were found during this pass
[13:56:08] [POSTPROCESS]::SICKBEARD: Moving file from /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p/Marvels.luke.Cage..s02e03..1080p.mkv to /mnt/Storage/TVShows/Marvel's Luke Cage/Season 02/Marvel's Luke Cage - S02E03 - Wig Out.mkv
[13:56:08] [POSTPROCESS]::SICKBEARD: Processing succeeded for /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p/Marvels.luke.Cage..s02e03..1080p.mkv
[13:56:08] [POSTPROCESS]::SICKBEARD: Found unwanted files: ['Marvels.luke.Cage..s02e03..1080p.mkv']
[13:56:08] [POSTPROCESS]::SICKBEARD: Deleted folder: /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p
[13:56:08] [POSTPROCESS]::SICKBEARD: Successfully processed
[13:56:09] [INFO]::CLEANDIR: Directory /mnt/Storage/Downloads/complete/tvshows/Marvels.luke.Cage..s02e03..1080p has been processed and removed ...
[13:56:09] [ERROR]::MAIN: Failed to add directories from {} for post-processing: 'Section' object has no attribute 'endswith'
[13:56:09] [ERROR]::MAIN: Failed to add directories from {} for post-processing: 'Section' object has no attribute 'endswith'
[13:56:09] [INFO]::MAIN: The ./nzbToMedia.py script completed successfully.
```
