### ISSUE TITLE
Fork Detection failing

### ISSUE THREAD

**Issue by jeffski10** [clinton-hall/nzbToMedia#1357]
Have started seeing errors when Sab calls the script. Using SickRage  at this version: https://github.com/SickRage/SickRage/releases/tag/v2018.06.15-1

[12:56:41] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:7073
[12:56:41] [DEBUG]::SERVER: Server responded at http://localhost:7073
[12:56:41] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
  File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 847, in main
    download_id='', failureLink=''.join(args[8:]))
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 717, in process
    download_id, inputCategory, failureLink)
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
    fork, fork_params = autoFork(section, inputCategory)
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/core/nzbToMediaAutoFork.py", line 84, in autoFork
    if param not in r.json()['data']['optionalParameters'].keys():
KeyError: 'optionalParameters'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x1b659e0>> ignored

**Comment by clinton-hall** [comment]
Ok. I think I see the issue.

SICKRAGETV/SiCKEAGE (The OTher SickRage) submitted a pull request to support their API...
The Fork you are on is still supported via regular WebUI interface (not API).

In autoProcessMedia.cfg, under your `[SickBeard]` and appropriate category, please ensure you blank-out the apikey
`apikey =` or even try `apikey = ""`

**Comment by jeffski10** [comment]
I've set the fork for now so it doesn't try that step but will give the api key change a go too.
