### ISSUE TITLE
ImportError: cannot import name chars_before error

### ISSUE THREAD

**Issue by irobot73** [clinton-hall/nzbToMedia#1364]
Following popped up recently while SABnzbd was doing its 'thang' for Headphones.  Since HP is setup to scan this folder periodically, it's not a deal killer

Uncompresses & moves as it should, but attempting to run the script, halts w/ '**Exit(1) ImportError: cannot import name chars_before**' and the following break-out

Pulled the latest/greatest, purged all the .PYC files and no change.  Ideas?  Something new I missed?  Appreciate the tools you guys put the time into:

```
Traceback (most recent call last):
File "..\nzbToMedia\nzbToHeadPhones.py", line 121, in <module>
import nzbToMedia
File "..\nzbToMedia\nzbToMedia.py", line 616, in <module>
import core
File "..\nzbToMedia\core\__init__.py", line 36, in <module>
from core.autoProcess.autoProcessComics import autoProcessComics
File "..\nzbToMedia\core\autoProcess\autoProcessComics.py", line 7, in <module>
from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
File "..\nzbToMedia\core\nzbToMediaUtil.py", line 14, in <module>
import guessit
File "..\nzbToMedia\libs\guessit\__init__.py", line 6, in <module>
from .api import guessit, GuessItApi
File "..\nzbToMedia\libs\guessit\api.py", line 17, in <module>
from .rules import rebulk_builder
File "..\nzbToMedia\libs\guessit\rules\__init__.py", line 11, in <module>
from .properties.episodes import episodes
File "..\nzbToMedia\libs\guessit\rules\properties\episodes.py", line 14, in <module>
from .title import TitleFromPosition
File "..\nzbToMedia\libs\guessit\rules\properties\title.py", line 14, in <module>
from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
File "..\nzbToMedia\libs\guessit\rules\properties\language.py", line 14, in <module>
from ..common.validators import seps_surround
File "..\nzbToMedia\libs\guessit\rules\common\validators.py", line 8, in <module>
from rebulk.validators import chars_before, chars_after, chars_surround
ImportError: cannot import name chars_before
```

**Comment by clinton-hall** [comment]
I am guessing your python already has a rebulk that is newer than the one I included?

this is included in nzbToMeda/libs/rebulk and this should be the first in the search path when nzbToMedia is run.

what version of Python are you running?

**Comment by irobot73** [comment]
Python 2.7.13 (Windows box, running from source).

**Comment by labrys** [comment]
Vendored libs have been updated.  This should no longer be an issue. Let us know if it is and we will reopen it.
