### ISSUE TITLE
Error trying to process TVshows in SR

### ISSUE THREAD

**Issue by netohugo** [clinton-hall/nzbToMedia#1366]
`[18:31:55] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[18:31:55] [INFO]::MAIN: Checking database structure...
[18:31:55] [INFO]::MAIN: Checking if git needs an update
[18:31:56] [INFO]::MAIN: No update needed
[18:31:56] [INFO]::MAIN: nzbToMedia Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (FreeBSD 11.0-RELEASE)
[18:31:56] [INFO]::MAIN: #########################################################
[18:31:56] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[18:31:56] [INFO]::MAIN: #########################################################
[18:31:56] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[18:31:56] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[18:31:56] [INFO]::MAIN: Calling SickBeard:tv to post-process:American.Horror.Story.S01E10.Smoldering.Children.1080p.WEB-DL.DD5.1.AAC2.0.H.264-SA89.nzb
[18:31:56] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
File "/usr/local/share/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 847, in main
download_id='', failureLink=''.join(args[8:]))
File "/usr/local/share/nzbToMedia/nzbToMedia.py", line 717, in process
download_id, inputCategory, failureLink)
File "/usr/local/share/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
fork, fork_params = autoFork(section, inputCategory)
File "/usr/local/share/nzbToMedia/core/nzbToMediaAutoFork.py", line 84, in autoFork
if param not in r.json()['data']['optionalParameters'].keys():
KeyError: 'optionalParameters'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x80077de10>> ignored`

FreeNAS-11.1-U5 (8e2a858a1) - updated
SabNZBd (2.3.4 [2a113f7]) and Sickrage (Branch: master, Commit: 0e72764974....) - updated as well,

Probably a permissive error?
Where is the problem?

Thanks!

**Comment by netohugo** [comment]
Edit:
Manual Post Processing in SR works like a charm...

**Comment by clinton-hall** [comment]
Remove the api key from autoProcessMedia.cfg
```
[SickBeard]
    [tv]
        apikey = ""
```
this api key only works with a version of SickRage that supports api postprocessing. I suspect you are on the other version, but this is fully supported with WebUI processing.

**Comment by netohugo** [comment]
Thank you for helpin but now returns other erros...

`[22:02:59] [INFO]::MAIN: Loading config from [/usr/local/share/nzbToMedia/autoProcessMedia.cfg]
[22:02:59] [INFO]::MAIN: Checking database structure...
[22:02:59] [INFO]::MAIN: Checking if git needs an update
[22:03:00] [INFO]::MAIN: No update needed
[22:03:00] [INFO]::MAIN: nzbToMedia Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (FreeBSD 11.0-RELEASE)
[22:03:01] [INFO]::MAIN: #########################################################
[22:03:01] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[22:03:01] [INFO]::MAIN: #########################################################
[22:03:01] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[22:03:01] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[22:03:01] [INFO]::MAIN: Calling SickBeard:tv to post-process:Scorpion.S04E06.Queen.Scary.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.nzb
[22:03:01] [INFO]::MAIN: Attempting to auto-detect tv fork
[22:03:01] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {}
[22:03:01] [INFO]::MAIN: SickBeard:tv fork set to custom
[22:03:01] [INFO]::MAIN: FLATTEN: Flattening directory: /mnt/media/downloads/sabnzbd/complete/tv/Scorpion.S04E06.Queen.Scary.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.1
[22:03:01] [INFO]::TRANSCODER: Checking [Scorpion.S04E06.Queen.Scary.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.1.mkv] for corruption, please stand by ...
[22:03:01] [INFO]::TRANSCODER: SUCCESS: [Scorpion.S04E06.Queen.Scary.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.1.mkv] has no corruption.
[22:03:01] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[22:03:01] [POSTPROCESS]::SICKBEARD: <!DOCTYPE html>
[22:03:01] [POSTPROCESS]::SICKBEARD: <html lang="">
[22:03:01] [POSTPROCESS]::SICKBEARD:     <head>
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta charset="utf-8">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="robots" content="noindex, nofollow">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta http-equiv="X-UA-Compatible" content="IE=edge">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:         
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="theme-color" content="#15528F">
[22:03:01] [POSTPROCESS]::SICKBEARD:         
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="msapplication-navbutton-color" content="#15528F">
[22:03:01] [POSTPROCESS]::SICKBEARD:         
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="apple-mobile-web-app-status-bar-style" content="#15528F">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="apple-mobile-web-app-capable" content="yes">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="mobile-web-app-capable" content="yes">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <title>SickRage - Login</title>
[22:03:01] [POSTPROCESS]::SICKBEARD:         
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="msapplication-TileColor" content="#FFFFFF">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="msapplication-TileImage" content="/sickrage/images/ico/favicon-144.png?v=79c0189802a179caab7fcf27c0c733b1">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta name="msapplication-config" content="/sickrage/css/browserconfig.xml?v=8221dfb6a367ec8cb84eb9aabe421ba6">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="srRoot" data-content="/sickrage">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="themeSpinner" data-content="-dark">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="anonURL" data-content="http://dereferer.org/?">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.ANIME_SPLIT_HOME" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.ANIME_SPLIT_HOME_IN_TABS" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.COMING_EPS_LAYOUT" data-content="calendar">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.COMING_EPS_SORT" data-content="date">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.DATE_PRESET" data-content="%d/%m/%Y">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.FUZZY_DATING" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.HISTORY_LAYOUT" data-content="compact">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.USE_SUBTITLES" data-content="True">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.HOME_LAYOUT" data-content="poster">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.POSTER_SORTBY" data-content="name">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.POSTER_SORTDIR" data-content="1">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.ROOT_DIRS" data-content="0|/mnt/media/videos/tvshows">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.SORT_ARTICLE" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.TIME_PRESET" data-content="%H:%M">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.TRIM_ZERO" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.SICKRAGE_BACKGROUND" data-content="False">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.FANART_BACKGROUND" data-content="True">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <meta data-var="sickbeard.FANART_BACKGROUND_OPACITY" data-content="0.4">
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="shortcut icon" href="/sickrage/images/ico/favicon.ico?v=0af1ff29b46a047128790843d1a0fd9e">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" sizes="16x16 32x32 64x64" href="/sickrage/images/ico/favicon.ico?v=0af1ff29b46a047128790843d1a0fd9e">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="196x196" href="/sickrage/images/ico/favicon-196.png?v=f7086b8a229d763216263ffbc303c8d9">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="160x160" href="/sickrage/images/ico/favicon-160.png?v=eb631747b1396567f8541702b2ae66ee">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="96x96" href="/sickrage/images/ico/favicon-96.png?v=182f7b9a84de1fb7ee188470373b230d">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="64x64" href="/sickrage/images/ico/favicon-64.png?v=b0fc517dc13229ab12e215dd89ecdbcc">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="32x32" href="/sickrage/images/ico/favicon-32.png?v=7aee67267c6649599af474104194251a">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="16x16" href="/sickrage/images/ico/favicon-16.png?v=574bdfd5ba2cf994e9eb4d0619634869">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="152x152" href="/sickrage/images/ico/favicon-152.png?v=6801f1145f063820264df49026d8066b">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="144x144" href="/sickrage/images/ico/favicon-144.png?v=79c0189802a179caab7fcf27c0c733b1">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="120x120" href="/sickrage/images/ico/favicon-120.png?v=e47b1f965e8d0c1b72481055ee7c4072">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="114x114" href="/sickrage/images/ico/favicon-114.png?v=fb0b8c5c7f8910aa0156b9b3e1222d12">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="76x76" href="/sickrage/images/ico/favicon-76.png?v=59a3974ed4cf88944f06ca93b59522e0">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="72x72" href="/sickrage/images/ico/favicon-72.png?v=3547e519617a22c78411998d07876099">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" href="/sickrage/images/ico/favicon-57.png?v=a650c9e703cda8482564750b67283f9b">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="mask-icon" href="/sickrage/images/ico/safari-pinned-tab.svg?v=3354bed7a367a4287080325e344f7026" color="#15528F">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/vender.min.css?v=200e1256055edc6398a9565435bc11f9"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/browser.css?v=1bceb1b25fe44961e9787c409988bba7" />
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/font-awesome.min.css?v=4083f5d376eb849a458cc790b53ba080" />
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/lib/jquery-ui-1.10.4.custom.min.css?v=a83a24bf595a1a0455f92d6afc604238" />
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/lib/jquery.qtip-2.2.1.min.css?v=6fa1b7ce01c0bdc927c9f662f74ddf21"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/style.css?v=5945a641b1ad2f0a65fe536b39cd538f"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/print.css?v=b3576230f83473eebc9b28d6c8a30c37" />
[22:03:01] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="/sickrage/css/country-flags.css?v=caffce63f7d74c5e83458089c55f3b77"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:             <link rel="stylesheet" type="text/css" href="/sickrage/css/dark.css?v=18848b350254a637f838adddcfc6446e" />
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:     </head>
[22:03:01] [POSTPROCESS]::SICKBEARD:     <body data-controller="FixME" data-action="FixME">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <nav class="navbar navbar-default navbar-fixed-top hidden-print" role="navigation">
[22:03:01] [POSTPROCESS]::SICKBEARD:             <div class="container-fluid">
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:                 <div class="navbar-header">
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsible-navbar">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <span class="sr-only">Toggle navigation</span>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <span class="icon-bar"></span>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <span class="icon-bar"></span>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <span class="icon-bar"></span>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </button>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <a class="navbar-brand" href="/sickrage/home/" title="SickRage"><img alt="SickRage" src="/sickrage/images/sickrage.png?v=546bcd247c79a3e90cfb13c2a33ad9da"
[22:03:01] [POSTPROCESS]::SICKBEARD:                                                                                          style="height: 50px;padding: 3px;"
[22:03:01] [POSTPROCESS]::SICKBEARD:                                                                                  class="img-responsive pull-left" /></a>
[22:03:01] [POSTPROCESS]::SICKBEARD:                 </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:         </nav>
[22:03:01] [POSTPROCESS]::SICKBEARD:         <div class="container-fluid">
[22:03:01] [POSTPROCESS]::SICKBEARD:             <div id="sub-menu-container" class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                 <div class="clearfix"></div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                 <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:     <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:         <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
[22:03:01] [POSTPROCESS]::SICKBEARD:             <div class="login">
[22:03:01] [POSTPROCESS]::SICKBEARD:                 <form action="" method="post">
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="col-md-12">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <h1>SickRage</h1>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="col-md-12">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <div class="form-group">
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <label for="username">Username</label>
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <input class="form-control" title="Username" name="username" type="text"
[22:03:01] [POSTPROCESS]::SICKBEARD:                                        placeholder="Username" autocomplete="off"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:                             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="col-md-12">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <div class="form-group">
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <label for="password">Password</label>
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <input class="form-control" title="Password" name="password" type="password"
[22:03:01] [POSTPROCESS]::SICKBEARD:                                        placeholder="Password" autocomplete="off"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:                             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <div class="row">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="col-md-12">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <div class="form-group">
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <label class="remember_me" title="for 30 days">
[22:03:01] [POSTPROCESS]::SICKBEARD:                                     <input class="inlay" id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked"/>&nbsp;Remember me
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 </label>
[22:03:01] [POSTPROCESS]::SICKBEARD:                                 <input class="btn btn-default pull-right" name="submit" type="submit" value="Login"/>
[22:03:01] [POSTPROCESS]::SICKBEARD:                             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                 </form>
[22:03:01] [POSTPROCESS]::SICKBEARD:             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                 </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             <div class="modal fade" id="site-notification-modal">
[22:03:01] [POSTPROCESS]::SICKBEARD:                 <div class="modal-dialog">
[22:03:01] [POSTPROCESS]::SICKBEARD:                     <div class="modal-content">
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="modal-header">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <h4 class="modal-title">Notice</h4>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="modal-body"></div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         <div class="modal-footer">
[22:03:01] [POSTPROCESS]::SICKBEARD:                             <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
[22:03:01] [POSTPROCESS]::SICKBEARD:                         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                     </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:                 </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:             </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:
[22:03:01] [POSTPROCESS]::SICKBEARD:         </div>
[22:03:01] [POSTPROCESS]::SICKBEARD:     </body>
[22:03:01] [POSTPROCESS]::SICKBEARD: </html>
[22:03:01] [ERROR]::MAIN: A problem was reported in the /usr/local/share/nzbToMedia/nzbToSickBeard.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!`

My auto ProcessMedia.cfg is set up:

`[SickBeard]                                                                                                                         
    #### autoProcessing for TV Series                                                                                               
    #### tv - category that gets called for post-processing with SB                                                                 
    [[tv]]                                                                                                                          
        enabled = 1                                                                                                                 
        host = localhost                                                                                                            
        port = 8081                                                                                                                 
        apikey = ""                                                                                                                 
        username = ""                                                                                                               
        password = ""                                                                                                               
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######                                                        
        web_root = /sickrage                                                                                                        
        ssl = 0                                                                                                                     
        fork = auto                                                                                                                 
        delete_failed = 1                                                                                                           
        # Enable/Disable linking for Torrents                                                                                       
        Torrent_NoLink = 0                                                                                                          
        keep_archive = 1                                                                                                            
        process_method = ""                                                                                                         
        # force processing of already processed content when running a manual scan.                                                 
        force = 0                                                                                                                   
        # tell SickRage/Medusa to delete all source files after processing.                                                         
        delete_on = 0                                                                                                               
        # tell Medusa to ignore check for associated subtitle check when postponing release                                         
        ignore_subs = 0                                                                                                             
        extract = 1                                                                                                                 
        nzbExtractionBy = Downloader                                                                                                
        # Set this to minimum required size to consider a media file valid (in MB)                                                  
        minSize = 0                                                                                                                 
        # Enable/Disable deleting ignored files (samples and invalid media files)                                                   
        delete_ignored = 1                                                                                                          
        ##### Enable if SickBeard is on a remote server for this category                                                           
        remote_path = 0                                                                                                             
        ##### Set to path where download client places completed downloads locally for this category                                
        watch_dir = ""                                                                                                              
        ##### Set the recursive directory permissions to the following (0 to disable)                                               
        chmodDirectory = 0   `

**Comment by netohugo** [comment]
Maybe process_method = "Move" ????

**Comment by netohugo** [comment]
I found out where I went wrong.
SR user and password are missing in autoProcessMedia.cfg  duhhh!

`[[tv]]                                                                      
        enabled = 1                                                             
        host = localhost                                                        
        port = 8081                                                             
        apikey = ""                                                             
        username = myuser                                                         
        password = mypass `

Thanx!
