### ISSUE TITLE
NameError: global name 'download_id' is not defined

### ISSUE THREAD

**Issue by italianbloke** [clinton-hall/nzbToMedia#1373]
Hi,

Sorry in advance if this has been covered elsewhere.
I'm getting this error in SABnzbd, could you please help me? 
Thanks.
```
[19:17:08] [INFO]::MAIN: Loading config from [/share/MD1_DATA/Download/nzbToMedia/autoProcessMedia.cfg]
[19:17:08] [INFO]::MAIN: Checking database structure...
[19:17:08] [INFO]::MAIN: Checking if git needs an update
[19:17:11] [INFO]::MAIN: No update needed
[19:17:11] [INFO]::MAIN: nzbToMedia Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (Linux 4.2.8)
[19:17:12] [INFO]::MAIN: #########################################################
[19:17:12] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[19:17:12] [INFO]::MAIN: #########################################################
[19:17:12] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[19:17:12] [INFO]::MAIN: Auto-detected SECTION:Lidarr
[19:17:12] [INFO]::MAIN: Calling Lidarr:audio to post-process:AIR-10 000 Hz Legend-CD-FLAC-2001-YUK.nzb
Traceback (most recent call last):
File "/share/Download/nzbToMedia/nzbToLidarr.py", line 244, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/share/MD1_DATA/Download/nzbToMedia/nzbToMedia.py", line 847, in main
download_id='', failureLink=''.join(args[8:]))
File "/share/MD1_DATA/Download/nzbToMedia/nzbToMedia.py", line 719, in process
result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
File "/share/MD1_DATA/Download/nzbToMedia/core/autoProcess/autoProcessMusic.py", line 200, in process
data = {"name": "DownloadedAlbumScan", "path": dirName, "downloadClientId": download_id, "importMode": "Move"}
NameError: global name 'download_id' is not defined
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x218aae0>> ignored
```

**Comment by clinton-hall** [comment]
Sorry for this. 
This was fixed for #1355 However this is only in Nightly.

Please change to Nightly branch and test.

**Comment by italianbloke** [comment]
Thanks for getting back to me so promptly.
I will test the Nightly branch and let you know.

**Comment by italianbloke** [comment]
I tested it and I got a new error:

[09:25:47] [WARNING]::LIDARR: No scan id was returned due to: 'id'
[09:25:47] [ERROR]::MAIN: A problem was reported in the /share/Download/nzbToMedia/nzbToLidarr.py script.
Lidarr: Failed to post-process - Unable to start scan!

##### FULL LOG #####

[09:25:46] [INFO]::MAIN: Loading config from [/share/MD1_DATA/Download/nzbToMedia/autoProcessMedia.cfg]
[09:25:47] [INFO]::MAIN: Checking database structure...
[09:25:47] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[09:25:47] [DEBUG]::MAIN: InitialSchema upgrade not required
[09:25:47] [DEBUG]::MAIN: Checking if we can use git commands: "/opt/bin/git" version
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" version with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" version : returned successful
[09:25:47] [DEBUG]::MAIN: Using: "/opt/bin/git"
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" symbolic-ref -q HEAD : returned successful
[09:25:47] [INFO]::MAIN: Checking if git needs an update
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse HEAD with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" rev-parse HEAD : returned successful
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" fetch origin with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" fetch origin : returned successful
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[09:25:47] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /share/MD1_DATA/Download/nzbToMedia
[09:25:47] [DEBUG]::MAIN: "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[09:25:47] [DEBUG]::MAIN: cur_commit = 003febeafe0136adcc9bb5a165306b3b2f7a128d % (newest_commit)= 003febeafe0136adcc9bb5a165306b3b2f7a128d, num_commits_behind = 0, num_commits_ahead = 0
[09:25:47] [INFO]::MAIN: No update needed
[09:25:47] [INFO]::MAIN: nzbToMedia Version:003febeafe0136adcc9bb5a165306b3b2f7a128d Branch:nightly (Linux 4.2.8)
[09:25:47] [DEBUG]::MAIN: Connecting to transmission: http://localhost:9091
[09:25:47] [INFO]::MAIN: #########################################################
[09:25:47] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[09:25:47] [INFO]::MAIN: #########################################################
[09:25:47] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/share/Download/nzbToMedia/nzbToLidarr.py', '/share/Download/sabnzbd/complete/lidarr/Air-Talkie Walkie-Limited Edition-2004-TLT', 'Air-Talkie Walkie-Limited Edition-2004-TLT.nzb', 'Air-Talkie Walkie-Limited Edition-2004-TLT', '', 'audio', 'alt.binaries.sounds.mp3.complete_cd', '0', '']
[09:25:47] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[09:25:47] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[09:25:47] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_Rtdrpj
[09:25:47] [DEBUG]::MAIN: Adding NZB download info for directory /share/Download/sabnzbd/complete/lidarr/Air-Talkie Walkie-Limited Edition-2004-TLT to database
[09:25:47] [INFO]::MAIN: Auto-detected SECTION:Lidarr
[09:25:47] [DEBUG]::MAIN: Checking for archives to extract in directory: /share/Download/sabnzbd/complete/lidarr/Air-Talkie Walkie-Limited Edition-2004-TLT
[09:25:47] [INFO]::MAIN: Calling Lidarr:audio to post-process:Air-Talkie Walkie-Limited Edition-2004-TLT.nzb
[09:25:47] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8686/api/v1
[09:25:47] [DEBUG]::SERVER: Server responded at http://localhost:8686/api/v1
[09:25:47] [DEBUG]::LIDARR: path: /share/Download/sabnzbd/complete/lidarr/Air-Talkie Walkie-Limited Edition-2004-TLT
[09:25:47] [DEBUG]::LIDARR: Opening URL: http://localhost:8686/api/v1/command with data: {"path": "/share/Download/sabnzbd/complete/lidarr/Air-Talkie Walkie-Limited Edition-2004-TLT", "name": "Rename"}
[09:25:47] [WARNING]::LIDARR: No scan id was returned due to: 'id'
[09:25:47] [ERROR]::MAIN: A problem was reported in the /share/Download/nzbToMedia/nzbToLidarr.py script.
Lidarr: Failed to post-process - Unable to start scan!

**Comment by jaywk** [comment]
Seeing the same problem with the nzbToLidarr.py script. Looks like it's attempting to contact Lidarr on http://localhost:8686/api/v1 although I have set all the options custom to where my instance of Lidarr is running which isn't localhost:8686
```#########################################################
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [INFO]::MAIN: #########################################################
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [INFO]::MAIN: Script triggered from NZBGet Version 21.0-testing-r2220.
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [INFO]::MAIN: Auto-detected SECTION:Lidarr
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [INFO]::MAIN: Calling Lidarr:music to post-process:Father John Misty - Pure Comedy (2017) FLAC
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [ERROR]::SERVER: Server failed to respond at http://localhost:8686/api/v1
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [ERROR]::LIDARR: Server did not respond. Exiting
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: [20:38:40] [ERROR]::MAIN: A problem was reported in the /mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToLidarr.py script.
Thu Sep 06 2018 14:38:40	INFO	nzbToLidarr: Lidarr: Failed to post-process - Lidarr did not `respond.!```

**Comment by clinton-hall** [comment]
@jaywk
Just to confirm here, have you entered the details through NZBGet Web UI page for nzbToMedia.py
```
lihost=localhost
liport=8686
liapikey=
```

**Comment by clinton-hall** [comment]
@italianbloke 
The main issue I have here is that there doesn't appear to be a documented process for calling Lidarr to process a download. This functionality exists in Radarr and Sonarr, so I added this for Lidarr (on request) and without documentation I built this to follow the Radarr/Sonarr method assuming this existed in Lidarr and just hadn't been documented.

This was added as an experiment with the intention to work toward functionality. But it has not been completed... I apologize for this, I actually hadn't intended it to be pushed to Master, but I had another urgent fix and I forgot this was in there...

So, at this time, I don't have a Lidarr installation of my own to test, and I can't see anything in the Lidarr api information that shows this process. https://github.com/lidarr/Lidarr/wiki/API
I expect there should be a command (https://github.com/lidarr/Lidarr/wiki/Command) but again none of these look to be able to process a download directory etc...

I also note that this page (https://github.com/lidarr/Lidarr/wiki/Custom-Post-Processing-Scripts) page details how to "trigger a custom script in your download client to tell Lidarr when to update, you can find more details here."
But then all the details that follow are actually relating to scripts that are triggered by Lidarr (Not the Downloader) after the download has been processed by Lidarr.

I myself haven't had a chance to talk to the Lidarr team and discuss this. I don't know if they are looking to allow this type of interaction, or if they wish for Lidarr to take the "lead" in terms of processing a download...

**Comment by jaywk** [comment]
@clinton-hall yes. I've updated lihost, liport, and liapikey with my specific Lidarr host, port, and api key. The script seems to ignore them and use localhost:8686 instead.

**Comment by clinton-hall** [comment]
@jaywk 
Just to confirm, there are 3 potential places this could be loaded and I want to check that we have identified the correct place.

Changes in autoProcessMedia.cfg
```
[Lidarr]
    [[music]]
```
Will be used by all downloaders, but will be over-written by anything set in NZBGet's config (for the script that has been called). In this case, after running the script you would find that the settings in autoProcessMedia.cfg have been changed.

Now, in NZBGet there are 2 places to set these:
1: Config for nzbToMedia.py -> only gets used when the category calls the script nzbToMedia.py
2: Config for nzbToLidarr.py -> only gets used when the category calls the script nzbToLidarr.py

This is done as some people just configure the 1 script (nzbToMedia.py) for all categories, and let the script determine which category to process. While some people call the specific script for the specific category. Some people also have both versions to allow for 2 categories to the same method, with different configurations... but that is another story

In your log, I note that it is in-fact calling the script: `/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToLidarr.py`
So in your case, the only config used would be the config from the nzbToLidarr.py script (in NZBGet Web UI) and not the config for nzbToMedia.py or the config in autoProcessMedia.cfg.

Can you please confirm that you have the correct settings and that these are saved in NZBGet? (you need to restart NZBGet after making any changes)

**Comment by jaywk** [comment]
I have always wondered the difference between the nzbTomedia.py and the individual scripts so thanks for the information. I have the options filled out in both the nzbToMedia.py and the nzbToLidarr.py scripts. I have also tried switching between the two when post processing yet they both produce the same failed result on separate attempts.

**Comment by clinton-hall** [comment]
One last thing to check here. 
`LiCategory` should be set as the category of the download in NZBGet (case sensitive!)
I know this seems stupid, but if LiCategory = Music and the category of the download is `music` this will cause issues.

**Comment by jaywk** [comment]
Yes, they are both set to lowercase ``music``

**Comment by italianbloke** [comment]
@clinton-hall 
No worries, thanks for taking the time to look into this. I just wanted to make sure there wasn't an issue with my configuration.

**Comment by clinton-hall** [comment]
@jaywk 
I just tested here, and it worked...

Can you manually edit 
`/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg`
```
[General]
    log_debug = 1
    log_db = 1
    log_env = 1
    log_git = 0
```

then run a postprocess again and post the log?
This shoudl show exactly what NZBGet is passing into the script, what it is doing, and hopefully let me see what is going wrong.

**Comment by jaywk** [comment]
So I took drastic measures and deleted my entire nzbget setup then reinstalled and reconfigured everything from scratch and things still will not process properly. Here are the debug logs from a failed post-process with nzbToLidarr.py

```
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr: [05:10:37] [ERROR]::MAIN: Unable to migrate config file /mnt/shared/Application Data/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg, exiting ...
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr: Traceback (most recent call last):
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget//scripts/nzbToMedia/nzbToLidarr.py", line 244, in <module>
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     result = nzbToMedia.main(sys.argv, section)
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 755, in main
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     core.initialize(section)
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/core/__init__.py", line 300, in initialize
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     CFG = config.addnzbget()
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 253, in addnzbget
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     CFG_NEW = config()
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/core/nzbToMediaConfig.py", line 94, in __init__
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     super(configobj.ConfigObj, self).__init__(*args, **kw)
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1229, in __init__
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     self._load(infile, configspec)
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/libs/configobj/configobj.py", line 1318, in _load
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr:     raise error
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr: configobj.configobj.ConfigObjError: Parsing failed with several errors.
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr: First error at line 223.
Fri Sep 07 2018 23:10:37	INFO	nzbToLidarr: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7f7c1d652a50>> ignored
Fri Sep 07 2018 23:10:37	ERROR	Post-process-script nzbToMedia/nzbToLidarr.py for Father John Misty-Pure Comedy-WEB-2017-ENTiTLED failed (terminated with unknown status)
```

**Comment by clinton-hall** [comment]
So this looks like a permissions issue with `/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/autoProcessMedia.cfg`
Check to see what the permissions/owner are and then check this against the user that runs NZBGet.

**Comment by jaywk** [comment]
There was a double // in my script path which seems to be the reason it was unable to migrate the config file; however, I have I am now seeing a similar issue as @italianbloke in the original post here.
```
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr: Traceback (most recent call last):
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToLidarr.py", line 244, in <module>
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:     result = nzbToMedia.main(sys.argv, section)
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 818, in main
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:     failureLink=failureLink)
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 719, in process
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:     result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:   File "/mnt/shared/Application Data/nzbget/scripts/nzbToMedia/core/autoProcess/autoProcessMusic.py", line 199, in process
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr:     data = {"name": "DownloadedAlbumScan", "path": dirName, "downloadClientId": download_id, "importMode": "Move"}
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr: NameError: global name 'download_id' is not defined
Sat Sep 08 2018 18:17:21	INFO	nzbToLidarr: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7feb64918210>> ignored
```

**Comment by nstead** [comment]
I'm seeing a similar problem, when trying to Autoprocess from nzbget.
These are the logs:
From nzbtomedia.log:
```
2019-01-05 16:26:50 INFO    ::MAIN: #########################################################
2019-01-05 16:26:50 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2019-01-05 16:26:50 INFO    ::MAIN: #########################################################
2019-01-05 16:26:50 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/scripts/nzbToMedia/nzbToLidarr.py']
2019-01-05 16:26:50 INFO    ::MAIN: Script triggered from NZBGet Version 20.0.
2019-01-05 16:26:50 DEBUG   ::MAIN: Adding NZB download info for directory /Downloads/AutoDownloads/music/Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN to database
2019-01-05 16:26:50 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'nzbget', 737064, u'da3fd8fbaf70476d90a8cf3eca91fdec', u'da3fd8fbaf70476d90a8cf3eca91fdec', u'Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN', u'/Downloads/AutoDownloads/music/Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN']
2019-01-05 16:26:50 DB      ::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name) VALUES (?, ?, ?, ?, ?, ?) with args [0, u'nzbget', 737064, u'da3fd8fbaf70476d90a8cf3eca91fdec', u'da3fd8fbaf70476d90a8cf3eca91fdec', u'Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN']
2019-01-05 16:26:51 INFO    ::MAIN: Auto-detected SECTION:Lidarr
2019-01-05 16:26:51 DEBUG   ::MAIN: Checking for archives to extract in directory: /Downloads/AutoDownloads/music/Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN
2019-01-05 16:26:51 INFO    ::MAIN: Calling Lidarr:music to post-process:Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN
2019-01-05 16:26:51 DEBUG   ::SERVER: Attempting to connect to server at http://172.17.0.1:8686/api/v1
2019-01-05 16:26:51 DEBUG   ::SERVER: Server responded at http://172.17.0.1:8686/api/v1
2019-01-05 16:26:51 DEBUG   ::LIDARR: remote_path: /volume2/Downloads/AutoDownloads/music/Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN
2019-01-05 16:26:51 DEBUG   ::LIDARR: Opening URL: http://172.17.0.1:8686/api/v1/command with data: {"path": "/volume2/Downloads/AutoDownloads/music/Coldplay-Ghost Stories-Deluxe Edition-CD-FLAC-2014-FORSAKEN", "name": "Rename"}
2019-01-05 16:26:53 WARNING ::LIDARR: No scan id was returned due to: 'id'
2019-01-05 16:26:53 ERROR   ::MAIN: A problem was reported in the /scripts/nzbToMedia/nzbToLidarr.py script.
```

**Comment by djderan** [comment]
I am having the same issue, I got it to Lidarr to work without running the script altogether though.
