### ISSUE TITLE
Headphones issue?  NameError: global name 'rmDir' is not defined

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#1382]
Using latest, I'd noticed that HP wasn't getting anything postproced directly and thought it was timing out but when I looked closely, I noticed the below stack?

[15:04:12] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8181/api
[15:04:12] [DEBUG]::SERVER: Server responded at http://localhost:8181/api
[15:04:12] [WARNING]::HEADPHONES: FAILED DOWNLOAD DETECTED
[15:04:12] [POSTPROCESS]::HEADPHONES: Deleting failed files and folder /home/@send/Music/Just_The_Hits_90s-4CD-2017.1
Traceback (most recent call last):
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 924, in <module>
exit(main(sys.argv))
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 854, in main
download_id='', failureLink=''.join(args[8:]))
File "/opt/Sick-Beard/autoProcessTV/nzbToMedia.py", line 726, in process
result = autoProcessMusic().process(sectionName, inputDirectory, inputName, status, clientAgent, inputCategory)
File "/opt/Sick-Beard/autoProcessTV/core/autoProcess/autoProcessMusic.py", line 237, in process
rmDir(dirName)
NameError: global name 'rmDir' is not defined
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x7fc3c67be690>> ignored

**Comment by clinton-hall** [comment]
Thanks for reporting. Should now be fixed in currently nightly branch.

**Comment by mgaulton** [comment]
Awesome, I'll check on it when i'm in front of the system.
