### ISSUE TITLE
Nzbtomedia failing in medusa

### ISSUE THREAD

**Issue by bartley69** [clinton-hall/nzbToMedia#1389]
Hi, with all this crazy sickrage stuff going on I've switched to medusa but unfortunately my shows fail to process.

This is the log I get.

<pre>

[22:32:04] [INFO]::MAIN: Loading config from [/share/MD0_DATA/Download/nzbToMedia/autoProcessMedia.cfg]
[22:32:04] [INFO]::MAIN: Checking database structure...
[22:32:05] [INFO]::MAIN: Checking if git needs an update
[22:32:07] [INFO]::MAIN: No update needed
[22:32:07] [INFO]::MAIN: nzbToMedia Version:5d5d69ecdd5fe043be8a915ffa26e8427c9641c4 Branch:master (Linux 3.4.6)
[22:32:07] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
[22:32:07] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[22:32:07] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[22:32:07] [INFO]::MAIN: #########################################################
[22:32:07] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[22:32:07] [INFO]::MAIN: #########################################################
[22:32:07] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[22:32:09] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[22:32:09] [INFO]::MAIN: Calling SickBeard:tv to post-process:The.Walking.Dead.S09E02.The.Bridge.720p.AMZN.WEBRip.DDP5.1.x264-CasStudio-xpost.nzb
[22:32:09] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 847, in main
download_id='', failureLink=''.join(args[8:]))
File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 717, in process
download_id, inputCategory, failureLink)
File "/share/MD0_DATA/Download/nzbToMedia/core/autoProcess/autoProcessTV.py", line 69, in processEpisode
fork, fork_params = autoFork(section, inputCategory)
File "/share/MD0_DATA/Download/nzbToMedia/core/nzbToMediaAutoFork.py", line 84, in autoFork
if param not in r.json()['data']['optionalParameters'].keys():
KeyError: 'optionalParameters'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0x2b5a310>> ignored

</pre>

Cheers.

**Comment by Xenocell12** [comment]
Hello my dude hopefully I can get you squared away. It sounds like to me that your autodetection of the fork is being a little wonky. 

To be honest its works sometimes. set your autodetect to "medusa" and try again.

Also I want to mention you do NOT need to fill in API codes from medusa into the cg. Just credentials if present. That is for the SiCKRAGE fork. (the narcissist fork)

**Comment by clinton-hall** [comment]
I have now opened this up so that api will work with SickChill, SiCKRAGE, and Medusa.

To achieve this you need to update to latest `nightly` branch and then continue to use auto fork.

I need to push this all to master, but I was hoping to do a few other checks first, and have found myself trying to do quick fixes/changes with very little time...

**Comment by spattersTatt** [comment]
Howdy, getting very  similar issues, with multiple combinations.  I did pull down the latest stable nzbToMedia, but not the nightly. I will try that and see if it resolves my issues.

From the log, when it calls the API, without credentials or API code, its just retuning the HTML source of the medusa postprocessing page.

Example:
[18:59:33] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8088/home/postprocess/processEpisode with params: {'nzbName': 'Magnum.P.I.2018.S01E07.720p.HEVC.x265-MeGusta.nzb', 'proc_type': 'manual', 'quiet': 1}
[18:59:33] [POSTPROCESS]::SICKBEARD: <!DOCTYPE html>
[18:59:33] [POSTPROCESS]::SICKBEARD: <html>
[18:59:33] [POSTPROCESS]::SICKBEARD:     <head>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <meta charset="utf-8">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <meta name="robots" content="noindex, nofollow">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <meta http-equiv="X-UA-Compatible" content="IE=edge">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <meta name="viewport" content="width=device-width, initial-scale=1.0">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <meta name="theme-color" content="#333333">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <title>Medusa</title>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <base href="http://localhost:8088/">
[18:59:33] [POSTPROCESS]::SICKBEARD:
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="shortcut icon" href="images/ico/favicon.ico?v=2">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" sizes="16x16 32x32 64x64" href="images/ico/favicon.ico">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="196x196" href="images/ico/favicon-196.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="160x160" href="images/ico/favicon-160.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="96x96" href="images/ico/favicon-96.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="64x64" href="images/ico/favicon-64.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="32x32" href="images/ico/favicon-32.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="icon" type="image/png" sizes="16x16" href="images/ico/favicon-16.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="152x152" href="images/ico/favicon-152.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="144x144" href="images/ico/favicon-144.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="120x120" href="images/ico/favicon-120.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="114x114" href="images/ico/favicon-114.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="76x76" href="images/ico/favicon-76.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" sizes="72x72" href="images/ico/favicon-72.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="apple-touch-icon" href="images/ico/favicon-57.png">
[18:59:33] [POSTPROCESS]::SICKBEARD:         <style>
[18:59:33] [POSTPROCESS]::SICKBEARD:         [v-cloak] {
[18:59:33] [POSTPROCESS]::SICKBEARD:             display: none !important;
[18:59:33] [POSTPROCESS]::SICKBEARD:         }
[18:59:33] [POSTPROCESS]::SICKBEARD:         </style>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/vendors.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/vender.min.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/bootstrap-formhelpers.min.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/browser.css?7181" />
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/lib/jquery-ui-1.10.4.custom.min.css?7181" />
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/lib/jquery.qtip-2.2.1.min.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/style.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/themed.css?7181" />
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/print.css?7181" />
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/country-flags.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:         <link rel="stylesheet" type="text/css" href="css/lib/vue-snotify-material.css?7181"/>
[18:59:33] [POSTPROCESS]::SICKBEARD:
[18:59:33] [POSTPROCESS]::SICKBEARD:     </head>

**Comment by spattersTatt** [comment]
I've just updated to nightly version, and re-ran a download.  Not using the API method I am still getting the HTML source of the medusa page request, not any post processing...  any ideas?
