### ISSUE TITLE
nzbToMedia.py not detecting SickChill fork and throwing exception

### ISSUE THREAD

**Issue by markheloking** [clinton-hall/nzbToMedia#1393]
nzbToMedia Branch/Commit: **5d5d69ecdd5fe043be8a915ffa26e8427c9641c4**
SickChill Branch/Commit: **61a763d303f7337709e03a76b01d9592e2dce14d**
SabNZBD Version: **2.3.5 [76c7a6c]**
OS: **Windows-10-10.0.17763**
Browser: **Google Chrome 70.0.3538.77 64-bit**

I just pulled the latest zip of the  master branch, took the default config and edited the following lines:

- Enabled forceclean
- Enabled log_debug
- Added ffmpeg_path
- Added SabNZDB apikey
- Added sc category to SickBeard:

```
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 0
        host = localhost
        port = 8081
        apikey = ""
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 0
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0
    [[sc]]
        enabled = 1
        host = localhost
        port = 8082
        apikey = **APIKEY**
        username = **USER**
        password = **PASS**
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 0
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = ""
        force = 0
        delete_on = 0
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        minSize = 0
        delete_ignored = 0
        remote_path = 0
        watch_dir = ""
        chmodDirectory = 0
```

Then I added the sc category in SabNZDB and put it to use nzbToSickbeard.py script, and then pushed a NZB download from SickChill to SabNZDB in the sc category. When the script ran post-download, the following output can be found in the debug log:

```
[21:30:10] [INFO]::MAIN: Loading config from [C:\ServerPrograms\SickRage\nzbToMedia\autoProcessMedia.cfg]
[21:30:10] [INFO]::MAIN: Checking database structure...
[21:30:10] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[21:30:10] [DEBUG]::MAIN: InitialSchema upgrade not required
[21:30:10] [INFO]::MAIN: Checking if source needs an update
[21:30:11] [DEBUG]::MAIN: cur_commit = None % (newest_commit)= 5d5d69ecdd5fe043be8a915ffa26e8427c9641c4, num_commits_behind = 0
[21:30:11] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[21:30:11] [INFO]::MAIN: nzbToMedia Version:11.05 Branch:master (Windows 10)
[21:30:11] [INFO]::MAIN: #########################################################
[21:30:11] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[21:30:11] [INFO]::MAIN: #########################################################
[21:30:11] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\ServerPrograms\\SickRage\\nzbToMedia\\nzbToSickBeard.py', 'D:\\Downloads\\Sabnzbd\\ToParse\\The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb', 'The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb.nzb', 'The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb', '', 'sc', 'alt.binaries.newznzb.lima', '-1', '']
[21:30:11] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[21:30:11] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[21:30:13] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_rxuc5y
[21:30:13] [DEBUG]::MAIN: Adding NZB download info for directory D:\Downloads\Sabnzbd\ToParse\The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb to database
[21:30:14] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[21:30:14] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\Downloads\Sabnzbd\ToParse\The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb
[21:30:14] [INFO]::MAIN: Calling SickBeard:sc to post-process:The_Big_Bang_Theory_S12E06_1080p_AMZN_WEB-DL_DD5_1_H_264-NTb.nzb
[21:30:14] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8082
[21:30:15] [DEBUG]::SERVER: Server responded at http://localhost:8082
[21:30:15] [INFO]::MAIN: Attempting to auto-detect sc fork
Traceback (most recent call last):
File "C:\ServerPrograms\SickRage\nzbToMedia\nzbToSickBeard.py", line 260, in <module>
result = nzbToMedia.main(sys.argv, section)
File "C:\ServerPrograms\SickRage\nzbToMedia\nzbToMedia.py", line 847, in main
download_id='', failureLink=''.join(args[8:]))
File "C:\ServerPrograms\SickRage\nzbToMedia\nzbToMedia.py", line 717, in process
download_id, inputCategory, failureLink)
File "C:\ServerPrograms\SickRage\nzbToMedia\core\autoProcess\autoProcessTV.py", line 69, in processEpisode
fork, fork_params = autoFork(section, inputCategory)
File "C:\ServerPrograms\SickRage\nzbToMedia\core\nzbToMediaAutoFork.py", line 84, in autoFork
if param not in r.json()['data']['optionalParameters'].keys():
KeyError: 'optionalParameters'
```

So it seems that nzbToMedia.py is having trouble detecting the SickChill fork.

The output when opening `http://localhost:8082/api/**APIKEY**/?cmd=help&subject=postprocess` in a browser is:

```
{"data": {"data": {"desc": "Manually post-process the files in the download folder", "optionalParameters": {"delete": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Delete processed files and folders", "type": "bool"}, "failed": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Mark download as failed", "type": "bool"}, "force_next": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Waits for the current processing queue item to finish and returns result of this request", "type": "bool"}, "force_replace": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Force already post-processed files to be post-processed again", "type": "bool"}, "is_priority": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Replace the file even if it exists in a higher quality", "type": "bool"}, "path": {"allowedValues": "see desc", "defaultValue": null, "desc": "The path to the folder to post-process", "type": "string"}, "process_method": {"allowedValues": ["copy", "move", "hardlink", "symlink", "symlink_reversed"], "defaultValue": false, "desc": "How should valid post-processed files be handled", "type": "string"}, "return_data": {"allowedValues": [0, 1], "defaultValue": false, "desc": "Returns the result of the post-process", "type": "bool"}, "type": {"allowedValues": ["auto", "manual"], "defaultValue": "auto", "desc": "The type of post-process being requested", "type": "string"}}, "requiredParameters": {}}, "message": "Manually post-process the files in the download folder", "result": "success"}, "message": "", "result": "success"}
```

The error persists after I change the fork from `auto` to `sickbeard-api` under the `[[sc]]` section.

[EDIT1]
Interestingly enough, the error seems to go away and the script runs fine if I change the fork from `auto` to `sickrage` under the `[[sc]]` section.

[EDIT2]
The problem with setting sickrage as the fork is that it uses `proc_dir` instead of `path` in the api call. This is fixed by using `sickrage-api`, not `sickbeard-api` as I suspected (found this out by looking through the sourcecode).
Auto fork detection for SickChill is still broken though.

**Comment by markheloking** [comment]
Interestingly enough, the error seems to go away and the script runs fine if I change the fork from `auto` to `sickrage` under the `[[sc]]` section.

**Comment by clinton-hall** [comment]
Please switch to nightly branch and test. Keep `fork = auto`
