### ISSUE TITLE
nzbToCouchPotato.py throws a TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Nimmsis** [clinton-hall/nzbToMedia#1396]
nzbToMedia Branch/Commit: **697ae37**
Couchpotato Branch/Commit: **12ca4c22**
SabNZBD Version: **2.3.5 [76c7a6c]**
OS: **Windows-2016-Server**

I have pulled the latest zip of the master branch
i also tested the nighly, same issue

`
[CouchPotato]

    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movies]]
        enabled = 1
        apikey = <XXX>
        host = localhost
        port = 6663
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        ssl = 0
        web_root = ""
        # api key for www.omdbapi.com (used as alternative to imdb)
        omdbapikey = ""
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 1
        wait_for = 2
        extract = 0
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if Couchpotato is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = ""
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0
`   

```
[08:43:47] [INFO]::MAIN: Loading config from [C:\Apps\nzbToMedia\autoProcessMedia.cfg]
[08:43:47] [INFO]::MAIN: Checking database structure...
[08:43:47] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[08:43:47] [DEBUG]::MAIN: InitialSchema upgrade not required
[08:43:47] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
[08:43:47] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Apps\nzbToMedia
[08:43:47] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
[08:43:47] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
[08:43:47] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Apps\nzbToMedia
[08:43:48] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
[08:43:48] [INFO]::MAIN: Checking if git needs an update
[08:43:48] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Apps\nzbToMedia
[08:43:48] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
[08:43:48] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Apps\nzbToMedia
[08:43:49] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
[08:43:49] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet "@{upstream}" with your shell in C:\Apps\nzbToMedia
[08:43:49] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet "@{upstream}" : returned successful
[08:43:49] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-list --left-right "@{upstream}"...HEAD with your shell in C:\Apps\nzbToMedia
[08:43:49] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-list --left-right "@{upstream}"...HEAD : returned successful
[08:43:49] [DEBUG]::MAIN: cur_commit = 697ae370adef98f378ad3b8109c3c2c7e52a18d5 % (newest_commit)= 697ae370adef98f378ad3b8109c3c2c7e52a18d5, num_commits_behind = 0, num_commits_ahead = 0
[08:43:49] [INFO]::MAIN: No update needed
[08:43:49] [INFO]::MAIN: nzbToMedia Version:697ae370adef98f378ad3b8109c3c2c7e52a18d5 Branch:master (Windows 10)
[08:43:49] [INFO]::MAIN: #########################################################
[08:43:49] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[08:43:49] [INFO]::MAIN: #########################################################
[08:43:49] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\Apps\\nzbToMedia\\nzbToCouchPotato.py', 'D:\\Files\\Download\\News\\Movies\\Big.Buck.Bunny.2008.1080p.x264-60fps.Surround', 'Big.Buck.Bunny.2008.1080p.x264-60fps.Surround.nzb', 'Big.Buck.Bunny.2008.1080p.x264-60fps.Surround', '', 'movies', 'alt.binaries.movies', '0', '']
[08:43:49] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[08:43:49] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[08:43:51] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_zngqlh
[08:43:51] [DEBUG]::MAIN: Adding NZB download info for directory D:\Files\Download\News\Movies\Big.Buck.Bunny.2008.1080p.x264-60fps.Surround to database
[08:43:51] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[08:43:51] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Big.Buck.Bunny.2008.1080p.x264-60fps.Surround.nzb
[08:43:51] [INFO]::MAIN: Attemping imdbID lookup for Big.Buck.Bunny.2008.1080p.x264-60fps.Surround.nzb
[08:43:51] [INFO]::MAIN: Searching folder and file names for imdbID ...
[08:43:51] [INFO]::MAIN: Searching IMDB for imdbID ...
[08:43:51] [INFO]::MAIN: Unable to determine imdbID: No api key provided for ombdapi.com.
[08:43:51] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:6663/api/0a595d828de540019b3f26609b7c8ca9/
[08:43:51] [DEBUG]::SERVER: Server responded at http://localhost:6663/api/0a595d828de540019b3f26609b7c8ca9/
[08:43:51] [DEBUG]::MAIN: Opening URL: http://localhost:6663/api/0a595d828de540019b3f26609b7c8ca9/media.list with PARAMS: {}
Traceback (most recent call last):
File "C:\Apps\nzbToMedia\nzbToCouchPotato.py", line 262, in <module>
result = nzbToMedia.main(sys.argv, section)
File "C:\Apps\nzbToMedia\nzbToMedia.py", line 862, in main
download_id='', failureLink=''.join(args[8:]))
File "C:\Apps\nzbToMedia\nzbToMedia.py", line 729, in process
inputCategory, failureLink)
File "C:\Apps\nzbToMedia\core\autoProcess\autoProcessMovie.py", line 186, in process
release = self.get_release(baseURL, imdbid, download_id)
File "C:\Apps\nzbToMedia\core\autoProcess\autoProcessMovie.py", line 77, in get_release
for release in releases:
TypeError: 'NoneType' object is not iterable

```

**Comment by Nimmsis** [comment]
Here is the response.

[media.txt](https://github.com/clinton-hall/nzbToMedia/files/2618619/media.txt)

**Comment by clinton-hall** [comment]
The problem was "The Wolf Of Wall Street" had releases = None....
Never seen that before from CouchPotato.
I added a test for this. Please update to latest nightly branch and test again.

**Comment by Nimmsis** [comment]
New fix seems to work, thx
