### ISSUE TITLE
IndexError: tuple index out of range in cleanDir()

### ISSUE THREAD

**Issue by brianjmurrell** [clinton-hall/nzbToMedia#1397]
Using 697ae370adef98f378ad3b8109c3c2c7e52a18d5, when a download fails I will often see:

Traceback (most recent call last):
File "/home/foo/.sickrage/contrib/nzbToMedia/nzbToSickBeard.py", line 263, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/home/foo/.sickrage/contrib/nzbToMedia/nzbToMedia.py", line 862, in main
download_id='', failureLink=''.join(args[8:]))
File "/home/foo/.sickrage/contrib/nzbToMedia/nzbToMedia.py", line 753, in process
cleanDir(inputDirectory, sectionName, inputCategory)
File "/home/foo/.sickrage/contrib/nzbToMedia/core/nzbToMediaUtil.py", line 789, in cleanDir
"Directory {0} still contains {1} unprocessed file(s), skipping ...\n{3}".format(path, num_files, files),
IndexError: tuple index out of range
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess object at 0xb714f58c>> ignored

I'll add some debugging to see what's going on in the meanwhile if you don't know off-hand what the problem is.

**Comment by clinton-hall** [comment]
https://github.com/clinton-hall/nzbToMedia/blob/master/core/nzbToMediaUtil.py#L788

That line doesn't have the `\n{3}` that appears in the traceback you posted.
It looks like, for some reason, that has been appended into line 788 (789?) of /home/foo/.sickrage/contrib/nzbToMedia/core/nzbToMediaUtil.py
