### ISSUE TITLE
Utorrent calls but nzbtomedia not running

### ISSUE THREAD

**Issue by fidofido300** [clinton-hall/nzbToMedia#1443]
I have been using same setup for the past 6 month and it was working reliably
after I updated nzbtomedia today I started to get

Traceback (most recent call last):
  File "c:\Sickrage\SickRage\contrib\nzbToMedia\TorrentToMedia.py", line 7, in <module>    import core
  File "c:\Sickrage\SickRage\contrib\nzbToMedia\core\__init__.py", line 46, in <module>    from core import logger, main_db, version_check, databases, transcoder
  File "c:\Sickrage\SickRage\contrib\nzbToMedia\core\databases.py", line 4, in <module>    from core.utils import backup_versioned_file
  File "c:\Sickrage\SickRage\contrib\nzbToMedia\core\utils.py", line 39, in <module>    import jaraco
ImportError: No module named jaraco

is there anythinf that I can do to rectify the situation :)
Thanks For your Work and answer

**Comment by labrys** [comment]
@fidofido300 It looks like you are using the nightly branch.  There are currently a lot of changes happening in nightly, so it might be better to stick to master for the time being.  

The cause of your issue is likely due to bytecode files (files ending in .pyc or .pyo) created by python not being cleaned up (see #1436).  Removing those files should allow your current setup to run successfully.  These will be cleaned up automatically when the code is merged to master.

**Comment by fidofido300** [comment]
Thank you
Bu I have Manually deleted every .pyc file and run the command executed by utorrent manually at a command promt and get the same error.

**Comment by labrys** [comment]
@fidofido300 From all the subfolders?  The bytecode files get generated in every folder with a .py file.

**Comment by labrys** [comment]
Try the following:
```
c:
cd c:\Sickrage\SickRage\contrib\nzbToMedia\
python -c "import libs.autoload; import jaraco"
```

**Comment by labrys** [comment]
Thanks for all the testing you're doing, I really appreciate it.  Can you try the following:
```
git clean -fdx core libs
python -c "import libs.autoload; import jaraco"
```

**Comment by fidofido300** [comment]
No Proplem 
Thanks you for your time!
c:\Sickrage\SickRage\contrib\nzbToMedia>python -c "import libs.autoload; import
jaraco"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jaraco


 Directory of c:\Sickrage\SickRage\contrib\nzbToMedia\libs

23/12/2018  09:41    <DIR>          .
23/12/2018  09:41    <DIR>          ..
22/12/2018  19:14                71 autoload.py
23/12/2018  09:41               202 autoload.pyc
23/12/2018  09:41    <DIR>          common
22/12/2018  19:14    <DIR>          custom
22/12/2018  19:14    <DIR>          py2
22/12/2018  19:14               142 requirements-common.txt
22/12/2018  19:14                29 requirements-custom.txt
22/12/2018  19:14                72 requirements-py2.txt
22/12/2018  19:14                16 requirements-win.txt
22/12/2018  19:14               127 requirements.txt
22/12/2018  19:14             1,935 util.py
23/12/2018  09:41             2,180 util.pyc
23/12/2018  09:41    <DIR>          win
22/12/2018  19:14               817 __init__.py
23/12/2018  09:41             1,384 __init__.pyc
22/12/2018  19:14               528 __main__.py
              12 File(s)          7,503 bytes
 
 Directory of c:\Sickrage\SickRage\contrib\nzbToMedia\libs\win

23/12/2018  09:41    <DIR>          .
23/12/2018  09:41    <DIR>          ..
22/12/2018  19:14    <DIR>          bin
22/12/2018  19:14    <DIR>          importlib_metadata
22/12/2018  19:14    <DIR>          jaraco
22/12/2018  19:14               540 jaraco.classes-1.5-py3.6-nspkg.pth
22/12/2018  19:14               540 jaraco.collections-1.6.0-py3.7-nspkg.pth
22/12/2018  19:14               540 jaraco.functools-1.20-py3.6-nspkg.pth
22/12/2018  19:14               540 jaraco.structures-1.1.2-py3.6-nspkg.pth
22/12/2018  19:14               540 jaraco.text-1.10.1-py3.6-nspkg.pth
22/12/2018  19:14               540 jaraco.ui-1.6-py3.6-nspkg.pth
22/12/2018  19:14               540 jaraco.windows-3.9.2-py3.7-nspkg.pth
22/12/2018  19:14    <DIR>          more_itertools
22/12/2018  19:14            56,793 path.py
22/12/2018  19:14            32,452 six.py
22/12/2018  19:14            40,532 test_path.py

**Comment by labrys** [comment]
OK I was able to reproduce the bug.  I think its because it's not processing the .pth files on load.

**Comment by labrys** [comment]
Should be fixed in nightly now.
