### ISSUE TITLE
nzbToSickBeard error

### ISSUE THREAD

**Issue by Pintglass** [clinton-hall/nzbToMedia#1474]
I'm having an issue getting the nzbTSickBeard script to run from within sabnzbd, i seem to be able to run the script manually. I have enabled debug logging in the cfg file but when the script is run from within sabnzbd i get no entries in the log.
Im running sabnzbd and sickchill on my synology nas.
The following is the error i get from sabnzbd
```
 -- Cleaning bytecode --
Traceback (most recent call last):
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/nzbToSickBeard.py", line 260, in <module>
import nzbToMedia
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 627, in <module>
cleanup.clean('core', 'libs')
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/cleanup.py", line 79, in clean
result = clean_bytecode()
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/cleanup.py", line 50, in clean_bytecode
'!**/__pycache__/',  # and __pycache__ folders
File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/cleanup.py", line 38, in git_clean
return subprocess.check_output(command)
File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```
Thanks

**Comment by labrys** [comment]
@Pintglass this should have been fixed, can you try updating and see if you still get the error?
