### ISSUE TITLE
"OSError: [Errno 2] No such file or directory" After nzbToMedia auto update

### ISSUE THREAD

**Issue by KohmeiK** [clinton-hall/nzbToMedia#1476]
This could be issue #1436, but I have no idea how to execute any of the possible solutions. Could someone verify this and kindly give me instructions on how to fix this? Thanks!

![capture](https://user-images.githubusercontent.com/19924289/50538199-2fc2f900-0baf-11e9-8ada-c4d763871487.PNG)

This was the first time it started not running, and every download after this has the same issue. 

```
[14:05:59] [INFO]::MAIN: Loading config from [/scripts/autoProcessMedia.cfg]
[14:06:00] [INFO]::MAIN: Checking database structure...
[14:06:00] [INFO]::MAIN: Checking if source needs an update
[14:06:00] [INFO]::MAIN: There is a newer version available (you're 7 commits behind)
[14:06:00] [INFO]::MAIN: Auto-Updating nzbToMedia, Please wait ...
[14:06:01] [INFO]::MAIN: Creating update folder /scripts/sb-update before extracting
[14:06:01] [INFO]::MAIN: Downloading update from 'https://github.com/clinton-hall/nzbToMedia/tarball/master'
[14:06:04] [INFO]::MAIN: Extracting file /scripts/sb-update/nzbtomedia-update.tar
[14:06:05] [INFO]::MAIN: Deleting file /scripts/sb-update/nzbtomedia-update.tar
[14:06:05] [INFO]::MAIN: Moving files from /scripts/sb-update/clinton-hall-nzbToMedia-c428b57 to /scripts
[14:06:05] [INFO]::MAIN: Restarting nzbToMedia with ['/usr/bin/python2', '/scripts/nzbToCouchPotato.py', '/downloads/sabnzbd/movie/Thor.The.Dark.World.2013.1080p.BluRay.x264-nikt0-xpost.cp(tt1981115)', 'Thor.The.Dark.World.2013.1080p.BluRay.x264-nikt0-xpost.cp(tt1981115).nzb', 'Thor.The.Dark.World.2013.1080p.BluRay.x264-nikt0-xpost.cp(tt1981115)', '', 'movie', 'alt.binaries.newznzb.alpha', '0']
-- Cleaning bytecode --
Traceback (most recent call last):
File "/scripts/nzbToCouchPotato.py", line 259, in <module>
import nzbToMedia
File "/scripts/nzbToMedia.py", line 627, in <module>
cleanup.clean('core', 'libs')
File "/scripts/cleanup.py", line 79, in clean
result = clean_bytecode()
File "/scripts/cleanup.py", line 50, in clean_bytecode
'!**/__pycache__/',  # and __pycache__ folders
File "/scripts/cleanup.py", line 38, in git_clean
return subprocess.check_output(command)
File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```
This is running on a Docker in Unraid. Sabnzbd Version: 2.3.5 [76c7a6c]

**Comment by labrys** [comment]
`OSError` should have already been caught in the latest update.  Can you try updating and see if it fixes your problem?

**Comment by Kohmei358** [comment]
Im not sure how to update manually. Is doing 'git pull' in the nzbToMedia directory correct?

**Comment by labrys** [comment]
Assuming you have a git install and that you are on master `git pull origin master` should have you updated to the latest.  You can check the `changelog.txt` and see if the version is `v11.8.0` to see if you're up to date on master/dev.

**Comment by labrys** [comment]
That error means its not a git repository.
Running `git init` would make it a git repository but would not update it to the correct upstream, then cleanup would likely erase your `core` and `libs` folders.

The issue you have is fixed in the latest master.  
You can update manually by downloading the latest release and extracting it.

**Comment by Kohmei358** [comment]
Could you let me know exactly how to do that? Do I delete my current nzbToMedia folder then downloaded again with `git clone` or `wget`? Or should I only replace certain files in this folder?

**Comment by labrys** [comment]
Sorry for the delay in responding, I was traveling for the holidays.

First, I would back up your `autoProcessMedia.cfg` and any custom scripts you may have installed, just to be safe.  You can download the latest source release from [here](https://github.com/clinton-hall/nzbToMedia/releases/latest) and extract it to your `nzbToMedia` folder..
