### ISSUE TITLE
Module Import Error?

### ISSUE THREAD

**Issue by AJohnsonCHC** [clinton-hall/nzbToMedia#1499]
Scripts updated today and all post processing for sickbeard is failing with the same error.

```
Sat Jan 05 2019 01:52:27	INFO	Executing post-process-script nzbToSickBeard.py for [Erai-raws].Zero.kara.Hajimeru.Mahou.no.Sho.-.01.[BDRip.1080p.AVC-YUV444P10.FLAC][889D8F1A]
Sat Jan 05 2019 01:52:27	INFO	nzbToSickBeard: fatal: not a git repository (or any of the parent directories): .git
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: Changing to directory: C:\ProgramData\NZBGet\scripts
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: -- Cleaning bytecode --
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: Error Code: 128
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: Directory is not a git repository
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: Returning to directory:  C:\Users\root\Desktop
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: -- Cleanup finished --
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: Traceback (most recent call last):
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:   File "C:\ProgramData\NZBGet\scripts\nzbToSickBeard.py", line 261, in <module>
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:     import nzbToMedia
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:   File "C:\ProgramData\NZBGet\scripts\nzbToMedia.py", line 633, in <module>
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:     import core
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:   File "C:\ProgramData\NZBGet\scripts\core\__init__.py", line 48, in <module>
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:     from core.utils import (
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:   File "C:\ProgramData\NZBGet\scripts\core\utils.py", line 19, in <module>
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard:     from qbittorrent import Client as qBittorrentClient
Sat Jan 05 2019 01:52:28	INFO	nzbToSickBeard: ImportError: cannot import name Client
```

**Comment by AJohnsonCHC** [comment]
Nevermind, I saw the 2 earlier pull requests and noticed the git error in the above log, I've recloned the repository and everything is working.
