### ISSUE TITLE
AttributeError: 'module' object has no attribute 'InitialSchema'

### ISSUE THREAD

**Issue by rkorn86** [clinton-hall/nzbToMedia#1516]
Im running nzbtomedia 12.0.5 and after everything successfully got sent to couchpotato im getting the following output and nzbget marks download as PP-Failure (even though everything went fine, except for the last error message):
```
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: -- Cleaning bytecode --
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: Error: [Errno 2] No such file or directory
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: -- Cleaning folders: ['libs', 'core'] --
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: Error: [Errno 2] No such file or directory
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: Returning to directory:  /run/s6/services/nzbget
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: -- Cleanup finished --
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: Traceback (most recent call last):
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:   File "/downloads/scripts/nzbToMedia/nzbToCouchPotato.py", line 263, in <module>
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:     result = nzbToMedia.main(sys.argv, section)
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:   File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 780, in main
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:     core.initialize(section)
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:   File "/downloads/scripts/nzbToMedia/core/__init__.py", line 326, in initialize
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato:     main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: AttributeError: 'module' object has no attribute 'InitialSchema'
Mon Jan  7 18:46:27 2019        INFO    nzbToCouchPotato: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x7fc5704ba510>> ignored
```
Im running NZBGet 20.0 and couchpotato inside docker container. Do you need any more information?

**Comment by labrys** [comment]
You can call it with no parameters..   It won't process anything, but it looks like its failing during initialization so that should not matter.

**Comment by rkorn86** [comment]
```
root@nuc:/$ /downloads/scripts/nzbToMedia/nzbToMedia.py
Changing to directory: /downloads/scripts/nzbToMedia

-- Cleaning bytecode --
Error: [Errno 2] No such file or directory

-- Cleaning folders: ['libs', 'core'] --
Error: [Errno 2] No such file or directory
Returning to directory:  /

-- Cleanup finished --

[22:42:11] [INFO]::MAIN: Loading config from [/downloads/scripts/nzbToMedia/autoProcessMedia.cfg]
Traceback (most recent call last):
  File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 955, in <module>
    exit(main(sys.argv))
  File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 780, in main
    core.initialize(section)
  File "/downloads/scripts/nzbToMedia/core/__init__.py", line 326, in initialize
    main_db.upgrade_database(main_db.DBConnection(), databases.InitialSchema)
AttributeError: 'module' object has no attribute 'InitialSchema'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x7ff37fd5b390>> ignored
```

**Comment by labrys** [comment]
Please try the following:
```
python -c "import cleanup; cleanup.force_clean_folder('libs', cleanup.FOLDER_STRUCTURE['libs'])"
```

**Comment by labrys** [comment]
Ok now please try the following:
```
python -c "import cleanup; cleanup.force_clean_folder('core', cleanup.FOLDER_STRUCTURE['core'])"
```

**Comment by rkorn86** [comment]
Sorry, but I just restarted from scratch, except my autoProcessMedia.cfg, and everything works now. Seems to be an update related issue I cannot reproduce anymore.

**Comment by labrys** [comment]
@rkorn86 It looks like the cleanup never executed and some files were left behind after the upgrade causing your issue.  I'm glad you're back up and running, and I'm sorry for your trouble.  Thanks for your patience.
