### ISSUE TITLE
CouchPotato with nzbtomedia.py not working

### ISSUE THREAD

**Issue by Silentbob101** [clinton-hall/nzbToMedia#1523]
The script seems to fall over on the post-processing step... I have previously had this working but have moved setup and am resetting everything up

```
Changing to directory: /Applications/SickChill/contrib/nzbToMedia

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /Applications/SABnzbd.app/Contents/Resources

-- Cleanup finished --

[02:39:47] [INFO]::MAIN: Loading config from [/Applications/SickChill/contrib/nzbToMedia/autoProcessMedia.cfg]
[02:39:47] [INFO]::MAIN: Checking database structure...
[02:39:47] [INFO]::MAIN: Checking if git needs an update
[02:39:48] [INFO]::MAIN: There is a newer version available (you're 59 commits behind)
[02:39:48] [INFO]::MAIN: nzbToMedia Version:f9f3fafb1ba6f61d5e2891e068495967dae5b249 Branch:master (Darwin 17.7.0)
[02:39:48] [WARNING]::MAIN: Failed to locate 7zip. Transcoding of disk images and extraction of .7z files will not be possible!
[02:39:48] [WARNING]::MAIN: Failed to locate par2. Repair and rename using par files will not be possible!
[02:39:48] [INFO]::MAIN: #########################################################
[02:39:48] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[02:39:48] [INFO]::MAIN: #########################################################
[02:39:48] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[02:39:48] [ERROR]::MAIN: Unable to open URL
[02:39:48] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[02:39:48] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Accidental.Courtesy.Daryl.Davis.Race.And.America.2016.1080p.WEB.x264-SKGTV English.cp(tt5390430).nzb
[02:39:48] [INFO]::MAIN: Attemping imdbID lookup for Accidental.Courtesy.Daryl.Davis.Race.And.America.2016.1080p.WEB.x264-SKGTV English.cp(tt5390430).nzb
[02:39:48] [INFO]::MAIN: Searching folder and file names for imdbID ...
[02:39:48] [INFO]::MAIN: Found imdbID [tt5390430]
[02:39:48] [ERROR]::MAIN: CouchPotato returned the following non-json data
[02:39:48] [ERROR]::MAIN:
[02:39:48] [ERROR]::MAIN: <!doctype html>
[02:39:48] [ERROR]::MAIN: <html class="dark">
[02:39:48] [ERROR]::MAIN: <head>
[02:39:48] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[02:39:48] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[02:39:48] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[02:39:48] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[02:39:48] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[02:39:48] [ERROR]::MAIN:
[02:39:48] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1441083262" rel="stylesheet" href="/static/style/combined.min.css?1441083262" type="text/css">
[02:39:48] [ERROR]::MAIN:
[02:39:48] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.vendor.min.js?1441083180"></script>
[02:39:48] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.base.min.js?1441083180"></script>
[02:39:48] [ERROR]::MAIN: <link href="/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[02:39:48] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/static/images/homescreen.png" />
[02:39:48] [ERROR]::MAIN:
[02:39:48] [ERROR]::MAIN: <title>CouchPotato</title>
[02:39:48] [ERROR]::MAIN: </head>
[02:39:48] [ERROR]::MAIN: <body class="page login">
[02:39:48] [ERROR]::MAIN: <form action="" method="post">
[02:39:48] [ERROR]::MAIN: <h1>CouchPotato</h1>
[02:39:48] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[02:39:48] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[02:39:48] [ERROR]::MAIN: <div class="ctrlHolder">
[02:39:48] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[02:39:48] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[02:39:48] [ERROR]::MAIN: </div>
[02:39:48] [ERROR]::MAIN: </form>
[02:39:48] [ERROR]::MAIN: </body>
[02:39:48] [ERROR]::MAIN: </html>
[02:39:48] [INFO]::TRANSCODER: Checking [Accidental.Courtesy.Daryl.Davis.Race.And.America.2016.1080p.WEB.x264-SKGTV.English.cp(tt5390430).mkv] for corruption, please stand by ...
[02:39:48] [INFO]::TRANSCODER: SUCCESS: [Accidental.Courtesy.Daryl.Davis.Race.And.America.2016.1080p.WEB.x264-SKGTV.English.cp(tt5390430).mkv] has no corruption.
[02:39:48] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Accidental.Courtesy.Daryl.Davis.Race.And.America.2016.1080p.WEB.x264-SKGTV English.cp(tt5390430).nzb
Traceback (most recent call last):
File "/Applications/SickChill/contrib/nzbToMedia/nzbToMedia.py", line 955, in <module>
exit(main(sys.argv))
File "/Applications/SickChill/contrib/nzbToMedia/nzbToMedia.py", line 885, in main
download_id='', failure_link=''.join(args[8:]))
File "/Applications/SickChill/contrib/nzbToMedia/nzbToMedia.py", line 748, in process
result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/Applications/SickChill/contrib/nzbToMedia/core/auto_process/movies.py", line 203, in process
result = r.json()
File "/Applications/SickChill/contrib/nzbToMedia/libs/common/requests/models.py", line 897, in json
return complexjson.loads(self.text, **kwargs)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.PosixProcess object at 0x106e6ff90>> ignored
```

I have previously had this working

**Comment by clinton-hall** [comment]
in autoProcessMedia.cfg
```
[CouchPotoato]
    [[movie]]
         apikey =
```
Api key must match the api key as set in CouchPotato

**Comment by Silentbob101** [comment]
Thanks for pointing me in the right direction... the API keys did match but I generated a new in couch potato and changed it and now it's working again thank you!
