### ISSUE TITLE
 Invalid return character or leading space in header: X-Api-Key

### ISSUE THREAD

**Issue by dargo1967** [clinton-hall/nzbToMedia#1529]
Greetings,

My install of NZBGet and Sonarr has been running untouched for at least a year if not more. Recently though post-process is failing.  The log is below.  It seems to not like Sonarr's api key.  I noticed that in the autoProcessMedia.cfg the api key has a leading space in it, like so:

        apikey = " xxxxxxxxxxxxxxxxxxx"
 
But when I remove the space (and even the quote too) and run nzbToMedia.py both the leading space and the quotes come back

Snip of the log below. 
 
Thanks!
```
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Removing libs/py2/yaml/scanner.pyc
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Removing libs/py2/yaml/serializer.pyc
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Removing libs/py2/yaml/tokens.pyc
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Removing libs/util.pyc
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: No folders to clean
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Returning to directory:  /home/pi
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: -- Cleanup finished --
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: Traceback (most recent call last):
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 955, in <module>
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     exit(main(sys.argv))
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 856, in main
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     failure_link=failure_link)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 750, in process
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/core/auto_process/tv.py", line 36, in process
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     fork, fork_params = auto_fork(section, input_category)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/core/forks.py", line 47, in auto_fork
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     r = requests.get(url, headers=headers, stream=True, verify=False)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/api.py", line 75, in get
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     return request('get', url, params=params, **kwargs)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/api.py", line 60, in request
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     return session.request(method=method, url=url, **kwargs)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/sessions.py", line 519, in request
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     prep = self.prepare_request(req)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/sessions.py", line 462, in prepare_request
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     hooks=merge_hooks(request.hooks, self.hooks),
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/models.py", line 314, in prepare
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     self.prepare_headers(headers)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/models.py", line 448, in prepare_headers
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     check_header_validity(header)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:   File "/opt/nzbget/scripts/nzbToMedia/libs/common/requests/utils.py", line 942, in check_header_validity
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia:     raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
Wed Jan 16 22:55:57 2019        INFO    nzbToMedia: requests.exceptions.InvalidHeader: Invalid return character or leading space in header: X-Api-Key
```

**Comment by labrys** [comment]
Can you enable debug logging and post the results?  Debug logging can be enabled by setting `log_debug = 1` in your `autoProcessMedia.cfg`

**Comment by clinton-hall** [comment]
Don't edit this in the .cfg file... it is in NZBGet, so it will always re-import the apikey from NZBGet.

To fix, in NZBGet go into the settings, look under nzbToMedia and the `ndapikey=` make sure there is no leading space. Then save settings, restart NZBGet and try to postprocess again...

**Comment by dargo1967** [comment]
Thank you!   There WAS a leading space in the nzbToMedia area of the NZBGet settings.  I had looked at that, but only under the NZBTONZBDRONE section where it was correct with no white space.  After removing that space everything is working fine again, thank you for your help.

**Comment by clinton-hall** [comment]
Glad we could resolve this one. Let us know if you have any further issues.
