### ISSUE TITLE
AutoProcessMedia.cfg overwritten with invalid file

### ISSUE THREAD

**Issue by nstead** [clinton-hall/nzbToMedia#1553]
I'm using nzbToMedia with nzbget and nzbDrone / Sonarr.

The problem I'm having is that when runs nzbToMedia as part of its post-processing, I see errors reported in the configuration file (AutoProcessMedia.cfg).
Among the errors, it reports "First error at line 78".  When I look at this line in AutoProcessMedia.cfg, I see at the end of the CouchPotato section, after the [[movie]] subsection, another subsection as follows:
```
     [[""]]
        apikey = ""
        host = ""
        port = ""
        ssl = 0
        web_root = ""
        method = manage
        delete_failed = 0
        remote_path = 1
        wait_for = 4
        omdbapikey = ""
        enabled = 1

```
Line 78 is the one which has `[[""]]`
There are similar subsections under [Sickbeard] and [Headphones].  I don't actually use any of these applications.
If I remove these subsections, and save the file, I can re-run the nzbget Post-processing, and it works...once.  After that the AutoProcessMedia.cfg file is overwritten with another version, which contains the offending subsections again.

Any advice would be gratefully received!

Here is the nzbget error log:
```
Wed Feb 13 2019 22:32:39 | Collection The.Big.Bang.Theory.S12E15.720p.HDTV.x264-AVS-Obfuscated added to history
-- | --
ERROR | Wed Feb 13 2019 22:32:39 | Post-process-script nzbToMedia/nzbToNzbDrone.py for The.Big.Bang.Theory.S12E15.720p.HDTV.x264-AVS-Obfuscated failed (terminated with unknown status)
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f0dcf7361d0>> ignored
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: First error at line 78.
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: configobj.ConfigObjError: Parsing failed with several errors.
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: raise error
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/libs/common/configobj.py", line 1318, in _load
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: self._load(infile, configspec)
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/libs/common/configobj.py", line 1229, in __init__
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: super(configobj.ConfigObj, self).__init__(*args, **kw)
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/core/configuration.py", line 95, in __init__
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: cfg_new = config()
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/core/configuration.py", line 254, in addnzbget
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: CFG = config.addnzbget()
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/core/__init__.py", line 329, in initialize
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: core.initialize(section)
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/nzbToMedia.py", line 780, in main
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: result = nzbToMedia.main(sys.argv, section)
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: File "/scripts/nzbToMedia/nzbToNzbDrone.py", line 250, in <module>
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Traceback (most recent call last):
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: -- Cleanup finished --
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Returning to directory: /
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: No folders to clean
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: -- Cleaning folders: ['libs', 'core'] --
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing nzbToMedia.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/util.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/py2/yaml/tokens.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/py2/yaml/serializer.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/py2/yaml/scanner.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/py2/yaml/resolver.pyc
INFO | Wed Feb 13 2019 22:32:39 | nzbToNzbDrone: Removing libs/py2/yaml/representer.pyc
```

**Comment by clinton-hall** [comment]
The way the script works, it loads the config from NZBGet. So even if you edit autoProcessMedia.cfg it will overwrite this with the config in NZBGet.

The solution here is to ensure that in NZBGet you configure all relevant config lines in the web ui pertaining to the scripts being executed.

In this case, check nzbToMedia.py or nzbToNzbDrone.py and make sure you set the relevant details in nd category, ndapikey etc...

**Comment by nstead** [comment]
OK, having played around with this for a week, it seems to have cured itself.  Not sure exactly what I did, but it seems to be working again now.

**Comment by clinton-hall** [comment]
glad to hear it is working.
