### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1570]
**Describe the bug**
ImportError: cannot import name Client, latest commit broke nzbtomedia completely  even my nzb downloads are affected by this
i'm on the latest version 832ef323401ae73a1fb7d4b20753590a4c98a6a3 - nightly

**Technical Specs**
macOS 10.14.3
Python 2.7.16
SabNZB & qBittorrent
Medusa

**Log**

Nothing in the nzbtomedia, Medusa logs only this traceback from Sab:

```Changing to directory: /Users/Admin/Apps/nzbToMedia

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /Applications/SABnzbd.app/Contents/Resources

-- Cleanup finished --

Traceback (most recent call last):
File "/Users/Admin/Apps/nzbToMedia/nzbToSickBeard.py", line 261, in <module>
import nzbToMedia
File "/Users/Admin/Apps/nzbToMedia/nzbToMedia.py", line 636, in <module>
import core
File "/Users/Admin/Apps/nzbToMedia/core/__init__.py", line 49, in <module>
from core.plugins.downloaders.configuration import (
File "/Users/Admin/Apps/nzbToMedia/core/plugins/downloaders/configuration.py", line 2, in <module>
from core.plugins.downloaders.torrent.configuration import (
File "/Users/Admin/Apps/nzbToMedia/core/plugins/downloaders/torrent/configuration.py", line 2, in <module>
from core.plugins.downloaders.torrent.utils import create_torrent_class
File "/Users/Admin/Apps/nzbToMedia/core/plugins/downloaders/torrent/utils.py", line 7, in <module>
from .qbittorrent import configure_client as qbittorrent_client
File "/Users/Admin/Apps/nzbToMedia/core/plugins/downloaders/torrent/qbittorrent.py", line 1, in <module>
from qbittorrent import Client as qBittorrentClient
ImportError: cannot import name Client```

**Comment by labrys** [comment]
Fix in progress

**Comment by labrys** [comment]
@XxUnkn0wnxX Should be fixed now.  Please let me know if you have any further issues.
