### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by fire222** [clinton-hall/nzbToMedia#1577]
this is the error in Sab
```
ERROR | Notification script returned exit code 1 and output "Changing to directory: C:\nzbToMedia\nzbToMedia-master -- Cleaning bytecode -- WARNING: Automatic cleanup could not be executed. If errors occur, manual cleanup may be required. REASON : Error: [WinError 2] The system cannot find the file specified Directory is not a git repository Force cleaning folder: libs Skipping required subfolders ['common', 'custom', 'py2', 'win'] Removing libs\__pycache__ Force cleaning folder: core Skipping required subfolders ['auto_process', 'extractor', 'utils'] Removing core\__pycache__ Returning to directory: C:\Program Files\SABnzbd -- Cleanup finished -- Traceback (most recent call last): File "C:\nzbToMedia\nzbToMedia-master\nzbToSickBeard.py", line 261, in import nzbToMedia File "C:\nzbToMedia\nzbToMedia-master\nzbToMedia.py", line 636, in import core File "C:\nzbToMedia\nzbToMedia-master\core\__init__.py", line 49, in from core.plugins.downloaders.configuration import ( ModuleNotFoundError: No module named 'core.plugins'

```
the nzbtomedia logs look like they stopped working yesterday at 16:27:46
```
2019-03-12 16:27:38 INFO    ::MAIN: Loading config from [C:\nzbToMedia\nzbToMedia-master\autoProcessMedia.cfg]
2019-03-12 16:27:38 INFO    ::MAIN: Python v3.7 will reach end of life in 1568 days.
2019-03-12 16:27:38 INFO    ::MAIN: Checking database structure...
2019-03-12 16:27:38 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2019-03-12 16:27:38 DEBUG   ::MAIN: InitialSchema upgrade not required
2019-03-12 16:27:38 INFO    ::MAIN: Checking if source needs an update
2019-03-12 16:27:38 DEBUG   ::MAIN: cur_commit = ef950d8024b66efb5935a6e0619b9e15b2e1036b % (newest_commit)= 8745af26298f995487ba3a21d74185c57fc158e2, num_commits_behind = 18
2019-03-12 16:27:38 INFO    ::MAIN: There is a newer version available (you're 18 commits behind)
2019-03-12 16:27:38 INFO    ::MAIN: Auto-Updating nzbToMedia, Please wait ...
2019-03-12 16:27:39 DEBUG   ::MAIN: cur_commit = ef950d8024b66efb5935a6e0619b9e15b2e1036b % (newest_commit)= 8745af26298f995487ba3a21d74185c57fc158e2, num_commits_behind = 18
2019-03-12 16:27:39 INFO    ::MAIN: Creating update folder C:\nzbToMedia\nzbToMedia-master\sb-update before extracting
2019-03-12 16:27:39 INFO    ::MAIN: Downloading update from 'https://github.com/clinton-hall/nzbToMedia/tarball/master'
2019-03-12 16:27:40 INFO    ::MAIN: Extracting file C:\nzbToMedia\nzbToMedia-master\sb-update\nzbtomedia-update.tar
2019-03-12 16:27:43 INFO    ::MAIN: Deleting file C:\nzbToMedia\nzbToMedia-master\sb-update\nzbtomedia-update.tar
2019-03-12 16:27:43 INFO    ::MAIN: Moving files from C:\nzbToMedia\nzbToMedia-master\sb-update\clinton-hall-nzbToMedia-8745af2 to C:\nzbToMedia\nzbToMedia-master
2019-03-12 16:27:46 INFO    ::MAIN: Restarting nzbToMedia with ['C:\\Users\\Ron\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', 'C:\\nzbToMedia\\nzbToMedia-master\\nzbToSickBeard.py', 'F:\\complete\\tv',  '']
```

**Comment by labrys** [comment]
@fire222 Looks like the post-update cleanup did not work for your install.  How did you install nzbToMedia?  Do you use git clone or download a Zip file or another method?

**Comment by fire222** [comment]
download a Zip file

**Comment by labrys** [comment]
So easy fix would be to download the latest release and extract it.  Just copy your existing config file to the new folder.  

The cleanup script relies on git as its primary cleanup method.  Advantage of a zip file is its easy to just download and extract it and replace the config.

**Comment by fire222** [comment]
no idea were I got the zip file from..I see the update here but it doesn't look like a zip file..not sure what to do with it..sorry so bad at this

**Comment by labrys** [comment]
From the main page click on releases
![image](https://user-images.githubusercontent.com/1867464/54314801-fe08de00-45b2-11e9-9b2c-5d6d1a96a627.png)
From the releases page find the correct version and download the zip file
![image](https://user-images.githubusercontent.com/1867464/54314922-458f6a00-45b3-11e9-87b8-49c482036e39.png)

**Comment by fire222** [comment]
thanks for the help...did all that but still get the same errors and no log file

**Comment by clinton-hall** [comment]
hopefully this is now fixed. Please update and confirm.

**Comment by labrys** [comment]
Good catch.  Need to add gitless update as a test to check for this

**Comment by fire222** [comment]
working great again..thanks!!
