### ISSUE TITLE
exit code from script is 1

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1610]
hi her i go after a new install of a syno nas with sab hp radar and sonarr.
This is the log :
```
[20:42:45] [INFO]::MAIN: Loading config from [/volume1/scripts/nzbToMedia-master/autoProcessMedia.cfg]
/volume1/scripts/nzbToMedia-master/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
[20:42:45] [INFO]::MAIN: Python v2.7 will reach end of life in 261 days.
[20:42:45] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[20:42:45] [INFO]::MAIN: Checking database structure...
[20:42:45] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[20:42:45] [INFO]::MAIN: Database upgrade required: Initial Schema
[20:42:45] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('downloads',)
[20:42:45] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[20:42:45] [DB]::MAIN: nzbtomedia.db: CREATE TABLE db_version (db_version INTEGER);
[20:42:45] [DB]::MAIN: nzbtomedia.db: CREATE TABLE downloads (input_directory TEXT, input_name TEXT, input_hash TEXT, input_id TEXT, client_agent TEXT, status INTEGER, last_update NUMERIC, CONSTRAINT pk_downloadID PRIMARY KEY (input_directory, input_name));
[20:42:45] [DB]::MAIN: nzbtomedia.db: INSERT INTO db_version (db_version) VALUES (2);
[20:42:45] [INFO]::MAIN: Checking if source needs an update
[20:42:47] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[20:42:47] [INFO]::MAIN: Auto-Updating nzbToMedia, Please wait ...
[20:42:48] [INFO]::MAIN: Creating update folder /volume1/scripts/nzbToMedia-master/sb-update before extracting
[20:42:48] [INFO]::MAIN: Downloading update from 'https://github.com/clinton-hall/nzbToMedia/tarball/master'
[20:42:55] [INFO]::MAIN: Extracting file /volume1/scripts/nzbToMedia-master/sb-update/nzbtomedia-update.tar
[20:42:56] [INFO]::MAIN: Deleting file /volume1/scripts/nzbToMedia-master/sb-update/nzbtomedia-update.tar
[20:42:56] [INFO]::MAIN: Moving files from /volume1/scripts/nzbToMedia-master/sb-update/clinton-hall-nzbToMedia-0db7c3e to /volume1/scripts/nzbToMedia-master
[20:42:56] [INFO]::MAIN: Restarting nzbToMedia with ['/volume2/@appstore/sabnzbd/env/bin/python', '/volume1/scripts/nzbToMedia-master/nzbToMedia.py', '/volume1/downloads/complete/muziek/Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC', 'Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC.nzb', 'Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC', '', 'muziek', 'alt.binaries.sounds.lossless', '0', '']
[20:42:57] [INFO]::MAIN: Loading config from [/volume1/scripts/nzbToMedia-master/autoProcessMedia.cfg]
/volume1/scripts/nzbToMedia-master/eol.py:139: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
[20:42:57] [INFO]::MAIN: Python v2.7 will reach end of life in 261 days.
[20:42:57] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[20:42:57] [INFO]::MAIN: Checking database structure...
[20:42:57] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[20:42:57] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[20:42:57] [INFO]::MAIN: Checking if source needs an update
[20:42:59] [INFO]::MAIN: No update needed
[20:42:59] [INFO]::MAIN: nzbToMedia Version:0db7c3e10c01cee85814a31fd3c5232b1d7d144e Branch:master (Linux 3.10.102)
[20:42:59] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[20:42:59] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[20:42:59] [INFO]::MAIN: #########################################################
[20:42:59] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[20:42:59] [INFO]::MAIN: #########################################################
[20:42:59] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[20:42:59] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 737164, u'SABnzbd_nzo_dFYhXp', u'SABnzbd_nzo_dFYhXp', u'Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC.nzb', u'/volume1/downloads/complete/muziek/Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC']
[20:42:59] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name) VALUES (?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 737164, u'SABnzbd_nzo_dFYhXp', u'SABnzbd_nzo_dFYhXp', u'Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC.nzb']
[20:43:00] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
[20:43:00] [INFO]::MAIN: Calling HeadPhones:muziek to post-process:Dire Straits - Brothers in Arms 2013 MFSL UDSACD 2099 24bit 88.2kHz SACD LOSSLESS FLAC.nzb
Changing to directory: /volume1/scripts/nzbToMedia-master

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils']
Returning to directory:  /volume2/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 964, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 894, in main
download_id='', failure_link=''.join(args[8:]))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 761, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia-master/core/auto_process/music.py", line 28, in process
delete_failed = int(cfg['delete_failed'])
KeyError: 'delete_failed'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7fba89be4590>> ignored
```
Please tell what to do to resolve this cause this is happenig to all media so music as well as series/movies.
Hope to hear soon

**Comment by labrys** [comment]
Check that your music section has a `delete_failed` option and that the config is properly formatted.

**Comment by ikkeenjij36** [comment]
> Check that your music section has a `delete_failed` option and that the config is properly formatted.

ok will do later tomorrow and report back

**Comment by ikkeenjij36** [comment]
> Check that your music section has a `delete_failed` option and that the config is properly formatted.

Well had no delet_failed in my config so that is solved but now i get thiss`Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 964, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 894, in main
download_id='', failure_link=''.join(args[8:]))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 761, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia-master/core/auto_process/music.py", line 28, in process
delete_failed = int(cfg['delete_failed'])
KeyError: 'delete_failed'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f6fe7db2610>> ignored
So what is going wrong here?
It's only on the music`section headphones

**Comment by clinton-hall** [comment]
same error.

Pleas ensure /volume1/scripts/nzbToMedia-master/autoProcessMedia.cfg
has the followoing
```
[HeadPhones]
    [[muziek]]
        delete_failed = 0
```

**Comment by ikkeenjij36** [comment]
> same error.
> 
> Pleas ensure /volume1/scripts/nzbToMedia-master/autoProcessMedia.cfg
> has the followoing
> 
> ```
> [HeadPhones]
>     [[muziek]]
>         delete_failed = 0
> ```

Hi did that,checked 3 times but still getting an error,only with hp sonarr radarr and cp working flawless

`Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 964, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 894, in main
download_id='', failure_link=''.join(args[8:]))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia.py", line 761, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia-master/core/auto_process/music.py", line 89, in process
res = force_process(params, url, apikey, input_name, dir_name, section, wait_for)
File "/volume1/scripts/nzbToMedia-master/core/auto_process/music.py", line 220, in force_process
r = requests.get(url, params=params, verify=False, timeout=(30, 300))
File "/volume1/scripts/nzbToMedia-master/libs/common/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/volume1/scripts/nzbToMedia-master/libs/common/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/volume1/scripts/nzbToMedia-master/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/volume1/scripts/nzbToMedia-master/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/volume1/scripts/nzbToMedia-master/libs/common/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8182): Read timed out. (read timeout=300)
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f007fb94610>> ignored`

**Comment by clinton-hall** [comment]
ok, First one was an issue with timeout, so this might be fixed by increasing wait_for (e.g. from 2 minutes to 10 minutes) in case Headphones is taking a long time to process.

```
[HeadPhones]
    [[muziek]]
        wait_for = 10
```
The second error you have is a failure to migrate (of read) the config file.

This usually happens when something gets formatted poorly (usually if using notepad in Windows).
You can try restoring the previous .cfg.old, start again with a fresh .cfg (from the .cfg.spec file) are otherwise review your .cfg carefully in a good editor (nano, or using notepad++ in Windows etc) and see if you can clear up the bad formatting.

alternatively you can sen the .cfg file to me via email `fock_wulf@hotmail.com` and I'll see if I can fix it for you.

**Comment by ikkeenjij36** [comment]
> ok, First one was an issue with timeout, so this might be fixed by increasing wait_for (e.g. from 2 minutes to 10 minutes) in case Headphones is taking a long time to process.
> 
> ```
> [HeadPhones]
>     [[muziek]]
>         wait_for = 10
> ```
> 
> The second error you have is a failure to migrate (of read) the config file.
> 
> This usually happens when something gets formatted poorly (usually if using notepad in Windows).
> You can try restoring the previous .cfg.old, start again with a fresh .cfg (from the .cfg.spec file) are otherwise review your .cfg carefully in a good editor (nano, or using notepad++ in Windows etc) and see if you can clear up the bad formatting.
> 
> alternatively you can sen the .cfg file to me via email `fock_wulf@hotmail.com` and I'll see if I can fix it for you.

Mail send and thnx for your help

**Comment by clinton-hall** [comment]
I can't actually test until I get home, but looking at the auroProcessMedia.cfg file I note
```
        importMode = Copy

    

[SickBeard]
```
at the bottom of the [Radar][[films]] section.
If you delete the extra "tab" line and the blank line, such that it looks like
```
        importMode = Copy

[SickBeard]
```
This should hopefully work.
