### ISSUE TITLE
qBittorrent 4.2.0alpha1 not working

### ISSUE THREAD

**Issue by Fietspomp86** [clinton-hall/nzbToMedia#1650]
Just switched from Deluge to qBit, so far it's working quite ok except for nzbtomedia.

When executing Torrenttomedia with the latest qBitTorrent, I get the following error:

> [12:00:59] [DEBUG]::MAIN: Connecting to qbittorrent: http://localhost:8111
Traceback (most recent call last):
  File "/opt/scripts/nzbToMedia/TorrentToMedia.py", line 370, in <module>
    exit(main(sys.argv))
  File "/opt/scripts/nzbToMedia/TorrentToMedia.py", line 294, in main
    core.initialize()
  File "/opt/scripts/nzbToMedia/core/__init__.py", line 1032, in initialize
    configure_torrent_class()
  File "/opt/scripts/nzbToMedia/core/plugins/downloaders/torrent/configuration.py", line 88, in configure_torrent_class
    core.TORRENT_CLASS = create_torrent_class(core.TORRENT_CLIENT_AGENT)
  File "/opt/scripts/nzbToMedia/core/plugins/downloaders/torrent/utils.py", line 32, in create_torrent_class
    return client()
  File "/opt/scripts/nzbToMedia/core/plugins/downloaders/torrent/qbittorrent.py", line 25, in configure_client
    client = qBittorrentClient('http://{0}:{1}/'.format(host, port))
  File "/opt/scripts/nzbToMedia/libs/common/qbittorrent/client.py", line 30, in __init__
    """)
RuntimeError:
                This wrapper only supports qBittorrent applications
                 with version higher than 3.1.x.
                 Please use the latest qBittorrent release.
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

**Technical Specs**
1. Running on Linux, Debian Stretch (Openmediavault 4)
2. Python version '3.5'
3. Download Client = Qbittorrent obviously.

EDIT:
Found a fix, copied some code from the Mylar repo:

[https://github.com/Arathen/mylar/blob/51ecfab5e7769f058c6a3b0e1384c02105ebfe43/lib/qbittorrent/client.py](url)

Using this client.py it works with the new Qbittorrent API V2!

**Comment by clinton-hall** [comment]
thanks. I have created a new branch `qbittorrent-patch-1`
are you able to confirm that this works?

I'll need to check how this works with older versions of qbittorrent... 
my suspicion is that I will need to update the wiki to specify that we would only support qBittorrent V4.1+

**Comment by Fietspomp86** [comment]
Alright thanks, just pulled it, let's see if it works!

**Comment by Fietspomp86** [comment]
Working ok with qbittorrent branch.
