### ISSUE TITLE
AttributeError: 'dict_keys' object has no attribute 'index'

### ISSUE THREAD

**Issue by ChrisNelsonF5** [clinton-hall/nzbToMedia#1653]
Hello all, running into an issue post-processing media.  Log is below.  Not sure what steps to do next.

**Describe the bug**
When post-processing media from SABNzbd, both movie and tv forks fail to post process.

**Technical Specs**
1. Running on Ubuntu Linux 18.04.3
2. Python version: tried 2.7 and 3.6, both fail
3. Download Client (NZBget, SABnbzd, Transmission): SABnbzd
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Medusa'

**Expected behavior**
I would expect that the scripts would post process, move and rename the media

**Log**
[04:54:50] [INFO]::MAIN: Loading config from [/opt/medusa/nzbToMedia/autoProcessMedia.cfg]
[04:54:50] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py
[04:54:50] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /usr/bin/par2
[04:54:50] [INFO]::ENVIRONMENT: AVAHI_COMPAT_NOWARN: 1
[04:54:50] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[04:54:50] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[04:54:50] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.5
[04:54:50] [INFO]::ENVIRONMENT: HOME: /home/chris
[04:54:50] [INFO]::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[04:54:50] [INFO]::ENVIRONMENT: SAB_BYTES: 3516170884
[04:54:50] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[04:54:50] [INFO]::ENVIRONMENT: SAB_AGE: 22d
[04:54:50] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[04:54:50] [INFO]::ENVIRONMENT: JOURNAL_STREAM: 9:31834
[04:54:50] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[04:54:50] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_a7w8eS
[04:54:50] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.bloaf
[04:54:50] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /home/chris/Downloads/incomplete/Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2/__ADMIN__/Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb.gz
[04:54:50] [INFO]::ENVIRONMENT: SAB_CAT: tv
[04:54:50] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /home/chris/Downloads/complete/Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated.1
[04:54:50] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[04:54:50] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[04:54:50] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[04:54:50] [INFO]::ENVIRONMENT: INVOCATION_ID: 23dfd59c51584350a7e3d6781bd9de7d
[04:54:50] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 3516170884
[04:54:50] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[04:54:50] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 6530
[04:54:50] [INFO]::ENVIRONMENT: SAB_FILENAME: Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb
[04:54:50] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[04:54:50] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 477
[04:54:50] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 3192282912
[04:54:50] [INFO]::ENVIRONMENT: SAB_PP: 3
[04:54:50] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /usr/bin
[04:54:50] [INFO]::ENVIRONMENT: SAB_URL: https://api.nzbgeek.info/api?t=get&id=53d2714139f443e12dd458e507576071&apikey=f8f9ccce6462867715f650d93aed930a
[04:54:50] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[04:54:50] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[04:54:50] [INFO]::ENVIRONMENT: SAB_FAILURE_URL:
[04:54:50] [INFO]::ENVIRONMENT: SAB_PRIORITY: -1
[04:54:50] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[04:54:50] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /usr/bin/unrar
[04:54:50] [INFO]::ENVIRONMENT: PWD: /
[04:54:50] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /usr/bin/7za
[04:54:50] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated
[04:54:50] [INFO]::MAIN: Python v3.6 will reach end of life in 828 days.
[04:54:50] [INFO]::MAIN: Checking database structure...
[04:54:50] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[04:54:50] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[04:54:50] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[04:54:50] [DEBUG]::MAIN: InitialSchema upgrade not required
[04:54:50] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /opt/medusa/nzbToMedia
[04:54:50] [DEBUG]::MAIN: git output: git version 2.17.1
[04:54:50] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[04:54:50] [DEBUG]::MAIN: Using: "/usr/bin/git"
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /opt/medusa/nzbToMedia
[04:54:50] [DEBUG]::MAIN: git output: refs/heads/master
[04:54:50] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[04:54:50] [INFO]::MAIN: Checking if git needs an update
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /opt/medusa/nzbToMedia
[04:54:50] [DEBUG]::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
[04:54:50] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /opt/medusa/nzbToMedia
[04:54:50] [DEBUG]::MAIN: git output:
[04:54:50] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /opt/medusa/nzbToMedia
[04:54:50] [DEBUG]::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
[04:54:50] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[04:54:50] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /opt/medusa/nzbToMedia
[04:54:51] [DEBUG]::MAIN: git output:
[04:54:51] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[04:54:51] [DEBUG]::MAIN: cur_commit = 46b2e8998ce7c0e4b853272f0bdb06a558852c81 % (newest_commit)= 46b2e8998ce7c0e4b853272f0bdb06a558852c81, num_commits_behind = 0, num_commits_ahead = 0
[04:54:51] [INFO]::MAIN: No update needed
[04:54:51] [INFO]::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Linux 4.15.0-58-generic)
[04:54:51] [INFO]::MAIN: #########################################################
[04:54:51] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[04:54:51] [INFO]::MAIN: #########################################################
[04:54:51] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/medusa/nzbToMedia/nzbToSickBeard.py', '/home/chris/Downloads/complete/Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated.1', 'Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb', 'Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated', '', 'tv', 'alt.binaries.bloaf', '0', '']
[04:54:51] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[04:54:51] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[04:54:51] [ERROR]::MAIN: Unable to open URL
[04:54:51] [DEBUG]::MAIN: Adding NZB download info for directory /home/chris/Downloads/complete/Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated.1 to database
[04:54:51] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET input_name = ?, input_hash = ?, input_id = ?, client_agent = ?, status = ?, last_update = ? WHERE input_directory = ? with args ["b'Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb'", 'None', 'None', 'sabnzbd', 0, 737319, "b'/home/chris/Downloads/complete/Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated.1'"]
[04:54:51] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (input_name, input_hash, input_id, client_agent, status, last_update) VALUES (?, ?, ?, ?, ?, ?) with args ["b'Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb'", 'None', 'None', 'sabnzbd', 0, 737319]
[04:54:51] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[04:54:51] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/chris/Downloads/complete/Peaky Blinders S05E01 1080p AMZN WEB-DL DDP5 1 H 264 1-AJP69-Obfuscated.1
[04:54:51] [INFO]::MAIN: Calling SickBeard:tv to post-process:Peaky.Blinders.S05E01.1080p.AMZN.WEB-DL.DDP5.1.H.264.1-AJP69-Obfuscated.2.nzb
[04:54:51] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8081
[04:54:51] [DEBUG]::SERVER: Server responded at http://localhost:8081
[04:54:51] [INFO]::MAIN: Attempting to auto-detect tv fork
[04:54:51] [INFO]::MAIN: SickBeard:tv fork auto-detection failed
Changing to directory: /opt/medusa/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/plugins/__pycache__/\nRemoving core/plugins/downloaders/__pycache__/\nRemoving core/plugins/downloaders/nzb/__pycache__/\nRemoving core/plugins/downloaders/torrent/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/__pycache__/\nRemoving libs/common/guessit/rules/common/__pycache__/\nRemoving libs/common/guessit/rules/markers/__pycache__/\nRemoving libs/common/guessit/rules/properties/__pycache__/\nRemoving libs/common/idna/__pycache__/\nRemoving libs/common/mutagen/__pycache__/\nRemoving libs/common/mutagen/asf/__pycache__/\nRemoving libs/common/mutagen/id3/__pycache__/\nRemoving libs/common/mutagen/mp4/__pycache__/\nRemoving libs/common/pkg_resources/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/packaging/__pycache__/\nRemoving libs/common/pkg_resources/extern/__pycache__/\nRemoving libs/common/pysrt/__pycache__/\nRemoving libs/common/qbittorrent/__pycache__/\nRemoving libs/common/rebulk/__pycache__/\nRemoving libs/common/rencode/__pycache__/\nRemoving libs/common/requests/__pycache__/\nRemoving libs/common/stevedore/__pycache__/\nRemoving libs/common/subliminal/__pycache__/\nRemoving libs/common/subliminal/providers/__pycache__/\nRemoving libs/common/transmissionrpc/__pycache__/\nRemoving libs/common/unidecode/__pycache__/\nRemoving libs/common/urllib3/__pycache__/\nRemoving libs/common/urllib3/contrib/__pycache__/\nRemoving libs/common/urllib3/packages/__pycache__/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/__pycache__/\nRemoving libs/common/urllib3/util/__pycache__/\nRemoving libs/common/yaml/__pycache__/\nRemoving libs/custom/synchronousdeluge/__pycache__/\nRemoving libs/custom/utorrent/__pycache__/\n'
b'Removing __pycache__/\nRemoving core/__pycache__/\nRemoving core/auto_process/__pycache__/\nRemoving core/extractor/__pycache__/\nRemoving core/plugins/__pycache__/\nRemoving core/plugins/downloaders/__pycache__/\nRemoving core/plugins/downloaders/nzb/__pycache__/\nRemoving core/plugins/downloaders/torrent/__pycache__/\nRemoving core/utils/__pycache__/\nRemoving libs/__pycache__/\nRemoving libs/common/__pycache__/\nRemoving libs/common/babelfish/__pycache__/\nRemoving libs/common/babelfish/converters/__pycache__/\nRemoving libs/common/beets/__pycache__/\nRemoving libs/common/beets/util/__pycache__/\nRemoving libs/common/bs4/__pycache__/\nRemoving libs/common/bs4/builder/__pycache__/\nRemoving libs/common/certifi/__pycache__/\nRemoving libs/common/chardet/__pycache__/\nRemoving libs/common/dateutil/__pycache__/\nRemoving libs/common/dateutil/parser/__pycache__/\nRemoving libs/common/dateutil/tz/__pycache__/\nRemoving libs/common/dogpile/__pycache__/\nRemoving libs/common/dogpile/cache/__pycache__/\nRemoving libs/common/dogpile/cache/backends/__pycache__/\nRemoving libs/common/dogpile/util/__pycache__/\nRemoving libs/common/guessit/__pycache__/\nRemoving libs/common/guessit/rules/__pycache__/\nRemoving libs/common/guessit/rules/common/__pycache__/\nRemoving libs/common/guessit/rules/markers/__pycache__/\nRemoving libs/common/guessit/rules/properties/__pycache__/\nRemoving libs/common/idna/__pycache__/\nRemoving libs/common/mutagen/__pycache__/\nRemoving libs/common/mutagen/asf/__pycache__/\nRemoving libs/common/mutagen/id3/__pycache__/\nRemoving libs/common/mutagen/mp4/__pycache__/\nRemoving libs/common/pkg_resources/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/__pycache__/\nRemoving libs/common/pkg_resources/_vendor/packaging/__pycache__/\nRemoving libs/common/pkg_resources/extern/__pycache__/\nRemoving libs/common/pysrt/__pycache__/\nRemoving libs/common/qbittorrent/__pycache__/\nRemoving libs/common/rebulk/__pycache__/\nRemoving libs/common/rencode/__pycache__/\nRemoving libs/common/requests/__pycache__/\nRemoving libs/common/stevedore/__pycache__/\nRemoving libs/common/subliminal/__pycache__/\nRemoving libs/common/subliminal/providers/__pycache__/\nRemoving libs/common/transmissionrpc/__pycache__/\nRemoving libs/common/unidecode/__pycache__/\nRemoving libs/common/urllib3/__pycache__/\nRemoving libs/common/urllib3/contrib/__pycache__/\nRemoving libs/common/urllib3/packages/__pycache__/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/__pycache__/\nRemoving libs/common/urllib3/util/__pycache__/\nRemoving libs/common/yaml/__pycache__/\nRemoving libs/custom/synchronousdeluge/__pycache__/\nRemoving libs/custom/utorrent/__pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/bin

-- Cleanup finished --

Traceback (most recent call last):
File "/opt/medusa/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/medusa/nzbToMedia/nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "/opt/medusa/nzbToMedia/nzbToMedia.py", line 805, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/opt/medusa/nzbToMedia/core/auto_process/tv.py", line 56, in process
fork, fork_params = auto_fork(section, input_category)
File "/opt/medusa/nzbToMedia/core/forks.py", line 171, in auto_fork
fork = core.FORKS.items()[core.FORKS.keys().index(core.FORK_DEFAULT)]
AttributeError: 'dict_keys' object has no attribute 'index'

**Comment by clinton-hall** [comment]
ok, it looks like there was a change made previously to re-arrange the way this is stored and parsed... I'll try and fix...

I note that this shouldn't actually be an issue as this is just a fall-back when auto-fork detection fails, and Medusa should be fine.

Can you please confirm you have set the correct api key (for Medusa) in the cfg and that you aren't using reverse proxy?

**Comment by ChrisNelsonF5** [comment]
That was it.  The API key for medusa was wrong.  Corrected the issue and script ran perfectly.

Thanks! Feel free to close this one out.
