### ISSUE TITLE
qbittorrent 4.2.0 broke TorrentToMedia

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [clinton-hall/nzbToMedia#1679]
**Describe the bug**
it seems since qbittorrent 4.2.0 TorrentToMedia no longer works, their WebAPI version has changed & they have switched to Libtorrent 1.2.

**Technical Specs**
macOS Catalina 10.15.1
Python 2.7.17, Python 3.7.5
qbittorrent 4.2.0
Medusa

nzbtomedia build: master

**Log**
```
/Users/ovidijus/Apps/nzbToMedia/TorrentToMedia.py ; exit;
Changing to directory: /Users/ovidijus/Apps/nzbToMedia

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc

Removing cleanup.pyc
Removing eol.pyc


-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /Users/ovidijus

-- Cleanup finished --

[16:14:10] [INFO]::MAIN: Loading config from [/Users/ovidijus/Apps/nzbToMedia/autoProcessMedia.cfg]
/Users/ovidijus/Apps/nzbToMedia/eol.py:146: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)
[16:14:10] [INFO]::MAIN: Python v2.7 will reach end of life in 27 days.
[16:14:10] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[16:14:10] [INFO]::MAIN: Checking database structure...
[16:14:10] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[16:14:10] [DEBUG]::MAIN: InitialSchema upgrade not required
[16:14:10] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/local/bin/git" version
[16:14:10] [DEBUG]::MAIN: Executing "/usr/local/bin/git" version with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:10] [DEBUG]::MAIN: "/usr/local/bin/git" version : returned successful
[16:14:10] [DEBUG]::MAIN: Using: "/usr/local/bin/git"
[16:14:10] [DEBUG]::MAIN: Executing "/usr/local/bin/git" symbolic-ref -q HEAD with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:10] [DEBUG]::MAIN: "/usr/local/bin/git" symbolic-ref -q HEAD : returned successful
[16:14:10] [INFO]::MAIN: Checking if git needs an update
[16:14:10] [DEBUG]::MAIN: Executing "/usr/local/bin/git" rev-parse HEAD with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:10] [DEBUG]::MAIN: "/usr/local/bin/git" rev-parse HEAD : returned successful
[16:14:10] [DEBUG]::MAIN: Executing "/usr/local/bin/git" fetch origin with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:11] [DEBUG]::MAIN: "/usr/local/bin/git" fetch origin : returned successful
[16:14:11] [DEBUG]::MAIN: Executing "/usr/local/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:11] [DEBUG]::MAIN: "/usr/local/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[16:14:11] [DEBUG]::MAIN: Executing "/usr/local/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /Users/ovidijus/Apps/nzbToMedia
[16:14:11] [DEBUG]::MAIN: "/usr/local/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[16:14:11] [DEBUG]::MAIN: cur_commit = 46b2e8998ce7c0e4b853272f0bdb06a558852c81 % (newest_commit)= 46b2e8998ce7c0e4b853272f0bdb06a558852c81, num_commits_behind = 0, num_commits_ahead = 0
[16:14:11] [INFO]::MAIN: No update needed
[16:14:11] [INFO]::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Darwin 19.0.0)
[16:14:11] [DEBUG]::MAIN: Connecting to qbittorrent: http://localhost:8082
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/nzbToMedia/TorrentToMedia.py", line 370, in <module>
    exit(main(sys.argv))
  File "/Users/ovidijus/Apps/nzbToMedia/TorrentToMedia.py", line 294, in main
    core.initialize()
  File "/Users/ovidijus/Apps/nzbToMedia/core/__init__.py", line 1032, in initialize
    configure_torrent_class()
  File "/Users/ovidijus/Apps/nzbToMedia/core/plugins/downloaders/torrent/configuration.py", line 88, in configure_torrent_class
    core.TORRENT_CLASS = create_torrent_class(core.TORRENT_CLIENT_AGENT)
  File "/Users/ovidijus/Apps/nzbToMedia/core/plugins/downloaders/torrent/utils.py", line 32, in create_torrent_class
    return client()
  File "/Users/ovidijus/Apps/nzbToMedia/core/plugins/downloaders/torrent/qbittorrent.py", line 25, in configure_client
    client = qBittorrentClient('http://{0}:{1}/'.format(host, port))
  File "/Users/ovidijus/Apps/nzbToMedia/libs/common/qbittorrent/client.py", line 30, in __init__
    """)
RuntimeError: 
                This wrapper only supports qBittorrent applications
                 with version higher than 3.1.x.
                 Please use the latest qBittorrent release.
                
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x10af6cc50>> ignored
```

**Comment by XxUnkn0wnxX** [comment]
no issues on nightly branch, just master

**Comment by clinton-hall** [comment]
yes, this has been updated in nightly https://github.com/clinton-hall/nzbToMedia/commit/fde87148627ff66650201087dab840dfd6fb5d70
but it has not yet been merged in master.

This is not backwards compatible so I was waiting to see when qbittorrent stable is updated to 4.2 before I move this into master.

**Comment by clinton-hall** [comment]
ok, stable went to 4.2 2 days ago.
I'll try and merge to master this weekend.

**Comment by clinton-hall** [comment]
merged into master.
