### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by jzahraoui** [clinton-hall/nzbToMedia#1694]
**Describe the bug**
getting error with python 3.7 on debian sid.
the call to imdbid = find_imdbid(dir_name, input_name, omdbapikey) seems to pass input_name variable as byte intead of string.
working well with python 2.
tried to checkout nightly and getting the same error.

**Technical Specs**
1. Running on Linux
2. Python version 3.7.5

**Log**

```
[20:04:08] [INFO]::MAIN: Searching folder and file names for imdbID ...
Traceback (most recent call last):
  File "nzbToCouchPotato.py", line 272, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/opt/nzbtomedia/nzbToMedia.py", line 1027, in main
    download_id=download_id or None, input_category=subsection)
  File "/opt/nzbtomedia/nzbToMedia.py", line 851, in process
    result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
  File "/opt/nzbtomedia/core/auto_process/movies.py", line 68, in process
    imdbid = find_imdbid(dir_name, input_name, omdbapikey)
  File "/opt/nzbtomedia/core/utils/identification.py", line 26, in find_imdbid
    m = re.search(r'\b(tt\d{7,8})\b', dir_name + input_name)
TypeError: can only concatenate str (not "bytes") to str
Exception ignored in: <function PosixProcess.__del__ at 0x7f5d9c459a70>
Traceback (most recent call last):
  File "/opt/nzbtomedia/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'

```

**Comment by clinton-hall** [comment]
I'm trying to figure out how this comes about... have you set the following?
```
[ASCII]
    convert = 1
```

I have made a slight change to the char replace. Are you able to update to latest nightly and test?

**Comment by jzahraoui** [comment]
Hello,
the problem solved. great :)
thank you very much.
yes I'm using "convert = 1" option.
