### ISSUE TITLE
KeyError: (3, 8)

### ISSUE THREAD

**Issue by Tiwas** [clinton-hall/nzbToMedia#1705]
**Describe the bug**
Running nzbToMedia from my sabnzb suddenly stopped working with a message that python 2.7 was no longer supported. Upgraded to 3.8.1 and it still failed, only now with the error "KeyError: (3, 8)". When trying to run it from the console I got the dump pasted below. I also tried pulling it again.

**Technical Specs**
1. Running on 'Windows 10 x64 8GB RAM'
2. Python version '3.8.1'
3. Download Client 'SABnbzd'
4. Intended Media Management 'SickChill'

**Expected behavior**
Kind of expected it to still post process my files ;)

**Log**
C:\SickRage\Scripts\nzbToMedia>python nzbToMedia.py
Traceback (most recent call last):
  File "nzbToMedia.py", line 627, in <module>
    eol.check()
  File "C:\SickRage\Scripts\nzbToMedia\eol.py", line 91, in check
    raise_for_status(version, grace_period)
  File "C:\SickRage\Scripts\nzbToMedia\eol.py", line 111, in raise_for_status
    days_left = lifetime(version)
  File "C:\SickRage\Scripts\nzbToMedia\eol.py", line 62, in lifetime
    time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 8)

**Comment by clinton-hall** [comment]
Try an manual Update via git...
I did add Python3.8 support a while back.

**Comment by Tiwas** [comment]
Ok, thanks. I did a "git clone" and thought that was enough. "git pull" fixed it. Mainly ;)

I'm now getting a "git output: fatal: no such branch: '''" in the console when running the script. I would really appreciate it if you'd take a quick look. Do you see anything that could trigger it?

**Config**
[General]
    # Enable/Disable update notifications
    version_notify = 1
    # Enable/Disable automatic updates
    auto_update = 1
    # Set to the full path to the git executable
    git_path = C:\Program Files\Git\bin\git.exe
    # GitHUB user for repo
    git_user = <username>
    # GitHUB branch for repo
    git_branch = master
    # Enable/Disable forceful cleaning of leftover files following postprocess
    force_clean = 0
    # Enable/Disable logging debug messages to nzbtomedia.log
    log_debug = 1
    # Enable/Disable logging database messages to nzbtomedia.log
    log_db = 1
    # Enable/Disable logging environment variables to debug nzbtomedia.log (helpful to track down errors calling external tools.)
    log_env = 1
    # Enable/Disable logging git output to debug nzbtomedia.log (helpful to track down update failures.)
    log_git = 1
    # Set to the directory to search for executables if not in default system path
    sys_path = ""
    # Set to the directory where your ffmpeg/ffprobe executables are located
    ffmpeg_path = C:\ffmpeg-20181111-e24a754-win64-static\bin
    # Enable/Disable media file checking using ffprobe.
    check_media = 1
    # Enable/Disable a safety check to ensure we don't process all downloads in the default_downloadDirectories by mistake.
    safe_mode = 1
    # Turn this on to disable additional extraction attempts for failed downloads. Default = 0 will attempt to extract and verify if media is present.
    no_extract_failed = 0

**Console**
C:\SickRage\Scripts\nzbToMedia>python nzbToMedia.py

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

[10:33:48] [INFO]::MAIN: Loading config from [C:\SickRage\Scripts\nzbToMedia\autoProcessMedia.cfg]
[10:33:48] [INFO]::ENVIRONMENT: ALLUSERSPROFILE: C:\ProgramData
[10:33:48] [INFO]::ENVIRONMENT: APPDATA: C:\Users\Kodi\AppData\Roaming
[10:33:48] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES: C:\Program Files (x86)\Common Files
[10:33:48] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
[10:33:48] [INFO]::ENVIRONMENT: COMMONPROGRAMW6432: C:\Program Files\Common Files
[10:33:48] [INFO]::ENVIRONMENT: COMPUTERNAME: MEDIACENTER
[10:33:48] [INFO]::ENVIRONMENT: COMSPEC: C:\WINDOWS\system32\cmd.exe
[10:33:48] [INFO]::ENVIRONMENT: DRIVERDATA: C:\Windows\System32\Drivers\DriverData
[10:33:48] [INFO]::ENVIRONMENT: FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
[10:33:48] [INFO]::ENVIRONMENT: FPS_BROWSER_USER_PROFILE_STRING: Default
[10:33:48] [INFO]::ENVIRONMENT: HOMEDRIVE: C:
[10:33:48] [INFO]::ENVIRONMENT: HOMEPATH: \Users\Kodi
[10:33:48] [INFO]::ENVIRONMENT: LOCALAPPDATA: C:\Users\Kodi\AppData\Local
[10:33:48] [INFO]::ENVIRONMENT: LOGONSERVER: \\MEDIACENTER
[10:33:48] [INFO]::ENVIRONMENT: NUMBER_OF_PROCESSORS: 4
[10:33:48] [INFO]::ENVIRONMENT: ONEDRIVE: C:\Users\Kodi\OneDrive
[10:33:48] [INFO]::ENVIRONMENT: ONEDRIVECONSUMER: C:\Users\Kodi\OneDrive
[10:33:48] [INFO]::ENVIRONMENT: OS: Windows_NT
[10:33:48] [INFO]::ENVIRONMENT: PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Python\Python38-32;C:\Python\Python38-32\Scripts;C:\Python\Python38-32\Scripts\;C:\Python\Python38-32\;C:\Users\Kodi\AppData\Local\Microsoft\WindowsApps;
[10:33:48] [INFO]::ENVIRONMENT: PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[10:33:48] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITECTURE: x86
[10:33:48] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITEW6432: AMD64
[10:33:48] [INFO]::ENVIRONMENT: PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
[10:33:48] [INFO]::ENVIRONMENT: PROCESSOR_LEVEL: 6
[10:33:48] [INFO]::ENVIRONMENT: PROCESSOR_REVISION: 3a09
[10:33:48] [INFO]::ENVIRONMENT: PROGRAMDATA: C:\ProgramData
[10:33:48] [INFO]::ENVIRONMENT: PROGRAMFILES: C:\Program Files (x86)
[10:33:48] [INFO]::ENVIRONMENT: PROGRAMFILES(X86): C:\Program Files (x86)
[10:33:48] [INFO]::ENVIRONMENT: PROGRAMW6432: C:\Program Files
[10:33:48] [INFO]::ENVIRONMENT: PROMPT: $P$G
[10:33:48] [INFO]::ENVIRONMENT: PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
[10:33:48] [INFO]::ENVIRONMENT: PUBLIC: C:\Users\Public
[10:33:48] [INFO]::ENVIRONMENT: SESSIONNAME: Console
[10:33:48] [INFO]::ENVIRONMENT: SYSTEMDRIVE: C:
[10:33:48] [INFO]::ENVIRONMENT: SYSTEMROOT: C:\WINDOWS
[10:33:48] [INFO]::ENVIRONMENT: TEMP: C:\Users\Kodi\AppData\Local\Temp
[10:33:48] [INFO]::ENVIRONMENT: TMP: C:\Users\Kodi\AppData\Local\Temp
[10:33:48] [INFO]::ENVIRONMENT: USERDOMAIN: MEDIACENTER
[10:33:48] [INFO]::ENVIRONMENT: USERDOMAIN_ROAMINGPROFILE: MEDIACENTER
[10:33:48] [INFO]::ENVIRONMENT: USERNAME: Kodi
[10:33:48] [INFO]::ENVIRONMENT: USERPROFILE: C:\Users\Kodi
[10:33:48] [INFO]::ENVIRONMENT: WINDIR: C:\WINDOWS
[10:33:48] [INFO]::MAIN: Python v3.8 will reach end of life in 1732 days.
[10:33:48] [INFO]::MAIN: Checking database structure...
[10:33:48] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[10:33:48] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[10:33:48] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[10:33:48] [DEBUG]::MAIN: InitialSchema upgrade not required
[10:33:48] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
[10:33:48] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\SickRage\Scripts\nzbToMedia
[10:33:48] [DEBUG]::MAIN: git output: git version 2.15.0.windows.1
[10:33:48] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
[10:33:48] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
[10:33:48] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\SickRage\Scripts\nzbToMedia
[10:33:48] [DEBUG]::MAIN: git output: refs/heads/master
[10:33:48] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
[10:33:48] [INFO]::MAIN: Checking if git needs an update
[10:33:48] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\SickRage\Scripts\nzbToMedia
[10:33:49] [DEBUG]::MAIN: git output: 5a6837759d90285664b3cb596662adb5bfbcb2a2
[10:33:49] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
[10:33:49] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\SickRage\Scripts\nzbToMedia
[10:33:49] [DEBUG]::MAIN: git output:
[10:33:49] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
[10:33:49] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\SickRage\Scripts\nzbToMedia
[10:33:50] [DEBUG]::MAIN: git output: fatal: no such branch: '''
[10:33:50] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''
[10:33:50] [DEBUG]::MAIN: git didn't return newest commit hash
[10:33:50] [INFO]::MAIN: No update needed
[10:33:50] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Windows 10)
[10:33:50] [INFO]::MAIN: #########################################################
[10:33:50] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[10:33:50] [INFO]::MAIN: #########################################################
[10:33:50] [DEBUG]::MAIN: Options passed into nzbToMedia: ['nzbToMedia.py']
[10:33:50] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[10:33:50] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[10:33:50] [ERROR]::MAIN: Failed to add directories from  for post-processing: [WinError 3] Systemet finner ikke angitt bane: ''
[10:33:50] [DEBUG]::MAIN: No directories identified in Radarr:movies for post-processing
[10:33:50] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[10:33:50] [ERROR]::MAIN: Failed to add directories from  for post-processing: [WinError 3] Systemet finner ikke angitt bane: ''
[10:33:50] [DEBUG]::MAIN: No directories identified in SickBeard:tv for post-processing
[10:33:50] [INFO]::MAIN: The nzbToMedia.py script completed successfully.

**Comment by clinton-hall** [comment]
I see this: 
https://stackoverflow.com/questions/4848607/git-fatal-no-such-ref-head

which suggests somehow your git head had gone missing.. but I don't know enough about git on Windows to know how to fix this...

i.e. I'm not sure if you can run `echo ref: refs/heads/master >.git/HEAD` in windows git...

otherwise looks like the advice is to re-clone.

**Comment by Tiwas** [comment]
Thanks for helping out. Tried the echo comand, and pretty much got the same as below. Did a reclone (moved the old directory first) and then copied my config file.

** Console **
python nzbToMedia.py

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

[23:10:11] [INFO]::MAIN: Loading config from [C:\SickRage\Scripts\nzbToMedia\autoProcessMedia.cfg]
[23:10:11] [INFO]::ENVIRONMENT: ALLUSERSPROFILE: C:\ProgramData
[23:10:11] [INFO]::ENVIRONMENT: APPDATA: C:\Users\Kodi\AppData\Roaming
[23:10:11] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES: C:\Program Files (x86)\Common Files
[23:10:11] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
[23:10:11] [INFO]::ENVIRONMENT: COMMONPROGRAMW6432: C:\Program Files\Common Files
[23:10:11] [INFO]::ENVIRONMENT: COMPUTERNAME: MEDIACENTER
[23:10:11] [INFO]::ENVIRONMENT: COMSPEC: C:\WINDOWS\system32\cmd.exe
[23:10:11] [INFO]::ENVIRONMENT: DRIVERDATA: C:\Windows\System32\Drivers\DriverData
[23:10:11] [INFO]::ENVIRONMENT: FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
[23:10:11] [INFO]::ENVIRONMENT: FPS_BROWSER_USER_PROFILE_STRING: Default
[23:10:11] [INFO]::ENVIRONMENT: HOMEDRIVE: C:
[23:10:11] [INFO]::ENVIRONMENT: HOMEPATH: \Users\Kodi
[23:10:11] [INFO]::ENVIRONMENT: LOCALAPPDATA: C:\Users\Kodi\AppData\Local
[23:10:11] [INFO]::ENVIRONMENT: LOGONSERVER: \\MEDIACENTER
[23:10:11] [INFO]::ENVIRONMENT: NUMBER_OF_PROCESSORS: 4
[23:10:11] [INFO]::ENVIRONMENT: ONEDRIVE: C:\Users\Kodi\OneDrive
[23:10:11] [INFO]::ENVIRONMENT: ONEDRIVECONSUMER: C:\Users\Kodi\OneDrive
[23:10:11] [INFO]::ENVIRONMENT: OS: Windows_NT
[23:10:11] [INFO]::ENVIRONMENT: PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Python\Python38-32;C:\Python\Python38-32\Scripts;C:\Python\Python38-32\Scripts\;C:\Python\Python38-32\;C:\Users\Kodi\AppData\Local\Microsoft\WindowsApps;
[23:10:11] [INFO]::ENVIRONMENT: PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[23:10:11] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITECTURE: x86
[23:10:11] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITEW6432: AMD64
[23:10:11] [INFO]::ENVIRONMENT: PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
[23:10:11] [INFO]::ENVIRONMENT: PROCESSOR_LEVEL: 6
[23:10:11] [INFO]::ENVIRONMENT: PROCESSOR_REVISION: 3a09
[23:10:11] [INFO]::ENVIRONMENT: PROGRAMDATA: C:\ProgramData
[23:10:11] [INFO]::ENVIRONMENT: PROGRAMFILES: C:\Program Files (x86)
[23:10:11] [INFO]::ENVIRONMENT: PROGRAMFILES(X86): C:\Program Files (x86)
[23:10:11] [INFO]::ENVIRONMENT: PROGRAMW6432: C:\Program Files
[23:10:11] [INFO]::ENVIRONMENT: PROMPT: $P$G
[23:10:11] [INFO]::ENVIRONMENT: PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
[23:10:11] [INFO]::ENVIRONMENT: PUBLIC: C:\Users\Public
[23:10:11] [INFO]::ENVIRONMENT: SESSIONNAME: Console
[23:10:11] [INFO]::ENVIRONMENT: SYSTEMDRIVE: C:
[23:10:11] [INFO]::ENVIRONMENT: SYSTEMROOT: C:\WINDOWS
[23:10:11] [INFO]::ENVIRONMENT: TEMP: C:\Users\Kodi\AppData\Local\Temp
[23:10:11] [INFO]::ENVIRONMENT: TMP: C:\Users\Kodi\AppData\Local\Temp
[23:10:11] [INFO]::ENVIRONMENT: USERDOMAIN: MEDIACENTER
[23:10:11] [INFO]::ENVIRONMENT: USERDOMAIN_ROAMINGPROFILE: MEDIACENTER
[23:10:11] [INFO]::ENVIRONMENT: USERNAME: Kodi
[23:10:11] [INFO]::ENVIRONMENT: USERPROFILE: C:\Users\Kodi
[23:10:11] [INFO]::ENVIRONMENT: WINDIR: C:\WINDOWS
[23:10:11] [INFO]::MAIN: Python v3.8 will reach end of life in 1732 days.
[23:10:11] [INFO]::MAIN: Checking database structure...
[23:10:11] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[23:10:11] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[23:10:11] [INFO]::MAIN: Database upgrade required: Initial Schema
[23:10:11] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('downloads',)
[23:10:11] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[23:10:11] [DB]::MAIN: nzbtomedia.db: CREATE TABLE db_version (db_version INTEGER);
[23:10:11] [DB]::MAIN: nzbtomedia.db: CREATE TABLE downloads (input_directory TEXT, input_name TEXT, input_hash TEXT, input_id TEXT, client_agent TEXT, status INTEGER, last_update NUMERIC, CONSTRAINT pk_downloadID PRIMARY KEY (input_directory, input_name));
[23:10:11] [DB]::MAIN: nzbtomedia.db: INSERT INTO db_version (db_version) VALUES (2);
[23:10:11] [DEBUG]::MAIN: InitialSchema upgrade completed
[23:10:11] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
[23:10:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\SickRage\Scripts\nzbToMedia
[23:10:11] [DEBUG]::MAIN: git output: git version 2.15.0.windows.1
[23:10:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
[23:10:11] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
[23:10:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\SickRage\Scripts\nzbToMedia
[23:10:11] [DEBUG]::MAIN: git output: refs/heads/master
[23:10:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
[23:10:11] [INFO]::MAIN: Checking if git needs an update
[23:10:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\SickRage\Scripts\nzbToMedia
[23:10:12] [DEBUG]::MAIN: git output: 5a6837759d90285664b3cb596662adb5bfbcb2a2
[23:10:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
[23:10:12] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\SickRage\Scripts\nzbToMedia
[23:10:12] [DEBUG]::MAIN: git output:
[23:10:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
[23:10:12] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\SickRage\Scripts\nzbToMedia
[23:10:12] [DEBUG]::MAIN: git output: fatal: no such branch: '''
[23:10:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''
[23:10:12] [DEBUG]::MAIN: git didn't return newest commit hash
[23:10:12] [INFO]::MAIN: No update needed
[23:10:12] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Windows 10)
[23:10:12] [INFO]::MAIN: #########################################################
[23:10:12] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[23:10:12] [INFO]::MAIN: #########################################################
[23:10:12] [DEBUG]::MAIN: Options passed into nzbToMedia: ['nzbToMedia.py']
[23:10:12] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[23:10:12] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[23:10:12] [ERROR]::MAIN: Failed to add directories from  for post-processing: [WinError 3] Systemet finner ikke angitt bane: ''
[23:10:12] [DEBUG]::MAIN: No directories identified in Radarr:movies for post-processing
[23:10:12] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[23:10:12] [ERROR]::MAIN: Failed to add directories from  for post-processing: [WinError 3] Systemet finner ikke angitt bane: ''
[23:10:12] [DEBUG]::MAIN: No directories identified in SickBeard:tv for post-processing
[23:10:12] [INFO]::MAIN: The nzbToMedia.py script completed successfully.

**Comment by clinton-hall** [comment]
Did this work as expected when called from SABnzbd? I note the logs were from a manual run where there was no directory passed in.

**Comment by Tiwas** [comment]
Sorry. I got it working, but cannot remember exactly what I did. Required some tinkering, though. And once I got it working it was working fine from the command line as well :)

**Comment by GregSawin** [comment]
Getting this issue with 3.9, a git pull didn't help but editing the eol.py file to add a line fixed it.  I changed this:
`PYTHON_EOL = {
    (3, 8): date('2024-10-14'),
`
to this:
`PYTHON_EOL = {
    (3, 9): date('2025-10-14'),
    (3, 8): date('2024-10-14'),
`

**Comment by clinton-hall** [comment]
Thanks for this. I have now added Py3.9 support (including CI testing) into the Nightly branch.
