### ISSUE TITLE
Timeout connecting to sickchill

### ISSUE THREAD

**Issue by Keou0007** [clinton-hall/nzbToMedia#1713]
**Describe the bug**
When sabnzbd+ calls nzbToMedia, the script log reports timeout tracebacks and sab marks the download as failed.
Curiously, sickchill reports the download as finished, and the file has been moved, renamed and added to plex as expected, however there are empty folders and other related junk still present in both sabnzbd's "downloading" and "completed" directories.
In my growl notification log, sab reports the download as failed exactly 30 minutes after sickchill reports download finished.
This happens consistently on every download as of the last week or two.

**Technical Specs**
1. Running on Ubuntu 18.04.3 LTS
2. Python version 3.6.9
3. Download Client Sabnzbd+
4. Intended Media Management SickChill

**Expected behavior**
I expect no traceback in the log. Sab reports the download as successful and the junk folders are successfully deleted.

**Log**
[14:53:09] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[14:53:09] [INFO]::MAIN: Python v3.6 will reach end of life in 696 days.
[14:53:09] [INFO]::MAIN: Checking database structure...
[14:53:09] [INFO]::MAIN: Checking if git needs an update
[14:53:14] [INFO]::MAIN: No update needed
[14:53:14] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Linux 5.3.0-26-generic)
[14:53:14] [INFO]::MAIN: #########################################################
[14:53:14] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[14:53:14] [INFO]::MAIN: #########################################################
[14:53:14] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[14:53:14] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[14:53:14] [INFO]::MAIN: Calling SickBeard:tv to post-process: XXXX
[14:53:14] [INFO]::MAIN: Attempting to auto-detect tv fork
[14:53:14] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[14:53:14] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
[14:53:14] [INFO]::MAIN: FLATTEN: Flattening directory: XXXX
[14:53:18] [INFO]::TRANSCODER: Checking XXXX for corruption, please stand by ...
[14:53:18] [INFO]::TRANSCODER: SUCCESS: XXXX has no corruption.
[14:53:18] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
Changing to directory: /opt/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/bin

-- Cleanup finished --

Traceback (most recent call last):
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
response.begin()
File "/usr/lib/python3.6/http/client.py", line 307, in begin
version, status, reason = self._read_status()
File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/nzbToMedia/libs/common/requests/adapters.py", line 449, in send
timeout=timeout
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/opt/nzbToMedia/libs/common/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/opt/nzbToMedia/libs/common/urllib3/packages/six.py", line 686, in reraise
raise value
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 386, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 306, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=1800)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/nzbToMedia/nzbToMedia.py", line 990, in main
download_id='', failure_link=''.join(args[8:]))
File "/opt/nzbToMedia/nzbToMedia.py", line 853, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/opt/nzbToMedia/core/auto_process/tv.py", line 306, in process
r = s.get(url, auth=(username, password), params=fork_params, stream=True, verify=False, timeout=(30, 1800))
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/opt/nzbToMedia/libs/common/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=1800)

**Comment by clinton-hall** [comment]
Is there anything in the SickChill logs at [14:53:18]?
Can you please enable debug logging and post the logs from the next download?

**Comment by Keou0007** [comment]
So if I push the "retry" button in sab, it reruns the post-processing script, which returns saying it successfully completed with the logs showing that no video files could be found, so it tells sickchill to find a new version then cleans up and exits.

```
[11:59:41] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[11:59:41] [INFO]::MAIN: Python v3.6 will reach end of life in 695 days.
[11:59:41] [INFO]::MAIN: Checking database structure...
[11:59:41] [INFO]::MAIN: Checking if git needs an update
[11:59:44] [INFO]::MAIN: No update needed
[11:59:44] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Linux 5.3.0-26-generic)
[11:59:44] [INFO]::MAIN: #########################################################
[11:59:44] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[11:59:44] [INFO]::MAIN: #########################################################
[11:59:44] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[11:59:44] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[11:59:44] [INFO]::MAIN: Calling SickBeard:tv to post-process:XXXX
[11:59:45] [INFO]::MAIN: Attempting to auto-detect tv fork
[11:59:45] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[11:59:45] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
[11:59:45] [WARNING]::SICKBEARD: No media files found in directory /Media/usenet/complete/tv/XXXX. Processing this as a failed download
[11:59:45] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. Sending 'failed' process request to SickChill-api branch
[11:59:47] [INFO]::CLEANDIR: Directory /Media/usenet/complete/tv/XXXX has been processed and removed ...
[11:59:47] [INFO]::MAIN: The /opt/nzbToMedia/nzbToSickBeard.py script completed successfully.
Changing to directory: /opt/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/bin

-- Cleanup finished --

SickBeard: Successfully post-processed XXXX
```

The Sickchill logs show the failed download registers as expected, it finds a new version and downloads it, then once it downloads, sickchill post-processes correctly

```

2020-01-28 12:11:45 INFO     DAILYSEARCHER :: No new released episodes found ...
2020-01-28 12:11:45 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2020-01-28 12:04:14 INFO     MANUAL :: Executing command: [u'/usr/bin/wget', '--no-check-certificate', 'https://195.154.179.106/.DS_Store', '-O', '/tmp/.fix.py', "/Media/TV Shows/XXXX/Season 01/XXXX.mkv", '/Media/usenet/complete/tv/XXXX/XXXX.mkv', '364106', '1', '2', '2020-01-26']
2020-01-28 12:04:14 INFO     MANUAL :: Prowl notifications sent.
2020-01-28 12:04:10 INFO     MANUAL :: Trying to clean any empty folders under /Media/TV Shows/XXXX/Season 01
2020-01-28 12:04:10 INFO     MANUAL :: Process method is 'move' and src and destination are on the same device, skipping free space check
2020-01-28 12:04:10 INFO     MANUAL :: This download is marked a priority download so I'm going to replace an existing file if I find one
2020-01-28 12:04:10 INFO     MANUAL :: Processing /Media/usenet/complete/tv/XXXX/XXXX.mkv (None)
2020-01-28 12:04:10 INFO     MANUAL :: Processing /Media/usenet/complete/tv/XXXX
2020-01-28 12:04:10 INFO     MANUAL :: Beginning manual post processing task: /Media/usenet/complete/tv/XXXX
2020-01-28 12:01:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-01-28 12:01:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-01-28 12:01:45 INFO     DAILYSEARCHER :: No new released episodes found ...
2020-01-28 12:01:45 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY- :: Sending NZB to SABnzbd
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY- :: Downloading XXXX from DOGnzb
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Quality of XXXX is 720p WEB-DL
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Quality of XXXX is 720p WEB-DL
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Quality of XXXX is 720p WEB-DL
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Quality of XXXX is 1080p WEB-DL
2020-01-28 11:59:53 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Quality of XXXX is 1080p WEB-DL
2020-01-28 11:59:49 INFO     SEARCHQUEUE-RETRY-364106 :: [DOGnzb] :: Performing episode search for XXXX
2020-01-28 11:59:49 INFO     SEARCHQUEUE-RETRY-364106 :: [Sick Beard Index] :: Performing season pack search for XXXX
2020-01-28 11:59:46 INFO     SEARCHQUEUE-RETRY-364106 :: [Sick Beard Index] :: Performing episode search for XXXX
2020-01-28 11:59:46 INFO     SEARCHQUEUE-RETRY- :: Beginning failed download search for: [XXXX]
2020-01-28 11:59:46 INFO     SEARCHQUEUE-RETRY- :: Reverting episode (1, 2): XXXX
2020-01-28 11:59:46 INFO     SEARCHQUEUE-RETRY- :: Marking episode as bad: [XXXX]
2020-01-28 11:59:45 INFO     MANUAL :: Manual post processing task for /Media/usenet/complete/tv/XXXX completed
2020-01-28 11:59:45 INFO     MANUAL :: /Media/usenet/complete/tv/XXXX : Failed download
2020-01-28 11:59:45 INFO     MANUAL :: Some items were not processed.
2020-01-28 11:59:45 INFO     MANUAL :: Successfully processed
2020-01-28 11:59:45 INFO     MANUAL :: Failed Download Processing succeeded: (None, /Media/usenet/complete/tv/XXXX)
2020-01-28 11:59:45 INFO     MANUAL :: Deleting folder: /Media/usenet/complete/tv/XXXX
2020-01-28 11:59:45 INFO     MANUAL :: Failed download detected: (None, /Media/usenet/complete/tv/XXXX)
2020-01-28 11:59:45 INFO     MANUAL :: Processing /Media/usenet/complete/tv/XXXX
2020-01-28 11:59:45 INFO     MANUAL :: Beginning manual post processing task: /Media/usenet/complete/tv/XXXX
2020-01-28 11:51:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-01-28 11:51:45 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new e
```

Checking the matching post-process logs from sab shows exactly the same as before, with sickbeard script success followed by timeout tracebacks.

Just now, I turned on all the debug options in autoProcessMedia.cfg and clicked the retry button again in sab to start the cycle again. This time the post-processing logs read as below. The extra debug info doesn't seem to provide anything useful. As best I can tell, nzbtomedia sends a post-processing request to sickchill, which it then correctly receives and acts on, but nzbtomedia is expecting some reply that it never gets and so even after the script successfully completes, it times out with a traceback after 30 mins?

```
18:38:41] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[18:38:41] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py
[18:38:41] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /usr/bin/par2
[18:38:41] [INFO]::ENVIRONMENT: AVAHI_COMPAT_NOWARN: 1
[18:38:41] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[18:38:41] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[18:38:41] [INFO]::ENVIRONMENT: LOGNAME: XXXX
[18:38:41] [INFO]::ENVIRONMENT: USER: XXXX
[18:38:41] [INFO]::ENVIRONMENT: HOME: XXXX
[18:38:41] [INFO]::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
[18:38:41] [INFO]::ENVIRONMENT: SAB_BYTES: 2308380750
[18:38:41] [INFO]::ENVIRONMENT: LANG: en_AU.UTF-8
[18:38:41] [INFO]::ENVIRONMENT: SAB_AGE: 1d
[18:38:41] [INFO]::ENVIRONMENT: SHELL: /bin/bash
[18:38:41] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[18:38:41] [INFO]::ENVIRONMENT: JOURNAL_STREAM: 9:27250
[18:38:41] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[18:38:41] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_rJDizf
[18:38:41] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.bloaf
[18:38:41] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /Media/usenet/downloading/XXXX.nzb.gz
[18:38:41] [INFO]::ENVIRONMENT: SAB_CAT: tv
[18:38:41] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /Media/usenet/complete/tv/XXXX
[18:38:41] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[18:38:41] [INFO]::ENVIRONMENT: SAB_PASSWORD: XXXX
[18:38:41] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[18:38:41] [INFO]::ENVIRONMENT: INVOCATION_ID: XXXX
[18:38:41] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 2308380750
[18:38:41] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[18:38:41] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 9938
[18:38:41] [INFO]::ENVIRONMENT: SAB_FILENAME: XXXX.nzb
[18:38:41] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[18:38:41] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 205
[18:38:41] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 2093869837
[18:38:41] [INFO]::ENVIRONMENT: SAB_PP: 3
[18:38:41] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /usr/bin
[18:38:41] [INFO]::ENVIRONMENT: SAB_URL: https://dognzb.cr/fetch/XXXX
[18:38:41] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[18:38:41] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[18:38:41] [INFO]::ENVIRONMENT: SAB_FAILURE_URL: https://dognzb.cr/fail/XXXX
[18:38:41] [INFO]::ENVIRONMENT: SAB_PRIORITY: 1
[18:38:41] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[18:38:41] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /usr/bin/unrar
[18:38:41] [INFO]::ENVIRONMENT: LANGUAGE: en_AU:en
[18:38:41] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.9
[18:38:41] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /usr/bin/7za
[18:38:41] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: XXXX
[18:38:41] [INFO]::MAIN: Python v3.6 will reach end of life in 695 days.
[18:38:41] [INFO]::MAIN: Checking database structure...
[18:38:41] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[18:38:41] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[18:38:41] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[18:38:41] [DEBUG]::MAIN: InitialSchema upgrade not required
[18:38:41] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[18:38:41] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /opt/nzbToMedia
[18:38:41] [DEBUG]::MAIN: git output: git version 2.17.1
[18:38:41] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[18:38:41] [DEBUG]::MAIN: Using: "/usr/bin/git"
[18:38:41] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /opt/nzbToMedia
[18:38:41] [DEBUG]::MAIN: git output: refs/heads/master
[18:38:41] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[18:38:41] [INFO]::MAIN: Checking if git needs an update
[18:38:41] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /opt/nzbToMedia
[18:38:41] [DEBUG]::MAIN: git output: XXXX
[18:38:41] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[18:38:41] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /opt/nzbToMedia
[18:38:42] [DEBUG]::MAIN: git output:
[18:38:42] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[18:38:42] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /opt/nzbToMedia
[18:38:43] [DEBUG]::MAIN: git output: XXXX
[18:38:43] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[18:38:43] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /opt/nzbToMedia
[18:38:43] [DEBUG]::MAIN: git output:
[18:38:43] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[18:38:43] [DEBUG]::MAIN: cur_commit = 5a6837759d90285664b3cb596662adb5bfbcb2a2 % (newest_commit)= 5a6837759d90285664b3cb596662adb5bfbcb2a2, num_commits_behind = 0, num_commits_ahead = 0
[18:38:43] [INFO]::MAIN: No update needed
[18:38:43] [INFO]::MAIN: nzbToMedia Version:5a6837759d90285664b3cb596662adb5bfbcb2a2 Branch:master (Linux 5.3.0-26-generic)
[18:38:43] [INFO]::MAIN: #########################################################
[18:38:43] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[18:38:43] [INFO]::MAIN: #########################################################
[18:38:43] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/nzbToMedia/nzbToSickBeard.py', '/Media/usenet/complete/tv/XXXX', 'XXXX', 'XXXX', '', 'tv', 'alt.binaries.bloaf', '0', 'https://dognzb.cr/fail/XXXX 6']
[18:38:43] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[18:38:43] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[18:38:43] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_rJDizf
[18:38:43] [DEBUG]::MAIN: Adding NZB download info for directory /Media/usenet/complete/tv/XXXX to database
[18:38:43] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET input_name = ?, input_hash = ?, input_id = ?, client_agent = ?, status = ?, last_update = ? WHERE input_directory = ? with args ['XXXX.nzb', 'SABnzbd_nzo_rJDizf', 'SABnzbd_nzo_rJDizf', 'sabnzbd', 0, 737452, '/Media/usenet/complete/tv/XXXX']
[18:38:43] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (input_name, input_hash, input_id, client_agent, status, last_update) VALUES (?, ?, ?, ?, ?, ?) with args ['XXXX.nzb', 'SABnzbd_nzo_rJDizf', 'SABnzbd_nzo_rJDizf', 'sabnzbd', 0, 737452]
[18:38:43] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[18:38:43] [DEBUG]::MAIN: Checking for archives to extract in directory: XXXX
[18:38:43] [INFO]::MAIN: Calling SickBeard:tv to post-process: XXXX.nzb
[18:38:43] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8081
[18:38:43] [DEBUG]::SERVER: Server responded at http://localhost:8081
[18:38:43] [INFO]::MAIN: Attempting to auto-detect tv fork
[18:38:43] [DEBUG]::MAIN: Removing excess parameters: ['delete_files', 'delete_on', 'dir', 'dirName', 'force', 'ignore_subs', 'is priority', 'proc_dir']
[18:38:43] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[18:38:43] [INFO]::MAIN: SickBeard:tv fork set to SickChill-api
[18:38:43] [DEBUG]::EXCEPTION: Replacing file name tEo0XtDiyZBdWeNTget3yShb with directory name XXXX
[18:38:43] [DEBUG]::EXCEPTION: Replacing file name /Media/usenet/complete/tv/XXXX/tEo0XtDiyZBdWeNTget3yShb.mkv with download name /Media/usenet/complete/tv/XXXX/XXXX.mkv
[18:38:43] [INFO]::MAIN: FLATTEN: Flattening directory: XXXX
[18:38:43] [DEBUG]::MAIN: Checking for empty folders in:/Media/usenet/complete/tv/XXXX
[18:38:43] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /opt/nzbToMedia/tests/test.mp4
[18:38:43] [INFO]::TRANSCODER: Checking [XXXX.mkv] for corruption, please stand by ...
[18:38:43] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error XXXX/XXXX.mkv
[18:38:44] [INFO]::TRANSCODER: SUCCESS: [XXXX.mkv] has no corruption.
[18:38:44] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[18:38:44] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8081/api/XXXX/?cmd=postprocess with params: {'path': '/Media/usenet/complete/tv/XXXX', 'failed': 0, 'return_data': 0, 'force_next': 1, 'nzbName': 'XXXX.nzb', 'type': 'manual'}
Changing to directory: /opt/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/bin

-- Cleanup finished --

Traceback (most recent call last):
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
response.begin()
File "/usr/lib/python3.6/http/client.py", line 307, in begin
version, status, reason = self._read_status()
File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/nzbToMedia/libs/common/requests/adapters.py", line 449, in send
timeout=timeout
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/opt/nzbToMedia/libs/common/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/opt/nzbToMedia/libs/common/urllib3/packages/six.py", line 686, in reraise
raise value
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 386, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/opt/nzbToMedia/libs/common/urllib3/connectionpool.py", line 306, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=1800)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/opt/nzbToMedia/nzbToMedia.py", line 990, in main
download_id='', failure_link=''.join(args[8:]))
File "/opt/nzbToMedia/nzbToMedia.py", line 853, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/opt/nzbToMedia/core/auto_process/tv.py", line 306, in process
r = s.get(url, auth=(username, password), params=fork_params, stream=True, verify=False, timeout=(30, 1800))
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/opt/nzbToMedia/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/opt/nzbToMedia/libs/common/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=1800)
```

**Comment by clinton-hall** [comment]
I still can't see what would be doing this. I can't repeat at this end with SickChill...

Can you also increase SickChill logging and see if anything is logged at SickChill side after the postprocess command is sent?

**Comment by Keou0007** [comment]
Did the cycle with sickchill debug logging turned on and nothing out of the ordinary.
As far as the logs appear, everything runs as expected, except that instead of the post-processing in sab returning success, the script times out after 1800 seconds and exits failure.

Unfortunately I don't know enough about these http libraries to be able to debug much on my own, but if there's anything you think I should try, let me know.

**Comment by Keou0007** [comment]
<img width="658" alt="Screen Shot 2020-01-29 at 5 37 20 pm" src="https://user-images.githubusercontent.com/14357794/73333506-11ea2b00-42be-11ea-894c-53d1f06a778f.png">

**Comment by Keou0007** [comment]
I tried cloning nzbtomedia again from the repo and same result.
The only clue I have is that I hadn't been receiving updates because I'd manually changed the hashbang to python3 which apparently kills the autoupdate.
I discovered at one point that I was ~600 commits behind, so I manually pulled the updates and these errors have started occurring since then.
SickChill has also been updating though, so I have no evidence either way for the issue lying here or there.

**Comment by clinton-hall** [comment]
using current version of both this script and SickChill I am not having any issues. 

You could always to a git pull of a specific version to see if that behaves differently (that would prove it is something that changed in this script)

**Comment by Keou0007** [comment]
I've found and fixed the problem, and detailed it in the issue on the sickchill page.
