### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by DrakeJones** [clinton-hall/nzbToMedia#1724]
**Describe the bug**
Could be a Python issue. https://bugs.python.org/issue35615

**Technical Specs**
1. Running on Windows 7x64'
2. Python version .7
3. Download Client SABnbzd
4. Intended Media Management CouchPotoato

**Expected behavior**
Direct unpack by SABnbzd then PP by CouchPotato
**Log**

A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)

[22:08:11] [INFO]::MAIN: Loading config from [C:\Scripts\nzbToMedia\autoProcessMedia.cfg]
[22:08:11] [INFO]::MAIN: Python v3.7 will reach end of life in 1211 days.
[22:08:11] [INFO]::MAIN: Checking database structure...
[22:08:11] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[22:08:11] [DEBUG]::MAIN: InitialSchema upgrade not required
[22:08:11] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: git version 2.21.0.windows.1
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful
[22:08:11] [DEBUG]::MAIN: Using: "C:\Program Files\Git\bin\git.exe"
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: refs/heads/master
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful
[22:08:11] [INFO]::MAIN: Checking if git needs an update
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Scripts\nzbToMedia
[22:08:11] [DEBUG]::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81
[22:08:11] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful
[22:08:11] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Scripts\nzbToMedia
[22:08:12] [DEBUG]::MAIN: git output:
[22:08:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful
[22:08:12] [DEBUG]::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\Scripts\nzbToMedia
[22:08:12] [DEBUG]::MAIN: git output: fatal: no such branch: '''
[22:08:12] [DEBUG]::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''
[22:08:12] [DEBUG]::MAIN: git didn't return newest commit hash
[22:08:12] [INFO]::MAIN: No update needed
[22:08:12] [INFO]::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Windows 7)
[22:08:12] [INFO]::MAIN: #########################################################
[22:08:12] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[22:08:12] [INFO]::MAIN: #########################################################
[22:08:12] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\Scripts\nzbToMedia\nzbToCouchPotato.py', 'D:\ADMIN\comp\movie\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)', 'A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb', 'A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)', '', 'movie', 'alt.binaries.nzb', '-1', '']
[22:08:12] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[22:08:12] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[22:08:14] [DEBUG]::MAIN: Adding NZB download info for directory D:\ADMIN\comp\movie\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200) to database
[22:08:14] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[22:08:14] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\ADMIN\comp\movie\A Quiet Place 2018 720p BluRay x264-WiKi-WhiteRev cp(tt6644200)
[22:08:14] [INFO]::MAIN: Calling CouchPotato:movie to post-process:A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb
[22:08:14] [INFO]::MAIN: Attemping imdbID lookup for A.Quiet.Place.2018.720p.BluRay.x264-WiKi-W.nzb
[22:08:14] [INFO]::MAIN: Searching folder and file names for imdbID ...
[22:08:14] [INFO]::MAIN: Found imdbID [tt6644200]
[22:08:14] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/
[22:08:15] [DEBUG]::SERVER: Server responded at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/
[22:08:15] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/media.get with PARAMS: {'id': 'tt6644200'}
Changing to directory: C:\Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing pycache/\nRemoving core/pycache/\nRemoving core/auto_process/pycache/\nRemoving core/extractor/pycache/\nRemoving core/plugins/pycache/\nRemoving core/plugins/downloaders/pycache/\nRemoving core/plugins/downloaders/nzb/pycache/\nRemoving core/plugins/downloaders/torrent/pycache/\nRemoving core/utils/pycache/\nRemoving libs/pycache/\nRemoving libs/common/pycache/\nRemoving libs/common/babelfish/pycache/\nRemoving libs/common/babelfish/converters/pycache/\nRemoving libs/common/beets/pycache/\nRemoving libs/common/beets/util/pycache/\nRemoving libs/common/bs4/pycache/\nRemoving libs/common/bs4/builder/pycache/\nRemoving libs/common/certifi/pycache/\nRemoving libs/common/chardet/pycache/\nRemoving libs/common/dateutil/pycache/\nRemoving libs/common/dateutil/parser/pycache/\nRemoving libs/common/dateutil/tz/pycache/\nRemoving libs/common/dogpile/pycache/\nRemoving libs/common/dogpile/cache/pycache/\nRemoving libs/common/dogpile/cache/backends/pycache/\nRemoving libs/common/dogpile/util/pycache/\nRemoving libs/common/guessit/pycache/\nRemoving libs/common/guessit/rules/pycache/\nRemoving libs/common/guessit/rules/common/pycache/\nRemoving libs/common/guessit/rules/markers/pycache/\nRemoving libs/common/guessit/rules/properties/pycache/\nRemoving libs/common/idna/pycache/\nRemoving libs/common/mutagen/pycache/\nRemoving libs/common/mutagen/asf/pycache/\nRemoving libs/common/mutagen/id3/pycache/\nRemoving libs/common/mutagen/mp4/pycache/\nRemoving libs/common/pkg_resources/pycache/\nRemoving libs/common/pkg_resources/_vendor/pycache/\nRemoving libs/common/pkg_resources/_vendor/packaging/pycache/\nRemoving libs/common/pkg_resources/extern/pycache/\nRemoving libs/common/pysrt/pycache/\nRemoving libs/common/qbittorrent/pycache/\nRemoving libs/common/rebulk/pycache/\nRemoving libs/common/rencode/pycache/\nRemoving libs/common/requests/pycache/\nRemoving libs/common/stevedore/pycache/\nRemoving libs/common/subliminal/pycache/\nRemoving libs/common/subliminal/providers/pycache/\nRemoving libs/common/transmissionrpc/pycache/\nRemoving libs/common/unidecode/pycache/\nRemoving libs/common/urllib3/pycache/\nRemoving libs/common/urllib3/contrib/pycache/\nRemoving libs/common/urllib3/packages/pycache/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/pycache/\nRemoving libs/common/urllib3/util/pycache/\nRemoving libs/common/yaml/pycache/\nRemoving libs/custom/synchronousdeluge/pycache/\nRemoving libs/custom/utorrent/pycache/\nRemoving libs/win/pycache/\nRemoving libs/win/jaraco/structures/pycache/\nRemoving libs/win/jaraco/windows/pycache/\nRemoving libs/win/jaraco/windows/api/pycache/\nRemoving libs/win/jaraco/windows/filesystem/pycache/\n'
b'Removing pycache/\nRemoving core/pycache/\nRemoving core/auto_process/pycache/\nRemoving core/extractor/pycache/\nRemoving core/plugins/pycache/\nRemoving core/plugins/downloaders/pycache/\nRemoving core/plugins/downloaders/nzb/pycache/\nRemoving core/plugins/downloaders/torrent/pycache/\nRemoving core/utils/pycache/\nRemoving libs/pycache/\nRemoving libs/common/pycache/\nRemoving libs/common/babelfish/pycache/\nRemoving libs/common/babelfish/converters/pycache/\nRemoving libs/common/beets/pycache/\nRemoving libs/common/beets/util/pycache/\nRemoving libs/common/bs4/pycache/\nRemoving libs/common/bs4/builder/pycache/\nRemoving libs/common/certifi/pycache/\nRemoving libs/common/chardet/pycache/\nRemoving libs/common/dateutil/pycache/\nRemoving libs/common/dateutil/parser/pycache/\nRemoving libs/common/dateutil/tz/pycache/\nRemoving libs/common/dogpile/pycache/\nRemoving libs/common/dogpile/cache/pycache/\nRemoving libs/common/dogpile/cache/backends/pycache/\nRemoving libs/common/dogpile/util/pycache/\nRemoving libs/common/guessit/pycache/\nRemoving libs/common/guessit/rules/pycache/\nRemoving libs/common/guessit/rules/common/pycache/\nRemoving libs/common/guessit/rules/markers/pycache/\nRemoving libs/common/guessit/rules/properties/pycache/\nRemoving libs/common/idna/pycache/\nRemoving libs/common/mutagen/pycache/\nRemoving libs/common/mutagen/asf/pycache/\nRemoving libs/common/mutagen/id3/pycache/\nRemoving libs/common/mutagen/mp4/pycache/\nRemoving libs/common/pkg_resources/pycache/\nRemoving libs/common/pkg_resources/_vendor/pycache/\nRemoving libs/common/pkg_resources/_vendor/packaging/pycache/\nRemoving libs/common/pkg_resources/extern/pycache/\nRemoving libs/common/pysrt/pycache/\nRemoving libs/common/qbittorrent/pycache/\nRemoving libs/common/rebulk/pycache/\nRemoving libs/common/rencode/pycache/\nRemoving libs/common/requests/pycache/\nRemoving libs/common/stevedore/pycache/\nRemoving libs/common/subliminal/pycache/\nRemoving libs/common/subliminal/providers/pycache/\nRemoving libs/common/transmissionrpc/pycache/\nRemoving libs/common/unidecode/pycache/\nRemoving libs/common/urllib3/pycache/\nRemoving libs/common/urllib3/contrib/pycache/\nRemoving libs/common/urllib3/packages/pycache/\nRemoving libs/common/urllib3/packages/ssl_match_hostname/pycache/\nRemoving libs/common/urllib3/util/pycache/\nRemoving libs/common/yaml/pycache/\nRemoving libs/custom/synchronousdeluge/pycache/\nRemoving libs/custom/utorrent/pycache/\nRemoving libs/win/pycache/\nRemoving libs/win/jaraco/structures/pycache/\nRemoving libs/win/jaraco/windows/pycache/\nRemoving libs/win/jaraco/windows/api/pycache/\nRemoving libs/win/jaraco/windows/filesystem/pycache/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory: C:\SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "C:\Scripts\nzbToMedia\nzbToCouchPotato.py", line 272, in
result = nzbToMedia.main(sys.argv, section)
File "C:\Scripts\nzbToMedia\nzbToMedia.py", line 942, in main
download_id='', failure_link=''.join(args[8:]))
File "C:\Scripts\nzbToMedia\nzbToMedia.py", line 803, in process
result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "C:\Scripts\nzbToMedia\core\auto_process\movies.py", line 80, in process
release = get_release(base_url, imdbid, download_id)
File "C:\Scripts\nzbToMedia\core\auto_process\movies.py", line 514, in get_release
for x2 in results.values():
RuntimeError: dictionary changed size during iteration

**Comment by clinton-hall** [comment]
Are you able to switch to the `Dictionary-fix1` branch and test the fix I just posted?

**Comment by DrakeJones** [comment]
Crashing just now.  I’ll switch to that branch tomorrow GMT+1, retry the download and let you know how it goes.  Thank you for the prompt response.

**Comment by DrakeJones** [comment]
It looks like you did it.  I ran nzbtomedia.py manually a couple of times.  

 

2020-03-05 16:13:09 INFO    ::MAIN: Loading config from [C:\Scripts\nzbToMedia\autoProcessMedia.cfg]

2020-03-05 16:13:09 INFO    ::MAIN: Python v3.7 will reach end of life in 1209 days.

2020-03-05 16:13:09 INFO    ::MAIN: Checking database structure...

2020-03-05 16:13:09 DEBUG   ::MAIN: Checking Initial Schema database upgrade

2020-03-05 16:13:09 DEBUG   ::MAIN: InitialSchema upgrade not required

2020-03-05 16:13:09 DEBUG   ::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version

2020-03-05 16:13:09 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:13:09 DEBUG   ::MAIN: git output: git version 2.21.0.windows.1

2020-03-05 16:13:09 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful

2020-03-05 16:13:09 DEBUG   ::MAIN: Using: "C:\Program Files\Git\bin\git.exe"

2020-03-05 16:13:09 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:13:09 DEBUG   ::MAIN: git output: refs/heads/master

2020-03-05 16:13:09 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful

2020-03-05 16:13:09 INFO    ::MAIN: Checking if git needs an update

2020-03-05 16:13:09 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:13:09 DEBUG   ::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81

2020-03-05 16:13:09 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful

2020-03-05 16:13:09 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:13:10 DEBUG   ::MAIN: git output: 

2020-03-05 16:13:10 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful

2020-03-05 16:13:10 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:13:10 DEBUG   ::MAIN: git output: fatal: no such branch: '''

2020-03-05 16:13:10 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''

2020-03-05 16:13:10 DEBUG   ::MAIN: git didn't return newest commit hash

2020-03-05 16:13:10 INFO    ::MAIN: No update needed

2020-03-05 16:13:10 INFO    ::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Windows 7)

2020-03-05 16:13:10 INFO    ::MAIN: #########################################################

2020-03-05 16:13:10 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##

2020-03-05 16:13:10 INFO    ::MAIN: #########################################################

2020-03-05 16:13:10 DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\Scripts\\nzbToMedia\\nzbToMedia.py']

2020-03-05 16:13:10 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...

2020-03-05 16:13:10 INFO    ::MAIN: Searching D:\ADMIN\comp\movie for mediafiles to post-process ...

2020-03-05 16:13:10 INFO    ::MAIN: Starting manual run for CouchPotato:movie - Folder: D:\ADMIN\comp\movie\A Quiet Place (2018) [BluRay] [1080p] [YTS.AM]

2020-03-05 16:13:10 INFO    ::MAIN: Checking database for download info for A Quiet Place (2018) [BluRay] [1080p] [YTS.AM] ...

2020-03-05 16:13:10 INFO    ::MAIN: Unable to locate download info for A Quiet Place (2018) [BluRay] [1080p] [YTS.AM], continuing to try and process this release ...

2020-03-05 16:13:10 INFO    ::MAIN: Auto-detected SECTION:CouchPotato

2020-03-05 16:13:10 DEBUG   ::MAIN: Checking for archives to extract in directory: D:\ADMIN\comp\movie\A Quiet Place (2018) [BluRay] [1080p] [YTS.AM]

2020-03-05 16:13:10 INFO    ::MAIN: Calling CouchPotato:movie to post-process:A Quiet Place (2018) [BluRay] [1080p] [YTS.AM]

2020-03-05 16:13:10 INFO    ::MAIN: Attemping imdbID lookup for A Quiet Place (2018) [BluRay] [1080p] [YTS.AM]

2020-03-05 16:13:10 INFO    ::MAIN: Searching folder and file names for imdbID ...

2020-03-05 16:13:10 INFO    ::MAIN: Searching IMDB for imdbID ...

2020-03-05 16:13:10 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com

2020-03-05 16:13:11 INFO    ::MAIN: Found imdbID [tt6644200]

2020-03-05 16:13:11 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:13:12 DEBUG   ::SERVER: Server responded at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:13:12 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/media.get with PARAMS: {'id': 'tt6644200'}

2020-03-05 16:15:31 INFO    ::MAIN: Loading config from [C:\Scripts\nzbToMedia\autoProcessMedia.cfg]

2020-03-05 16:15:31 INFO    ::MAIN: Python v3.7 will reach end of life in 1209 days.

2020-03-05 16:15:31 INFO    ::MAIN: Checking database structure...

2020-03-05 16:15:31 DEBUG   ::MAIN: Checking Initial Schema database upgrade

2020-03-05 16:15:31 DEBUG   ::MAIN: InitialSchema upgrade not required

2020-03-05 16:15:31 DEBUG   ::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version

2020-03-05 16:15:31 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:15:31 DEBUG   ::MAIN: git output: git version 2.21.0.windows.1

2020-03-05 16:15:31 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful

2020-03-05 16:15:31 DEBUG   ::MAIN: Using: "C:\Program Files\Git\bin\git.exe"

2020-03-05 16:15:31 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:15:31 DEBUG   ::MAIN: git output: refs/heads/master

2020-03-05 16:15:31 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful

2020-03-05 16:15:31 INFO    ::MAIN: Checking if git needs an update

2020-03-05 16:15:31 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:15:31 DEBUG   ::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81

2020-03-05 16:15:31 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful

2020-03-05 16:15:31 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:15:32 DEBUG   ::MAIN: git output: 

2020-03-05 16:15:32 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful

2020-03-05 16:15:32 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:15:32 DEBUG   ::MAIN: git output: fatal: no such branch: '''

2020-03-05 16:15:32 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''

2020-03-05 16:15:32 DEBUG   ::MAIN: git didn't return newest commit hash

2020-03-05 16:15:32 INFO    ::MAIN: No update needed

2020-03-05 16:15:32 INFO    ::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Windows 7)

2020-03-05 16:15:32 INFO    ::MAIN: #########################################################

2020-03-05 16:15:32 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##

2020-03-05 16:15:32 INFO    ::MAIN: #########################################################

2020-03-05 16:15:32 DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\Scripts\\nzbToMedia\\nzbToMedia.py']

2020-03-05 16:15:32 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...

2020-03-05 16:15:32 INFO    ::MAIN: Searching D:\ADMIN\comp\movie for mediafiles to post-process ...

2020-03-05 16:15:32 INFO    ::MAIN: Starting manual run for CouchPotato:movie - Folder: D:\ADMIN\comp\movie\A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:15:32 INFO    ::MAIN: Checking database for download info for A Quiet Place (2018) [1080p] [YTS.ME] ...

2020-03-05 16:15:32 INFO    ::MAIN: Unable to locate download info for A Quiet Place (2018) [1080p] [YTS.ME], continuing to try and process this release ...

2020-03-05 16:15:32 INFO    ::MAIN: Auto-detected SECTION:CouchPotato

2020-03-05 16:15:32 DEBUG   ::MAIN: Checking for archives to extract in directory: D:\ADMIN\comp\movie\A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:15:32 INFO    ::MAIN: Calling CouchPotato:movie to post-process:A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:15:32 INFO    ::MAIN: Attemping imdbID lookup for A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:15:32 INFO    ::MAIN: Searching folder and file names for imdbID ...

2020-03-05 16:15:32 INFO    ::MAIN: Searching IMDB for imdbID ...

2020-03-05 16:15:32 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com

2020-03-05 16:15:32 INFO    ::MAIN: Found imdbID [tt6644200]

2020-03-05 16:15:32 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:15:33 DEBUG   ::SERVER: Server responded at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:15:33 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/media.get with PARAMS: {'id': 'tt6644200'}

2020-03-05 16:16:48 INFO    ::MAIN: Loading config from [C:\Scripts\nzbToMedia\autoProcessMedia.cfg]

2020-03-05 16:16:48 INFO    ::MAIN: Python v3.7 will reach end of life in 1209 days.

2020-03-05 16:16:48 INFO    ::MAIN: Checking database structure...

2020-03-05 16:16:48 DEBUG   ::MAIN: Checking Initial Schema database upgrade

2020-03-05 16:16:48 DEBUG   ::MAIN: InitialSchema upgrade not required

2020-03-05 16:16:48 DEBUG   ::MAIN: Checking if we can use git commands: "C:\Program Files\Git\bin\git.exe" version

2020-03-05 16:16:48 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" version with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:16:49 DEBUG   ::MAIN: git output: git version 2.21.0.windows.1

2020-03-05 16:16:49 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" version : returned successful

2020-03-05 16:16:49 DEBUG   ::MAIN: Using: "C:\Program Files\Git\bin\git.exe"

2020-03-05 16:16:49 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:16:49 DEBUG   ::MAIN: git output: refs/heads/master

2020-03-05 16:16:49 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" symbolic-ref -q HEAD : returned successful

2020-03-05 16:16:49 INFO    ::MAIN: Checking if git needs an update

2020-03-05 16:16:49 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse HEAD with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:16:49 DEBUG   ::MAIN: git output: 46b2e8998ce7c0e4b853272f0bdb06a558852c81

2020-03-05 16:16:49 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse HEAD : returned successful

2020-03-05 16:16:49 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" fetch origin with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:16:49 DEBUG   ::MAIN: git output: 

2020-03-05 16:16:49 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" fetch origin : returned successful

2020-03-05 16:16:49 DEBUG   ::MAIN: Executing "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' with your shell in C:\Scripts\nzbToMedia

2020-03-05 16:16:49 DEBUG   ::MAIN: git output: fatal: no such branch: '''

2020-03-05 16:16:49 DEBUG   ::MAIN: "C:\Program Files\Git\bin\git.exe" rev-parse --verify --quiet '@{upstream}' returned : fatal: no such branch: '''

2020-03-05 16:16:49 DEBUG   ::MAIN: git didn't return newest commit hash

2020-03-05 16:16:49 INFO    ::MAIN: No update needed

2020-03-05 16:16:49 INFO    ::MAIN: nzbToMedia Version:46b2e8998ce7c0e4b853272f0bdb06a558852c81 Branch:master (Windows 7)

2020-03-05 16:16:50 INFO    ::MAIN: #########################################################

2020-03-05 16:16:50 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##

2020-03-05 16:16:50 INFO    ::MAIN: #########################################################

2020-03-05 16:16:50 DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\Scripts\\nzbToMedia\\nzbToMedia.py']

2020-03-05 16:16:50 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...

2020-03-05 16:16:50 INFO    ::MAIN: Searching D:\ADMIN\comp\movie for mediafiles to post-process ...

2020-03-05 16:16:50 INFO    ::MAIN: Starting manual run for CouchPotato:movie - Folder: D:\ADMIN\comp\movie\A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:16:50 INFO    ::MAIN: Checking database for download info for A Quiet Place (2018) [1080p] [YTS.ME] ...

2020-03-05 16:16:50 INFO    ::MAIN: Unable to locate download info for A Quiet Place (2018) [1080p] [YTS.ME], continuing to try and process this release ...

2020-03-05 16:16:50 INFO    ::MAIN: Auto-detected SECTION:CouchPotato

2020-03-05 16:16:50 DEBUG   ::MAIN: Checking for archives to extract in directory: D:\ADMIN\comp\movie\A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:16:50 INFO    ::MAIN: Calling CouchPotato:movie to post-process:A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:16:50 INFO    ::MAIN: Attemping imdbID lookup for A Quiet Place (2018) [1080p] [YTS.ME]

2020-03-05 16:16:50 INFO    ::MAIN: Searching folder and file names for imdbID ...

2020-03-05 16:16:50 INFO    ::MAIN: Searching IMDB for imdbID ...

2020-03-05 16:16:50 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com

2020-03-05 16:16:50 INFO    ::MAIN: Found imdbID [tt6644200]

2020-03-05 16:16:50 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:16:51 DEBUG   ::SERVER: Server responded at http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/

2020-03-05 16:16:51 DEBUG   ::MAIN: Opening URL: http://localhost:5050/api/1c29776a3d8d4d2e8b49683fc8a4f7a2/media.get with PARAMS: {'id': 'tt6644200'}

**Comment by clinton-hall** [comment]
I'm not convinced. I note this still appears to stop after checking for releases in CP... it doesn't then carry on with checking for valid files etc.

I would have expected that if the script failed you would have received a trace-back, or there should have been logging to show how/why it finished...

**Comment by DrakeJones** [comment]
Fair enough. I’m just dabbler, CH.  For me download attempts (A Quiet Place (2018)) failed consistently a number of times for nzbs from various sources. I am pretty confident that it was a just bad upload, but that particular error is not what was to be expected on our side of the equation.  Perhaps it might be best if your try that very same .  Let me know what I can do.  

 

Manual CP>SABnzbd

 

Thanks.

Doug

**Comment by clinton-hall** [comment]
I have merged into nightly and testing here. You should switch back to nightly branch as the Dictionary-fix1 branch has been deleted now.

**Comment by DrakeJones** [comment]
Done.

**Comment by clinton-hall** [comment]
Merged to master

**Comment by DrakeJones** [comment]
Thank you.
