### ISSUE TITLE
Exit(1) Exception AttributeError: "'NoneType' object has no attribute 'path'" in > ignored

### ISSUE THREAD

**Issue by Sarcas666** [clinton-hall/nzbToMedia#1725]
**Describe the bug**
Suddenly the script has stopped postprocessing my downloads. The error appears for downloaded and failed downloads. The files that do get downloaded can be manually processed with Medusa. Every file gets the same error. I am not aware of any changes I made on the Mac mini recently.

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '....'
MacMini MacOS 10.15.3

2. Python version '....'
2.7 (due to SABnbzd ) and 3.8 (default)

3. Download Client (NZBget, SABnbzd, Transmission) '....'
SABnbzd 2.3.9
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '....'
Radarr 0.2.0.1480, Medusa 0.3.12 

**Expected behavior**
A proper processing of the script, resulting in a failed download or succeeded, and passing the result to the media manager.

**Log**
Please provide an extract, or full debug log that indicates the issue.

This log is the log of an incomplete download, but logs of completed downloads are all similar after `[timestamp] [INFO]::MAIN: Attempting to auto-detect tv fork`

```
/Applications/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
Changing to directory: /Applications/nzbToMedia

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /Applications/SABnzbd.app/Contents/Resources

-- Cleanup finished --

WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
[19:37:50] [INFO]::MAIN: Loading config from [/Applications/nzbToMedia/autoProcessMedia.cfg]
[19:37:50] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py
[19:37:50] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /Users/myname/Downloads/MediaDownloads/incompleteSABnzbd/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta/__ADMIN__/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.nzb.gz
[19:37:50] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/par2/par2-sl64
[19:37:50] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[19:37:50] [INFO]::ENVIRONMENT: PYTHONDONTWRITEBYTECODE: 1
[19:37:50] [INFO]::ENVIRONMENT: SAB_PP_STATUS: -1
[19:37:50] [INFO]::ENVIRONMENT: LOGNAME: myname
[19:37:50] [INFO]::ENVIRONMENT: USER: myname
[19:37:50] [INFO]::ENVIRONMENT: PATH: /usr/bin:/bin:/usr/sbin:/sbin
[19:37:50] [INFO]::ENVIRONMENT: HOME: /Users/myname
[19:37:50] [INFO]::ENVIRONMENT: PYTHONUNBUFFERED: 1
[19:37:50] [INFO]::ENVIRONMENT: SAB_BYTES: 0
[19:37:50] [INFO]::ENVIRONMENT: ARGVZERO: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[19:37:50] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[19:37:50] [INFO]::ENVIRONMENT: SAB_AGE: 18326d
[19:37:50] [INFO]::ENVIRONMENT: SHELL: /bin/zsh
[19:37:50] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_FAIL_MSG: Download failed - Not on your server(s) - https://sabnzbd.org/not-complete
[19:37:50] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_aU4KNR
[19:37:50] [INFO]::ENVIRONMENT: SECURITYSESSIONID: 186a7
[19:37:50] [INFO]::ENVIRONMENT: XPC_FLAGS: 0x0
[19:37:50] [INFO]::ENVIRONMENT: SAB_CAT: tv
[19:37:50] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /Users/myname/Downloads/MediaDownloads/tv/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.1
[19:37:50] [INFO]::ENVIRONMENT: SSL_CERT_FILE: /Applications/SABnzbd.app/Contents/Resources/cacert.pem
[19:37:50] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[19:37:50] [INFO]::ENVIRONMENT: EXECUTABLEPATH: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[19:37:50] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[19:37:50] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/7zip/7za
[19:37:50] [INFO]::ENVIRONMENT: _PY2APP_LAUNCHED_: 1
[19:37:50] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[19:37:50] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_FILENAME: Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta
[19:37:50] [INFO]::ENVIRONMENT: SAB_GROUP:
[19:37:50] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME:
[19:37:50] [INFO]::ENVIRONMENT: XPC_SERVICE_NAME: org.sabnzbd.team.28152
[19:37:50] [INFO]::ENVIRONMENT: SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.lqUUVyb41s/Listeners
[19:37:50] [INFO]::ENVIRONMENT: SAB_PP: 3
[19:37:50] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /Applications/SABnzbd.app/Contents/Resources
[19:37:50] [INFO]::ENVIRONMENT: LC_ALL: en_US.UTF-8
[19:37:50] [INFO]::ENVIRONMENT: SAB_URL: https://nzbfinder.ws/getnzb?id=myid.nzb&r=b6801274b887c59cd2e8dc5a943cf515
[19:37:50] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[19:37:50] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[19:37:50] [INFO]::ENVIRONMENT: TMPDIR: /var/folders/5w/r2d89fbn7j18rf4yv8p928zc0000gq/T/
[19:37:50] [INFO]::ENVIRONMENT: LaunchInstanceID: AB081EA9-FF2B-4288-A0D2-20EF698B747A
[19:37:50] [INFO]::ENVIRONMENT: SAB_FAILURE_URL:
[19:37:50] [INFO]::ENVIRONMENT: SAB_PRIORITY: 1
[19:37:50] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[19:37:50] [INFO]::ENVIRONMENT: VERSIONER_PYTHON_VERSION: 2.7
[19:37:50] [INFO]::ENVIRONMENT: RESOURCEPATH: /Applications/SABnzbd.app/Contents/Resources
[19:37:50] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/unrar/unrar
[19:37:50] [INFO]::ENVIRONMENT: __CF_USER_TEXT_ENCODING: 0x1F7:0x0:0x5
[19:37:50] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[19:37:50] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.9
[19:37:50] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta
[19:37:50] [INFO]::MAIN: Python v2.7 reached end of life 64 days ago.
[19:37:50] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[19:37:50] [INFO]::MAIN: Checking database structure...
[19:37:50] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[19:37:50] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args (u'db_version',)
[19:37:50] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[19:37:50] [DEBUG]::MAIN: InitialSchema upgrade not required
[19:37:50] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[19:37:50] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /Applications/nzbToMedia
[19:37:50] [DEBUG]::MAIN: git output: git version 2.21.0 (Apple Git-122.2)
[19:37:50] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[19:37:50] [DEBUG]::MAIN: Using: "/usr/bin/git"
[19:37:50] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /Applications/nzbToMedia
[19:37:50] [DEBUG]::MAIN: git output: refs/heads/nightly
[19:37:50] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[19:37:50] [INFO]::MAIN: Checking if git needs an update
[19:37:50] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /Applications/nzbToMedia
[19:37:50] [DEBUG]::MAIN: git output: c037387fc3c2fe7e2a4cd713ec3d27367585cc0c
[19:37:50] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[19:37:50] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /Applications/nzbToMedia
[19:37:51] [DEBUG]::MAIN: git output:
[19:37:51] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[19:37:51] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /Applications/nzbToMedia
[19:37:51] [DEBUG]::MAIN: git output: c037387fc3c2fe7e2a4cd713ec3d27367585cc0c
[19:37:51] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[19:37:51] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /Applications/nzbToMedia
[19:37:51] [DEBUG]::MAIN: git output:
[19:37:51] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[19:37:51] [DEBUG]::MAIN: cur_commit = c037387fc3c2fe7e2a4cd713ec3d27367585cc0c % (newest_commit)= c037387fc3c2fe7e2a4cd713ec3d27367585cc0c, num_commits_behind = 0, num_commits_ahead = 0
[19:37:51] [INFO]::MAIN: No update needed
[19:37:51] [INFO]::MAIN: nzbToMedia Version:c037387fc3c2fe7e2a4cd713ec3d27367585cc0c Branch:nightly (Darwin 19.3.0)
[19:37:51] [INFO]::MAIN: #########################################################
[19:37:51] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[19:37:51] [INFO]::MAIN: #########################################################
[19:37:51] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/Applications/nzbToMedia/nzbToSickBeard.py', '/Users/myname/Downloads/MediaDownloads/tv/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.1', 'Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta', 'Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta', '', 'tv', 'None', '-1', '']
[19:37:51] [INFO]::MAIN: Script triggered from SABnzbd Version 2.3.9.
[19:37:51] [DEBUG]::MAIN: Adding NZB download info for directory /Users/myname/Downloads/MediaDownloads/tv/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.1 to database
[19:37:51] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 737489, u'SABnzbd_nzo_aU4KNR', u'SABnzbd_nzo_aU4KNR', u'Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta', u'/Users/myname/Downloads/MediaDownloads/tv/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.1']
[19:37:51] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name) VALUES (?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 737489, u'SABnzbd_nzo_aU4KNR', u'SABnzbd_nzo_aU4KNR', u'Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta']
[19:37:51] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[19:37:51] [DEBUG]::MAIN: Checking for archives to extract in directory: /Users/myname/Downloads/MediaDownloads/tv/Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta.1
[19:37:51] [INFO]::MAIN: Calling SickBeard:tv to post-process:Star.Trek.Picard.S01E07.720p.HEVC.x265-MeGusta
[19:37:51] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8081
[19:37:51] [DEBUG]::SERVER: Server responded at http://localhost:8081
[19:37:51] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
File "/Applications/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/Applications/nzbToMedia/nzbToMedia.py", line 968, in main
failure_link=os.environ['SAB_FAILURE_URL'])
File "/Applications/nzbToMedia/nzbToMedia.py", line 853, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/Applications/nzbToMedia/core/auto_process/tv.py", line 56, in process
fork, fork_params = auto_fork(section, input_category)
File "/Applications/nzbToMedia/core/forks.py", line 135, in auto_fork
rem_params, found = api_check(r, params, rem_params)
File "/Applications/nzbToMedia/core/forks.py", line 33, in api_check
json_data = json_data.get('data', json_data)
AttributeError: 'unicode' object has no attribute 'get'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x109e76c90>> ignored

```

**Comment by clinton-hall** [comment]
can you switch to `Py2-unicode` branch and test?
I had made a change to the way auto-fork tested the api, and this appears to have an issue in python2.

**Comment by Sarcas666** [comment]
I entered the commands of the [wiki](https://github.com/clinton-hall/nzbToMedia/wiki/Branches#switching-branches-in-nzbtomedia) ('change branches'), but after my `git pull` I am getting
```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> Py2-unicode
```

I am unsure how to proceed.

**Comment by clinton-hall** [comment]
ok, I have merged into nightly. What happens if you switch back to nightly branch and try a git pull again?

**Comment by Sarcas666** [comment]
It didn't work out:

```
/Applications/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
warnings.warn(msg, LifetimeWarning)
Changing to directory: /Applications/nzbToMedia

-- Cleaning bytecode --

No bytecode to clean

-- Cleaning folders: [u'libs', u'core'] --
No folders to clean

Returning to directory:  /Applications/SABnzbd.app/Contents/Resources

-- Cleanup finished --

WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
[09:21:20] [INFO]::MAIN: Loading config from [/Applications/nzbToMedia/autoProcessMedia.cfg]
[09:21:21] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToSickBeard.py
[09:21:21] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /Users/muyname/Downloads/MediaDownloads/incompleteSABnzbd/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI/__ADMIN__/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.nzb.gz
[09:21:21] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/par2/par2-sl64
[09:21:21] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[09:21:21] [INFO]::ENVIRONMENT: PYTHONDONTWRITEBYTECODE: 1
[09:21:21] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[09:21:21] [INFO]::ENVIRONMENT: LOGNAME: muyname
[09:21:21] [INFO]::ENVIRONMENT: USER: muyname
[09:21:21] [INFO]::ENVIRONMENT: PATH: /usr/bin:/bin:/usr/sbin:/sbin
[09:21:21] [INFO]::ENVIRONMENT: HOME: /Users/muyname
[09:21:21] [INFO]::ENVIRONMENT: PYTHONUNBUFFERED: 1
[09:21:21] [INFO]::ENVIRONMENT: SAB_BYTES: 7126344251
[09:21:21] [INFO]::ENVIRONMENT: ARGVZERO: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[09:21:21] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[09:21:21] [INFO]::ENVIRONMENT: SAB_AGE: 13h
[09:21:21] [INFO]::ENVIRONMENT: SHELL: /bin/zsh
[09:21:21] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[09:21:21] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[09:21:21] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_WKnd5G
[09:21:21] [INFO]::ENVIRONMENT: SECURITYSESSIONID: 186a8
[09:21:21] [INFO]::ENVIRONMENT: XPC_FLAGS: 0x0
[09:21:21] [INFO]::ENVIRONMENT: SAB_CAT: tv
[09:21:21] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /Users/muyname/Downloads/MediaDownloads/tv/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.1
[09:21:21] [INFO]::ENVIRONMENT: SSL_CERT_FILE: /Applications/SABnzbd.app/Contents/Resources/cacert.pem
[09:21:21] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[09:21:21] [INFO]::ENVIRONMENT: EXECUTABLEPATH: /Applications/SABnzbd.app/Contents/MacOS/SABnzbd
[09:21:21] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[09:21:21] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/7zip/7za
[09:21:21] [INFO]::ENVIRONMENT: _PY2APP_LAUNCHED_: 1
[09:21:21] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 7126344251
[09:21:21] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND: /usr/bin/unzip
[09:21:21] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 4445
[09:21:21] [INFO]::ENVIRONMENT: SAB_FILENAME: Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.nzb
[09:21:21] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.goat
[09:21:21] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 1565
[09:21:21] [INFO]::ENVIRONMENT: XPC_SERVICE_NAME: org.sabnzbd.team.28152
[09:21:21] [INFO]::ENVIRONMENT: SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.ycP5q5kTHT/Listeners
[09:21:21] [INFO]::ENVIRONMENT: SAB_PP: 3
[09:21:21] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 7125604916
[09:21:21] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[09:21:21] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /Applications/SABnzbd.app/Contents/Resources
[09:21:21] [INFO]::ENVIRONMENT: LC_ALL: en_US.UTF-8
[09:21:21] [INFO]::ENVIRONMENT: SAB_URL: https://nzbfinder.ws/getnzb?id=myid.nzb&r=b6801274b887c59cd2e8dc5a943cf515
[09:21:21] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[09:21:21] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[09:21:21] [INFO]::ENVIRONMENT: TMPDIR: /var/folders/5w/r2d89fbn7j18rf4yv8p928zc0000gq/T/
[09:21:21] [INFO]::ENVIRONMENT: LaunchInstanceID: 0EB23CFF-0189-40B7-81E2-6528C09D4728
[09:21:21] [INFO]::ENVIRONMENT: SAB_FAILURE_URL: https://nzbfinder.ws/failed?guid=aa602fa6-ba25-495a-b417-857c2133b193&userid=myid&api_token=myapitoken
[09:21:21] [INFO]::ENVIRONMENT: SAB_PRIORITY: 3
[09:21:21] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[09:21:21] [INFO]::ENVIRONMENT: VERSIONER_PYTHON_VERSION: 2.7
[09:21:21] [INFO]::ENVIRONMENT: RESOURCEPATH: /Applications/SABnzbd.app/Contents/Resources
[09:21:21] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /Applications/SABnzbd.app/Contents/Resources/osx/unrar/unrar
[09:21:21] [INFO]::ENVIRONMENT: __CF_USER_TEXT_ENCODING: 0x1F7:0x0:0x5
[09:21:21] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[09:21:21] [INFO]::ENVIRONMENT: SAB_VERSION: 2.3.9
[09:21:21] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI
[09:21:21] [INFO]::MAIN: Python v2.7 reached end of life 67 days ago.
[09:21:21] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[09:21:21] [INFO]::MAIN: Checking database structure...
[09:21:21] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[09:21:21] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args (u'db_version',)
[09:21:21] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[09:21:21] [DEBUG]::MAIN: InitialSchema upgrade not required
[09:21:21] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[09:21:21] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /Applications/nzbToMedia
[09:21:21] [DEBUG]::MAIN: git output: git version 2.21.0 (Apple Git-122.2)
[09:21:21] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[09:21:21] [DEBUG]::MAIN: Using: "/usr/bin/git"
[09:21:21] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /Applications/nzbToMedia
[09:21:21] [DEBUG]::MAIN: git output: refs/heads/nightly
[09:21:21] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[09:21:21] [INFO]::MAIN: Checking if git needs an update
[09:21:21] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /Applications/nzbToMedia
[09:21:21] [DEBUG]::MAIN: git output: 001f754cd36f401fd47cd17d53515524db730519
[09:21:21] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[09:21:21] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /Applications/nzbToMedia
[09:21:22] [DEBUG]::MAIN: git output:
[09:21:22] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[09:21:22] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /Applications/nzbToMedia
[09:21:22] [DEBUG]::MAIN: git output: 001f754cd36f401fd47cd17d53515524db730519
[09:21:22] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[09:21:22] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /Applications/nzbToMedia
[09:21:22] [DEBUG]::MAIN: git output:
[09:21:22] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[09:21:22] [DEBUG]::MAIN: cur_commit = 001f754cd36f401fd47cd17d53515524db730519 % (newest_commit)= 001f754cd36f401fd47cd17d53515524db730519, num_commits_behind = 0, num_commits_ahead = 0
[09:21:22] [INFO]::MAIN: No update needed
[09:21:22] [INFO]::MAIN: nzbToMedia Version:001f754cd36f401fd47cd17d53515524db730519 Branch:nightly (Darwin 19.3.0)
[09:21:22] [INFO]::MAIN: #########################################################
[09:21:22] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[09:21:22] [INFO]::MAIN: #########################################################
[09:21:22] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/Applications/nzbToMedia/nzbToSickBeard.py', '/Users/muyname/Downloads/MediaDownloads/tv/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.1', 'Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.nzb', 'Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI', '', 'tv', 'alt.binaries.goat', '0', 'https://nzbfinder.ws/failed?guid=aa602fa6-ba25-495a-b417-857c2133b193&userid=76085&api_token=b6801274b887c59cd2e8dc5a943cf515']
[09:21:22] [INFO]::MAIN: Script triggered from SABnzbd Version 2.3.9.
[09:21:22] [DEBUG]::MAIN: Adding NZB download info for directory /Users/muyname/Downloads/MediaDownloads/tv/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.1 to database
[09:21:22] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 737492, u'SABnzbd_nzo_WKnd5G', u'SABnzbd_nzo_WKnd5G', u'Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI', u'/Users/muyname/Downloads/MediaDownloads/tv/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.1']
[09:21:22] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name) VALUES (?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 737492, u'SABnzbd_nzo_WKnd5G', u'SABnzbd_nzo_WKnd5G', u'Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI']
[09:21:23] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[09:21:23] [DEBUG]::MAIN: Checking for archives to extract in directory: /Users/muyname/Downloads/MediaDownloads/tv/Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI.1
[09:21:23] [INFO]::MAIN: Calling SickBeard:tv to post-process:Good.Omens.S01E01.In.the.Beginning.2160p.AMZN.WEB-DL.DTS-HD.MA.5.1.HDR.HEVC-MZABI
[09:21:23] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8081
[09:21:23] [DEBUG]::SERVER: Server responded at http://localhost:8081
[09:21:23] [INFO]::MAIN: Attempting to auto-detect tv fork
Traceback (most recent call last):
File "/Applications/nzbToMedia/nzbToSickBeard.py", line 273, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/Applications/nzbToMedia/nzbToMedia.py", line 968, in main
failure_link=os.environ['SAB_FAILURE_URL'])
File "/Applications/nzbToMedia/nzbToMedia.py", line 853, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/Applications/nzbToMedia/core/auto_process/tv.py", line 56, in process
fork, fork_params = auto_fork(section, input_category)
File "/Applications/nzbToMedia/core/forks.py", line 139, in auto_fork
rem_params, found = api_check(r, params, rem_params)
File "/Applications/nzbToMedia/core/forks.py", line 31, in api_check
if six.PY3:
NameError: global name 'six' is not defined
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x10b908c90>> ignored
```

**Comment by clinton-hall** [comment]
just fixed... stupid over-sight on my behalf!

**Comment by Sarcas666** [comment]
Confirming it works again!
Thanks for you time, again.
