### ISSUE TITLE
Exception AttributeError: "'NoneType' object has no attribute 'path'"

### ISSUE THREAD

**Issue by boredazfcuk** [clinton-hall/nzbToMedia#1739]
Error generated when nzbToSickBeard runs. 

**Technical Specs**
1. OS version: Alpine Linux v3.11
2. Python version: 3.8.2
3. SABnbzd
4. SickRage

**Expected behaviour**
For media to be processed correctly

**Log**
```
/nzbToMedia $ ./nzbToSickBeard.py
/nzbToMedia/eol.py:147: LifetimeWarning: Python 2.7 is no longer supported.
  warnings.warn(msg, LifetimeWarning)

-- Cleaning bytecode --
Removing cleanup.pyc
Removing eol.pyc
Removing nzbToMedia.pyc

Removing cleanup.pyc
Removing eol.pyc
Removing nzbToMedia.pyc


-- Cleaning folders: [u'libs', u'core'] --
No folders to clean


-- Cleanup finished --

[15:21:51] [INFO]::MAIN: Loading config from [/nzbToMedia/autoProcessMedia.cfg]
[15:21:51] [INFO]::ENVIRONMENT: other_complete_dir: /storage/downloads/complete/other/
[15:21:51] [INFO]::ENVIRONMENT: media_access_domain: ******
[15:21:51] [INFO]::ENVIRONMENT: global_api_key: ******
[15:21:51] [INFO]::ENVIRONMENT: music_complete_dir: /storage/downloads/complete/music/
[15:21:51] [INFO]::ENVIRONMENT: headphones_enabled: True
[15:21:51] [INFO]::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_password: ******
[15:21:51] [INFO]::ENVIRONMENT: config_dir: /config
[15:21:51] [INFO]::ENVIRONMENT: sickgear_enabled: True
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_group: sabnzbd
[15:21:51] [INFO]::ENVIRONMENT: TERM: xterm
[15:21:51] [INFO]::ENVIRONMENT: user_id: 3311
[15:21:51] [INFO]::ENVIRONMENT: SHLVL: 1
[15:21:51] [INFO]::ENVIRONMENT: stack_user: boredazfcuk
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_connections: 10
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_ssl: 1
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_user: ******
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_watch_dir: /storage/downloads/watch/sabnzbd/
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_incoming_dir: /storage/downloads/incoming/sabnzbd/
[15:21:51] [INFO]::ENVIRONMENT: HOME: /home/boredazfcuk
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host: ******
[15:21:51] [INFO]::ENVIRONMENT: couchpotato_enabled: True
[15:21:51] [INFO]::ENVIRONMENT: affinity:container: =******
[15:21:51] [INFO]::ENVIRONMENT: tv_complete_dir: /storage/downloads/complete/tv/
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_enabled: True
[15:21:51] [INFO]::ENVIRONMENT: movie_complete_dir: /storage/downloads/complete/movie/
[15:21:51] [INFO]::ENVIRONMENT: TZ: Europe/London
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_group_id: 3340
[15:21:51] [INFO]::ENVIRONMENT: app_base_dir: /SABnzbd
[15:21:51] [INFO]::ENVIRONMENT: OLDPWD: /SABnzbd
[15:21:51] [INFO]::ENVIRONMENT: HOSTNAME: ******
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_priority: 0
[15:21:51] [INFO]::ENVIRONMENT: PWD: /nzbToMedia
[15:21:51] [INFO]::ENVIRONMENT: stack_password: ******
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_server_host_port: 443
[15:21:51] [INFO]::ENVIRONMENT: sabnzbd_file_backup_dir: /storage/downloads/backup/sabnzbd/
[15:21:51] [INFO]::MAIN: Python v2.7 reached end of life 111 days ago.
[15:21:51] [WARNING]::MAIN: Please upgrade to a more recent Python version.
[15:21:51] [INFO]::MAIN: Checking database structure...
[15:21:51] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[15:21:51] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args (u'db_version',)
[15:21:51] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[15:21:51] [DEBUG]::MAIN: InitialSchema upgrade not required
[15:21:51] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git" version
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" version with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" version : returned successful
[15:21:51] [DEBUG]::MAIN: Using: "/usr/bin/git"
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
[15:21:51] [INFO]::MAIN: Checking if git needs an update
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" fetch origin : returned successful
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[15:21:51] [DEBUG]::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /nzbToMedia
[15:21:51] [DEBUG]::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[15:21:51] [DEBUG]::MAIN: cur_commit = f5e4ec0981ab2f6fd97b14b24aa363a393396073 % (newest_commit)= f5e4ec0981ab2f6fd97b14b24aa363a393396073, num_commits_behind = 0, num_commits_ahead = 0
[15:21:51] [INFO]::MAIN: No update needed
[15:21:51] [INFO]::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Linux 4.19.0-8-amd64)
[15:21:52] [INFO]::MAIN: #########################################################
[15:21:52] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[15:21:52] [INFO]::MAIN: #########################################################
[15:21:52] [DEBUG]::MAIN: Options passed into nzbToMedia: ['./nzbToSickBeard.py']
[15:21:52] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[15:21:52] [INFO]::MAIN: Searching /storage/downloads/complete/tv/ for mediafiles to post-process ...
[15:21:52] [INFO]::MAIN: Starting manual run for SickBeard:tv - Folder: /storage/downloads/complete/tv/******
[15:21:52] [INFO]::MAIN: Checking database for download info for ****** ...
[15:21:52] [DB]::DB: Getting download info for ****** from the DB
[15:21:52] [DB]::MAIN: nzbtomedia.db: SELECT * FROM downloads WHERE input_name=? AND status=? with args [u'******', 0]
[15:21:52] [INFO]::MAIN: Unable to locate download info for ******, continuing to try and process this release ...
[15:21:52] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[15:21:52] [DEBUG]::MAIN: Checking for archives to extract in directory: /storage/downloads/complete/tv/******
[15:21:52] [INFO]::MAIN: Calling SickBeard:tv to post-process:******
[15:21:52] [DEBUG]::SERVER: Attempting to connect to server at https://sickgear:8081/sickgear
[15:21:52] [DEBUG]::SERVER: Server responded at https://sickgear:8081/sickgear
[15:21:52] [INFO]::MAIN: SickBeard:tv fork set to SickGear
[15:21:52] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /nzbToMedia/tests/test.mp4
[15:21:52] [INFO]::TRANSCODER: Checking [******.mkv] for corruption, please stand by ...
[15:21:52] [DEBUG]::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /storage/downloads/complete/tv/******/******.mkv
[15:21:52] [INFO]::TRANSCODER: SUCCESS: [******.mkv] has no corruption.
[15:21:52] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[15:21:52] [DEBUG]::SICKBEARD: Opening URL: https://sickgear:8081/sickgear/api/******/ with params: {u'nzbName': u'******', u'cmd': u'sg.postprocess', u'quiet': 1, u'failed': 0, u'dir': u'/storage/downloads/complete/tv/******'}
[15:22:18] [ERROR]::MAIN: A problem was reported when trying to perform a manual run for SickBeard:tv.
[15:22:18] [INFO]::MAIN: Starting manual run for SickBeard:tv - Folder: /storage/downloads/complete/tv/******
[15:22:18] [INFO]::MAIN: Checking database for download info for ****** ...
[15:22:18] [DB]::DB: Getting download info for ****** from the DB
[15:22:18] [DB]::MAIN: nzbtomedia.db: SELECT * FROM downloads WHERE input_name=? AND status=? with args [u'******', 0]
[15:22:18] [INFO]::MAIN: Found download info for ******, setting variables now ...
Traceback (most recent call last):
  File "./nzbToSickBeard.py", line 273, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/nzbToMedia/nzbToMedia.py", line 1019, in main
    client_agent = text_type(core.DOWNLOAD_INFO[0].get('client_agent', 'manual'))
AttributeError: 'Row' object has no attribute 'get'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <core.utils.processes.PosixProcess object at 0x7f4550458510>> ignored


It then generates this in SickGear: 2020-04-21 15:22:18 TORNADO :: API (sabnzbd):: 'NoneType' object has no attribute 'get'
```

**Comment by boredazfcuk** [comment]
So, turns out my ffmpeg path was somehow set to `/usr/local/bin/ffmpeg/usr/local/bin/ffmpeg`

Corrected it and all is good
