### ISSUE TITLE
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

### ISSUE THREAD

**Issue by slayerXcore** [clinton-hall/nzbToMedia#1747]
**Describe the bug**
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

**Technical Specs**
1. Running on Windows 10 1909
2. Python version 3.7
3. Download Client SABnbzd
4. Intended Media Management SickRage

**Expected behavior**
post processing to succeed 
**Log**
Please provide an extract, or full debug log that indicates the issue.
nzbToMedia log
2020-05-09 03:06:44 INFO    ::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
2020-05-09 03:06:44 INFO    ::MAIN: Python v3.7 will reach end of life in 1144 days.
2020-05-09 03:06:44 INFO    ::MAIN: Checking database structure...
2020-05-09 03:06:44 INFO    ::MAIN: Checking if git needs an update
2020-05-09 03:06:45 INFO    ::MAIN: No update needed
2020-05-09 03:06:45 INFO    ::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
2020-05-09 03:06:45 WARNING ::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
2020-05-09 03:06:45 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2020-05-09 03:06:45 INFO    ::MAIN: #########################################################
2020-05-09 03:06:45 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2020-05-09 03:06:45 INFO    ::MAIN: #########################################################
2020-05-09 03:06:45 INFO    ::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
2020-05-09 03:06:45 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2020-05-09 03:06:45 INFO    ::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 iNTERNAL 720p WEB h264-HILLARY
2020-05-09 03:06:45 INFO    ::MAIN: SickBeard:tv fork set to SickRage
2020-05-09 03:06:45 INFO    ::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 iNTERNAL 720p WEB h264-HILLARY.12
2020-05-09 03:06:45 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2020-05-09 03:06:45 ERROR   ::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.

Sab log from GUI 
[03:06:44] [INFO]::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
[03:06:44] [INFO]::MAIN: Python v3.7 will reach end of life in 1144 days.
[03:06:44] [INFO]::MAIN: Checking database structure...
[03:06:44] [INFO]::MAIN: Checking if git needs an update
[03:06:45] [INFO]::MAIN: No update needed
[03:06:45] [INFO]::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
[03:06:45] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[03:06:45] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[03:06:45] [INFO]::MAIN: #########################################################
[03:06:45] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[03:06:45] [INFO]::MAIN: #########################################################
[03:06:45] [INFO]::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
[03:06:45] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[03:06:45] [INFO]::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 iNTERNAL 720p WEB h264-HILLARY
[03:06:45] [INFO]::MAIN: SickBeard:tv fork set to SickRage
[03:06:45] [INFO]::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 iNTERNAL 720p WEB h264-HILLARY.12
[03:06:45] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[03:06:45] [ERROR]::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.
Changing to directory: C:\PythonApps\Sab-Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  C:\Program Files\SABnzbd

-- Cleanup finished --

SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

**Comment by clinton-hall** [comment]
Try connecting to SickRage using api, and use auto-fork

so in autoProcessMedia.cfg
```
[SickBeard]
    [[tv]]
        apikey = [enter your SickRage api key here]
        fork = auto
```

**Comment by slayerXcore** [comment]
currently I have

I am running an ssl cert from cacert.org

`[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = mydomain.**
        port = 8081
        apikey = ********************************
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 1
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        keep_archive = 1
        process_method = move
        # force processing of already processed content when running a manual scan.
        force = 0
        # tell SickRage/Medusa to delete all source files after processing.
        delete_on = 0
        # tell Medusa to ignore check for associated subtitle check when postponing release
        ignore_subs = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleting ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = D:\TV_DL
        ##### Set the recursive directory permissions to the following (0 to disable)
        chmodDirectory = 0`

**Comment by slayerXcore** [comment]
the problem with auto is fork auto-detection fails

[01:54:27] [INFO]::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
[01:54:27] [INFO]::MAIN: Python v3.7 will reach end of life in 1143 days.
[01:54:27] [INFO]::MAIN: Checking database structure...
[01:54:27] [INFO]::MAIN: Checking if git needs an update
[01:54:28] [INFO]::MAIN: No update needed
[01:54:28] [INFO]::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
[01:54:28] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[01:54:28] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[01:54:28] [INFO]::MAIN: #########################################################
[01:54:28] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[01:54:28] [INFO]::MAIN: #########################################################
[01:54:28] [INFO]::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
[01:54:28] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[01:54:28] [INFO]::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
[01:54:28] [INFO]::MAIN: Attempting to auto-detect tv fork
[01:54:28] [INFO]::MAIN: SickBeard:tv fork auto-detection failed
[01:54:28] [INFO]::MAIN: SickBeard:tv fork set to default
[01:54:28] [INFO]::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
[01:54:28] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[01:54:28] [ERROR]::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.
Changing to directory: C:\PythonApps\Sab-Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  C:\Program Files\SABnzbd

-- Cleanup finished --

SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

**Comment by slayerXcore** [comment]
sickrage debug level log 
2020-05-10 02:23:59 DEBUG::API::postprocess: current params {'proc_dir': 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.1', 'failed': '0', 'process_method': 'move', 'quiet': '1', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost'}
2020-05-10 02:23:59 DEBUG::API::all params: '{'proc_dir': 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.1', 'failed': '0', 'process_method': 'move', 'quiet': '1', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', 'cmd': 'postprocess'}'
2020-05-10 02:23:59 DEBUG::API::IP:127.0.0.1 - ACCESS GRANTED

**Comment by clinton-hall** [comment]
can you enable debug logginf in nzbToMedia?
```
[General]
    log_debug = 1
```
the logs should then give more details to indicate why auto fork isn't working.
Last time I checked it was working for SickRage...

**Comment by slayerXcore** [comment]
sab log

[03:17:47] [INFO]::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
[03:17:47] [INFO]::MAIN: Python v3.7 will reach end of life in 1143 days.
[03:17:47] [INFO]::MAIN: Checking database structure...
[03:17:47] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[03:17:47] [DEBUG]::MAIN: InitialSchema upgrade not required
[03:17:47] [DEBUG]::MAIN: Checking if we can use git commands: git version
[03:17:47] [DEBUG]::MAIN: Executing git version with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git version : returned successful
[03:17:47] [DEBUG]::MAIN: Using: git
[03:17:47] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[03:17:47] [INFO]::MAIN: Checking if git needs an update
[03:17:47] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[03:17:47] [DEBUG]::MAIN: Executing git fetch origin with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:48] [DEBUG]::MAIN: git fetch origin : returned successful
[03:17:48] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:48] [DEBUG]::MAIN: git didn't return newest commit hash
[03:17:48] [INFO]::MAIN: No update needed
[03:17:48] [INFO]::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
[03:17:48] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[03:17:48] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[03:17:48] [INFO]::MAIN: #########################################################
[03:17:48] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[03:17:48] [INFO]::MAIN: #########################################################
[03:17:48] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\PythonApps\\Sab-Scripts\\nzbToMedia\\nzbToMedia.py', 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'Station.19.S03E15.SUBFRENCH.720p.WEB.H264-CiELOS-xpost.nzb', 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', '', 'tv', 'alt.binaries.wtfnzb.kilo', '0', '']
[03:17:48] [INFO]::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
[03:17:48] [DEBUG]::MAIN: Adding NZB download info for directory D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5 to database
[03:17:48] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[03:17:48] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:48] [INFO]::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
[03:17:48] [DEBUG]::SERVER: Attempting to connect to server at https://r.slayerxcore.co:8081
[03:17:49] [DEBUG]::SERVER: Server responded at https://r.slayerxcore.co:8081
[03:17:49] [INFO]::MAIN: Attempting to auto-detect tv fork
[03:17:50] [INFO]::MAIN: SickBeard:tv fork auto-detection failed
[03:17:50] [INFO]::MAIN: SickBeard:tv fork set to default
[03:17:50] [INFO]::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:50] [DEBUG]::MAIN: Checking for empty folders in:D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:50] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[03:17:50] [DEBUG]::SICKBEARD: Opening URL: https://r.slayerxcore.co:8081/api/c156f18eb7da91be709938ddce53c035/ with params: {'dir': 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'quiet': 1, 'proc_type': 'manual', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', 'cmd': 'postprocess'}
[03:17:50] [ERROR]::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.
Changing to directory: C:\PythonApps\Sab-Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  C:\Program Files\SABnzbd

-- Cleanup finished --

SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

nzbtomedia.log

2020-05-10 03:17:47 INFO    ::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
2020-05-10 03:17:47 INFO    ::MAIN: Python v3.7 will reach end of life in 1143 days.
2020-05-10 03:17:47 INFO    ::MAIN: Checking database structure...
2020-05-10 03:17:47 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2020-05-10 03:17:47 DEBUG   ::MAIN: InitialSchema upgrade not required
2020-05-10 03:17:47 DEBUG   ::MAIN: Checking if we can use git commands: git version
2020-05-10 03:17:47 DEBUG   ::MAIN: Executing git version with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG   ::MAIN: git version : returned successful
2020-05-10 03:17:47 DEBUG   ::MAIN: Using: git
2020-05-10 03:17:47 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
2020-05-10 03:17:47 INFO    ::MAIN: Checking if git needs an update
2020-05-10 03:17:47 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2020-05-10 03:17:47 DEBUG   ::MAIN: Executing git fetch origin with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:48 DEBUG   ::MAIN: git fetch origin : returned successful
2020-05-10 03:17:48 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:48 DEBUG   ::MAIN: git didn't return newest commit hash
2020-05-10 03:17:48 INFO    ::MAIN: No update needed
2020-05-10 03:17:48 INFO    ::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
2020-05-10 03:17:48 WARNING ::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
2020-05-10 03:17:48 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature  ...
2020-05-10 03:17:48 INFO    ::MAIN: #########################################################
2020-05-10 03:17:48 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2020-05-10 03:17:48 INFO    ::MAIN: #########################################################
2020-05-10 03:17:48 DEBUG   ::MAIN: Options passed into nzbToMedia: ['C:\\PythonApps\\Sab-Scripts\\nzbToMedia\\nzbToMedia.py', 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'Station.19.S03E15.SUBFRENCH.720p.WEB.H264-CiELOS-xpost.nzb', 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', '', 'tv', 'alt.binaries.wtfnzb.kilo', '0', '']
2020-05-10 03:17:48 INFO    ::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
2020-05-10 03:17:48 DEBUG   ::MAIN: Adding NZB download info for directory D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5 to database
2020-05-10 03:17:48 INFO    ::MAIN: Auto-detected SECTION:SickBeard
2020-05-10 03:17:48 DEBUG   ::MAIN: Checking for archives to extract in directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:48 INFO    ::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
2020-05-10 03:17:48 DEBUG   ::SERVER: Attempting to connect to server at https://r.slayerxcore.co:8081
2020-05-10 03:17:49 DEBUG   ::SERVER: Server responded at https://r.slayerxcore.co:8081
2020-05-10 03:17:49 INFO    ::MAIN: Attempting to auto-detect tv fork
2020-05-10 03:17:50 INFO    ::MAIN: SickBeard:tv fork auto-detection failed
2020-05-10 03:17:50 INFO    ::MAIN: SickBeard:tv fork set to default
2020-05-10 03:17:50 INFO    ::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:50 DEBUG   ::MAIN: Checking for empty folders in:D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:50 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2020-05-10 03:17:50 DEBUG   ::SICKBEARD: Opening URL: https://r.slayerxcore.co:8081/api/c156f18eb7da91be709938ddce53c035/ with params: {'dir': 'D:\\TV_DL\\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'quiet': 1, 'proc_type': 'manual', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', 'cmd': 'postprocess'}
2020-05-10 03:17:50 ERROR   ::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.

**Comment by slayerXcore** [comment]
sab log

[03:17:47] [INFO]::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
[03:17:47] [INFO]::MAIN: Python v3.7 will reach end of life in 1143 days.
[03:17:47] [INFO]::MAIN: Checking database structure...
[03:17:47] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[03:17:47] [DEBUG]::MAIN: InitialSchema upgrade not required
[03:17:47] [DEBUG]::MAIN: Checking if we can use git commands: git version
[03:17:47] [DEBUG]::MAIN: Executing git version with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git version : returned successful
[03:17:47] [DEBUG]::MAIN: Using: git
[03:17:47] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[03:17:47] [INFO]::MAIN: Checking if git needs an update
[03:17:47] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:47] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[03:17:47] [DEBUG]::MAIN: Executing git fetch origin with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:48] [DEBUG]::MAIN: git fetch origin : returned successful
[03:17:48] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
[03:17:48] [DEBUG]::MAIN: git didn't return newest commit hash
[03:17:48] [INFO]::MAIN: No update needed
[03:17:48] [INFO]::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
[03:17:48] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[03:17:48] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
[03:17:48] [INFO]::MAIN: #########################################################
[03:17:48] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[03:17:48] [INFO]::MAIN: #########################################################
[03:17:48] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py', 'D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'Station.19.S03E15.SUBFRENCH.720p.WEB.H264-CiELOS-xpost.nzb', 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', '', 'tv', 'alt.binaries.wtfnzb.kilo', '0', '']
[03:17:48] [INFO]::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
[03:17:48] [DEBUG]::MAIN: Adding NZB download info for directory D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5 to database
[03:17:48] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[03:17:48] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:48] [INFO]::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
[03:17:48] [DEBUG]::SERVER: Attempting to connect to server at https://mydomain.**:8081
[03:17:49] [DEBUG]::SERVER: Server responded at https://mydomain.**:8081
[03:17:49] [INFO]::MAIN: Attempting to auto-detect tv fork
[03:17:50] [INFO]::MAIN: SickBeard:tv fork auto-detection failed
[03:17:50] [INFO]::MAIN: SickBeard:tv fork set to default
[03:17:50] [INFO]::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:50] [DEBUG]::MAIN: Checking for empty folders in:D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
[03:17:50] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[03:17:50] [DEBUG]::SICKBEARD: Opening URL: https://mydomain.**:8081/api/********************************/ with params: {'dir': 'D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'quiet': 1, 'proc_type': 'manual', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', 'cmd': 'postprocess'}
[03:17:50] [ERROR]::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.
Changing to directory: C:\PythonApps\Sab-Scripts\nzbToMedia

-- Cleaning bytecode --
b'Removing pycache/\n'
b'Removing pycache/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory: C:\Program Files\SABnzbd

-- Cleanup finished --

SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!

nzbtomedia.log

2020-05-10 03:17:47 INFO ::MAIN: Loading config from [C:\PythonApps\Sab-Scripts\nzbToMedia\autoProcessMedia.cfg]
2020-05-10 03:17:47 INFO ::MAIN: Python v3.7 will reach end of life in 1143 days.
2020-05-10 03:17:47 INFO ::MAIN: Checking database structure...
2020-05-10 03:17:47 DEBUG ::MAIN: Checking Initial Schema database upgrade
2020-05-10 03:17:47 DEBUG ::MAIN: InitialSchema upgrade not required
2020-05-10 03:17:47 DEBUG ::MAIN: Checking if we can use git commands: git version
2020-05-10 03:17:47 DEBUG ::MAIN: Executing git version with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG ::MAIN: git version : returned successful
2020-05-10 03:17:47 DEBUG ::MAIN: Using: git
2020-05-10 03:17:47 DEBUG ::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG ::MAIN: git symbolic-ref -q HEAD : returned successful
2020-05-10 03:17:47 INFO ::MAIN: Checking if git needs an update
2020-05-10 03:17:47 DEBUG ::MAIN: Executing git rev-parse HEAD with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:47 DEBUG ::MAIN: git rev-parse HEAD : returned successful
2020-05-10 03:17:47 DEBUG ::MAIN: Executing git fetch origin with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:48 DEBUG ::MAIN: git fetch origin : returned successful
2020-05-10 03:17:48 DEBUG ::MAIN: Executing git rev-parse --verify --quiet '@{upstream}' with your shell in C:\PythonApps\Sab-Scripts\nzbToMedia
2020-05-10 03:17:48 DEBUG ::MAIN: git didn't return newest commit hash
2020-05-10 03:17:48 INFO ::MAIN: No update needed
2020-05-10 03:17:48 INFO ::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Windows 10)
2020-05-10 03:17:48 WARNING ::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
2020-05-10 03:17:48 WARNING ::MAIN: Install ffmpeg with x264 support to enable this feature ...
2020-05-10 03:17:48 INFO ::MAIN: #########################################################
2020-05-10 03:17:48 INFO ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2020-05-10 03:17:48 INFO ::MAIN: #########################################################
2020-05-10 03:17:48 DEBUG ::MAIN: Options passed into nzbToMedia: ['C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py', 'D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'Station.19.S03E15.SUBFRENCH.720p.WEB.H264-CiELOS-xpost.nzb', 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', '', 'tv', 'alt.binaries.wtfnzb.kilo', '0', '']
2020-05-10 03:17:48 INFO ::MAIN: Script triggered from SABnzbd Version 3.0.0Alpha2.
2020-05-10 03:17:48 DEBUG ::MAIN: Adding NZB download info for directory D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5 to database
2020-05-10 03:17:48 INFO ::MAIN: Auto-detected SECTION:SickBeard
2020-05-10 03:17:48 DEBUG ::MAIN: Checking for archives to extract in directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:48 INFO ::MAIN: Calling SickBeard:tv to post-process:Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost
2020-05-10 03:17:48 DEBUG ::SERVER: Attempting to connect to server at https://r.slayerxcore.co:8081
2020-05-10 03:17:49 DEBUG ::SERVER: Server responded at https://mydomain.**:8081
2020-05-10 03:17:49 INFO ::MAIN: Attempting to auto-detect tv fork
2020-05-10 03:17:50 INFO ::MAIN: SickBeard:tv fork auto-detection failed
2020-05-10 03:17:50 INFO ::MAIN: SickBeard:tv fork set to default
2020-05-10 03:17:50 INFO ::MAIN: FLATTEN: Flattening directory: D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:50 DEBUG ::MAIN: Checking for empty folders in:D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5
2020-05-10 03:17:50 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2020-05-10 03:17:50 DEBUG ::SICKBEARD: Opening URL: https://mydomain.**:8081/api/********************************/ with params: {'dir': 'D:\TV_DL\Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost.5', 'quiet': 1, 'proc_type': 'manual', 'nzbName': 'Station 19 S03E15 SUBFRENCH 720p WEB H264-CiELOS-xpost', 'cmd': 'postprocess'}
2020-05-10 03:17:50 ERROR ::MAIN: A problem was reported in the C:\PythonApps\Sab-Scripts\nzbToMedia\nzbToMedia.py script.

**Comment by clinton-hall** [comment]
What happens when you go to this url from the system that is running?
https://mydomain.**:8081/api/********************************/?cmd=help&subject=postprocess

Also, any reason you use `host = mydomain.**` instead of just using `host = localhost`?

**Comment by slayerXcore** [comment]
browser displays 

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\tornado\web.py", line 1682, in _execute
    result = await result
  File "C:\PythonApps\SickRage\sickrage\core\webserver\handlers\api.py", line 132, in prepare
    if 'outputType' in out_dict:
TypeError: argument of type 'coroutine' is not iterable

**Comment by slayerXcore** [comment]
using dns name due to ssl certificate

**Comment by clinton-hall** [comment]
ok... so SickRage is failing to process the api request... do any api commands work? is it possible to generate an api help call?

**Comment by slayerXcore** [comment]
I'm not familiar with the sickrage/sickbeard api. I've been using them for about a decade without any issues and your script for something like 5 years. could switching to python 3 be whats breaking things? I have removed python2 from my system path in hopes to fix this but no luck. I am even running the alpha 2 of sab3 which uses python3 to try and see what fixes things. everything is the latest version and I am out of ideas hence asking here thinking it was a possibly script broken
