### ISSUE TITLE
Problem with python 3.8 sabnzbd 3.0 and nzbtomedia

### ISSUE THREAD

**Issue by tixetsal** [clinton-hall/nzbToMedia#1766]
**Describe the bug**
I am receiving this error message in sabnzbd, instead of media being properly processed by Sonarr and Radarr:

Traceback (most recent call last):
File "/var/lib/sabnzbd/scripts/nzbToMedia/nzbToRadarr.py", line 264, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/var/lib/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 966, in main
result = process(os.environ['SAB_COMPLETE_DIR'], input_name=os.environ['SAB_FINAL_NAME'], status=int(os.environ['SAB_PP_STATUS']),
File "/var/lib/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 851, in process
result = movies.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/var/lib/sabnzbd/scripts/nzbToMedia/core/auto_process/movies.py", line 253, in process
logger.postprocess('Radarr response: {0}'.format(result['state']))
TypeError: list indices must be integers or slices, not str

I am on all the latest packages in Arch Linux, this is python 3.8, sabnzbd and Sonarr/Radarr

I have tried the nightly branch and still experience this. I am also experiencing a cheroot bug that was recently introduced, but I don't know if it's impacting this issue or not.  IT causes this output in sabnzbd, but the program does not crash:

[16/Aug/2020:19:44:27] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 1795, in serve
    self.tick()
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 2030, in tick
    self.connections.expire()
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 107, in expire
    for sock_fd, conn in timed_out_connections:
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 102, in <genexpr>
    timed_out_connections = (
  File "/usr/lib/python3.8/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: dictionary changed size during iteration

Am I doing something wrong? Thanks as always for your help.

**Comment by clinton-hall** [comment]
Have you ever had this configuration working or is this a new install? 

I can't see if the cheroot issues are in anyway connected as I can't see the timing or sequence of events that lead to it...

As far as the nzbToMedia error, it looks as though Radarr is not providing the response we would expect to see... which could be a config error, or a change over at Radarr...

What was logged immediately prior to the error? 
With debug logging I would have expected to see `Opening URL: http://locahost:XXXX//api/command with PARAMS: XXXXXX`

**Comment by tixetsal** [comment]
Hi. It was working at one point, yes. This is running on an Arch server that I've been using for many years. *BUT* I've recently had problems with sabnzbd (including the cheroot bug) so I have recently reinstalled sabnzbd, which kicked off a csacade effect due to it generating new APIs. 

I had seemingly resolved all of the api mismatches and everything was running well until a cheroot update introduced the error messages from sabnzbd where i had to disable pushover notifications (the bug is being addressed) and then I noticed that nzbtomedia was erroring-out vs sorting my new downloads. Here is the full log:

`2020-08-16` 19:08:02 INFO    ::MAIN: Checking database structure...
2020-08-16 19:08:02 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2020-08-16 19:08:02 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2020-08-16 19:08:02 DB      ::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
2020-08-16 19:08:02 DEBUG   ::MAIN: InitialSchema upgrade not required
2020-08-16 19:08:02 DEBUG   ::MAIN: Checking if we can use git commands: "/usr/bin/git" version
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" version with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: git version 2.28.0
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" version : returned successful
2020-08-16 19:08:02 DEBUG   ::MAIN: Using: "/usr/bin/git"
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" symbolic-ref -q HEAD with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: refs/heads/master
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" symbolic-ref -q HEAD : returned successful
2020-08-16 19:08:02 INFO    ::MAIN: Checking if git needs an update
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" rev-parse HEAD with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: f5e4ec0981ab2f6fd97b14b24aa363a393396073
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" rev-parse HEAD : returned successful
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" fetch origin with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: 
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" fetch origin : returned successful
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: f5e4ec0981ab2f6fd97b14b24aa363a393396073
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
2020-08-16 19:08:02 DEBUG   ::MAIN: Executing "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /var/lib/sabnzbd/scripts/nzbToMedia
2020-08-16 19:08:02 DEBUG   ::MAIN: git output: 
2020-08-16 19:08:02 DEBUG   ::MAIN: "/usr/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
2020-08-16 19:08:02 DEBUG   ::MAIN: cur_commit = f5e4ec0981ab2f6fd97b14b24aa363a393396073 % (newest_commit)= f5e4ec0981ab2f6fd97b14b24aa363a393396073, num_commits_behind = 0, num_commits_ahead = 0
2020-08-16 19:08:02 INFO    ::MAIN: No update needed
2020-08-16 19:08:02 INFO    ::MAIN: nzbToMedia Version:f5e4ec0981ab2f6fd97b14b24aa363a393396073 Branch:master (Linux 5.8.1-arch1-1)
2020-08-16 19:08:02 INFO    ::MAIN: #########################################################
2020-08-16 19:08:02 INFO    ::MAIN: ## ..::[nzbToMedia.py]::.. ##
2020-08-16 19:08:02 INFO    ::MAIN: #########################################################
2020-08-16 19:08:02 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/var/lib/sabnzbd/scripts/nzbToMedia/nzbToNzbDrone.py', '/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2', 'The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264
-KiNGS.nzb', 'The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS', '', 'tv', 'alt.binaries.tv', '0', '']
2020-08-16 19:08:02 INFO    ::MAIN: Script triggered from SABnzbd Version 3.0.0.
2020-08-16 19:08:02 DEBUG   ::MAIN: Adding NZB download info for directory /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2 to database
2020-08-16 19:08:02 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET input_name = ?, input_hash = ?, input_id = ?, client_agent = ?, status = ?, last_update = ? WHERE input_directory = ? with args ['The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS', 'SA
Bnzbd_nzo_bfdc8eom', 'SABnzbd_nzo_bfdc8eom', 'sabnzbd', 0, 737653, '/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2']
2020-08-16 19:08:02 DB      ::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (input_name, input_hash, input_id, client_agent, status, last_update) VALUES (?, ?, ?, ?, ?, ?) with args ['The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS', 'SABnzbd_nzo_b
fdc8eom', 'SABnzbd_nzo_bfdc8eom', 'sabnzbd', 0, 737653]
2020-08-16 19:08:02 INFO    ::MAIN: Auto-detected SECTION:NzbDrone
2020-08-16 19:08:02 DEBUG   ::MAIN: Checking for archives to extract in directory: /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:02 INFO    ::MAIN: Extracting /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2/160912_04.part12.rar to /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:02 DEBUG   ::MAIN: Extracting ['unrar', 'x', '-o+', '-y'] /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2/160912_04.part12.rar /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-
KiNGS.2
2020-08-16 19:08:06 INFO    ::MAIN: EXTRACTOR: Extraction was successful for /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2/160912_04.part12.rar to /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H
.264-KiNGS.2
2020-08-16 19:08:09 INFO    ::MAIN: Removing extracted archive 160912_04.part12.rar from folder /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2 ...
<snip>
2020-08-16 19:08:48 INFO    ::MAIN: Removing extracted archive 160912_04.part19.rar from folder /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2 ...
2020-08-16 19:08:49 INFO    ::MAIN: Calling NzbDrone:tv to post-process:The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS
2020-08-16 19:08:49 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:8081
2020-08-16 19:08:49 DEBUG   ::SERVER: Server responded at http://localhost:8081
2020-08-16 19:08:49 INFO    ::MAIN: Attempting to verify tv fork
2020-08-16 19:08:49 INFO    ::MAIN: NzbDrone:tv fork set to default
2020-08-16 19:08:49 INFO    ::MAIN: FLATTEN: Flattening directory: /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:49 DEBUG   ::MAIN: Checking for empty folders in:/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:49 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /var/lib/sabnzbd/scripts/nzbToMedia/tests/test.mp4
2020-08-16 19:08:49 INFO    ::TRANSCODER: Checking [160912_04.mkv] for corruption, please stand by ...
2020-08-16 19:08:49 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2/160912_04.mkv
2020-08-16 19:08:49 INFO    ::TRANSCODER: SUCCESS: [160912_04.mkv] has no corruption.
2020-08-16 19:08:49 INFO    ::MAIN: Checking for files to be transcoded
2020-08-16 19:08:49 DEBUG   ::NZBDRONE: SUCCESS: Transcoding succeeded for files in /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:49 DEBUG   ::NZBDRONE: Config setting 'chmodDirectory' currently set to 0o0
2020-08-16 19:08:49 POSTPROCESS::NZBDRONE: SUCCESS: The download succeeded, sending a post-process request
2020-08-16 19:08:49 DEBUG   ::NZBDRONE: path: /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2
2020-08-16 19:08:49 DEBUG   ::NZBDRONE: Opening URL: http://localhost:8081/api/command with data: {"name": "DownloadedEpisodesScan", "path": "/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2", "downloadClientId": "SABnzbd_nzo_bfdc8eom", "importMode": "Copy"}
2020-08-16 19:08:49 WARNING ::NZBDRONE: No scan id was returned due to: list indices must be integers or slices, not str
2020-08-16 19:08:49 ERROR   ::MAIN: A problem was reported in the /var/lib/sabnzbd/scripts/nzbToMedia/nzbToNzbDrone.py script.``

**Comment by clinton-hall** [comment]
what happens if you go to the following page
`http://localhost:8081/api/command?name=DownloadedEpisodesScan&path=/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2&downloadClientId=SABnzbd_nzo_bfdc8eom&importMode=Copy`

This should return json data. please post the output here.

**Comment by tixetsal** [comment]
This is the output:
`{
  "error": "Unauthorized"
}`

**Comment by clinton-hall** [comment]
Ah, sorry the logging doesn't capture the apikey

Please try again using the Sonarr API key in the following:

`http://localhost:8081/api/command?apikey=<apikey here>&name=DownloadedEpisodesScan&path=/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.2&downloadClientId=SABnzbd_nzo_bfdc8eom&importMode=Copy`

**Comment by tixetsal** [comment]
That's OK. I should have been able to figure out what was missing. It *did* encourage me to go back and look at my config files again and verify apis and credentials one more time. I didn't find anything new.

So with api in the call, I am just returned:

`[]`

**Comment by clinton-hall** [comment]
very strange.... The script expects to get a return that provides a job id and status...
So it could be that something has changed in Sonarr...
I'll try and have a play.

Are there any entries into Sonar logs when you enter that url?

**Comment by tixetsal** [comment]
It's odd that both Sonarr and Radarr are impacted. I'm running both from AUR.

I checked Sonarr logs, and it's not being logged when I enter the URL. I am happy to try anything else.

**Comment by clinton-hall** [comment]
Can you switch nzbToMedia to `Radarr-return` branch?
I have just changed the logging to show what data was returned from the post so that we can hopefully catch what is causing the issue.

Please try a download from sabnzbd and send through the nzbToMedia debug logging.

**Comment by tixetsal** [comment]
I switched branches, but the only output logged was what we'd seen before:

`2020-08-18 16:52:27 INFO    ::MAIN: Calling NzbDrone:tv to post-process:The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT
2020-08-18 16:52:27 DEBUG   ::SERVER: Attempting to connect to server at http://localhost:8081
2020-08-18 16:52:27 DEBUG   ::SERVER: Server responded at http://localhost:8081
2020-08-18 16:52:27 INFO    ::MAIN: Attempting to verify tv fork
2020-08-18 16:52:27 INFO    ::MAIN: NzbDrone:tv fork set to default
2020-08-18 16:52:27 INFO    ::MAIN: FLATTEN: Flattening directory: /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT
2020-08-18 16:52:27 DEBUG   ::MAIN: Checking for empty folders in:/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT
2020-08-18 16:52:27 DEBUG   ::MAIN: Checking for empty folders in:/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/Sample
2020-08-18 16:52:27 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /var/lib/sabnzbd/scripts/nzbToMedia/tests/test.mp4
2020-08-18 16:52:27 INFO    ::TRANSCODER: Checking [The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT.mkv] for corruption, please stand by ...
2020-08-18 16:52:27 DEBUG   ::MAIN: calling command: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -show_error /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT.mkv
2020-08-18 16:52:27 INFO    ::TRANSCODER: SUCCESS: [The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT.mkv] has no corruption.
2020-08-18 16:52:27 INFO    ::MAIN: Checking for files to be transcoded
2020-08-18 16:52:27 DEBUG   ::NZBDRONE: SUCCESS: Transcoding succeeded for files in /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT
2020-08-18 16:52:27 DEBUG   ::NZBDRONE: Config setting 'chmodDirectory' currently set to 0o0
2020-08-18 16:52:27 POSTPROCESS::NZBDRONE: SUCCESS: The download succeeded, sending a post-process request
2020-08-18 16:52:27 DEBUG   ::NZBDRONE: path: /mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT
2020-08-18 16:52:27 DEBUG   ::NZBDRONE: Opening URL: http://localhost:8081/api/command with data: {"name": "DownloadedEpisodesScan", "path": "/mnt/nvme/downloads/complete/tv/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT/The.Exorcist.S01E01.GERMAN.DL.1080p.WEB.H264-FENDT", "downloadClientId": "SABnzbd_nzo_9wy5ledy", "importMode": "Copy"}
2020-08-18 16:52:27 POSTPROCESS::POSTPROCESS: Sonarr response: []
2020-08-18 16:52:27 WARNING ::NZBDRONE: No scan id was returned due to: list indices must be integers or slices, not str
2020-08-18 16:52:27 ERROR   ::MAIN: A problem was reported in the /var/lib/sabnzbd/scripts/nzbToMedia/nzbToMedia.py script.`

What shall we try next? There was an update to sabnzbd in the AUR today, but it didn't have any impact on this situation. 

Should I reinstall Sonarr for good measure?

**Comment by clinton-hall** [comment]
There was a difference in the logging:
`POSTPROCESS::POSTPROCESS: Sonarr response: []`

This shows that (just as you found when you hit that url in the browser) that Sonarr is NOT returning any data when the command is posted.

According to Sonarr documentation, the command api is supposed to return data:
https://github.com/Sonarr/Sonarr/wiki/Command

https://github.com/Sonarr/Sonarr/wiki/Command#returns-1

So what we need to do here is confirm if in-fact Sonarr is renaming the episode... In many cases, where the import mode is move, we could just check that the original file is no longer in the download directory. But as you are using copy, it is very difficult for nzbToMedia to know what Sonarr is finished if Sonarr doesn't tell us!

I think it is time to ask over at Sonarr.

**Comment by clinton-hall** [comment]
Can you please check the Sonarr debug or trace logs at `2020-08-18 16:52:27`
there should be any entry similar to `20-8-18 16:52:27.8|Debug|Api|[GET] /api/v3/command: 200.OK (4 ms)`

Also, please confirm the Sonarr version number.

Based on feedback from Sonarr, it sounds like the behaviour we would expect to see if the URL base is set in Sonarr, but not in nzbToMedia. Can you please verify if you are using a URL base?

If you are using this, you will need to put that into autoProcessMedia.cfg
```
[NzbDrone]
    [[tv]]
        web_root =<Sonarr URL base>
```

**Comment by tixetsal** [comment]
I must have copied an old .cfg file over the one with the proper web root defined. This is all on me. 

Thanks so much for your time and help, and everything is working as expected now.

**Comment by clinton-hall** [comment]
All good. I hadn't even considered this originally as I had thought api issues would give an "Unathorised" and URL base/web root would give a page not found or similar.... I never anticipated the re-direction. so good to know for future.

Glad it is all working for you now.
