### ISSUE TITLE
issues after update dsm

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1785]
**Describe the bug**
script not working as expected

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '...syno lates dsm 6.2.3.'
2. Python version '...3.7.'
3. Download Client (NZBget, SABnbzd, Transmission) '.sabnzbd...'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '..sonarr and headphones..'

**Expected behavior**
not updating nzbtomedia and a pp error with headphones
**Log**
Please provide an extract, or full debug log that indicates the issue.
Sonarr/nzbtomedia error?
`fatal: not a git repository (or any parent up to mount point /volume1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[11:27:08] [INFO]::MAIN: Loading config from [/volume1/scripts/nzbToMedia-master/nzbToMedia-master/autoProcessMedia.cfg]
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_DSM_LANGUAGE: def
[11:27:08] [INFO]::ENVIRONMENT: TERM: vt102
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_TEMP_LOGFILE: /tmp/synopkgmgr.log-sabnzbd
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_DSM_ARCH: broadwell
[11:27:08] [INFO]::ENVIRONMENT: NAME: python3
[11:27:08] [INFO]::ENVIRONMENT: PATH: /volume1/@appstore/sabnzbd/bin:/volume1/@appstore/sabnzbd/env/bin:/usr/local/python3/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
[11:27:08] [INFO]::ENVIRONMENT: SELF: sabnzbd
[11:27:08] [INFO]::ENVIRONMENT: PWD: /
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_PKGDEST: /volume1/@appstore/sabnzbd
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_PKGVER: 3.0.2-43
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_DSM_VERSION_MINOR: 2
[11:27:08] [INFO]::ENVIRONMENT: SHLVL: 2
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_DSM_VERSION_BUILD: 25426
[11:27:08] [INFO]::ENVIRONMENT: UPSTART_INSTANCE:
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_PKGNAME: sabnzbd
[11:27:08] [INFO]::ENVIRONMENT: UPSTART_EVENTS: syno.pkgctl.pkgstart syno.pkgctl.started
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_DSM_VERSION_MAJOR: 6
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_PKGDEST_VOL: /volume1
[11:27:08] [INFO]::ENVIRONMENT: UPSTART_JOB: pkgctl-sabnzbd
[11:27:08] [INFO]::ENVIRONMENT: SYNOPKG_PKGPORT: 8080
[11:27:08] [INFO]::ENVIRONMENT: _: /bin/env
[11:27:08] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[11:27:08] [INFO]::ENVIRONMENT: AVAHI_COMPAT_NOWARN: 1
[11:27:08] [INFO]::ENVIRONMENT: SAB_BYTES: 10221452725
[11:27:08] [INFO]::ENVIRONMENT: SAB_BYTES_DOWNLOADED: 9341100762
[11:27:08] [INFO]::ENVIRONMENT: SAB_BYTES_TRIED: 10221452725
[11:27:08] [INFO]::ENVIRONMENT: SAB_CAT: tvseries
[11:27:08] [INFO]::ENVIRONMENT: SAB_DUPLICATE: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_ENCRYPTED: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_FAIL_MSG:
[11:27:08] [INFO]::ENVIRONMENT: SAB_FILENAME: The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated.nzb
[11:27:08] [INFO]::ENVIRONMENT: SAB_FINAL_NAME: The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated
[11:27:08] [INFO]::ENVIRONMENT: SAB_GROUP: alt.binaries.town
[11:27:08] [INFO]::ENVIRONMENT: SAB_NZO_ID: SABnzbd_nzo_3try42cm
[11:27:08] [INFO]::ENVIRONMENT: SAB_OVERSIZED: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_PASSWORD:
[11:27:08] [INFO]::ENVIRONMENT: SAB_PP: 3
[11:27:08] [INFO]::ENVIRONMENT: SAB_PRIORITY: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_REPAIR: 1
[11:27:08] [INFO]::ENVIRONMENT: SAB_SCRIPT: nzbToMedia.py
[11:27:08] [INFO]::ENVIRONMENT: SAB_STATUS: Running
[11:27:08] [INFO]::ENVIRONMENT: SAB_UNPACK: 1
[11:27:08] [INFO]::ENVIRONMENT: SAB_UNWANTED_EXT: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_URL: The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated.nzb
[11:27:08] [INFO]::ENVIRONMENT: SAB_FAILURE_URL:
[11:27:08] [INFO]::ENVIRONMENT: SAB_COMPLETE_DIR: /volume1/downloads/complete/tvseries/The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated
[11:27:08] [INFO]::ENVIRONMENT: SAB_PP_STATUS: 0
[11:27:08] [INFO]::ENVIRONMENT: SAB_DOWNLOAD_TIME: 314
[11:27:08] [INFO]::ENVIRONMENT: SAB_AVG_BPS: 28985
[11:27:08] [INFO]::ENVIRONMENT: SAB_AGE: 1488d
[11:27:08] [INFO]::ENVIRONMENT: SAB_ORIG_NZB_GZ: /volume1/downloads/incomplete/The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated/__ADMIN__/The.Walking.Dead.S06E11.Knots.Untie.1080p.BluRay.REMUX.AVC.TrueHD.7.1-PrivateHD-Obfuscated.nzb.gz
[11:27:08] [INFO]::ENVIRONMENT: SAB_PROGRAM_DIR: /volume1/@appstore/sabnzbd/share/SABnzbd
[11:27:08] [INFO]::ENVIRONMENT: SAB_PAR2_COMMAND: /volume1/@appstore/sabnzbd/bin/par2
[11:27:08] [INFO]::ENVIRONMENT: SAB_MULTIPAR_COMMAND:
[11:27:08] [INFO]::ENVIRONMENT: SAB_RAR_COMMAND: /volume1/@appstore/sabnzbd/bin/unrar
[11:27:08] [INFO]::ENVIRONMENT: SAB_ZIP_COMMAND:
[11:27:08] [INFO]::ENVIRONMENT: SAB_7ZIP_COMMAND: /volume1/@appstore/sabnzbd/bin/7za
[11:27:08] [INFO]::ENVIRONMENT: SAB_VERSION: 3.0.2
[11:27:08] [INFO]::MAIN: Python v3.7 will reach end of life in 1003 days.
[11:27:08] [INFO]::MAIN: Checking database structure...
[11:27:08] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[11:27:08] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[11:27:08] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[11:27:08] [DEBUG]::MAIN: InitialSchema upgrade not required
[11:27:08] [INFO]::MAIN: Checking if source needs an update
[11:27:11] [DEBUG]::MAIN: cur_commit = None % (newest_commit)= 4c33b5574b9816633d44346bd302f284ed5a5510, num_commits_behind = 0
[11:27:11] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[11:27:11] [INFO]::MAIN: Auto-Updating nzbToMedia, Please wait ...
[11:27:11] [DEBUG]::MAIN: cur_commit = None % (newest_commit)= 4c33b5574b9816633d44346bd302f284ed5a5510, num_commits_behind = 0
[11:27:11] [INFO]::MAIN: Clearing out update folder /volume1/scripts/nzbToMedia-master/nzbToMedia-master/sb-update before extracting
[11:27:11] [INFO]::MAIN: Creating update folder /volume1/scripts/nzbToMedia-master/nzbToMedia-master/sb-update before extracting
[11:27:11] [INFO]::MAIN: Downloading update from 'https://github.com/clinton-hall/nzbToMedia/tarball/master'
[11:27:11] [ERROR]::MAIN: Error while trying to update: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
[11:27:11] [DEBUG]::MAIN: Traceback: Traceback (most recent call last):
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 1319, in do_open
encode_chunked=req.has_header('Transfer-encoding'))
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1252, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1298, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1247, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1026, in _send_output
self.send(msg)
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 966, in send
self.connect()
File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1422, in connect
server_hostname=server_hostname)
File "/var/packages/python3/target/lib/python3.7/ssl.py", line 423, in wrap_socket
session=session
File "/var/packages/python3/target/lib/python3.7/ssl.py", line 870, in _create
self.do_handshake()
File "/var/packages/python3/target/lib/python3.7/ssl.py", line 1139, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/core/version_check.py", line 464, in update
urlretrieve(tar_download_url, tar_download_path)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 247, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 525, in open
response = self._open(req, data)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 543, in _open
'_open', req)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 503, in _call_chain
result = func(*args)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 1362, in https_open
context=self._context, check_hostname=self._check_hostname)
File "/var/packages/python3/target/lib/python3.7/urllib/request.py", line 1321, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

fatal: not a git repository (or any parent up to mount point /volume1)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[11:27:11] [ERROR]::MAIN: Update failed, not restarting. Check your log for more information.`

erro2 Headphones pp script:
`File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/nzbToMedia.py", line 1059, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/nzbToMedia.py", line 968, in main
failure_link=os.environ['SAB_FAILURE_URL'])
File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/nzbToMedia.py", line 855, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/core/auto_process/music.py", line 35, in process
delete_failed = int(cfg['delete_failed'])
KeyError: 'delete_failed'
Exception ignored in: <function PosixProcess.__del__ at 0x7f0230bbd7a0>
Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia-master/nzbToMedia-master/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'`

**Comment by clinton-hall** [comment]
What is the address of the script that SABnzbd is calling? are you using symlinks as this may cause the script to run the update in the wrong location.
I note this appears to be in `/volume1/scripts/nzbToMedia-master/nzbToMedia-master`... why the double-up? 

I am not sure why the SSL errors. I would suggest there is a problem with the python package on your system... It may be related to the following.
https://github.com/SynoCommunity/spksrc/issues/4137
