### ISSUE TITLE
TorrentToMedia is failing on a manual run

### ISSUE THREAD

**Issue by MrCee** [clinton-hall/nzbToMedia#1802]
Ive been having some problems with TorrentToMedia on a manual run,but note nzbToMedia is working as expected.

I've tried Master and Nighly, I have chmod 777 the downloads directory recursively. I'm using Radarr although don't see anything unusual in the logs there. I'm noticing that the folder name `/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4` is missing just before the traceback message in the log.

Here's the nzbToMedia log

```
[20:21:49] [INFO]::MAIN: Starting manual run for Radarr:movie - Folder:/volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG
[20:21:49] [INFO]::MAIN: Checking database for download info for It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG ...
[20:21:49] [DB]::DB: Getting download info for It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG from the DB
[20:21:49] [DB]::MAIN: nzbtomedia.db: SELECT * FROM downloads WHERE input_name=? AND status=? with args ['It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG', 0]
[20:21:49] [INFO]::MAIN: Unable to locate download info for It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG, continuing to try and process this release ...
[20:21:49] [DEBUG]::MAIN: Received Directory: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG | Name: It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG | Category: movie
[20:21:49] [DEBUG]::MAIN: SEARCH: Found the Category: movie in directory structure
[20:21:49] [INFO]::MAIN: SEARCH: Found torrent file It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4 in input directory directory /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG
[20:21:49] [INFO]::MAIN: SEARCH: Setting input_directory to /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:49] [DEBUG]::MAIN: Determined Directory: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4 | Name: It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4 | Category: movie
[20:21:50] [INFO]::MAIN: Auto-detected SECTION:Radarr
[20:21:50] [INFO]::MAIN: Output directory set to: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [DEBUG]::MAIN: Scanning files in directory: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [DEBUG]::MAIN: Found 1 files in /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [INFO]::MAIN: FLATTEN: Flattening directory: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [WARNING]::MAIN: Found no media files in /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [INFO]::MAIN: Calling Radarr:movie to post-process:It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
[20:21:50] [INFO]::MAIN: Changing file mode of /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4 to 0o777
Traceback (most recent call last):
  File "/nzbToMedia/TorrentToMedia.py", line 372, in <module>
    exit(main(sys.argv))
  File "/nzbToMedia/TorrentToMedia.py", line 357, in main
    client_agent)
  File "/nzbToMedia/TorrentToMedia.py", line 236, in process_torrent
    core.rchmod(output_destination, core.TORRENT_CHMOD_DIRECTORY)
  File "/volume1/@appstore/nzbToMedia/core/utils/paths.py", line 162, in rchmod
    os.chmod(path, mod)
FileNotFoundError: [Errno 2] No such file or directory: '/volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4'
Exception ignored in: <function PosixProcess.__del__ at 0xb5b304ac>
Traceback (most recent call last):
  File "/volume1/@appstore/nzbToMedia/core/utils/processes.py", line 95, in __del__
AttributeError: 'NoneType' object has no attribute 'isfile'
```
Thank you.

**Comment by clinton-hall** [comment]
there are a couple of interesting things going on here... basically the script seems be be doing opposite to what would usually happen.

usually I would expect 
download to: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4
then the script link/move/copy files to: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4

In your case, the download is already in its own directory, and the script is trying to link it back into its own directory, with the extension added back in....
There are a few settings involved, so I can't immediately see what combination is causing it to try and keep the extension in the directory name.
Also, it doesn't seem to actually try to copy/link/move files anyway, so I guess you have `Torrent_NoLink =1`?

I would recommend `Torrent_NoLink =0` and then set `useLink = hard` and `outputDirectory = /volume1/completed/` or similar... that way

download to: /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4

will get hard-linked to /volume1/completed/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4

then get processed by Radarr.

**Comment by clinton-hall** [comment]
oh, I notice this is a manual run.... is this happening after the script has already run once and moved/copied/linked the files into their own directory? or is this running on files that have been downloaded to /volume1/downloads/movie/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG/It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG.mp4 by your torrent client?

**Comment by MrCee** [comment]
Thanks, Clinton

This is happening after either SAB or Download Station has moved the file to /volume1/downloads/movie from the previous incomplete or TEMP directory on the same volume. I've had this happen a few times in the last few weeks and made sure I looked at chmod/chown of all directories & files before posting.

I'm only attempting a manual run here because, for whatever reason, this file has been left behind/unprocessed out of usual nzbToMedia processing, and this happens from time to time if Radarr or Sickchill isn't running.  I've always had the script set to move but will try using hard in future. I think you are correct, yes, the script has already moved/linked to a folder called It.Chapter.Two.2019.720p.BluRay.H264.AAC-RARBG in the previous mzbToMedia attempt which I am fixing now.
I have made sure to always truncate `> nzbtomedia.db` and always do this when I need to intervene with any manual processing using TorrentToMedia.  Let me know if there's something else I should be looking out for here.

I changed the name of the folder the mp4 sits in this morning and tried your suggested settings and everything processed fine. I cannot be sure what did the trick. I have tried to replicate this scenario several times this morning and cannot.
Next time I'll try one thing at a time, which would have been helpful just now.

**Comment by MrCee** [comment]
It's been a while, but sometimes a manual run just needs to run and update the client. 
What I see from my end is unless a file is queued or snatched, the manual run does not work although the logs will say it's worked perfectly. And the file will disappear.
I don't often get this scenario, but a manual run used to force the client to respond. 
It doesn't happen as it used to some years ago, I'd like to help this along if I can and obviously more information will need to be provided.

If I download something separately, move it into the correct folder for SickChill (TV Episode), run ./TorrentToMedia.py because the show is not snatched or downloading, the file is deleted . I do remember a time when the manual run would work with the client regardless.
