### ISSUE TITLE
[WARNING]::EXCEPTION: No name replacement determined for thumb

### ISSUE THREAD

**Issue by ikkeenjij36** [clinton-hall/nzbToMedia#1835]
**Describe the bug**
The pp sarts up but fails after 300 secs with this as first report/fault

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) '..synology dsm 62.xxx..'
2. Python version '.3.8...'
3. Download Client (NZBget, SABnbzd, Transmission) '..sabnzbd ..'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) '.headphones...'

**Expected behavior**
as told above

**Log**
Please provide an extract, or full debug log that indicates the issue.
`[14:36:00] [INFO]::MAIN: Script triggered from SABnzbd Version 3.2.1.
[14:36:00] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC to database
[14:36:00] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
[14:36:00] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC
[14:36:00] [INFO]::MAIN: Calling HeadPhones:muziek to post-process:Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC
[14:36:00] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8182/api
[14:36:00] [DEBUG]::SERVER: Server responded at http://localhost:8182/api
[14:36:00] [WARNING]::EXCEPTION: No name replacement determined for thumb
[14:36:00] [DEBUG]::EXCEPTION: Replacing file name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/thumb.jpg with download name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC.jpg
[14:36:00] [WARNING]::EXCEPTION: No name replacement determined for folder
[14:36:00] [DEBUG]::EXCEPTION: Replacing file name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/folder.jpg with download name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC.NTM.jpg
[14:36:00] [WARNING]::EXCEPTION: No name replacement determined for Disc
[14:36:00] [DEBUG]::EXCEPTION: Replacing file name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/Artwork/Disc.jpg with download name /volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC/Artwork/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC.jpg
[14:36:00] [DEBUG]::MAIN: Attempting to get current status for release:Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC
[14:36:00] [DEBUG]::MAIN: Opening URL: http://localhost:8182/api with PARAMS: {'apikey': 'b3d16df1a9ae5b916996ba60c2b67b5a', 'cmd': 'getHistory'}
[14:36:00] [DEBUG]::HEADPHONES: Opening URL: http://localhost:8182/api with PARAMS: {'apikey': 'b3d16df1a9ae5b916996ba60c2b67b5a', 'cmd': 'forceProcess', 'dir': '/volume1/downloads/complete/muziek/Dire Straits - Making Movies (2012 SHM-SACD) (1980) FLAC'}
Changing to directory: /volume1/scripts/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /volume1/@appstore/sabnzbd/share/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/var/packages/python38/target/lib/python3.8/http/client.py", line 1347, in getresponse
response.begin()
File "/var/packages/python38/target/lib/python3.8/http/client.py", line 307, in begin
version, status, reason = self._read_status()
File "/var/packages/python38/target/lib/python3.8/http/client.py", line 268, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/var/packages/python38/target/lib/python3.8/socket.py", line 669, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia/libs/common/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 637, in urlopen
retries = retries.increment(method, url, error=e, _pool=self,
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/packages/six.py", line 686, in reraise
raise value
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 597, in urlopen
httplib_response = self._make_request(conn, method, url,
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 386, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/volume1/scripts/nzbToMedia/libs/common/urllib3/connectionpool.py", line 306, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8182): Read timed out. (read timeout=300)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/volume1/scripts/nzbToMedia/nzbToMedia.py", line 1061, in <module>
exit(main(sys.argv))
File "/volume1/scripts/nzbToMedia/nzbToMedia.py", line 966, in main
result = process(os.environ['SAB_COMPLETE_DIR'], input_name=os.environ['SAB_FINAL_NAME'], status=int(os.environ['SAB_PP_STATUS']),
File "/volume1/scripts/nzbToMedia/nzbToMedia.py", line 855, in process
result = music.process(section_name, input_directory, input_name, status, client_agent, input_category)
File "/volume1/scripts/nzbToMedia/core/auto_process/music.py", line 86, in process
res = force_process(params, url, apikey, input_name, dir_name, section, wait_for)
File "/volume1/scripts/nzbToMedia/core/auto_process/music.py", line 227, in force_process
r = requests.get(url, params=params, verify=False, timeout=(30, 300))
File "/volume1/scripts/nzbToMedia/libs/common/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/volume1/scripts/nzbToMedia/libs/common/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/volume1/scripts/nzbToMedia/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/volume1/scripts/nzbToMedia/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/volume1/scripts/nzbToMedia/libs/common/requests/adapters.py", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8182): Read timed out. (read timeout=300)`

**Comment by clinton-hall** [comment]
what shows in the HeadPhones logs at [14:36:00]?
It looks as though HeadPhones is not responding to the rename request.

**Comment by ikkeenjij36** [comment]
That is indeed the problem,should i retry to the dev of headphones?

Op zo 18 jul. 2021 03:19 schreef Clinton Hall ***@***.***>:

**Comment by clinton-hall** [comment]
if you an increase the headphones logging level, then retry, send through the headphones logs.

**Comment by ikkeenjij36** [comment]
` : Updating file permissions in /volume1/muziek/Robyn/Robyn Is Here [1995]
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Scanning music directory: /volume1/muziek/Robyn/Robyn Is Here [1995]
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : 13 new/modified songs found and added to the database
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Found 13 new/modified tracks in: '/volume1/muziek/Robyn/Robyn Is Here [1995]'. Matching tracks to the appropriate releases....
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Now matching songs by Robyn
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 15.3% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 30.7% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 46.1% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 61.5% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 76.9% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Track matching is 92.3% complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Completed matching tracks from directory: /volume1/muziek/Robyn/Robyn Is Here [1995]
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Updating artist track counts
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Scanning complete for artist: Robyn
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Post-processing for Robyn - Robyn Is Here complete
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Processing: Robyn - Don't Stop The Music (2002)
18-Jul-2021 18:46:44 - INFO    :: CP Server Thread-7 : Querying MusicBrainz for the release group id for: Robyn - Don't Stop The Music
18-Jul-2021 18:46:45 - INFO    :: CP Server Thread-7 : Starting post-processing for: Robyn - Donâ€™t Stop the Music
18-Jul-2021 18:46:46 - INFO    :: CP Server Thread-7 : Encoding for folder '/volume1/downloads/complete/muziek/Robyn - robyn IS HERE (1995) MP3/Robyn.5x/Robyn - 5 cd's/Robyn - Don't Stop The Music (2002)' is not required
18-Jul-2021 18:46:46 - INFO    :: CP Server Thread-7 : Searching for artwork at CAA
18-Jul-2021 18:46:48 - INFO    :: CP Server Thread-7 : Artwork found at CAA
18-Jul-2021 18:46:48 - INFO    :: CP Server Thread-7 : Embedding album art
18-Jul-2021 18:46:49 - INFO    :: CP Server Thread-7 : Cleaning up files
18-Jul-2021 18:46:49 - INFO    :: CP Server Thread-7 : Adding album art to folder
18-Jul-2021 18:46:49 - INFO    :: CP Server Thread-7 : Preparing to write metadata to tracks....
18-Jul-2021 18:47:01 - WARNING :: CP Server Thread-7 : No accurate album match found for Robyn, Donâ€™t Stop the Music -  not writing metadata
18-Jul-2021 18:47:01 - INFO    :: CP Server Thread-10 : Received API command: getHistory
18-Jul-2021 18:47:09 - INFO    :: CP Server Thread-8 : Received API command: getHistory
18-Jul-2021 18:47:09 - INFO    :: CP Server Thread-3 : Received API command: forceProcess
18-Jul-2021 18:47:09 - INFO    :: CP Server Thread-3 : Force checking download folder for completed downloads
18-Jul-2021 18:47:09 - INFO    :: CP Server Thread-3 : Found no folders to process. Aborting.
18-Jul-2021 18:47:09 - INFO    :: CP Server Thread-4 : Received API command: getHistory
18-Jul-2021 18:47:30 - INFO    :: CP Server Thread-7 : Received API command: getHistory`

**Comment by clinton-hall** [comment]
And what is the nzbToMedia logs that relate to that?

It looks as though HeadPhones successfully renames the download BEFORE nzbToMedia sends the forceProcess request.
If that is the case, then HeadPhones needs to be set so that it doesn't scan the downlaod directory until it is triggered by the api.
