### ISSUE TITLE
NZBtoRadarr stopped working 2 months ago: 

### ISSUE THREAD

**Issue by Fuergrissa1** [clinton-hall/nzbToMedia#1851]
Using NZBtoRADARR with NZBGet, has worked great for (some number of years) but post-processing started failing on 8/12. or at least 8/12 is the last date that an entry was made in the NZBtoMEDIA log file. The NZBGet log shows:

`nzbToRadarr:  C:\Users\....\AppData\Local\Programs\Python\Python39\python.exe: can't  open file 'C:\ProgramData\NZBGet\scripts\L': [Errno 2] No such file or  directory`

and indeed, that directory doesn't exist. I have checked that the scripts folder in NZB is correct (C:\ProgramData\NZBGet\scripts\), it is finding nzbToRadarr after all, but I am guessing that when nzbToRadarr calls nzbToMedia.py it cannot find it. I cannot find any setting in NZB get that would be responsible for that \L\ in the file path? I also don't see any options for more verbose logging. Advice appreciated.

**Comment by clinton-hall** [comment]
#987 
I'm not sure where to start. There are no more logging options inside nzbToMedia, since nzbToMedia never runs.
My gut feeling is that there is an issue with the environment (NZBGet) or with Python itself.

Can you manually run nzbToRadarr?

**Comment by Fuergrissa1** [comment]
so run something like:

`python nzbToRadarr sectionName inputDirectory inputName status clientAgent download_id inputCategory  failureLink`

are there any arguments I don't need? section, and input directory/name are easy enough, but I'm not sure what NZBget sends for anything from status over

**Comment by clinton-hall** [comment]
just run `./nzbToRadarr` we want to see if this will spawn the process correctly.

**Comment by Fuergrissa1** [comment]
I'm sure I am not understanding what you are asking me to do. I do not know how to run the script manually.

If I run from windows powershell:
`PS C:\ProgramData\NZBGet\scripts> py nzbToRadarr.py
Requested Python version (2) is not installed`
I have python 3.9 installed btw

if I run from within VSCode:
`PS C:\ProgramData\NZBGet\scripts>  & 'C:\Users\.\AppData\Local\Programs\Python\Python39\python.exe' 'c:\Users\.\.vscode\extensions\ms-python.python-2021.9.1246542782\pythonFiles\lib\python\debugpy\launcher' '63467' '--' 'c:\ProgramData\NZBGet\scripts\nzbToRadarr.py'
Traceback (most recent call last):
  File "c:\ProgramData\NZBGet\scripts\nzbToRadarr.py", line 246, in <module>
    import nzbToMedia
  File "c:\ProgramData\NZBGet\scripts\nzbToMedia.py", line 573, in <module> 
    import core
  File "c:\ProgramData\NZBGet\scripts\core\__init__.py", line 35, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "c:\ProgramData\NZBGet\scripts\core\autoProcess\autoProcessComics.py", line 7, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "c:\ProgramData\NZBGet\scripts\core\nzbToMediaUtil.py", line 14, in <module>
    import guessit
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\rules\__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\rules\properties\episodes.py", line 14, in <module>
    from .title import TitleFromPosition
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\rules\properties\title.py", line 14, in <module>
    from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
  File "c:\ProgramData\NZBGet\scripts\libs\guessit\rules\properties\language.py", line 9, in <module>
    import babelfish
  File "c:\ProgramData\NZBGet\scripts\libs\babelfish\__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "c:\ProgramData\NZBGet\scripts\libs\babelfish\converters\__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "c:\ProgramData\NZBGet\scripts\libs\pkg_resources.py", line 29
    def _bypass_ensure_directory(name, mode=0777):
                                               ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers`

If this is not what your asking for can you tell me exactly what to do?

**Comment by clinton-hall** [comment]
ok... that traceback is showing files that shouldn't be there, so I think you will need to re-clone the repository.

Try renaming c:\ProgramData\NZBGet\scripts to c:\ProgramData\NZBGet\scripts2
then re-clone nzbToMedia to c:\ProgramData\NZBGet\scripts
finally you can copy back autoProcessMedia.cfg from c:\ProgramData\NZBGet\scripts2 to c:\ProgramData\NZBGet\scripts

then see if this now runs without any traceback.

Foe me, in Windows using Python 3.8

```
C:\Users\fock_\Documents\GitHub\nzbToMedia> py nzbToRadarr.py

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean


-- Cleanup finished --

[14:25:13] [INFO]::MAIN: Loading config from [C:\Users\fock_\Documents\GitHub\nzbToMedia\autoProcessMedia.cfg]
[14:25:13] [INFO]::MAIN: Python v3.8 will reach end of life in 1107 days.
[14:25:13] [INFO]::MAIN: Checking database structure...
[14:25:13] [INFO]::MAIN: Database upgrade required: Initial Schema
[14:25:13] [INFO]::MAIN: Checking if git needs an update
[14:25:14] [INFO]::MAIN: No update needed
[14:25:14] [INFO]::MAIN: nzbToMedia Version:f9dde62762f7ad4fa6a5bfca892af7263a28a3e3 Branch:master (Windows 10)
[14:25:14] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[14:25:14] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[14:25:14] [WARNING]::MAIN: Failed to locate ffprobe.exe. Video corruption detection disabled!
[14:25:14] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[14:25:14] [INFO]::MAIN: #########################################################
[14:25:14] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[14:25:14] [INFO]::MAIN: #########################################################
[14:25:14] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[14:25:14] [INFO]::MAIN: The nzbToRadarr.py script completed successfully.
```

**Comment by Fuergrissa1** [comment]
after the clone and installing pywin32 it looks like this:
probably not related but that location is correct for Git

```
Changing to directory: c:\ProgramData\NZBGet\scripts

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  C:\ProgramData\NZBGet\scripts

-- Cleanup finished --

[15:33:58] [INFO]::MAIN: Loading config from [c:\ProgramData\NZBGet\scripts\autoProcessMedia.cfg]
[15:33:58] [INFO]::MAIN: Python v3.9 will reach end of life in 1461 days.
[15:33:58] [INFO]::MAIN: Checking database structure...
[15:33:58] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[15:33:58] [INFO]::MAIN: Database upgrade required: Initial Schema
[15:33:58] [DEBUG]::MAIN: InitialSchema upgrade completed
[15:33:58] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files\Git" version
[15:33:58] [DEBUG]::MAIN: Executing "C:\Program Files\Git" version with your shell in c:\ProgramData\NZBGet\scripts
[15:33:58] [DEBUG]::MAIN: Not using: "C:\Program Files\Git"
[15:33:58] [DEBUG]::MAIN: Trying known alternative git locations
[15:33:58] [DEBUG]::MAIN: Checking if we can use git commands: "c:\program files\git" version
[15:33:58] [DEBUG]::MAIN: Executing "c:\program files\git" version with your shell in c:\ProgramData\NZBGet\scripts
[15:33:58] [DEBUG]::MAIN: Not using: "c:\program files\git"
[15:33:58] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.[15:33:58] [DEBUG]::MAIN: No git specified, can't use git commands
[15:33:58] [INFO]::MAIN: Checking if git needs an update
[15:33:58] [DEBUG]::MAIN: No git specified, can't use git commands
[15:33:58] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[15:33:58] [INFO]::MAIN: No update needed
[15:33:58] [INFO]::MAIN: nzbToMedia Version:12.1.09 Branch:master (Windows 10)
[15:33:58] [INFO]::MAIN: #########################################################
[15:33:58] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[15:33:58] [INFO]::MAIN: #########################################################
[15:33:58] [DEBUG]::MAIN: Options passed into nzbToMedia: ['c:\\ProgramData\\NZBGet\\scripts\\nzbToRadarr.py']
[15:33:58] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[15:33:58] [INFO]::MAIN: Searching  for mediafiles to post-process ...
[15:33:58] [ERROR]::MAIN: Failed to add directories from  for post-processing: [WinError 3] The system cannot find the path specified: ''
[15:33:58] [DEBUG]::MAIN: No directories identified in Radarr:movie for post-processing
Traceback (most recent call last):
  File "c:\ProgramData\NZBGet\scripts\nzbToRadarr.py", line 267, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "c:\ProgramData\NZBGet\scripts\nzbToMedia.py", line 1012, in main
    for dir_name in get_dirs(section, subsection, link='move'):
  File "c:\ProgramData\NZBGet\scripts\core\utils\common.py", line 99, in get_dirs
    directory = os.path.join(watch_directory, subsection)
  File "C:\Users\Casey\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not Section
```

tried postprocessing from NZBGet again and the error is still the same, an unnecessary L is being appended to the path for the scripts folder, I still cannot find where it is coming from, but the above makes it look like NZBtoRadarr is not the problem right?

`nzbToRadarr: C:\Users\Casey\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\ProgramData\NZBGet\scripts\L': [Errno 2] No such file or directory`

**Comment by Fuergrissa1** [comment]
It works! thank you!
