### ISSUE TITLE
Python 3.10 EOL date not set

### ISSUE THREAD

**Issue by SanderV4n** [clinton-hall/nzbToMedia#1866]
**Describe the bug**
Running with python 3.10 does not work. 

**Technical Specs**
1. Running on Fedora 35
2. Python version 3.10

**Expected behavior**
Running with python 3.10

**Log**

Traceback (most recent call last):
File "/usr/share/nzbToMedia/nzbToNzbDrone.py", line 259, in <module>
import nzbToMedia
File "/usr/share/nzbToMedia/nzbToMedia.py", line 727, in <module>
eol.check()
File "/usr/share/nzbToMedia/eol.py", line 100, in check
warn_for_status(version, grace_period)
File "/usr/share/nzbToMedia/eol.py", line 141, in warn_for_status
days_left = lifetime(version)
File "/usr/share/nzbToMedia/eol.py", line 71, in lifetime
time_left = PYTHON_EOL[(major, minor)] - now
KeyError: (3, 10)

Change needed:
eol.py line 30
```
PYTHON_EOL = {
+    (3, 10): date('2026-10-01'),
    (3, 9): date('2025-10-05'),
```

**Comment by clinton-hall** [comment]
Hmmm... and that is why we add CI tests!

While this works to add Python 3.10 support, the tests have flagged that the version of Babelfish currently bundled in nzbToMedia is not working with Python 3.10 (at least not with the 3.10.0 version currently available in the Ubuntu 20.04 image on Azure).

I'll need to do some more tests before merging. As I see it now, this project is not (yet) compatible with Python 3.10

**Comment by clinton-hall** [comment]
I note that latest Babelfish fixes this...
https://github.com/Diaoul/babelfish

I'll need to update and test.

**Comment by clinton-hall** [comment]
ok. Babelfish updated and appears to work in all Py versions.
Currently in nightly branch.

**Comment by SanderV4n** [comment]
Hi @clinton-hall 

I made the change locally, this made it run a bit better but still have a traceback:

Traceback (most recent call last):
File "/usr/share/nzbToMedia/nzbToLidarr.py", line 251, in <module>
import nzbToMedia
File "/usr/share/nzbToMedia/nzbToMedia.py", line 730, in <module>
import core
File "/usr/share/nzbToMedia/core/__init__.py", line 52, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "/usr/share/nzbToMedia/core/databases.py", line 11, in <module>
from core.utils import backup_versioned_file
File "/usr/share/nzbToMedia/core/utils/__init__.py", line 13, in <module>
from core.utils.common import clean_dir, flatten, get_dirs, process_dir
File "/usr/share/nzbToMedia/core/utils/common.py", line 14, in <module>
from core.utils.files import list_media_files, move_file
File "/usr/share/nzbToMedia/core/utils/files.py", line 15, in <module>
import guessit
File "/usr/share/nzbToMedia/libs/common/guessit/__init__.py", line 8, in <module>
from .api import guessit, GuessItApi
File "/usr/share/nzbToMedia/libs/common/guessit/api.py", line 20, in <module>
from .rules import rebulk_builder
File "/usr/share/nzbToMedia/libs/common/guessit/rules/__init__.py", line 11, in <module>
from .properties.episodes import episodes
File "/usr/share/nzbToMedia/libs/common/guessit/rules/properties/episodes.py", line 14, in <module>
from .title import TitleFromPosition
File "/usr/share/nzbToMedia/libs/common/guessit/rules/properties/title.py", line 11, in <module>
from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
File "/usr/share/nzbToMedia/libs/common/guessit/rules/properties/language.py", line 10, in <module>
import babelfish
File "/usr/share/nzbToMedia/libs/common/babelfish/__init__.py", line 20, in <module>
from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
File "/usr/share/nzbToMedia/libs/common/babelfish/converters/__init__.py", line 11, in <module>
class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by clinton-hall** [comment]
yes, exactly. That is why you will need to update to the latest nightly branch. This includes the latest babelfish that is compatible with python 3.10

the new babelfish does not use collections.MutableMapping

**Comment by tixetsal** [comment]
I was also affected by this issue, and switching to nightly resolved the problem. Thanks!
