### ISSUE TITLE
QNAP - nzbToSickbeard not working on post process in NZBGet

### ISSUE THREAD

**Issue by Freakadude** [clinton-hall/nzbToMedia#1870]
**Describe the bug**
For some reason after a couple of weeks of working now nzbToMedia specifically nzbtoSickbeard (using Medusa) always gives me an error during post process. For fun i have tried different Sickbeard forks (SickChill, SickGear) and have the same issue.

In NZBget i have only the NZBTOSICKBEARD part configured of all the nzbToMedia scripts

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'QNAP NAS  TS-431P'
2. Python version 'Python 2.7.13 and Python 3.10.0'
3. Download Client (NZBget, SABnbzd, Transmission) 'NZBget'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Medusa'

**Expected behavior**
Post processing script should trigger Medusa correctly but it always fails. 

**Log**
Below a sample log entry:
`Sat Dec 25 2021 15:11:06	INFO	Executing post-process-script nzbToMedia/nzbToSickBeard.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard: Traceback (most recent call last):
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:   File "/share/Download/scripts/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:     import nzbToMedia
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/nzbToMedia.py", line 727, in <module>
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:     eol.check()
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 100, in check
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:     warn_for_status(version, grace_period)
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 141, in warn_for_status
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:     days_left = lifetime(version)
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 71, in lifetime
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard:     time_left = PYTHON_EOL[(major, minor)] - now
Sat Dec 25 2021 15:11:06	INFO	nzbToSickBeard: KeyError: (3, 10)
Sat Dec 25 2021 15:11:06	ERROR	Post-process-script nzbToMedia/nzbToSickBeard.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB failed (terminated with unknown status)
Sat Dec 25 2021 15:11:06	INFO	Executing post-process-script Logger.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB
Sat Dec 25 2021 15:11:07	INFO	Post-process-script Logger.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB successful
Sat Dec 25 2021 15:11:07	INFO	Collection The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB added to history
Sat Dec 25 2021 15:12:42	INFO	Post-processing again The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB
Sat Dec 25 2021 15:12:42	INFO	The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB returned from history back to download queue
Sat Dec 25 2021 15:12:42	INFO	Queueing The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB for post-processing
Sat Dec 25 2021 15:12:42	INFO	Executing post-process-script nzbToMedia/nzbToSickBeard.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard: Traceback (most recent call last):
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:   File "/share/Download/scripts/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:     import nzbToMedia
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/nzbToMedia.py", line 727, in <module>
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:     eol.check()
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 100, in check
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:     warn_for_status(version, grace_period)
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 141, in warn_for_status
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:     days_left = lifetime(version)
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/eol.py", line 71, in lifetime
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard:     time_left = PYTHON_EOL[(major, minor)] - now
Sat Dec 25 2021 15:12:42	INFO	nzbToSickBeard: KeyError: (3, 10)
Sat Dec 25 2021 15:12:42	ERROR	Post-process-script nzbToMedia/nzbToSickBeard.py for The.Americans.2013.S02E03.The.Walk.In.720p.WEB-DL.DD5.1.H.264-NTB failed (terminated with unknown status)`

**Comment by Freakadude** [comment]
So based on the error which i traced back to the eol.py file i figured the issue is that since i am runnning Python 3.10 version in the eol.py there was no key pair set for the eol check with 3, 10. So i added one line with the same date for 3,10 as there was for 3,9 just to see what the script would say if i'd run it now. 

Eol was now not an issue anymore however i got below list of "issues" back from the system:

[~] # python3 /share/Download/scripts/nzbToMedia/nzbToSickBeard.py
Changing to directory: /share/CACHEDEV1_DATA/Download/scripts/nzbToMedia

-- Cleaning bytecode --
fatal: not a git repository (or any parent up to mount point /share)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
WARNING: Automatic cleanup could not be executed.
         If errors occur, manual cleanup may be required.
REASON : Error Code: 128

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'utils']
Returning to directory:  /root

-- Cleanup finished --

Traceback (most recent call last):
  File "/share/Download/scripts/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
    import nzbToMedia
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/nzbToMedia.py", line 730, in <module>
    import core
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
    from core import logger, main_db, version_check, databases, transcoder
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/core/databases.py", line 11, in <module>
    from core.utils import backup_versioned_file
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/core/utils/__init__.py", line 13, in <module>
    from core.utils.common import clean_dir, flatten, get_dirs, process_dir
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/core/utils/common.py", line 14, in <module>
    from core.utils.files import list_media_files, move_file
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/core/utils/files.py", line 15, in <module>
    import guessit
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/api.py", line 20, in <module>
    from .rules import rebulk_builder
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/rules/properties/episodes.py", line 14, in <module>
    from .title import TitleFromPosition
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/rules/properties/title.py", line 11, in <module>
    from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/share/CACHEDEV1_DATA/Download/scripts/nzbToMedia/libs/common/babelfish/converters/__init__.py", line 11, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by Freakadude** [comment]
I didn't like the part in the above error between the cleaning up bytecode part so i tried the following: Since i had these scripts manually installed on my NAS in a scripts directory i thought maybe there was something missing so i deleted my manual install of the nzbtoMedia scripts and installed them again using sherpa on QNAP.

The message between the bytecode now seems to be better however Post Processing still fails with the exact same lines given as above:


Sun Dec 26 2021 18:17:20	INFO	Executing post-process-script nzbToSickBeard.py for The.Americans.2013.S02E07.Arpanet.720p.WEB-DL.DD5.1.h.264-NTb
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: Changing to directory: /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: -- Cleaning bytecode --
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: b'Removing __pycache__/\n'
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: b'Removing __pycache__/\n'
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: No folders to clean
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: Returning to directory:  /
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: -- Cleanup finished --
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: Traceback (most recent call last):
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToSickBeard.py", line 270, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     import nzbToMedia
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 730, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     import core
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/__init__.py", line 52, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from core import logger, main_db, version_check, databases, transcoder
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/databases.py", line 11, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from core.utils import backup_versioned_file
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/utils/__init__.py", line 13, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from core.utils.common import clean_dir, flatten, get_dirs, process_dir
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/utils/common.py", line 14, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from core.utils.files import list_media_files, move_file
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/utils/files.py", line 15, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     import guessit
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/__init__.py", line 8, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .api import guessit, GuessItApi
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/api.py", line 20, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .rules import rebulk_builder
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/rules/__init__.py", line 11, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .properties.episodes import episodes
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/rules/properties/episodes.py", line 14, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .title import TitleFromPosition
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/rules/properties/title.py", line 11, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/guessit/rules/properties/language.py", line 10, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     import babelfish
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/babelfish/__init__.py", line 20, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:   File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/babelfish/converters/__init__.py", line 11, in <module>
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard:     class CaseInsensitiveDict(collections.MutableMapping):
Sun Dec 26 2021 18:17:27	INFO	nzbToSickBeard: AttributeError: module 'collections' has no attribute 'MutableMapping'
Sun Dec 26 2021 18:17:27	ERROR	Post-process-script nzbToSickBeard.py for The.Americans.2013.S02E07.Arpanet.720p.WEB-DL.DD5.1.h.264-NTb failed (terminated with unknown status)

**Comment by Freakadude** [comment]
Nevermind. I found in issue [https://github.com/clinton-hall/nzbToMedia/issues/1866](url) a similar problem has been described due to Python 3.10 version and the nightly branch fixed it also for me.
