### ISSUE TITLE
exit(-1) cannot run script c:\nzbtomedia\

### ISSUE THREAD

**Issue by Jonnehs** [clinton-hall/nzbToMedia#1880]
**Describe the bug**
Migrated all downloaders etc to a new 2022 VM, but the scripts will not work when called from SABnzbd

**Technical Specs**
Windows 2022
Python 3.73
SABnzbd
SichChill, Radarr

**Expected behavior**
SABnzbd calls the script, but it exits with the error "exit(-1) cannot run script c:\nzbtomedia\... .py"

**Log**
No nzbtomedia logs seem to be generated

**Comment by Jonnehs** [comment]
From SABnzbd log:

2022-03-17 15:52:21,785::DEBUG::[newsunpack:235] Failed script C:\nzbToMedia\nzbToMedia.py, Traceback: 
Traceback (most recent call last):
  File "sabnzbd\newsunpack.py", line 216, in external_processing
  File "sabnzbd\misc.py", line 1163, in build_and_run_command
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1435, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by clinton-hall** [comment]
the problem here is that SABnzbd is not able to find nzbToMedia to run.

Check the SABnzbd settings to ensure this is pointing at the correct location for nzbToMedia.py. i.e. is this really located at C:\nzbToMedia\nzbToMedia.py?
