### ISSUE TITLE
Processing with Radarr failed in last stage

### ISSUE THREAD

**Issue by Jelmerb** [clinton-hall/nzbToMedia#1884]
**Describe the bug**
Torrent not removed from Transmission and rest of the downloaded files not cleaned after processing by Radarr. The media files are moved to the destination folder though, so I between finishing processing and nzbToMedia completing it's script things go wrong.  

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'Synology DS720+ with DSM 7.1-42661 Update 1.'
2. Python version '3.8'
3. Download Client (NZBget, SABnbzd, Transmission) 'Transmission'
4. Intended Media Management (SickChill, CouchPotoato, Radarr, Sonarr) 'Radarr'

**Expected behavior**
Torrent is stopped and removed from Transmission after Radarr finishes processing and the rest of the downloaded files are deleted.

**Log**
```
2022-05-14 05:40:53 DEBUG   ::RADARR: Opening URL: http://172.17.0.1:7878/api/v3/command with PARAMS: {'name': 'DownloadedMoviesScan', 'path': '/downloads/processed/movie/GoldenEye.1995.INTERNAL.2160p.WEB.H265-DEFLATE', 'downloadClientId': '1ab3285e18217cd58cc57f21198f0a32d22d9964', 'importMode': 'Move'}
2022-05-14 05:40:53 POSTPROCESS::RADARR: Starting DownloadedMoviesScan scan for GoldenEye.1995.INTERNAL.2160p.WEB.H265-DEFLATE
2022-05-14 05:40:53 DEBUG   ::RADARR: Scan started with id: 42590
2022-05-14 05:40:53 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:40:53 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:41:53 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:41:54 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:42:54 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:42:54 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:43:54 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:43:54 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:44:55 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:44:55 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:45:55 POSTPROCESS::RADARR: Checking for status change, please stand by ...
2022-05-14 05:45:56 DEBUG   ::RADARR: The Scan command return status: started
2022-05-14 05:46:57 WARNING ::RADARR: GoldenEye.1995.INTERNAL.2160p.WEB.H265-DEFLATE does not appear to have changed status after 6 minutes, Please check your logs.
2022-05-14 05:46:57 ERROR   ::MAIN: A problem was reported in the autoProcess* script. If torrent was paused we will resume seeding
2022-05-14 05:46:57 DEBUG   ::MAIN: Starting torrent GoldenEye.1995.INTERNAL.2160p.WEB.H265-DEFLATE in transmission
2022-05-14 05:47:02 ERROR   ::MAIN: A problem was reported in the /config/nzbToMedia/TorrentToMedia.py script.
```

**Comment by clinton-hall** [comment]
so it looks like the files aren't moved within 6 minutes...
Can you see (either in Radar logs, or perhaps with file timestamps) what time the files were moved to the destination?
You can try increasing the length of `wait_for = 6` if this is the issue.

**Comment by Jelmerb** [comment]
Hi Clinton, thanks for the quick reply. The files aren't moved between volumes and in the past Radarr or nzbToMedia didn't have problems moving large files at all. 

I found this error in the Radarr logs. 

```
2022-05-14 05:40:53.8|Warn|DownloadedMovieCommandService|External directory scan request for unknown download 1ab3285e18217cd58cc57f21198f0a32d22d9964, attempting normal import. [/downloads/processed/movie/GoldenEye.1995.INTERNAL.2160p.WEB.H265-DEFLATE]
2022-05-14 05:42:56.8|Error|CommandExecutor|Error occurred while executing task ProcessMonitoredDownloads

[v4.1.0.6175] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 379
   at NzbDrone.Core.Datastore.BasicRepository`1.SetFields(TModel model, Expression`1[] properties) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 329
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 113
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44
```

**Comment by Jelmerb** [comment]
I am downloading a 21.1 gb file now and increased the `wait_for` propertie to 30 minutes which should be long enough.

**Comment by Jelmerb** [comment]
OK, so you were right. No problems now after increasing the `wait_for` property. It took Radarr 10 minutes to move the 21,1 GB file so I think I will increase it to 60 minutes just to be sure. Strange, this is the first time I encountered this problem. All the folders the files are moved between are on the same volume. Probably has something to do with transmission/nzbToMedia and Radarr running in different Docker containers.
