### ISSUE TITLE
Post Processing failing since 3 days ago

### ISSUE THREAD

**Issue by GTunney** [clinton-hall/nzbToMedia#1897]
**Describe the bug**
Unable to post process anything from Watcher3 or SickGear since 3 days ago

**Technical Specs**
1. Linux QNAP NAS
2. Python 3.10.5
3. SabNzbD
4.  SickGear and Watcher3

**Expected behavior**
Media files should be post processed if complete or post processing should mark as failed

**Log**
`[13:31:06] [INFO]::MAIN: Loading config from [/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/autoProcessMedia.cfg]
[13:31:06] [INFO]::MAIN: Python v3.10 will reach end of life in 1484 days.
[13:31:06] [INFO]::MAIN: Checking database structure...
[13:31:06] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[13:31:06] [DEBUG]::MAIN: InitialSchema upgrade not required
[13:31:06] [DEBUG]::MAIN: Checking if we can use git commands: "/opt/bin/git" version
[13:31:06] [DEBUG]::MAIN: Executing "/opt/bin/git" version with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:06] [DEBUG]::MAIN: git output: git version 2.34.3
[13:31:06] [DEBUG]::MAIN: "/opt/bin/git" version : returned successful
[13:31:06] [DEBUG]::MAIN: Using: "/opt/bin/git"
[13:31:06] [DEBUG]::MAIN: Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:06] [DEBUG]::MAIN: git output: refs/heads/master
[13:31:06] [DEBUG]::MAIN: "/opt/bin/git" symbolic-ref -q HEAD : returned successful
[13:31:06] [INFO]::MAIN: Checking if git needs an update
[13:31:06] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:06] [DEBUG]::MAIN: git output: 7436ba77161af412c00e745e13149576da583721
[13:31:06] [DEBUG]::MAIN: "/opt/bin/git" rev-parse HEAD : returned successful
[13:31:06] [DEBUG]::MAIN: Executing "/opt/bin/git" fetch origin with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:10] [DEBUG]::MAIN: git output:
[13:31:10] [DEBUG]::MAIN: "/opt/bin/git" fetch origin : returned successful
[13:31:10] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse --verify --quiet '@{upstream}' with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:10] [DEBUG]::MAIN: git output: 7436ba77161af412c00e745e13149576da583721
[13:31:10] [DEBUG]::MAIN: "/opt/bin/git" rev-parse --verify --quiet '@{upstream}' : returned successful
[13:31:10] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-list --left-right '@{upstream}'...HEAD with your shell in /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia
[13:31:10] [DEBUG]::MAIN: git output:
[13:31:10] [DEBUG]::MAIN: "/opt/bin/git" rev-list --left-right '@{upstream}'...HEAD : returned successful
[13:31:10] [DEBUG]::MAIN: cur_commit = 7436ba77161af412c00e745e13149576da583721 % (newest_commit)= 7436ba77161af412c00e745e13149576da583721, num_commits_behind = 0, num_commits_ahead = 0
[13:31:10] [INFO]::MAIN: No update needed
[13:31:10] [INFO]::MAIN: nzbToMedia Version:7436ba77161af412c00e745e13149576da583721 Branch:master (Linux 5.10.60-qnap)
[13:31:10] [INFO]::MAIN: #########################################################
[13:31:10] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[13:31:10] [INFO]::MAIN: #########################################################
[13:31:10] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToSickBeard.py', '/share/Download/TV/Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX.1', 'Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX', 'Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX', '', 'tv', 'None', '-1', '']
[13:31:10] [INFO]::MAIN: Script triggered from SABnzbd Version 3.6.1.
[13:31:10] [DEBUG]::MAIN: Adding NZB download info for directory /share/Download/TV/Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX.1 to database
[13:31:12] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[13:31:12] [DEBUG]::MAIN: Checking for archives to extract in directory: /share/Download/TV/Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX.1
[13:31:12] [INFO]::MAIN: Calling SickBeard:tv to post-process:Brassic.S04E01.Getting.There.1080p.AHDTV.x264-DARKFLiX
[13:31:12] [DEBUG]::SERVER: Attempting to connect to server at https://localhost:5004
Changing to directory: /share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToSickBeard.py", line 278, in <module>
result = nzbToMedia.main(sys.argv, section)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 971, in main
result = process(os.environ['SAB_COMPLETE_DIR'], input_name=os.environ['SAB_FINAL_NAME'], status=int(os.environ['SAB_PP_STATUS']),
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/nzbToMedia.py", line 858, in process
result = tv.process(section_name, input_directory, input_name, status, client_agent, download_id, input_category, failure_link)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/auto_process/tv.py", line 63, in process
if server_responding('{0}{1}:{2}{3}'.format(protocol, host, port, web_root)):
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/core/utils/network.py", line 81, in server_responding
requests.get(base_url, timeout=(60, 120), verify=False)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/connectionpool.py", line 597, in urlopen
httplib_response = self._make_request(conn, method, url,
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/connectionpool.py", line 343, in _make_request
self._validate_conn(conn)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/connectionpool.py", line 839, in _validate_conn
conn.connect()
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/connection.py", line 330, in connect
self.ssl_context = create_urllib3_context(
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/util/ssl_.py", line 264, in create_urllib3_context
context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)
File "/share/CACHEDEV1_DATA/.qpkg/nzbToMedia/nzbToMedia/libs/common/urllib3/contrib/pyopenssl.py", line 391, in __init__
self._ctx = OpenSSL.SSL.Context(self.protocol)
File "/opt/lib/python3.10/site-packages/OpenSSL/SSL.py", line 674, in __init__
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'`

**Comment by GTunney** [comment]
Managed to resolve with a removal and reinstall of nzbtomedia.
