### ISSUE TITLE
sabnzbd error

### ISSUE THREAD

**Issue by landcraft** [clinton-hall/nzbToMedia#1953]
**Describe the bug**
Downloads are processed, but I get an error in SABnzbd

**Technical Specs**
1. Running on Ubuntu
2. Python version 3.10.6
3. Download Client SABnbzd
4. Intended Media Management Radarr

**Expected behavior**
nzbToRadarr.py script should run without errors

**Log**
/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")
Changing to directory: /nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'
Returning to directory:  /app/sabnzbd

-- Cleanup finished --

Traceback (most recent call last):
File "/nzbToMedia/nzbToRadarr.py", line 269, in <module>
import nzbToMedia
File "/nzbToMedia/nzbToMedia.py", line 734, in <module>
import core
File "/nzbToMedia/core/__init__.py", line 52, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "/nzbToMedia/core/databases.py", line 11, in <module>
from core.utils import backup_versioned_file
File "/nzbToMedia/core/utils/__init__.py", line 14, in <module>
from core.utils.download_info import get_download_info, update_download_info_status
File "/nzbToMedia/core/utils/download_info.py", line 14, in <module>
database = main_db.DBConnection()
File "/nzbToMedia/core/main_db.py", line 65, in __init__
self.connection = sqlite3.connect(db_filename(filename), 20)
sqlite3.OperationalError: unable to open database file

**Comment by labrys** [comment]
Please verify the database file exists and the permissions on the file.

**Comment by landcraft** [comment]
> 

where is the database meant to be?

**Comment by labrys** [comment]
It should be in the same folder as the nzbToMedia scripts and should be called nzbtomedia.db.

**Comment by landcraft** [comment]
it's not there - how do I create it? this is a new install...

**Comment by labrys** [comment]
It should be created on first launch.  If it is not, then there are likely permissions errors for the folder.

**Comment by labrys** [comment]
@landcraft verify that the user running sab has access to the nzbToMedia directory

**Comment by landcraft** [comment]
okay I've chowned and chmodded the directory. will test

**Comment by landcraft** [comment]
tested and works! thanks for the help.
Now I'm seeing a couple of other errors:
```[18:15:19] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/local/bin/git" version
[18:15:19] [DEBUG]::MAIN: Executing "/usr/local/bin/git" version with your shell in /nzbToMedia
[18:15:19] [DEBUG]::MAIN: git output: /bin/sh: /usr/local/bin/git: not found
[18:15:19] [DEBUG]::MAIN: "/usr/local/bin/git" version returned : /bin/sh: /usr/local/bin/git: not found, treat as error for now
[18:15:19] [DEBUG]::MAIN: Not using: "/usr/local/bin/git"
[18:15:19] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
[18:15:19] [DEBUG]::MAIN: No git specified, can't use git commands
[18:15:19] [INFO]::MAIN: Checking if git needs an update
[18:15:19] [DEBUG]::MAIN: No git specified, can't use git commands
[18:15:19] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!```
and I'm still getting this:
```-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'

-- Cleaning folders: ['libs', 'core'] --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'
Returning to directory:  /app/sabnzbd

-- Cleanup finished --```

Any advice?

**Comment by labrys** [comment]
Those are warnings only, so they can be ignored.  Question, how did you install?

**Comment by landcraft** [comment]
git clone

**Comment by labrys** [comment]
@landcraft See this line in the output:
```
[18:15:19] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
```

**Comment by landcraft** [comment]
it might be because I'm running everything (radarr, sab etc) in containers?

**Comment by labrys** [comment]
Probably so git is probably not available.  As the log entry suggests, try deleting the .git folder.

**Comment by landcraft** [comment]
is it worth trying to find a way to install git in the containers, or not worth the hassle, you think?

**Comment by labrys** [comment]
I've always used git updates but there is a source update manager which should work just fine for you.  Just as an fyi, in the future nzbToMedia will be installed as a library and you'll be able to use pip to update it so git will no longer be necessary.

**Comment by landcraft** [comment]
OK great. many thanks for your help!
