### ISSUE TITLE
Error on synology

### ISSUE THREAD

**Issue by shizo971** [clinton-hall/nzbToMedia#1960]
**Describe the bug**

**Technical Specs**
1. Running on Synology DS918+
2. Python version '3.11.1-2'
3. Download Client "SABnbzd"
4. Intended Media Management "Medusa"

**Expected behavior**
The script doesn't run anymore on my DS918+

**Log**
Traceback (most recent call last):
File "/volume1/@appdata/sabnzbd/scripts/nzbToMedia/nzbToMedia.py", line 732, in <module>
eol.check()
File "/volume1/@appdata/sabnzbd/scripts/nzbToMedia/eol.py", line 101, in check
warn_for_status(version, grace_period)
File "/volume1/@appdata/sabnzbd/scripts/nzbToMedia/eol.py", line 142, in warn_for_status
days_left = lifetime(version)
^^^^^^^^^^^^^^^^^
File "/volume1/@appdata/sabnzbd/scripts/nzbToMedia/eol.py", line 72, in lifetime
time_left = PYTHON_EOL[(major, minor)] - now
~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: (3, 11)

I don't know how to solve this.

Best regards.

**Comment by shizo971** [comment]
Add (3, 11) line and everything is ok

PYTHON_EOL = {
    (3, 11): date('2027-10-02'),
    (3, 10): date('2026-10-01'),

**Comment by clinton-hall** [comment]
what branch / commit are you on?
Current master already has 3.11 support added.

**Comment by shizo971** [comment]
Hello, thank your for your feedback

I'm in the master branch.

Below is the functional script :

[21:02:20] [INFO]::MAIN: Loading config from
***@***.***/sabnzbd/scripts/nzbToMedia/autoProcessMedia.cfg]
[21:02:20] [INFO]::MAIN: Python v3.11 will reach end of life in 1720 days.
[21:02:20] [INFO]::MAIN: Checking database structure...
[21:02:20] [INFO]::MAIN: Checking if git needs an update
[21:02:20] [ERROR]::MAIN: Unable to determine installed version via
git, please check your logs!
[21:02:20] [INFO]::MAIN: No update needed
[21:02:20] [INFO]::MAIN: nzbToMedia Version:12.1.10 Branch:master
(Linux 4.4.180+)
[21:02:20] [INFO]::MAIN:
#########################################################
[21:02:20] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[21:02:20] [INFO]::MAIN:
#########################################################
[21:02:20] [INFO]::MAIN: Script triggered from SABnzbd Version 3.7.1.
[21:02:20] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[21:02:20] [INFO]::MAIN: Calling SickBeard:series to post-process:The
Last of Us S01E01 When Youre Lost in the Darkness 1080p AMZN WEB-DL
DDP5 1 H 264-NTb
[21:02:20] [INFO]::MAIN: SickBeard:series fork set to Medusa-apiv2
[21:02:20] [INFO]::MAIN: FLATTEN: Flattening directory:
/volume1/Telechargement/sabnzbd/complet/series/The Last of Us S01E01
When Youre Lost in the Darkness 1080p AMZN WEB-DL DDP5 1 H 264-NTb
[21:02:20] [INFO]::TRANSCODER: Checking
[The.Last.of.Us.S01E01.When.Youre.Lost.in.the.Darkness.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv]
for corruption, please stand by ...
[21:02:20] [INFO]::TRANSCODER: SUCCESS:
[The.Last.of.Us.S01E01.When.Youre.Lost.in.the.Darkness.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv]
has no corruption.
[21:02:20] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded,
sending a post-process request


Best regards.



Le mar. 17 janv. 2023 à 05:06, Clinton Hall ***@***.***> a
écrit :

**Comment by shizo971** [comment]
i think the commit is 27669389 

 master: 27669389 V12.1.10

**Comment by clinton-hall** [comment]
yes, there have been updates since that.
If you do a git pull you should get on to the latest version and all should work with Py 3.11

**Comment by shizo971** [comment]
Thank you, eveything is ok now with git and updates :)

[22:24:52] [INFO]::MAIN: Loading config from [/volume1/@appdata/sabnzbd/scripts/nzbToMedia/autoProcessMedia.cfg]
[22:24:52] [INFO]::MAIN: Python v3.11 will reach end of life in 1706 days.
[22:24:52] [INFO]::MAIN: Checking database structure...
[22:24:52] [INFO]::MAIN: Checking if git needs an update
[22:24:53] [INFO]::MAIN: No update needed
[22:24:53] [INFO]::MAIN: nzbToMedia Version:bd9c91ff5e8ee801d9b7a52843a2be8317eb688e Branch:master (Linux 4.4.180+)
[22:24:53] [INFO]::MAIN: #########################################################
[22:24:53] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[22:24:53] [INFO]::MAIN: #########################################################
[22:24:53] [INFO]::MAIN: Script triggered from SABnzbd 3.7.1.
[22:24:53] [INFO]::MAIN: Auto-detected SECTION:SickBeard
