### ISSUE TITLE
Updated to Python 3.12.2 on the Mac and now erroring out in EOL?

### ISSUE THREAD

**Issue by rr0ss0rr** [clinton-hall/nzbToMedia#1985]
Running on a Mac and Homebrew updated python last night to 3.12.2 and am now receiving the following in the nzbget log (I restarted the Mac to see if it cleared up the error (it did not):

```
ERROR	Thu Feb 22 2024 10:04:04	Post-process-script nzbToSickBeard.py for My Show s01e01.720p.WEB.H264-ROPATA failed (terminated with unknown status)
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: KeyError: (3, 12)
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: ~~~~~~~~~~^^^^^^^^^^^^^^^^
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: time_left = PYTHON_EOL[(major, minor)] - now
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: File "/Applications/nzbToMedia/eol.py", line 73, in lifetime
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: ^^^^^^^^^^^^^^^^^
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: days_left = lifetime(version)
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: File "/Applications/nzbToMedia/eol.py", line 143, in warn_for_status
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: warn_for_status(version, grace_period)
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: File "/Applications/nzbToMedia/eol.py", line 102, in check
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: eol.check()
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: File "/Applications/nzbToMedia/nzbToMedia.py", line 731, in <module>
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: import nzbToMedia
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: File "/Applications/nzbToMedia/nzbToSickBeard.py", line 275, in <module>
INFO	Thu Feb 22 2024 10:04:04	nzbToSickBeard: Traceback (most recent call last):
INFO	Thu Feb 22 2024 10:04:04	Executing post-process-script nzbToSickBeard.py for My Show s01e01.720p.WEB.H264-ROPATA
```

NZBGet is also setup with *ShellOverride*(`.py=/usr/local/bin/python3`)
Thanks

**UPDATE**
It seems Medusa is not starting with python 3.12 erroring out on 
`register_finder(pkgutil.ImpImporter, find_on_path)`
Due to the removal of the long-deprecated pkgutil.ImpImporter class

Downgraded python to 3.11 and everything is back to normal

**Comment by DrakeJones** [comment]
Try adding `(3, 12): date('2028-10-1')` to eol.py.

**Comment by rr0ss0rr** [comment]
Thanks .. That makes sense ;-)
