### ISSUE TITLE
NzbToMedia from a kubernetes pod (truenas)

### ISSUE THREAD

**Issue by fadern** [clinton-hall/nzbToMedia#1994]
**Describe the bug**
Hi,
I'm currently trying to migrate from my Synology nas to a new Truenas scale installation.
Sabnzbd and sickchill are up and running in the new environment but I have some trouble to get this great script working.
The script is located at a seperate dataset that is mounted into the pod. Sabnzbd have access to the script.
It seems that the pod is missing GIT but the script should maybe be able to run without it?
Python is at v3.12 so I had to edit the eol.py a bit.  @LN     (3, 12): date('2028-10-31'),
Now the script goes a bit further but it exits with this.. See **Log**

**Technical Specs**
1. Running on (Windows, Linux, NAS Model etc) 'TrueNas Scale'
2. Python version '3.12'
3. Download Client  'SABnbzd'
4. Intended Media Management 'SickChill'

**Expected behavior**
The script to run successfully 

**Log**
`Changing to directory: /mnt/nzbToMedia

-- Cleaning bytecode --
WARNING: Automatic cleanup could not be executed.
If errors occur, manual cleanup may be required.
REASON : Error: [Errno 2] No such file or directory: 'git'

Directory is not a git repository

Force cleaning folder: libs
Skipping required subfolders ['common', 'custom', 'py2', 'win']

Force cleaning folder: core
Skipping required subfolders ['auto_process', 'extractor', 'plugins', 'processor', 'utils']
Returning to directory:  /app

-- Cleanup finished --

/mnt/nzbToMedia/libs/common/beets/mediafile.py:19: UserWarning: beets.mediafile is deprecated; use mediafile instead
warnings.warn("beets.mediafile is deprecated; use mediafile instead")
Traceback (most recent call last):
File "/mnt/nzbToMedia/nzbToMedia.py", line 734, in <module>
import core
File "/mnt/nzbToMedia/core/__init__.py", line 52, in <module>
from core import logger, main_db, version_check, databases, transcoder
File "/mnt/nzbToMedia/core/databases.py", line 11, in <module>
from core.utils import backup_versioned_file
File "/mnt/nzbToMedia/core/utils/__init__.py", line 13, in <module>
from core.utils.common import clean_dir, flatten, get_dirs, process_dir
File "/mnt/nzbToMedia/core/utils/common.py", line 14, in <module>
from core.utils.files import list_media_files, move_file
File "/mnt/nzbToMedia/core/utils/files.py", line 15, in <module>
import guessit
File "/mnt/nzbToMedia/libs/common/guessit/__init__.py", line 8, in <module>
from .api import guessit, GuessItApi
File "/mnt/nzbToMedia/libs/common/guessit/api.py", line 20, in <module>
from .rules import rebulk_builder
File "/mnt/nzbToMedia/libs/common/guessit/rules/__init__.py", line 11, in <module>
from .properties.episodes import episodes
File "/mnt/nzbToMedia/libs/common/guessit/rules/properties/episodes.py", line 16, in <module>
from .title import TitleFromPosition
File "/mnt/nzbToMedia/libs/common/guessit/rules/properties/title.py", line 11, in <module>
from .language import (
File "/mnt/nzbToMedia/libs/common/guessit/rules/properties/language.py", line 10, in <module>
import babelfish
File "/mnt/nzbToMedia/libs/common/babelfish/__init__.py", line 14, in <module>
from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
File "/mnt/nzbToMedia/libs/common/babelfish/converters/__init__.py", line 5, in <module>
from pkg_resources import iter_entry_points, EntryPoint
File "/mnt/nzbToMedia/libs/common/pkg_resources/__init__.py", line 57, in <module>
from pkg_resources.extern import six
ImportError: cannot import name 'six' from 'pkg_resources.extern' (/mnt/nzbToMedia/libs/common/pkg_resources/extern/__init__.py)`

**Comment by fadern** [comment]
I saw that the nightly had some python 3.12 commits so I tried it and turned out working good.
