### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data

### ISSUE THREAD

**Issue by p0psicles** [clinton-hall/nzbToMedia#565]
Postproc of The Big Bang Theory - 7x16 - La Polarizacion De La Mesa [Web-Dl 1080p][Dual+Subtítulos]

```
      [12:46:42] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
```

[12:46:42] [INFO]::MAIN: Checking database structure...
[12:46:42] [INFO]::MAIN: Database upgrade required: Initial Schema
[12:46:42] [INFO]::MAIN: Checking if git needs an update
[12:46:43] [INFO]::MAIN: No update needed
[12:46:43] [INFO]::MAIN: nzbToMedia Version:d904aafb99938455e3fed45d70d392eb021f1da8 Branch:master (Linux 3.2.0-4-686-pae)
[12:46:43] [ERROR]::MAIN: Failed to connect to Transmission
[12:46:43] [INFO]::MAIN: #########################################################
[12:46:43] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[12:46:43] [INFO]::MAIN: #########################################################
[12:46:43] [INFO]::MAIN: Script triggered from SABnzbd
Traceback (most recent call last):
  File "/opt/nzbToMedia/nzbToSickBeard.py", line 255, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/opt/nzbToMedia/nzbToMedia.py", line 691, in main
    download_id='')
  File "/opt/nzbToMedia/nzbToMedia.py", line 514, in process
    encoded, inputDirectory1 = CharReplace(inputDirectory)
  File "/opt/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 355, in CharReplace
    if ((Name[Idx] == '\xC2') | (Name[Idx] == '\xC3')) & ((Name[Idx+1] >= '\xA0') & (Name[Idx+1] <= '\xFF')):
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x955b36c>> ignore

**Comment by snout1979** [comment]
Sorry for the late reply. pyicu had do be installed (i did this with pip), but it depends on the C/C++ libraries provided by ICU (http://site.icu-project.org). Both pyicu and ICU are cross-platform, though...

**Comment by clinton-hall** [comment]
interesting.... I might try and add this but have a try/except incase the libs can't be loaded.
