### ISSUE TITLE
error on manual run

### ISSUE THREAD

**Issue by Jorman** [clinton-hall/nzbToMedia#625]
Hi, after I saw that a movie is not automatically renamed, I tried to do a manual run, but this is the error that I see on console:

[/share/CACHEDEV1_DATA/scripts/nzbToMedia] # ./nzbToMedia.py
[21:05:54] [INFO]::MAIN: Loading config from [/share/CACHEDEV1_DATA/scripts/nzbToMedia/autoProcessMedia.cfg]
[21:05:54] [INFO]::MAIN: Checking database structure...
[21:05:54] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[21:05:54] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[21:05:54] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[21:05:54] [DEBUG]::MAIN: InitialSchema upgrade not required
[21:05:54] [DEBUG]::MAIN: Checking if we can use git commands: "/opt/bin/git" version
[21:05:54] [DEBUG]::MAIN: Executing "/opt/bin/git" version with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:54] [DEBUG]::MAIN: "/opt/bin/git" version : returned successful
[21:05:54] [DEBUG]::MAIN: Using: "/opt/bin/git"
[21:05:54] [DEBUG]::MAIN: Executing "/opt/bin/git" symbolic-ref -q HEAD with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:54] [DEBUG]::MAIN: "/opt/bin/git" symbolic-ref -q HEAD : returned successful
[21:05:54] [INFO]::MAIN: Checking if git needs an update
[21:05:54] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse HEAD with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:54] [DEBUG]::MAIN: "/opt/bin/git" rev-parse HEAD : returned successful
[21:05:54] [DEBUG]::MAIN: Executing "/opt/bin/git" fetch origin with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:55] [DEBUG]::MAIN: "/opt/bin/git" fetch origin : returned successful
[21:05:55] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:55] [DEBUG]::MAIN: "/opt/bin/git" rev-parse --verify --quiet "@{upstream}" : returned successful
[21:05:55] [DEBUG]::MAIN: Executing "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /share/CACHEDEV1_DATA/scripts/nzbToMedia
[21:05:55] [DEBUG]::MAIN: "/opt/bin/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
[21:05:55] [DEBUG]::MAIN: cur_commit = 9b143cd6f2eb2edc14f32149ed9e4532c3ecd7c6 % (newest_commit)= 9b143cd6f2eb2edc14f32149ed9e4532c3ecd7c6, num_commits_behind = 0, num_commits_ahead = 0
[21:05:55] [INFO]::MAIN: No update needed
[21:05:55] [INFO]::MAIN: nzbToMedia Version:9b143cd6f2eb2edc14f32149ed9e4532c3ecd7c6 Branch:dev (Linux 3.4.6)
[21:05:56] [DEBUG]::MAIN: Connecting to transmission: http://localhost:9091
[21:05:56] [INFO]::MAIN: #########################################################
[21:05:56] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[21:05:56] [INFO]::MAIN: #########################################################
[21:05:56] [DEBUG]::MAIN: Options passed into nzbToMedia: ['./nzbToMedia.py']
[21:05:56] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[21:05:56] [INFO]::MAIN: Searching /share/CACHEDEV1_DATA/Download/automatics/complete/torrent/movie for mediafiles to post-process ...
[21:05:56] [INFO]::MAIN: Searching /share/CACHEDEV1_DATA/Download/automatics/process/movie for mediafiles to post-process ...
[21:05:56] [INFO]::MAIN: Starting manual run for CouchPotato:movie - Folder:/share/CACHEDEV1_DATA/Download/automatics/process/movie/As.Above.So.Below-Necropolis.La.Città.Dei.Morti.2014.iTALiAN.DTS.Dual.1080p.BluRay.x264-TrTd_TeaM
[21:05:56] [INFO]::MAIN: Checking database for download info for As.Above.So.Below-Necropolis.La.Città.Dei.Morti.2014.iTALiAN.DTS.Dual.1080p.BluRay.x264-TrTd_TeaM ...
[21:05:56] [DB]::DB: Getting download info for As.Above.So.Below-Necropolis.La.Città.Dei.Morti.2014.iTALiAN.DTS.Dual.1080p.BluRay.x264-TrTd_TeaM from the DB
[21:05:56] [DB]::MAIN: nzbtomedia.db: SELECT \* FROM downloads WHERE input_name=? AND status=? with args [u'As.Above.So.Below-Necropolis.La.Citt\xe0.Dei.Morti.2014.iTALiAN.DTS.Dual.1080p.BluRay.x264-TrTd_TeaM', 0]
[21:05:56] [INFO]::MAIN: Unable to locate download info for As.Above.So.Below-Necropolis.La.Città.Dei.Morti.2014.iTALiAN.DTS.Dual.1080p.BluRay.x264-TrTd_TeaM, continuing to try and process this release ...
[21:05:56] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
Traceback (most recent call last):
  File "./nzbToMedia.py", line 775, in <module>
    exit(main(sys.argv))
  File "./nzbToMedia.py", line 750, in main
    download_id=download_id, inputCategory=subsection)
  File "./nzbToMedia.py", line 570, in process
    inputName, inputDirectory = convert_to_ascii(inputName, inputDirectory)
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 394, in convert_to_ascii
    encoded, inputName = CharReplace(inputName)
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 363, in CharReplace
    if ((Name[Idx] == '\xC2') | (Name[Idx] == '\xC3')) & ((Name[Idx+1] >= '\xA0') & (Name[Idx+1] <= '\xFF')):
  File "/opt/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x8b4abec>> ignored

**Comment by milefork** [comment]
Confirmed. http://pastebin.com/gZXVrwdX
