### ISSUE TITLE
Noob help please

### ISSUE THREAD

**Issue by pohq** [clinton-hall/nzbToMedia#650]
Hi Team, I have installed CP and Sickbeard, on my Sinology NAS everything is working GREAT. I have the below errors in SABNZBD though. There is zero "error" logs as such in SAB, CP or Sickbeard As I say EVERYTHING is working and I could just ignore these but my OCD won't let me! Any help for a noob would be appreciated. Logs below. I'm using a Sinology NAS and Macbook. 

Thanks.

           Traceback (most recent call last):
  File "/usr/local/sabnzbd/var/scripts/nzbToCouchPotato.py", line 247, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia.py", line 612, in main
    nzbtomedia.initialize(section)
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbtomedia/__init__.py", line 255, in initialize
    if not config.migrate():
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbtomedia/nzbToMediaConfig.py", line 237, in migrate
    CFG_NEW.write()
  File "/volume1/@appstore/sabnzbd/var/scripts/libs/configobj/configobj.py", line 2120, in write
    with open(self.filename, 'wb') as h:
IOError: [Errno 13] Permission denied: '/volume1/@appstore/sabnzbd/var/scripts/autoProcessMedia.cfg'
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x2c1428f0>> ignored

**Comment by pohq** [comment]
Hi Clinton, 24hrs later and I'm all good now. Just wanted to say thanks.

**Comment by clinton-hall** [comment]
glad it is working. please let me know if you have any further issues.
