### ISSUE TITLE
Post processing errors

### ISSUE THREAD

**Issue by thomass02** [clinton-hall/nzbToMedia#655]
Running windows 7. This is what I get from sabnzb:
Traceback (most recent call last):
File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 782, in 
exit(main(sys.argv))
File "C:\SickRage\Scripts\nzbToMedia\nzbToMedia.py", line 612, in main
nzbtomedia.initialize(section)
File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia__init__.py", line 221, in initialize
MYAPP = RunningProcess()
File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia\nzbToMediaUtil.py", line 1098, in init
self.process = WindowsProcess()
File "C:\SickRage\Scripts\nzbToMedia\nzbtomedia\nzbToMediaUtil.py", line 1113, in init
from win32event import CreateMutex
ImportError: No module named win32event
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'" in > ignored

Please help. I have my python path variables. Changed all the nessessary info on the autoprocessMedia.cfg file. Have my categories set up correctly in sab.

Thanks

**Comment by clinton-hall** [comment]
Please make sure you have Python installed with the correct (matching) pywin installed.
Currently your Python does not include a win32event module (this is installed by pywin)

**Comment by thomass02** [comment]
I did this them I get the error in issue number 656. :-(

**Comment by clinton-hall** [comment]
#656
