### ISSUE TITLE
AttributeError: 'module' object has no attribute 'STARTUPINFO'

### ISSUE THREAD

**Issue by Tjiet** [clinton-hall/nzbToMedia#676]
With the latest dev build on OSX an error occurs when running the pp.

           Traceback (most recent call last):
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbToSickBeard.py", line 252, in <module>
    import nzbToMedia
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbToMedia.py", line 491, in <module>
    import nzbtomedia
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbtomedia/__init__.py", line 28, in <module>
    from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbtomedia/autoProcess/autoProcessComics.py", line 6, in <module>
    from nzbtomedia.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbtomedia/nzbToMediaUtil.py", line 19, in <module>
    from nzbtomedia.linktastic import linktastic
  File "/Users/tjiet/Documents/Sabnzbd/Scripts/nzbtomedia/linktastic/linktastic.py", line 28, in <module>
    info = subprocess.STARTUPINFO()
AttributeError: 'module' object has no attribute 'STARTUPINFO'

**Comment by swno** [comment]
Same error here on debian, after manual start (do not know for automatic start)
```
Traceback (most recent call last):
  File ".nzbtomedia/TorrentToMedia.py", line 7, in <module>
    import nzbtomedia
  File "/home/tomtom/.nzbtomedia/nzbtomedia/__init__.py", line 28, in <module>
    from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
  File "/home/tomtom/.nzbtomedia/nzbtomedia/autoProcess/autoProcessComics.py", line 6, in <module>
    from nzbtomedia.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/home/tomtom/.nzbtomedia/nzbtomedia/nzbToMediaUtil.py", line 19, in <module>
    from nzbtomedia.linktastic import linktastic
  File "/home/tomtom/.nzbtomedia/nzbtomedia/linktastic/linktastic.py", line 28, in <module>
    info = subprocess.STARTUPINFO()
AttributeError: 'module' object has no attribute 'STARTUPINFO'
```
Commit : 9b2af442d6cc9a39e8431c22bb8521fd6f2394d4
Branch : dev

**Comment by Tjiet** [comment]
The autoupdatr features seems broken, so this needs to be fixed asap and a manual git pull should make it work when it is fixed

**Comment by clinton-hall** [comment]
`info = subprocess.STARTUPINFO()`
this does appear in my code.... can you try deleting the file /home/tomtom/.nzbtomedia/nzbtomedia/linktastic/linktastic.py
then do a `git reset --hard` and try a `git pull`
does the script now run?

**Comment by Tjiet** [comment]
macmedia:linktastic tjiet$ ls
__init__.py     __init__.pyc    linktastic.py   linktastic.pyc
macmedia:linktastic tjiet$ rm linktastic.py
macmedia:linktastic tjiet$ git reset --hard
HEAD is now at 9b2af44 Merge pull request #675 from Jaerin/master
macmedia:linktastic tjiet$ git pull
Already up-to-date.
macmedia:linktastic tjiet$ ls
__init__.py     __init__.pyc    linktastic.py   linktastic.pyc

Same results.

**Comment by clinton-hall** [comment]
`Jaerin/master`
This isn't my repository...

@Jaerin is doing some great work to improve this project... as it turns out this particular feature (which was added to my dev branch (sorry @Jaerin, I should have said nightly...) appears to have an issue with some python instances...

I'll try and look into this...
