### ISSUE TITLE
Script failing, linktastic?

### ISSUE THREAD

**Issue by sgtsquiggs** [clinton-hall/nzbToMedia#690]
I'm using SABnzbd w/ Sickbeard. Everything had been running smoothly for a long time. Lately, every completed download yields the following error:

```
           Traceback (most recent call last):
  File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
    import nzbToMedia
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbToMedia.py", line 491, in <module>
    import nzbtomedia
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbtomedia/__init__.py", line 28, in <module>
    from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbtomedia/autoProcess/autoProcessComics.py", line 6, in <module>
    from nzbtomedia.nzbToMediaUtil import convert_to_ascii, remoteDir, server_responding
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbtomedia/nzbToMediaUtil.py", line 19, in <module>
    from nzbtomedia.linktastic import linktastic
  File "/share/CACHEDEV1_DATA/Download/nzbToMedia/nzbtomedia/linktastic/linktastic.py", line 28, in <module>
    info = subprocess.STARTUPINFO()
AttributeError: 'module' object has no attribute 'STARTUPINFO'
```

**Comment by clinton-hall** [comment]
you are on dev branch?

There was a change made to dev branch by mistake. This has been fixed, but anyone who updated on dev branch during that day will have this...

to fix
```
cd /share/CACHEDEV1_DATA/Download/nzbToMedia
git reset --hard 2864b73
git pull
```

this should fix the issue.

**Comment by clinton-hall** [comment]
and my apologies for this. I have tried to always test commits to ensure the updater itself works... but in this case I tested on nightly but updated on dev...
