### ISSUE TITLE
SSL error with NMA

### ISSUE THREAD

**Issue by Youmi15** [clinton-hall/nzbToMedia#703]
### Steps to reproduce:
When I am testing Notify My Android, I am getting the this SSL error. The API for NMA is correct, as it does work in SickRage. Any ideas? Everything else works though, so it is not really a pressing issue.

Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 5b1dd686 (2015-01-17 13:04:58)

### Logs:
```
02-08 16:50:42 ERROR [          couchpotato.api] Failed doing api request "notify.notifymyandroid.test": Traceback (most recent call last):
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/CouchpotatoV2/main/couchpotato/api.py", line 36, in run_handler
    res = api[route](**kwargs)
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/CouchpotatoV2/main/couchpotato/core/notifications/base.py", line 65, in test
    listener = 'test'
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/CouchpotatoV2/main/couchpotato/core/notifications/base.py", line 50, in _notify
    return self.notify(*args, **kwargs)
  File "/opt/sybhttpd/localhost.drives/SATA_DISK/Apps/CouchpotatoV2/main/couchpotato/core/notifications/notifymyandroid.py", line 27, in notify
    batch_mode = len(keys) > 1
  File "/share/Apps/CouchpotatoV2/main/libs/pynma/pynma.py", line 94, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "/share/Apps/CouchpotatoV2/main/libs/pynma/pynma.py", line 108, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "/share/Apps/local/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/share/Apps/local/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/share/Apps/local/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/share/Apps/local/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/share/Apps/local/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/share/Apps/local/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/share/Apps/local/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/share/Apps/local/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/share/Apps/local/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) 
```

**Comment by clinton-hall** [comment]
Did you mean to post this on the CouchPotatoServer issues page?
This doesn't appear to be related to my scripts.

**Comment by Youmi15** [comment]
Oh haha, wrong place indeed. Sorry about that!

**Comment by clinton-hall** [comment]
no worries...
