### ISSUE TITLE
Couchpotato script not working

### ISSUE THREAD

**Issue by stanthewizzard** [clinton-hall/nzbToMedia#714]
I got this from sabnzbd

           [12:42:42] [INFO]::MAIN: Loading config from [/home/nzb/nzbToMedia/autoProcessMedia.cfg]
[12:42:42] [INFO]::MAIN: Checking database structure...
[12:42:42] [INFO]::MAIN: Checking if git needs an update
[12:42:43] [INFO]::MAIN: No update needed
[12:42:43] [INFO]::MAIN: nzbToMedia Version:77da142216ba6dc91bb654635d4bd03f13c881e5 Branch:master (Linux 3.2.0-4-amd64)
[12:42:43] [INFO]::MAIN: #########################################################
[12:42:43] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[12:42:43] [INFO]::MAIN: #########################################################
[12:42:43] [INFO]::MAIN: Script triggered from SABnzbd
[12:42:43] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[12:42:43] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Ouija.2014.720p.BRRip.XviD.AC3-RARBG.nzb
[12:42:43] [INFO]::MAIN: Attemping imdbID lookup for Ouija.2014.720p.BRRip.XviD.AC3-RARBG.nzb
[12:42:43] [INFO]::MAIN: Searching folder and file names for imdbID ...
[12:42:43] [INFO]::MAIN: Searching IMDB for imdbID ...
[12:42:44] [WARNING]::MAIN: Unable to find a imdbID for Ouija.2014.720p.BRRip.XviD.AC3-RARBG.nzb
[12:42:44] [ERROR]::MAIN: CouchPotato returned the following non-json data
[12:42:44] [ERROR]::MAIN: 
[12:42:44] [ERROR]::MAIN: <!doctype html>
[12:42:44] [ERROR]::MAIN: <html>
[12:42:44] [ERROR]::MAIN: <head>
[12:42:44] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[12:42:44] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[12:42:44] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[12:42:44] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[12:42:44] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[12:42:44] [ERROR]::MAIN: 
[12:42:44] [ERROR]::MAIN: <link rel="stylesheet" href="/couchpotato/minified/front.css?1424723510" type="text/css">
[12:42:44] [ERROR]::MAIN: 
[12:42:44] [ERROR]::MAIN: <script type="text/javascript" src="/couchpotato/minified/front.js?1424723513"></script>
[12:42:44] [ERROR]::MAIN: <link href="/couchpotato/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[12:42:44] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/couchpotato/static/images/homescreen.png" />
[12:42:44] [ERROR]::MAIN: <script type="text/javascript">
[12:42:44] [ERROR]::MAIN: window.addEvent('domready', function(){
[12:42:44] [ERROR]::MAIN: new Form.Check($('remember_me'));
[12:42:44] [ERROR]::MAIN: });
[12:42:44] [ERROR]::MAIN: </script>
[12:42:44] [ERROR]::MAIN: <title>CouchPotato</title>
[12:42:44] [ERROR]::MAIN: </head>
[12:42:44] [ERROR]::MAIN: <body class="page login">
[12:42:44] [ERROR]::MAIN: <form action="" method="post">
[12:42:44] [ERROR]::MAIN: <h1>CouchPotato</h1>
[12:42:44] [ERROR]::MAIN: <div class="ctrlHolder"><input class="inlay" name="username" type="text" placeholder="Username" autocomplete="off" /></div>
[12:42:44] [ERROR]::MAIN: <div class="ctrlHolder"><input class="inlay" name="password" type="password" placeholder="Password" autocomplete="off" /></div>
[12:42:44] [ERROR]::MAIN: <div class="ctrlHolder">
[12:42:44] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input class="inlay" id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[12:42:44] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[12:42:44] [ERROR]::MAIN: </div>
[12:42:44] [ERROR]::MAIN: </form>
[12:42:44] [ERROR]::MAIN: </body>
[12:42:44] [ERROR]::MAIN: </html>
[12:42:44] [ERROR]::TRANSCODER: Checking [/home/nzb/nzbToMedia/tests/test.mp4] has failed
[12:42:44] [INFO]::TRANSCODER: DISABLED: ffprobe failed to analyse test file. Stopping corruption check.
[12:42:44] [ERROR]::TRANSCODER: Checking [/home/nzb/nzbToMedia/tests/test.mp4] has failed
[12:42:44] [INFO]::TRANSCODER: DISABLED: ffprobe failed to analyse test file. Stopping corruption check.
[12:42:44] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Ouija.2014.720p.BRRip.XviD.AC3-RARBG.nzb
Traceback (most recent call last):
  File "/home/nzb/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/home/nzb/nzbToMedia/nzbToMedia.py", line 710, in main
    download_id='')
  File "/home/nzb/nzbToMedia/nzbToMedia.py", line 595, in process
    inputCategory, failureLink)
  File "/home/nzb/nzbToMedia/nzbtomedia/autoProcess/autoProcessMovie.py", line 242, in process
    result = r.json()
  File "/home/nzb/nzbToMedia/libs/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 451, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 402, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 420, in raw_decode
    raise JSONDecodeError("No JSON object could be decoded", s, idx)
simplejson.decoder.JSONDecodeError: No JSON object could be decoded: line 2 column 1 (char 1)
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <bound method PosixProcess.__del__ of <nzbtomedia.nzbToMediaUtil.PosixProcess instance at 0x213b5a8>> ignored

           
Ouija.2014.720p.BRRip.XviD.AC3-RARBG
close

Exit(1) Exception AttributeError: "’NoneType’ object has no attribute ’path’" in (More)
			2015-02-26 12:42:44
 
    22.5 GB Today    39.7 GB This week    128.5 GB This month    128.5 GB Total

**Comment by clinton-hall** [comment]
Can you edit autoProcessMedia.cfg [General] log_debug = 1
Then post logs after the next movie is processed?

Have you put your correct Api key for CouchPotato into autoProcessMedia.cfg?
Are you using any url_base or reverse proxy etc?

**Comment by stanthewizzard** [comment]
I'm sleepy
wrong apikey
work like a charm

I'm ashamed ;)

Flabergasted by your work !

**Comment by clinton-hall** [comment]
It happens.
Please let me know if you encounter any issues.
