### ISSUE TITLE
OT: (Frozen) folders appearing randomly 

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/nzbToMedia#727]
Hey All, 

I apologize for using this forum, but i figured you're all using the same apps I am, so might have knowledge about this.

Randomly, my uTorrent processed folder gets folders rename to include (Frozen) and I'm not sure which app is doing it nor how to stop it.

I'm using Couchpotato, SickRage, Headphones, Mylar, LazyLibrarian, uTorrent and SAB on linux. 

Tried a log search but I can't seem to catch the culprit. Any suggestions appreciated.

**Comment by clinton-hall** [comment]
is this the download complete directory or the processed directory?
is this actually adding the word `Frozen` in there?

**Comment by mgaulton** [comment]
It's the download complete directory, where files from utorrent are
moved (/home/processing moves to /home/processed). A folder called
'Stuff' becomes 'Stuff (Frozen'

**Comment by clinton-hall** [comment]
Can you show the contents of nzbToMedia.log? This will show if the renaming is happening before, during or after the postprocess script.

**Comment by mgaulton** [comment]
I grepped out Frozen and only had one hit.

server5:/opt/nzbtomedia/nzbToMedia/logs # grep 'Frozen' *
nzbtomedia.log.3:    renameUnprocessedFolder(albumpath, tag="Frozen")

This seems to be the relevant portion of the log, relating to headphones, not Sickrage

2015-02-03 20:01:00 DEBUG   ::MAIN: Connecting to utorrent: http://localhost:8087/gui/
2015-02-03 20:01:02 INFO    ::MAIN: #########################################################
2015-02-03 20:01:02 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2015-02-03 20:01:02 INFO    ::MAIN: #########################################################
2015-02-03 20:01:02 DEBUG   ::MAIN: Options passed into TorrentToMedia: ['/opt/nzbtomedia/nzbToMedia/TorrentToMedia.py', '/home/processed/Music', 'Arisen Flame - Hyper (Original Mix).mp3', 'Music', '98BEA56B60AE40E5061C43630D942DE85A4C8384']
2015-02-03 20:01:02 DEBUG   ::MAIN: Adding TORRENT download info for directory /home/processed/Music to database
2015-02-03 20:01:02 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'utorrent', 735632, u'98BEA56B60AE40E5061C43630D942DE85A4C8384', u'98BEA56B60AE40E5061C43630D942DE85A4C8384', u'Arisen Flame - Hyper (Original Mix).mp3', u'/home/processed/Music']
2015-02-03 20:01:02 DEBUG   ::MAIN: Received Directory: /home/processed/Music | Name: Arisen Flame - Hyper (Original Mix).mp3 | Category: Music
2015-02-03 20:01:02 DEBUG   ::MAIN: SEARCH: Found the Category: Music in directory structure
2015-02-03 20:01:02 INFO    ::MAIN: SEARCH: Found torrent file Arisen Flame - Hyper (Original Mix).mp3 in input directory directory /home/processed/Music
2015-02-03 20:01:02 INFO    ::MAIN: SEARCH: Setting inputDirectory to /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:02 DEBUG   ::MAIN: Determined Directory: /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3 | Name: Arisen Flame - Hyper (Original Mix).mp3 | Category: Music
2015-02-03 20:01:02 INFO    ::MAIN: Auto-detected SECTION:HeadPhones
2015-02-03 20:01:02 DEBUG   ::MAIN: Stopping torrent Arisen Flame - Hyper (Original Mix).mp3 in utorrent while processing
2015-02-03 20:01:08 INFO    ::MAIN: Output directory set to: /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 DEBUG   ::MAIN: Scanning files in directory: /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 DEBUG   ::MAIN: Found 1 files in /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 INFO    ::COPYLINK: MEDIAFILE: [Arisen Flame - Hyper (Original Mix).mp3]
2015-02-03 20:01:08 INFO    ::COPYLINK: SOURCE FOLDER: [/home/processed/Music]
2015-02-03 20:01:08 INFO    ::COPYLINK: TARGET FOLDER: [/home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3]
2015-02-03 20:01:08 INFO    ::COPYLINK: SOURCE AND TARGET folders are the same, skipping ...
2015-02-03 20:01:08 INFO    ::MAIN: FLATTEN: Flattening directory: /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 ERROR   ::FLATTEN: Could not flatten /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 INFO    ::MAIN: Calling HeadPhones:Music to post-process:Arisen Flame - Hyper (Original Mix).mp3
2015-02-03 20:01:08 DEBUG   ::EXCEPTION: Replacing file name /home/processed/Music/Arisen Flame - Hyper (Original Mix).mp3 with download name /home/processed/Music/Arisen.Flame.-.Hyper.(Original.Mix).mp3
2015-02-03 20:01:08 DEBUG   ::MAIN: Attempting to get current status for release:Music
2015-02-03 20:01:08 DEBUG   ::MAIN: Opening URL: http://localhost:8181/api with PARAMS: {'cmd': 'getHistory', 'apikey': 'fa1b45d8f6afc176f93205981ef8bb1c'}
2015-02-03 20:01:08 ERROR   ::HEADPHONES: Could not find a status for Arisen Flame - Hyper (Original Mix).mp3, is it in the wanted list ?
2015-02-03 20:01:08 DEBUG   ::HEADPHONES: Opening URL: http://localhost:8181/api with PARAMS: {'cmd': 'forceProcess', 'apikey': 'fa1b45d8f6afc176f93205981ef8bb1c', 'dir': '/home/processed'}
2015-02-03 20:04:44 DEBUG   ::HEADPHONES: Result: <!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/opt/headphones-master/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/headphones-master/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/headphones-master/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/headphones-master/headphones/webserve.py", line 1305, in api
    return a.fetchData()
  File "/opt/headphones-master/headphones/api.py", line 83, in fetchData
    methodToCall(**self.kwargs)
  File "/opt/headphones-master/headphones/api.py", line 328, in _forceProcess
    postprocessor.forcePostProcess(self.dir)
  File "/opt/headphones-master/headphones/postprocessor.py", line 1230, in forcePostProcess
    verify(rgid, folder)
  File "/opt/headphones-master/headphones/postprocessor.py", line 106, in verify
    renameUnprocessedFolder(albumpath, tag="Frozen")
  File "/opt/headphones-master/headphones/postprocessor.py", line 1046, in renameUnprocessedFolder
    os.rename(path, new_path)
OSError: [Errno 2] No such file or directory
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>

2015-02-03 20:04:44 ERROR   ::HEADPHONES: Server returned status 500
2015-02-03 20:04:44 ERROR   ::MAIN: A problem was reported in the autoProcess* script. If torrent was paused we will resume seeding
2015-02-03 20:04:44 DEBUG   ::MAIN: Starting torrent Arisen Flame - Hyper (Original Mix).mp3 in utorrent

**Comment by clinton-hall** [comment]
So the culprit is HeadPhones... For whatever reason it is renaming it to frozen, thinking the whole directory is the frozen album.

Nothing in my script passed any album details in to HeadPhones.

**Comment by mgaulton** [comment]
Yea, I had a suspicion that might be the case. I'm using the uTorrent
API piece of Headphones, rather than blackhole.
