### ISSUE TITLE
Unable to get this to work with Vuze or Deluge

### ISSUE THREAD

**Issue by saitoh183** [clinton-hall/nzbToMedia#734]
I followed the indications in the wiki but it just fails to run

Vuze
```java.io.IOException: Cannot run program "C:\nzbToMedia\TorrentToMedia.py": CreateProcess error=193, %1 is not a valid Win32 application
at java.lang.ProcessBuilder.start(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at java.lang.Runtime.exec(Unknown Source)
at com.aelitis.azureus.plugins.azexec.AzExecPlugin$7.run(AzExecPlugin.java:243)
at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1092)
at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl$4.run(UtilitiesImpl.java:483)
at org.gudy.azureus2.core3.util.AEThread2$threadWrapper.run(AEThread2.java:294)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
at java.lang.ProcessImpl.create(Native Method)
at java.lang.ProcessImpl.<init>(Unknown Source)```

I set it to C:\nzbToMedia\TorrentToMedia.py "%D%N%L%I%K%F"

Vuze : 5.6.0.0
azexec: 1.3.1
Java : 8.0 update 40 (x86 & x64)

Deluge:

see here : http://forum.deluge-torrent.org/viewtopic.php?f=12&t=50423

**Comment by clinton-hall** [comment]
Please make sure you have installed Python and the corresponding PyWin version. Pywin should include the `CreateProcess` module that is causing the error in TorrentToMedia when called from both downloaders.

To Verify, you should be able to manually run the script. If not, no downloader will be able to call it.

**Comment by saitoh183** [comment]
Yes i could run the script manually

![image](https://cloud.githubusercontent.com/assets/1534197/6763208/0a8919e0-cf49-11e4-820e-265e895ccfdd.png)

**Comment by saitoh183** [comment]
@clinton-hall 
manual run of script:

http://pastebin.com/Zh7EDpyr

From vuze it doesnt even start cuz nothing is written to log.

How about Deluge?

**Comment by saitoh183** [comment]
@clinton-hall 

I tried the Test function for the azexec on my download and i sitll get 

org.gudy.azureus2.plugins.PluginException: Failed to create process
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl.createProcess(UtilitiesImpl.java:517)
	at com.aelitis.azureus.plugins.azexec.AzExecPlugin$7.run(AzExecPlugin.java:246)
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1092)
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl$4.run(UtilitiesImpl.java:483)
	at org.gudy.azureus2.core3.util.AEThread2$threadWrapper.run(AEThread2.java:294)
Caused by: java.io.IOException: Cannot run program "C:\nzbToMedia\TorrentToMedia.py": CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl.createProcess(UtilitiesImpl.java:513)
	... 4 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 9 more

I updated pywin from 218 to 219 and i downloaded the amd64 version. even after the install i ran the  pywin32_postinstall.py -install just in case because i was getting the 

close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

at the edn of the normal installation.

**Comment by clinton-hall** [comment]
Have you tried the 32 bit version of Python?

**Comment by saitoh183** [comment]
@clinton-hall 

I will give it a try

**Comment by saitoh183** [comment]
@clinton-hall 

java.io.IOException: Cannot run program "C:\nzbToMedia\TorrentToMedia.py": CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at java.lang.Runtime.exec(Unknown Source)
	at com.aelitis.azureus.plugins.azexec.AzExecPlugin$7.run(AzExecPlugin.java:243)
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1092)
	at org.gudy.azureus2.pluginsimpl.local.utils.UtilitiesImpl$4.run(UtilitiesImpl.java:483)
	at org.gudy.azureus2.core3.util.AEThread2$threadWrapper.run(AEThread2.java:294)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 8 more

sill no go...i reinstall python 32 and pywin32 i tested with a test script that i found on the vuze forum that opens calc and notepad and it works.

**Comment by clinton-hall** [comment]
earlier, when you said you could run the script manually, was this by command line calling python, calling the script directly, or by double-clicking the script?

**Comment by saitoh183** [comment]
@clinton-hall 

cmd python

**Comment by saitoh183** [comment]
@clinton-hall 

If i double click the scripts, it runs also

**Comment by clinton-hall** [comment]
and calling the script directly from command line (not with python)?

**Comment by saitoh183** [comment]
@clinton-hall 

yes that works also

**Comment by clinton-hall** [comment]
have you tried getting vuze to call a batch script that calls TorrentToMedia?

it seems vuze is having issues calling python.

**Comment by saitoh183** [comment]
But if i do that Will i still  be able to pass the variables?

**Comment by clinton-hall** [comment]
Yes... But first let's see if it will start.

**Comment by saitoh183** [comment]
in cmd i just put c:\nzbtomedia\torrenttomedia.py or call python in front?

**Comment by saitoh183** [comment]
@clinton-hall 

Ok..calling a cmd with C:\nzbToMedia\TorrentToMedia.py in it works...

**Comment by clinton-hall** [comment]
Ok, now just have the batch file call

    C:\nzbToMedia\TorrentToMedia.py %1

**Comment by saitoh183** [comment]
ok, but what is tha advantage of calling the variables? since it still processes the file without it.

**Comment by clinton-hall** [comment]
More reliable, as we can match the torrent HASH against CouchPotato releases, we can also pause seeding (and if using the option to delete Torrent, we can do this through vuze)
In general, it. Is more reliable with this info passed in.

**Comment by saitoh183** [comment]
@clinton-hall 

I decided to switch back to deluge and used the method you proposed(cmd). Now it seems to work but i do see this in my log 

2015-03-23 13:15:00 INFO    ::MAIN: ## ..::[TorrentToMedia.py]::.. ##
2015-03-23 13:15:00 INFO    ::MAIN: #########################################################
2015-03-23 13:15:00 DEBUG   ::MAIN: Options passed into TorrentToMedia: ['C:\\nzbToMedia\\TorrentToMedia.py', 'e6e0d52891979fdde94178ce17d8c07aac067ea2']
2015-03-23 13:15:00 WARNING ::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...

I also always have leftover folders in my Completed directory (process directory is cleaned)
![image](https://cloud.githubusercontent.com/assets/1534197/6786975/ded54f02-d165-11e4-9483-75a24369c094.png)


here is the full log:
http://pastebin.com/MW2Fr36T

**Comment by clinton-hall** [comment]
For deluge, you need to pass the 3 parameters

    C:\nzbToMedia\TorrentToMedia.py %1 %2 %3

**Comment by saitoh183** [comment]
@clinton-hall 

Will that also correct leftover files in my Completed folder? I know i should sitll have the orginal file for seeding but i also have another copy from the torrenttomedia process

**Comment by clinton-hall** [comment]
What leftover files? Is this in the TorrentToMedia outputDirectory or the actual directory SickRage renames to?

**Comment by saitoh183** [comment]
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[sickrage]]
        enabled = 1
        host = srv-saitoh-app
        port = 8084
        username = ""
        password = ""
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = auto
        delete_failed = 1
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        process_method = move
        # force processing of already processed content when running a manual scan.
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 1
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = \\SRV-SAITOH-APP\Torrents\Complete\sickrage\

[Torrent]
    ###### clientAgent - Supported clients: utorrent, transmission, deluge, rtorrent, vuze, other
    clientAgent = deluge
    ###### useLink - Set to hard for physical links, sym for symbolic links, move to move, and no to not use links (copy)
    useLink = no
    ###### outputDirectory - Default output directory (categories will be appended as sub directory to outputDirectory)
    outputDirectory = \\SRV-SAITOH-APP\Torrents\TorrentToMedia_process\
    ###### Enter the default path to your default download directory (non-category downloads). this directory is protected by safe_mode. 
    default_downloadDirectory = \\SRV-SAITOH-APP\Torrents\Complete\
    ###### Other categories/labels defined for your downloader. Does not include CouchPotato, SickBeard, HeadPhones, Mylar categories.
    categories = french
    ###### A list of categories that you don't want to be flattened (i.e preserve the directory structure when copying/linking.
    noFlatten = pictures, manual
    ###### uTorrent Hardlink solution (You must edit this if your using TorrentToMedia.py with uTorrent)
    uTorrentWEBui = http://localhost:8081/gui/
    uTorrentUSR = your username
    uTorrentPWD = your password
    ###### Transmission (You must edit this if your using TorrentToMedia.py with uTorrent)
    TransmissionHost = localhost
    TransmissionPort = 8081
    TransmissionUSR = your username
    TransmissionPWD = your password
    #### Deluge (You must edit this if your using TorrentToMedia.py with deluge. Note that the host/port is for the deluge daemon, not the webui)
    DelugeHost = localhost
    DelugePort = 58846
    DelugeUSR = hidden
    DelugePWD = hidden
    ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
    deleteOriginal = 0

and the screenshot above shows that it creates a show folder with a file in it...this is besides the one it creates and deletes in the process folder and the original one that is in the sickrage folder

**Comment by clinton-hall** [comment]
Ah, I see... These can be deleted. This should not happen when triggered by Deluge (with parameters) these were created as part of the "manual run" when it detected single downloads.

**Comment by saitoh183** [comment]
Ah..gotcha..One more thing, deleteOrignial applies to all torrents or can it just apply to a single tag (ie sickrage and not for french)?

**Comment by clinton-hall** [comment]
Delete original applied to all categories.

**Comment by saitoh183** [comment]
Thanks Clinton for all your help. Might want to ajust the wiki for deluge about adding the variables and myabe state that deluge under windows doesnt play well with script execution.
