### ISSUE TITLE
ImportError: cannot import name ProtocolError

### ISSUE THREAD

**Issue by bartley69** [clinton-hall/nzbToMedia#758]
I just updated my Qnap NAS firmware and now my downloads are failing with an error. Any idea how to resolve it?

<pre>
Traceback (most recent call last):
  File "/share/Download/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
    import nzbToMedia
  File "/share/MD0_DATA/Download/nzbToMedia/nzbToMedia.py", line 491, in <module>
    import nzbtomedia
  File "/share/MD0_DATA/Download/nzbToMedia/nzbtomedia/__init__.py", line 28, in <module>
    from nzbtomedia.autoProcess.autoProcessComics import autoProcessComics
  File "/share/MD0_DATA/Download/nzbToMedia/nzbtomedia/autoProcess/autoProcessComics.py", line 4, in <module>
    import requests
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py", line 34, in <module>
    from .connection import (
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/urllib3/connection.py", line 43, in <module>
    from .util import (
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/urllib3/util/__init__.py", line 18, in <module>
    from .retry import Retry
  File "/share/MD0_DATA/Download/nzbToMedia/libs/requests/packages/urllib3/util/retry.py", line 4, in <module>
    from ..exceptions import (
ImportError: cannot import name ProtocolError
</pre>

Thanks.

**Comment by bartley69** [comment]
I've googled a bunch but cannot find a solution. I Believe it is a problem with python but I have no idea how to fix it. Any ideas?

I should have just stayed on the older FW as it was working perfectly :'(

**Comment by bartley69** [comment]
Now i've really messed it up...Been randomly messing aroudn with shit trying anything i find on google trying to get it working again.

I'n my NAS I'm getting an error pop up saying - Error : Failed to start SickBeard-TVRage, /opt/bin/python2.7 was not found. Please re-install the Pythin ipkg.

Error - http://s30.postimg.org/aqo2bg6lt/errors.jpg

I have installed the python ipkg from the app store but the program still won't start. I get the same error for Couch Potato also.

I'm really fucked here, fairly noob, any help would be greatly appreciated.

**Comment by bartley69** [comment]
I've found a similar issue here but there was no resolution - http://forum.qnap.com/viewtopic.php?p=383664&sid=a2408ffb7abf95a97a12c2b464e3240e

**Comment by bartley69** [comment]
Managed to get my programs up and going again! Just back to the origional problem of the post-processing failing as mentioned in the OP. Any ideas on how to fix it?

**Comment by bartley69** [comment]
Fixed!!!! I removed all files from my /libs/requests/ folder and restarted my NAS. All is well in the world!

**Comment by clinton-hall** [comment]
Yeah, recent QNAP and Python qpkg updates cause issues...
I have not been able to verify all modules on QNAP...

**Comment by clinton-hall** [comment]
I just updated the requests module... this fixes another (similar) issue, so hopefully this is now resolved...
Currently in nightly build.
