### ISSUE TITLE
Mylar prost-processing times out

### ISSUE THREAD

**Issue by skywayskase** [clinton-hall/nzbToMedia#767]
Hey there,
So I just rebuilt my computer and setup fresh copies of all my downloading software and this collection of scripts. However, every time Mylar downloads a comic via SABnzbd, the post-proccing seems to time out and I get the following "Exit(1) requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8090): Read timed out. (read timeout=300)".
I went and compared the newly edited script from this build to my previous build and I don't see anything that I might have left out or entered incorrectly. Any advice would be appreciated.

This is a Windows 7 64-bit machine running SABnzbd 0.7.20 and Mylar's latest development build all on the same machine.

**Comment by skywayskase** [comment]
Here is a print-out of what the script returns in SABnzbd:

           [11:40:33] [INFO]::MAIN: Loading config from [C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\autoProcessMedia.cfg]
[11:40:33] [INFO]::MAIN: Checking database structure...
[11:40:33] [INFO]::MAIN: Checking if git needs an update
[11:40:33] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[11:40:33] [INFO]::MAIN: No update needed
[11:40:33] [INFO]::MAIN: nzbToMedia Version:10.11 Branch:master (Windows 7)
[11:40:33] [INFO]::MAIN: #########################################################
[11:40:33] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[11:40:33] [INFO]::MAIN: #########################################################
[11:40:33] [INFO]::MAIN: Script triggered from SABnzbd
[11:40:33] [INFO]::MAIN: Auto-detected SECTION:Mylar
[11:40:33] [INFO]::MAIN: Calling Mylar:comics to post-process:Guardians.3000.008.2015.Digital.Zone-Empire.nzb
Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\ComicRN.py", line 121, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\nzbToMedia.py", line 712, in main
    download_id='')
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\nzbToMedia.py", line 603, in process
    inputCategory)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\core\autoProcess\autoProcessComics.py", line 61, in processEpisode
    r = requests.get(url, auth=(username, password), params=params, stream=True, verify=False, timeout=(30, 300))
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\api.py", line 65, in get
    return request('get', url, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8090): Read timed out. (read timeout=300)

**Comment by skywayskase** [comment]
And here is the relevent section of the autoProcessMedia.cfg file

[Mylar]
    #### autoProcessing for Comics
    #### comics - category that gets called for post-processing with Mylar
    [[comics]]
        enabled = 1
        host = localhost
        port = 8090
        username = XXXXXX
        password = XXXXXX
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = /mylar
        ssl = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        extract = 1
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 15
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 1
        ##### Enable if Mylar is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = D:\Downloads\To Sort\Comics

**Comment by skywayskase** [comment]
And here's a screen-shot of the "Quality & Post Processing" tab in mylar.

![image](https://cloud.githubusercontent.com/assets/11436704/7920781/0b290720-0856-11e5-8644-cb320a33e460.png)

**Comment by clinton-hall** [comment]
in autoProcessMedia.cfg, please set
```
[General]
    log_debug = 1
```
then post the logs after another failure.
Hopefully this will give some additional logging data to try and narrow this down?

**Comment by skywayskase** [comment]
Okay, with here's from the last comic post-processing failed for. I'm at work so this is copied from SABnzbd instead of directly from the log, hopefully this will suffice, but let me know if not..

```
[07:19:51] [INFO]::MAIN: Loading config from [C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\autoProcessMedia.cfg]
[07:19:51] [INFO]::MAIN: Checking database structure...
[07:19:51] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[07:19:51] [DEBUG]::MAIN: InitialSchema upgrade not required
[07:19:51] [DEBUG]::MAIN: Checking if we can use git commands: "C:\Program Files (x86)\Git\cmd" version
[07:19:51] [DEBUG]::MAIN: Executing "C:\Program Files (x86)\Git\cmd" version with your shell in C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia
[07:19:51] [DEBUG]::MAIN: Not using: "C:\Program Files (x86)\Git\cmd"
[07:19:51] [DEBUG]::MAIN: Trying known alternative git locations
[07:19:51] [DEBUG]::MAIN: Checking if we can use git commands: "c:\program files (x86)\git\cmd" version
[07:19:51] [DEBUG]::MAIN: Executing "c:\program files (x86)\git\cmd" version with your shell in C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia
[07:19:51] [DEBUG]::MAIN: Not using: "c:\program files (x86)\git\cmd"
[07:19:51] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
[07:19:51] [DEBUG]::MAIN: No git specified, can't use git commands
[07:19:51] [INFO]::MAIN: Checking if git needs an update
[07:19:51] [DEBUG]::MAIN: No git specified, can't use git commands
[07:19:51] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[07:19:51] [INFO]::MAIN: No update needed
[07:19:51] [INFO]::MAIN: nzbToMedia Version:10.11 Branch:master (Windows 7)
[07:19:51] [INFO]::MAIN: #########################################################
[07:19:51] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[07:19:51] [INFO]::MAIN: #########################################################
[07:19:51] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\Program Files (x86)\\SABnzbd\\Scripts\\nzbToMedia\\ComicRN.py', 'D:\\Downloads\\To Sort\\Comics\\X-tinction.Agenda.001.2015.Digital.Zone-Empire.1', 'X-tinction.Agenda.001.2015.Digital.Zone-Empire.nzb', 'X-tinction.Agenda.001.2015.Digital.Zone-Empire', '', 'comics', 'alt.binaries.comics.dcp', '0']
[07:19:51] [INFO]::MAIN: Script triggered from SABnzbd
[07:19:51] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[07:19:51] [DEBUG]::MAIN: Adding NZB download info for directory D:\Downloads\To Sort\Comics\X-tinction.Agenda.001.2015.Digital.Zone-Empire.1 to database
[07:19:51] [INFO]::MAIN: Auto-detected SECTION:Mylar
[07:19:51] [DEBUG]::MAIN: Checking for archives to extract in directory: D:\Downloads\To Sort\Comics\X-tinction.Agenda.001.2015.Digital.Zone-Empire.1
[07:19:51] [INFO]::MAIN: Calling Mylar:comics to post-process:X-tinction.Agenda.001.2015.Digital.Zone-Empire.nzb
[07:19:52] [DEBUG]::MYLAR: Opening URL: http://localhost:8090/mylar/post_process
Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\ComicRN.py", line 121, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\nzbToMedia.py", line 712, in main
    download_id='')
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\nzbToMedia.py", line 603, in process
    inputCategory)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\core\autoProcess\autoProcessComics.py", line 61, in processEpisode
    r = requests.get(url, auth=(username, password), params=params, stream=True, verify=False, timeout=(30, 300))
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\api.py", line 65, in get
    return request('get', url, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\SABnzbd\Scripts\nzbToMedia\libs\requests\adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8090): Read timed out. (read timeout=300)
```

**Comment by clinton-hall** [comment]
What happens when you go to http://localhost:8090/mylar/post_process
Locally?
Does the server respond in under 5 minutes?
What is odd here is that the logs don't show a 5 minute delay. This spears to immediately time out.

**Comment by skywayskase** [comment]
When I try that locally I get:

![image](https://cloud.githubusercontent.com/assets/11436704/7998639/f1727618-0af3-11e5-8354-2fb5a9b98540.png)

**Comment by skywayskase** [comment]
@evilhero

**Comment by skywayskase** [comment]
Well I fixed post-processing by disabling Metadata Tagging in Mylar. I'm not entirely sure why that broke it on this build, but it worked fine on my last build.. But I'll do some more testing and report back.

**Comment by skywayskase** [comment]
Okay, I was wrong, turning off comic tagging didn't fix it. I seemed like it did for manually grabbed nzbs, but when mylar grabbed it's own they still timed out.

**Comment by skywayskase** [comment]
Today I tested post-processing with the scripts that came with Mylar. It didn't even time out, it just "ran" (doing nothing) until I turned off the server. I tried this with both Comic tagger checked and unchecked in the Mylar config.

**Comment by evilhero** [comment]
If you're having problems running the comicRN.py script that comes with mylar then you need to log an issue on mylar's github, with the relevant portion of the  mylar.log file includes as well as the Sabnzbd log. 

If you can't get it working with Clinton's script, nor the mylar script then there's obviously some misconfiguration at the mylar level.  I would also suggest to not add in another level of complexity at this point by trying metatagging - if we can get it working without, then try with ;)

**Comment by skywayskase** [comment]
Okay, I figured it out. I had Mylar looking in the wrong directory... Thanks to @evilhero for prompting me look closer at the Mylar logs.
