### ISSUE TITLE
IOError: [Errno socket error] [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Mickroz** [clinton-hall/nzbToMedia#772]
Running SickRage master on synology DSM 5.2
```
20:58:12|INFO    ====================
20:58:12|INFO    nzbToSickBeard V9.2
20:58:12|INFO    MAIN: Script triggered from SABnzbd 0.7.17+, starting autoProcessTV...
20:58:12|INFO    Loading config from /usr/local/sabnzbd/var/scripts/nzbToMedia/autoProcessMedia.cfg
20:58:12|INFO    FLATTEN: Flattening directory: /volume1/downloads/complete/series/Game.of.Thrones.S05E09.720p.HDTV.x264-DON
20:58:12|INFO    REMOVER: Removing empty folders in: /volume1/downloads/complete/series/Game.of.Thrones.S05E09.720p.HDTV.x264-DON
20:58:12|INFO    The download succeeded. Sending process request to SickBeard's default branch
20:58:12|INFO    Waiting for 0.0 seconds to allow SB to process newly extracted files
20:58:12|ERROR   Unable to open URL
Traceback (most recent call last):
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/autoProcess/autoProcessTV.py", line 208, in processEpisode
    urlObj = myOpener.openit(url)
  File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/autoProcess/autoProcessTV.py", line 33, in openit
    return urllib.FancyURLopener.open(self, url)
  File "/usr/local/python/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/python/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/local/python/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/local/python/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/usr/local/python/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/usr/local/python/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/usr/local/python/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused
20:58:12|INFO    MAIN: A problem was reported in the autoProcessTV script.
```
autoProcessMedia.cfg
```
[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[series]]
        enabled = 1
        host = localhost
        port = 8899
        username = ****
        password = ****
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root =
        ssl = 0
        fork = auto
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        process_method =
        # force processing of already processed content when running a manual scan.
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir =
```

**Comment by clinton-hall** [comment]
Can you please update to the current version of nzbToMedia?

then can you edit autoProcessMedia.cfg
```
[General]
    log_debug = 1
```
then post the logs after the next failed process.
Can you also confirm what url you would usually use to connect to SickRage?

**Comment by Mickroz** [comment]
it is, i did.
i have some other scripts that connect to SickRage with the same url settings as posted, the only difference is that the other scripts use web_root =/
I will download the file again.

**Comment by clinton-hall** [comment]
Your logs showed a very old version of this script. I made several changes since then, including fixes for SickRage login.
The update should fix this.

**Comment by Mickroz** [comment]
Got the same output.
Just to be sure.
git pull
Already up-to-date.
git fetch --all
Fetching origin
git reset --hard origin/master
HEAD is now at eef278d remove excess variable setting.

**Comment by Mickroz** [comment]
well, i figured it out, i had a old pull in my scripts dir, en for some reason sabnzbd isn't saving the new scripts location, so it works now.

**Comment by clinton-hall** [comment]
Glad to hear you got it working.
