### ISSUE TITLE
Add/improve bit-rate handling for transcoding and ripping (old #606 closed now)

### ISSUE THREAD

**Issue by thesatman** [clinton-hall/nzbToMedia#793]
Old thread #606 is closed now and I am not sure if you are following this, so I took the liberty to open a new issue.

How did things work out with the bitrate check before converting to mp4-scene? (please look at the last comments in #606) How do I put all this in my config?

**Comment by clinton-hall** [comment]
I believe this is all working. Just set `outputDefault = mp4-scene-release`

**Comment by clinton-hall** [comment]
as far as the bit-rate checks go, I thought this was handled by one of the other settings (I thought we set a quality setting in there for the mp4-scene-release... but I honestly don't know if this works as intended... can you please let me know if the bitrate is still too high using this?

Sorry for being so slack on these 2 issues... as this was all around last December, I was trying to spend time with familiy, then new year got hectic at work and the first week on February I was told I no longer had a job... Started a new job 3 days later and I have been run off my feet ever since (but enjoying the new job so much more)...

Add into that the fact that I have a 3 year old son, my wife and I got a new puppy (now 5 months old) we renovated the master bedroom and our 12 year old dog has cancer (only 1-4 months to go)... Well, as you can guess this project hasn't been receiving the attention I would like to give it.

**Comment by thesatman** [comment]
I will test it, but my CP looks to be limping. I am running the latest version but am getting errors in the log, and CP is not downloading nor post processing anything. I posted the error at Ruudburgers CP Github, but the issue got closed right away as "already reported". Not sure it is a CP issue or a misconfiguration from my end. It worked fine until a few days ago... Maybe you could give me a hint where to look?
	
	I totally understand your position, and believe me, there is no reason to apologize. Been there done that ;).
	
	 

	On Saturday, July 11, 2015 01:31 AM CEST, Clinton Hall <notifications@github.com> wrote:
	 

	as far as the bit-rate checks go, I thought this was handled by one of the other settings (I thought we set a quality setting in there for the mp4-scene-release... but I honestly don't know if this works as intended... can you please let me know if the bitrate is still too high using this?
	
	Sorry for being so slack on these 2 issues... as this was all around last December, I was trying to spend time with familiy, then new year got hectic at work and the first week on February I was told I no longer had a job... Started a new job 3 days later and I have been run off my feet ever since (but enjoying the new job so much more)...
	
	Add into that the fact that I have a 3 year old son, my wife and I got a new puppy (now 5 months old) we renovated the master bedroom and our 12 year old dog has cancer (only 1-4 months to go)... Well, as you can guess this project hasn't been receiving the attention I would like to give it.
	
	---

**Comment by thesatman** [comment]
Hi again. I finally came across an iso file, so I can test this. I am having some difficulties getting nzbToMedia to do the job. Hope you can give me a few pointers?

I have the iso file located in the same folder where I uTorrent stores the finnished downloads:

C:\Video\link_w_torrent_download\couchpotato_\

my autoprocessmedia.cfg has:

    [[couchpotato_]]
        enabled = 1
        web_root = ""
        Torrent_NoLink = 0
        method = renamer
        delete_failed = 0
        wait_for = 2
        extract = 1
        remote_path = 1
        watch_dir = C:\Video\link_w_torrent_download
[Transcoder]
    transcode = 1
    concat = 1
    ignoreExtensions = .avi, .mkv, .mp4
    outputDefault = mp4-scene-release

I run C:\Python27\python.exe C:\nzbToMedia-GIT\nzbToMedia\NzbToMedia.py

The output:

[11:45:57] [INFO]::MAIN: No update needed
[11:45:57] [INFO]::MAIN: nzbToMedia Version:d94d9f50de618dd76c5d8f2135dae260aea1721c Branch:nightly (Windows 7)
[11:45:57] [DEBUG]::MAIN: Connecting to utorrent: http://localhost:8082/gui/
[11:45:57] [INFO]::MAIN: #########################################################
[11:45:57] [INFO]::MAIN: ## ..::[NzbToMedia.py]::.. ##
[11:45:57] [INFO]::MAIN: #########################################################
[11:45:57] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\\nzbToMedia-GIT\\nzbToMedia\\NzbToMedia.py']
[11:45:57] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[11:45:57] [INFO]::MAIN: Searching C:\Video\link_w_torrent_download\couchpotato_ for mediafiles to post-process ...
[11:45:57] [INFO]::MAIN: Starting manual run for CouchPotato:couchpotato_ - Folder:C:\Video\link_w_torrent_download\couc
hpotato_\moviename (1997)
[11:45:57] [INFO]::MAIN: Checking database for download info for moviename (1997) ...
[11:45:57] [INFO]::MAIN: Unable to locate download info for moviename (1997), continuing to try and process this release ...

[11:45:58] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[11:45:58] [DEBUG]::MAIN: Checking for archives to extract in directory: C:\Video\link_w_torrent_download\couchpotato_\moviename (1997)
[11:45:58] [INFO]::MAIN: Calling CouchPotato:couchpotato_ to post-process:moviename (1997)
[11:45:59] [INFO]::MAIN: Attemping imdbID lookup for moviename (1997)
[11:45:59] [INFO]::MAIN: Searching folder and file names for imdbID ...
[11:45:59] [INFO]::MAIN: Searching IMDB for imdbID ...
[11:45:59] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
[11:46:00] [INFO]::MAIN: Found imdbID [tt0123456]
[11:46:00] [DEBUG]::MAIN: Opening URL: http://localhost:5050/api/4af235adae52473db2f1378a8dc508f3/media.get with PARAMS:
 {'id': u'tt0123456'}
[11:46:01] [ERROR]::MAIN: no media found for id tt0123456
[11:46:01] [INFO]::MAIN: Checking for files to be transcoded
[11:46:01] [DEBUG]::TRANSCODER: Attempting to rip disk image: C:\Video\link_w_torrent_download\couchpotato_\moviename (1997)\moviename (1997).iso
[11:46:01] [DEBUG]::TRANSCODER: Attempting to extract .vob from image file C:\Video\link_w_torrent_download\couchpotato_\moviename (1997)\moviename (1997).iso
[11:46:01] [DEBUG]::MAIN: calling command: C:\nzbToMedia-GIT\nzbToMedia\core\extractor\bin\AMD64\7z.exe l C:\Video\link_
w_torrent_download\couchpotato_\moviename (1997)\moviename (1997).iso
[11:46:01] [DEBUG]::TRANSCODER: Successfully extracted .vob file {'C:\\Video\\link_w_torrent_download\\couchpotato_\\moviename (1997)\\moviename (1997).iso': {'files': [], 'name': 'moviename (1997)'}} from disk image
Traceback (most recent call last):
  File "C:\nzbToMedia-GIT\nzbToMedia\NzbToMedia.py", line 796, in <module>
    exit(main(sys.argv))
  File "C:\nzbToMedia-GIT\nzbToMedia\NzbToMedia.py", line 771, in main
    download_id=download_id, inputCategory=subsection)
  File "C:\nzbToMedia-GIT\nzbToMedia\NzbToMedia.py", line 595, in process
    inputCategory, failureLink)
  File "C:\nzbToMedia-GIT\nzbToMedia\core\autoProcess\autoProcessMovie.py", line 203, in process
    result, newDirName = transcoder.Transcode_directory(dirName)
  File "C:\nzbToMedia-GIT\nzbToMedia\core\transcoder\transcoder.py", line 705, in Transcode_directory
    command = buildCommands(file, newDir, movieName, bitbucket)
  File "C:\nzbToMedia-GIT\nzbToMedia\core\transcoder\transcoder.py", line 126, in buildCommands
    video_details, result = getVideoDetails(data['files'][0], img, bitbucket)
IndexError: list index out of range

Please note that the torrent is not in the torrent list anymore. So basically what needs to be done is for nzbToMedia to scan the folder and detect the iso, extract the main movie vob file. Then convert it to a mp4-scene video file.

What am I doing wrong? No file is extracted, and it ends with the error above. Thank you for your time and your help :)

**Comment by clinton-hall** [comment]
Interesting. This appears that 7zip did not return a list of files in the iso

**Comment by clinton-hall** [comment]
Can you call
`C:\nzbToMedia-GIT\nzbToMedia\core\extractor\bin\AMD64\7z.exe l C:\Video\link_w_torrent_download\couchpotato_\moviename (1997)\moviename (1997).iso`

and post the output?

**Comment by thesatman** [comment]
The output is :

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
Error: C:\Video\link_w_torrent_download\couchpotato_\movie\movie.iso:
Can not open file as archive
Errors: 1

I can open the iso file with Winrar, and can mount it with Virtual Drive.

**Comment by clinton-hall** [comment]
Interesting.
7zip opens iso on Linux.

Perhaps the version of 7zip I bundle is old?
Can you install latest 7zip and try same command (replacing 7zip path with the newest version)?

**Comment by thesatman** [comment]
I am running the latest stable version.

**Comment by clinton-hall** [comment]
Can you test the same command from above, replacing the path to 7zip, after installing this version?
http://www.7-zip.org/a/7z1509-x64.exe
