### ISSUE TITLE
Issue with moving files

### ISSUE THREAD

**Issue by boomertheweim** [clinton-hall/nzbToMedia#794]
Ok I am new to this. Any idea what I am doing wrong?

BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek
[16:04:19] [INFO]::MAIN: Loading config from [C:\nzb\nzbToMedia\autoProcessMedia.cfg]
[16:04:19] [INFO]::ENVIRONMENT: TMP: C:\Users\DAVID_~1\AppData\Local\Temp
[16:04:19] [INFO]::ENVIRONMENT: COMPUTERNAME: DELL
[16:04:19] [INFO]::ENVIRONMENT: USERDOMAIN: DELL
[16:04:19] [INFO]::ENVIRONMENT: PSMODULEPATH: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
[16:04:19] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES: C:\Program Files\Common Files
[16:04:19] [INFO]::ENVIRONMENT: PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
[16:04:19] [INFO]::ENVIRONMENT: PROGRAMFILES: C:\Program Files
[16:04:19] [INFO]::ENVIRONMENT: PROCESSOR_REVISION: 3a09
[16:04:19] [INFO]::ENVIRONMENT: SYSTEMROOT: C:\Windows
[16:04:19] [INFO]::ENVIRONMENT: PATH: C:\Python27\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Python27\Scripts
[16:04:19] [INFO]::ENVIRONMENT: PROGRAMFILES(X86): C:\Program Files (x86)
[16:04:19] [INFO]::ENVIRONMENT: COMSPEC: C:\Windows\system32\cmd.exe
[16:04:19] [INFO]::ENVIRONMENT: TEMP: C:\Users\DAVID_~1\AppData\Local\Temp
[16:04:19] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
[16:04:19] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITECTURE: AMD64
[16:04:19] [INFO]::ENVIRONMENT: ALLUSERSPROFILE: C:\ProgramData
[16:04:19] [INFO]::ENVIRONMENT: LOCALAPPDATA: C:\Users\david_000\AppData\Local
[16:04:19] [INFO]::ENVIRONMENT: HOMEPATH: \Users\david_000
[16:04:19] [INFO]::ENVIRONMENT: USERDOMAIN_ROAMINGPROFILE: DELL
[16:04:19] [INFO]::ENVIRONMENT: PROGRAMW6432: C:\Program Files
[16:04:19] [INFO]::ENVIRONMENT: USERNAME: david_000
[16:04:19] [INFO]::ENVIRONMENT: LOGONSERVER: \MicrosoftAccount
[16:04:19] [INFO]::ENVIRONMENT: PROMPT: $P$G
[16:04:19] [INFO]::ENVIRONMENT: SESSIONNAME: Console
[16:04:19] [INFO]::ENVIRONMENT: PROGRAMDATA: C:\ProgramData
[16:04:19] [INFO]::ENVIRONMENT: PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[16:04:19] [INFO]::ENVIRONMENT: FP_NO_HOST_CHECK: NO
[16:04:19] [INFO]::ENVIRONMENT: WINDIR: C:\Windows
[16:04:19] [INFO]::ENVIRONMENT: APPDATA: C:\Users\david_000\AppData\Roaming
[16:04:19] [INFO]::ENVIRONMENT: HOMEDRIVE: C:
[16:04:19] [INFO]::ENVIRONMENT: OS: Windows_NT
[16:04:19] [INFO]::ENVIRONMENT: SYSTEMDRIVE: C:
[16:04:19] [INFO]::ENVIRONMENT: NUMBER_OF_PROCESSORS: 4
[16:04:19] [INFO]::ENVIRONMENT: PROCESSOR_LEVEL: 6
[16:04:19] [INFO]::ENVIRONMENT: COMMONPROGRAMW6432: C:\Program Files\Common Files
[16:04:19] [INFO]::ENVIRONMENT: __COMPAT_LAYER: DetectorsVista
[16:04:19] [INFO]::ENVIRONMENT: PUBLIC: C:\Users\Public
[16:04:19] [INFO]::ENVIRONMENT: USERPROFILE: C:\Users\david_000
[16:04:19] [INFO]::MAIN: Checking database structure...
[16:04:19] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[16:04:19] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[16:04:19] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[16:04:19] [DEBUG]::MAIN: InitialSchema upgrade not required
[16:04:19] [DEBUG]::MAIN: Checking if we can use git commands: git version
[16:04:19] [DEBUG]::MAIN: Executing git version with your shell in C:\nzb\nzbToMedia
[16:04:23] [DEBUG]::MAIN: git output: git version 1.9.5.msysgit.0
[16:04:23] [DEBUG]::MAIN: git version : returned successful
[16:04:23] [DEBUG]::MAIN: Using: git
[16:04:23] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\nzb\nzbToMedia
[16:04:23] [DEBUG]::MAIN: git output: refs/heads/master
[16:04:23] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[16:04:23] [INFO]::MAIN: Checking if git needs an update
[16:04:23] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in C:\nzb\nzbToMedia
[16:04:23] [DEBUG]::MAIN: git output: eef278d22fb7f6e2739894cf089e141cf75f8528
[16:04:23] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[16:04:23] [DEBUG]::MAIN: Executing git fetch origin with your shell in C:\nzb\nzbToMedia
[16:04:26] [DEBUG]::MAIN: git output: 
[16:04:26] [DEBUG]::MAIN: git fetch origin : returned successful
[16:04:26] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\nzb\nzbToMedia
[16:04:26] [DEBUG]::MAIN: git output: eef278d22fb7f6e2739894cf089e141cf75f8528
[16:04:26] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[16:04:26] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\nzb\nzbToMedia
[16:04:26] [DEBUG]::MAIN: git output: 
[16:04:26] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[16:04:26] [DEBUG]::MAIN: cur_commit = eef278d22fb7f6e2739894cf089e141cf75f8528 % (newest_commit)= eef278d22fb7f6e2739894cf089e141cf75f8528, num_commits_behind = 0, num_commits_ahead = 0
[16:04:26] [INFO]::MAIN: No update needed
[16:04:26] [INFO]::MAIN: nzbToMedia Version:eef278d22fb7f6e2739894cf089e141cf75f8528 Branch:master (Windows 8)
[16:04:26] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[16:04:26] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[16:04:26] [WARNING]::MAIN: Failed to locate ffprobe.exe. Video corruption detection disabled!
[16:04:26] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[16:04:26] [INFO]::MAIN: #########################################################
[16:04:26] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[16:04:26] [INFO]::MAIN: #########################################################
[16:04:26] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\nzb\nzbToMedia\nzbToSickBeard.py', 'Y:\TV Shows\Bbq Pitmasters\Season 7\BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek\..', 'BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek.nzb', 'BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek', '', 'tv', 'alt.binaries.ath', '0']
[16:04:26] [INFO]::MAIN: Script triggered from SABnzbd
[16:04:26] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[16:04:29] [ERROR]::MAIN: Unable to open URL
[16:04:29] [DEBUG]::MAIN: Adding NZB download info for directory Y:\TV Shows\Bbq Pitmasters\Season 7\BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek.. to database
[16:04:29] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 735791, u'None', u'None', u'BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek.nzb', u'Y:\TV Shows\Bbq Pitmasters\Season 7\BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek\..']
[16:04:29] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735791, u'None', u'None', u'BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek.nzb', u'Y:\TV Shows\Bbq Pitmasters\Season 7\BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek\..']
[16:04:29] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[16:04:29] [DEBUG]::MAIN: Checking for archives to extract in directory: Y:\TV Shows\Bbq Pitmasters\Season 7\BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek..
[16:04:29] [INFO]::MAIN: Calling SickBeard:tv to post-process:BBQ.Pitmasters.S07E06.HDTV.x264-CRIMSON-NZBgeek.nzb
[16:06:30] [ERROR]::SICKBEARD: Server did not respond. Exiting
[16:06:30] [DEBUG]::PLEX: Attempting to update Plex Library for category tv.
Traceback (most recent call last):
  File "C:\nzb\nzbToMedia\nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\nzb\nzbToMedia\nzbToMedia.py", line 712, in main
    download_id='')
  File "C:\nzb\nzbToMedia\nzbToMedia.py", line 611, in process
    plex_update(inputCategory)
  File "C:\nzb\nzbToMedia\core\nzbToMediaUtil.py", line 1074, in plex_update
    requests.get(url, timeout=(60, 120), verify=False)
  File "C:\nzb\nzbToMedia\libs\requests\api.py", line 65, in get
    return request('get', url, *_kwargs)
  File "C:\nzb\nzbToMedia\libs\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "C:\nzb\nzbToMedia\libs\requests\sessions.py", line 461, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\nzb\nzbToMedia\libs\requests\sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "C:\nzb\nzbToMedia\libs\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(11001, 'getaddrinfo failed'))

**Comment by clinton-hall** [comment]
Make sure you edit `autoProcessMedia.cfg`
and in 
```
[SickBeard]
    [[tv]]
```
set the appropriate host, port, user and pass.

**Comment by boomertheweim** [comment]
Here's my file.  I think it's ok.  My folder is sitting on a network drive, the Y drive.

The actual file had my user id and password.

[SickBeard]
    #### autoProcessing for TV Series
    #### tv - category that gets called for post-processing with SB
    [[tv]]
        enabled = 1
        host = localhost
        port = 8081
        username = xxxxx
        password = xxxxxx
        ###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
        web_root = ""
        ssl = 0
        fork = sickrage
        delete_failed = 0
        # Enable/Disable linking for Torrents
        Torrent_NoLink = 0
        process_method = ""
        # force processing of already processed content when running a manual scan.
        force = 0
        extract = 1
        nzbExtractionBy = Downloader
        # Set this to minimum required size to consider a media file valid (in MB)
        minSize = 0
        # Enable/Disable deleteing ignored files (samples and invalid media files)
        delete_ignored = 0
        ##### Enable if SickBeard is on a remote server for this category
        remote_path = 0
        ##### Set to path where download client places completed downloads locally for this category
        watch_dir = Y:\sickrage

**Comment by clinton-hall** [comment]
From your windows system, what url do you use to access SickBeard/SickRage?
Are Sab and SickRage both running on this windows system?

**Comment by boomertheweim** [comment]
I have http://192.168.1.85:8081/, but I can also use localhost:8081.

Sab and SickRage are on the same system.

**Comment by clinton-hall** [comment]
Try host = 127.0.0.1
Or
host = 192.168.1.85

**Comment by boomertheweim** [comment]
I think I am making progress.  It's placing the file in folder which it was downloaded in, not the correct folder, like Show>Season>Episode

        [19:25:40] [INFO]::MAIN: Loading config from [Y:\nzbToMedia\autoProcessMedia.cfg]
[19:25:40] [INFO]::ENVIRONMENT: TMP: C:\Users\DAVID_~1\AppData\Local\Temp
[19:25:40] [INFO]::ENVIRONMENT: COMPUTERNAME: DELL
[19:25:40] [INFO]::ENVIRONMENT: USERDOMAIN: DELL
[19:25:40] [INFO]::ENVIRONMENT: PSMODULEPATH: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
[19:25:40] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES: C:\Program Files\Common Files
[19:25:40] [INFO]::ENVIRONMENT: PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
[19:25:40] [INFO]::ENVIRONMENT: PROGRAMFILES: C:\Program Files
[19:25:40] [INFO]::ENVIRONMENT: PROCESSOR_REVISION: 3a09
[19:25:40] [INFO]::ENVIRONMENT: SYSTEMROOT: C:\Windows
[19:25:40] [INFO]::ENVIRONMENT: PATH: C:\Python27\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Python27\Scripts
[19:25:40] [INFO]::ENVIRONMENT: PROGRAMFILES(X86): C:\Program Files (x86)
[19:25:40] [INFO]::ENVIRONMENT: COMSPEC: C:\Windows\system32\cmd.exe
[19:25:40] [INFO]::ENVIRONMENT: TEMP: C:\Users\DAVID_~1\AppData\Local\Temp
[19:25:40] [INFO]::ENVIRONMENT: COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
[19:25:40] [INFO]::ENVIRONMENT: PROCESSOR_ARCHITECTURE: AMD64
[19:25:40] [INFO]::ENVIRONMENT: ALLUSERSPROFILE: C:\ProgramData
[19:25:40] [INFO]::ENVIRONMENT: LOCALAPPDATA: C:\Users\david_000\AppData\Local
[19:25:40] [INFO]::ENVIRONMENT: HOMEPATH: \Users\david_000
[19:25:40] [INFO]::ENVIRONMENT: USERDOMAIN_ROAMINGPROFILE: DELL
[19:25:40] [INFO]::ENVIRONMENT: PROGRAMW6432: C:\Program Files
[19:25:40] [INFO]::ENVIRONMENT: USERNAME: david_000
[19:25:40] [INFO]::ENVIRONMENT: LOGONSERVER: \\MicrosoftAccount
[19:25:40] [INFO]::ENVIRONMENT: PROMPT: $P$G
[19:25:40] [INFO]::ENVIRONMENT: SESSIONNAME: Console
[19:25:40] [INFO]::ENVIRONMENT: PROGRAMDATA: C:\ProgramData
[19:25:40] [INFO]::ENVIRONMENT: PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[19:25:40] [INFO]::ENVIRONMENT: FP_NO_HOST_CHECK: NO
[19:25:40] [INFO]::ENVIRONMENT: WINDIR: C:\Windows
[19:25:40] [INFO]::ENVIRONMENT: APPDATA: C:\Users\david_000\AppData\Roaming
[19:25:40] [INFO]::ENVIRONMENT: HOMEDRIVE: C:
[19:25:40] [INFO]::ENVIRONMENT: SYSTEMDRIVE: C:
[19:25:40] [INFO]::ENVIRONMENT: NUMBER_OF_PROCESSORS: 4
[19:25:40] [INFO]::ENVIRONMENT: PROCESSOR_LEVEL: 6
[19:25:40] [INFO]::ENVIRONMENT: COMMONPROGRAMW6432: C:\Program Files\Common Files
[19:25:40] [INFO]::ENVIRONMENT: OS: Windows_NT
[19:25:40] [INFO]::ENVIRONMENT: PUBLIC: C:\Users\Public
[19:25:40] [INFO]::ENVIRONMENT: USERPROFILE: C:\Users\david_000
[19:25:40] [INFO]::MAIN: Checking database structure...
[19:25:40] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[19:25:40] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[19:25:40] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[19:25:40] [DEBUG]::MAIN: InitialSchema upgrade not required
[19:25:40] [DEBUG]::MAIN: Checking if we can use git commands: git version
[19:25:40] [DEBUG]::MAIN: Executing git version with your shell in Y:\nzbToMedia
[19:25:40] [DEBUG]::MAIN: git output: git version 1.9.5.msysgit.0
[19:25:40] [DEBUG]::MAIN: git version : returned successful
[19:25:40] [DEBUG]::MAIN: Using: git
[19:25:40] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in Y:\nzbToMedia
[19:25:41] [DEBUG]::MAIN: git output: refs/heads/master
[19:25:41] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[19:25:41] [INFO]::MAIN: Checking if git needs an update
[19:25:41] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in Y:\nzbToMedia
[19:25:41] [DEBUG]::MAIN: git output: eef278d22fb7f6e2739894cf089e141cf75f8528
[19:25:41] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[19:25:41] [DEBUG]::MAIN: Executing git fetch origin with your shell in Y:\nzbToMedia
[19:25:42] [DEBUG]::MAIN: git output: 
[19:25:42] [DEBUG]::MAIN: git fetch origin : returned successful
[19:25:42] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in Y:\nzbToMedia
[19:25:42] [DEBUG]::MAIN: git output: eef278d22fb7f6e2739894cf089e141cf75f8528
[19:25:42] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[19:25:42] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in Y:\nzbToMedia
[19:25:42] [DEBUG]::MAIN: git output: 
[19:25:42] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[19:25:42] [DEBUG]::MAIN: cur_commit = eef278d22fb7f6e2739894cf089e141cf75f8528 % (newest_commit)= eef278d22fb7f6e2739894cf089e141cf75f8528, num_commits_behind = 0, num_commits_ahead = 0
[19:25:42] [INFO]::MAIN: No update needed
[19:25:42] [INFO]::MAIN: nzbToMedia Version:eef278d22fb7f6e2739894cf089e141cf75f8528 Branch:master (Windows 8)
[19:25:42] [WARNING]::MAIN: Failed to locate ffmpeg.exe. Transcoding disabled!
[19:25:42] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[19:25:42] [WARNING]::MAIN: Failed to locate ffprobe.exe. Video corruption detection disabled!
[19:25:42] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[19:25:42] [INFO]::MAIN: #########################################################
[19:25:42] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[19:25:42] [INFO]::MAIN: #########################################################
[19:25:42] [DEBUG]::MAIN: Options passed into nzbToMedia: ['Y:\\nzbToMedia\\nzbToSickBeard.py', 'Y:\\TV Shows\\Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F', 'Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F.nzb', 'Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F', '', '*', 'alt.binaries.boneless', '0']
[19:25:42] [INFO]::MAIN: Script triggered from SABnzbd
[19:25:42] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[19:25:43] [ERROR]::MAIN: Unable to open URL
[19:25:43] [DEBUG]::MAIN: Adding NZB download info for directory Y:\TV Shows\Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F to database
[19:25:43] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 735793, u'None', u'None', u'Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F.nzb', u'Y:\\TV Shows\\Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F']
[19:25:43] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735793, u'None', u'None', u'Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F.nzb', u'Y:\\TV Shows\\Alaskan.Bush.People.S02E12.Bloodlines.HDTV.x264-W4F']
[19:25:44] [ERROR]::MAIN: Category:[*] is not defined or is not enabled. Please rename it or ensure it is enabled for the appropriate section in your autoProcessMedia.cfg and try again.
[19:25:44] [ERROR]::MAIN: A problem was reported in the Y:\nzbToMedia\nzbToSickBeard.py script.

**Comment by boomertheweim** [comment]
I got it to work finally after I changed the url to 127.0.0.1.  Now I need to get utorrent to work
