### ISSUE TITLE
UnicodeDecodeError and execution of the script

### ISSUE THREAD

**Issue by Jorman** [clinton-hall/nzbToMedia#802]
Hi man, how are you?

So It's some time that I don't check if all is ok, but now I see some problems that I can't explain, the 1st one is about the Unicode error, this is the error

`Traceback (most recent call last):
  File "./TorrentToMedia.py", line 330, in <module>
    exit(main(sys.argv))
  File "./TorrentToMedia.py", line 315, in main
    clientAgent)
  File "./TorrentToMedia.py", line 172, in processTorrent
    inputName, outputDestination = convert_to_ascii(inputName, outputDestination)
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 396, in convert_to_ascii
    encoded, inputName = CharReplace(inputName)
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/nzbToMediaUtil.py", line 365, in CharReplace
    if ((Name[Idx] == '\xC2') | (Name[Idx] == '\xC3')) & ((Name[Idx+1] >= '\xA0') & (Name[Idx+1] <= '\xFF')):
  File "/opt/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 0: unexpected end of data`

The 2nd problem is with Transmission, seems that Transmission call the Torrent to media, but if I check the log of nzblog I can't see the call, with sab all works fine, only with torrent.

See this part's of logs

Transmission log:
`[2015-07-29 13:54:14.779 CEST] Face.Off.S09E01.Intergalactic.Zoo.720p.HDTV.x264-DHD[rarbg] Calling script "/share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py" (torrent.c:2119)
[2015-07-29 13:54:14.779 CEST] Face.Off.S09E01.Intergalactic.Zoo.720p.HDTV.x264-DHD[rarbg] Pausing (torrent.c:1857)
[2015-07-29 13:54:14.779 CEST] Saved "/share/CACHEDEV1_DATA/.qpkg/Transmission/conf/resume/Face.Off.S09E01.Intergalactic.Zoo.720p.HDTV.x264-DHD[rarbg].48aa8d62840030fc.resume" (variant.c:1214)
[2015-07-29 13:55:18.841 CEST] Face.Off.S09E01.Intergalactic.Zoo.720p.HDTV.x264-DHD[rarbg] Connection failed (announcer.c:996)
[2015-07-29 13:55:18.841 CEST] Face.Off.S09E01.Intergalactic.Zoo.720p.HDTV.x264-DHD[rarbg] Retrying announce in 7217 seconds. (announcer.c:1005)`

Nzbtomedia log:
`2015-07-22 21:42:41 DB      ::MAIN: nzbtomedia.db: UPDATE downloads SET status=?, last_update=? WHERE input_name=? with args [1, 735801, u'Americas.Got.Talent.S10E09.720p.NBC.WEBRip.AAC2.0.x264-monkee.nzb']
2015-07-22 21:42:42 INFO    ::CLEANDIR: Directory /share/CACHEDEV1_DATA/Download/automatics/complete/sabnzb/tv/Americas.Got.Talent.S10E09.720p.NBC.WEBRip.AAC2.0.x264-monkee has been processed and removed ...
2015-07-22 21:42:42 INFO    ::MAIN: The /share/CACHEDEV1_DATA/scripts/nzbToMedia/nzbToSickBeard.py script completed successfully.
2015-07-29 19:27:01 INFO    ::MAIN: Loading config from [/share/CACHEDEV1_DATA/scripts/nzbToMedia/autoProcessMedia.cfg]
2015-07-29 19:27:01 INFO    ::MAIN: Checking database structure...
2015-07-29 19:27:01 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2015-07-29 19:27:01 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2015-07-29 19:27:01 DB      ::MAIN: nzbtomedia.db: SELECT db_version FROM db_version`

See the times, no calling trace on nzb only my manual run.

Do you have some ideas?

**Comment by clinton-hall** [comment]
It might be that Transmission doesn't have the correct environment variables to execute python scripts.

Not sure exactly how to go about tracking this down, but you might want to try changing the first line of `/share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py`
change this to `#!/usr/bin/python`
then see if this shows anything in the logs when Transmission calls it.

As far as the encoding issues goes, I do have an open issue here to improve the encoding check, but I have not had time to look into this.

**Comment by Jorman** [comment]
I've python2 on my system, and is 2.7.3
python instead is 2.5.6

Btw, I'll try to point to a bash script where inside it I call the TorrentToMedia.py script
