### ISSUE TITLE
Debug log ends at Opening URL: http://www.omdbapi.com

### ISSUE THREAD

**Issue by ratherDashing** [clinton-hall/nzbToMedia#810]
This script has been working for 1+ years.  Today it started acting up:

2015-08-15 14:53:43 INFO    ::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
2015-08-15 14:53:43 INFO    ::MAIN: Checking database structure...
2015-08-15 14:53:43 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2015-08-15 14:53:43 DEBUG   ::MAIN: InitialSchema upgrade not required
2015-08-15 14:53:43 DEBUG   ::MAIN: Checking if we can use git commands: git version
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git version with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git version : returned successful
2015-08-15 14:53:43 DEBUG   ::MAIN: Using: git
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git symbolic-ref -q HEAD with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git symbolic-ref -q HEAD : returned successful
2015-08-15 14:53:43 INFO    ::MAIN: Checking if git needs an update
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git rev-parse HEAD with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git rev-parse HEAD : returned successful
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git fetch origin with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git fetch origin : returned successful
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
2015-08-15 14:53:43 DEBUG   ::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/nzbToMedia
2015-08-15 14:53:43 DEBUG   ::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2015-08-15 14:53:43 DEBUG   ::MAIN: cur_commit = eef278d22fb7f6e2739894cf089e141cf75f8528 % (newest_commit)= eef278d22fb7f6e2739894cf089e141cf75f8528, num_commits_behind = 0, num_commits_ahead = 0
2015-08-15 14:53:43 INFO    ::MAIN: No update needed
2015-08-15 14:53:43 INFO    ::MAIN: nzbToMedia Version:eef278d22fb7f6e2739894cf089e141cf75f8528 Branch:master (Linux 3.16.0-45-generic)
2015-08-15 14:53:44 INFO    ::MAIN: #########################################################
2015-08-15 14:53:44 INFO    ::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
2015-08-15 14:53:44 INFO    ::MAIN: #########################################################
2015-08-15 14:53:44 DEBUG   ::MAIN: Options passed into nzbToMedia: ['/opt/nzbToMedia/nzbToCouchPotato.py', '/home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER', 'Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb', 'Feast.2014.PROPER.BDRip.x264-SPRiNTER', '', 'movies', 'alt.binaries.triballs', '0']
2015-08-15 14:53:44 INFO    ::MAIN: Script triggered from SABnzbd
2015-08-15 14:53:44 DEBUG   ::MAIN: Searching for nzoid from SAbnzbd ...
2015-08-15 14:53:44 DEBUG   ::MAIN: Adding NZB download info for directory /home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER to database
2015-08-15 14:53:44 INFO    ::MAIN: Auto-detected SECTION:CouchPotato
2015-08-15 14:53:44 DEBUG   ::MAIN: Checking for archives to extract in directory: /home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER
2015-08-15 14:53:44 INFO    ::MAIN: Calling CouchPotato:movies to post-process:Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb
2015-08-15 14:53:44 INFO    ::MAIN: Attemping imdbID lookup for Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb
2015-08-15 14:53:44 INFO    ::MAIN: Searching folder and file names for imdbID ...
2015-08-15 14:53:44 INFO    ::MAIN: Searching IMDB for imdbID ...
2015-08-15 14:53:44 DEBUG   ::MAIN: Opening URL: http://www.omdbapi.com

that's where the log ends.  Sabnzbd says this:

14:53:43] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[14:53:43] [INFO]::MAIN: Checking database structure...
[14:53:43] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[14:53:43] [DEBUG]::MAIN: InitialSchema upgrade not required
[14:53:43] [DEBUG]::MAIN: Checking if we can use git commands: git version
[14:53:43] [DEBUG]::MAIN: Executing git version with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git version : returned successful
[14:53:43] [DEBUG]::MAIN: Using: git
[14:53:43] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[14:53:43] [INFO]::MAIN: Checking if git needs an update
[14:53:43] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[14:53:43] [DEBUG]::MAIN: Executing git fetch origin with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git fetch origin : returned successful
[14:53:43] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[14:53:43] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/nzbToMedia
[14:53:43] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[14:53:43] [DEBUG]::MAIN: cur_commit = eef278d22fb7f6e2739894cf089e141cf75f8528 % (newest_commit)= eef278d22fb7f6e2739894cf089e141cf75f8528, num_commits_behind = 0, num_commits_ahead = 0
[14:53:43] [INFO]::MAIN: No update needed
[14:53:43] [INFO]::MAIN: nzbToMedia Version:eef278d22fb7f6e2739894cf089e141cf75f8528 Branch:master (Linux 3.16.0-45-generic)
[14:53:44] [INFO]::MAIN: #########################################################
[14:53:44] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[14:53:44] [INFO]::MAIN: #########################################################
[14:53:44] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/nzbToMedia/nzbToCouchPotato.py', '/home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER', 'Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb', 'Feast.2014.PROPER.BDRip.x264-SPRiNTER', '', 'movies', 'alt.binaries.triballs', '0']
[14:53:44] [INFO]::MAIN: Script triggered from SABnzbd
[14:53:44] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[14:53:44] [DEBUG]::MAIN: Adding NZB download info for directory /home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER to database
[14:53:44] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[14:53:44] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/mwarren/Downloads/complete/Movies/Feast.2014.PROPER.BDRip.x264-SPRiNTER
[14:53:44] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb
[14:53:44] [INFO]::MAIN: Attemping imdbID lookup for Feast.2014.PROPER.BDRip.x264-SPRiNTER.nzb
[14:53:44] [INFO]::MAIN: Searching folder and file names for imdbID ...
[14:53:44] [INFO]::MAIN: Searching IMDB for imdbID ...
[14:53:44] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
Traceback (most recent call last):
  File "/opt/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/opt/nzbToMedia/nzbToMedia.py", line 712, in main
    download_id='')
  File "/opt/nzbToMedia/nzbToMedia.py", line 595, in process
    inputCategory, failureLink)
  File "/opt/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 136, in process
    imdbid = find_imdbid(dirName, inputName)
  File "/opt/nzbToMedia/core/nzbToMediaUtil.py", line 976, in find_imdbid
    results = r.json()
  File "/opt/nzbToMedia/libs/requests/models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 780 (char 779)

**Comment by clinton-hall** [comment]
I can't reproduce here.
Was OMDB down temporarily?
Is this still causing issues, or has it been resolved?

**Comment by ratherDashing** [comment]
works today, you can mark it as closed.  thanks for the great scripts, they are a life saver

**Comment by clinton-hall** [comment]
glad to hear. Enjoy.
