### ISSUE TITLE
TorrentToMedia not called from transmission

### ISSUE THREAD

**Issue by Jorman** [clinton-hall/nzbToMedia#826]
Hi, I don't know why, but transmission finish one download and not call TorrentToMedia, I tried many way but no one seems to works

[2015-09-17 18:44:49.271 CEST] Americas.Got.Talent.S10E26.720p.NBC.WEBRip.AAC2.0.x264-monkee[rarbg] Calling script "/opt/bin/python2 /share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py" (torrent.c:2119)

I also tried only /share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py but nothing, any ideas?

Don't seems even that the TorrentToMedia was launched because there is no trace on the nzbtomedia logs

Any idea?

Ps I'm on nightly

**Comment by Jorman** [comment]
Ok man, I've some update for you, maybe it helps

On manual run, the torrent was not deleted and the directory was not completely cleaned, here the log for the manual run:
[link] (https://gist.github.com/Jorman/96c8adebe950b8328394#file-manual-run-torrenttomedia)

For the torrent side I maked an "intermediate" file that launch the TorrentToMedia
the code is this:
```
/share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py >> /share/CACHEDEV1_DATA/Public/testscript-error.txt 2>&1
```
So the testscript-error report:
```
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py", line 7, in <module>
    import core
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/__init__.py", line 28, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/autoProcess/autoProcessComics.py", line 4, in <module>
    import requests
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/compat.py", line 39, in <module>
    import cookielib
ImportError: No module named cookielib
```
So, I don't know if it helps, but I think that transmission when calling TorrentToMedia return this error, what do you think @clinton-hall ?

**Comment by clinton-hall** [comment]
Looks like Transmission is missing an Environment variable that sets the location for Python modules... Probably PYTHONPATH

**Comment by Jorman** [comment]
mmm any idea about put it on transmission start script? I've a qnap but I don't really know the right path of python, maybe

PYTHONPATH="${PYTHONPATH}:/share/CACHEDEV1_DATA/.qpkg/Optware/local/lib/python2.7/site-packages"
export PYTHONPATH

can work?

**Comment by clinton-hall** [comment]
Yes, that looks right. Try it.

**Comment by Jorman** [comment]
Nope, always same problem
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/TorrentToMedia.py", line 7, in <module>
    import core
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/__init__.py", line 28, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/core/autoProcess/autoProcessComics.py", line 4, in <module>
    import requests
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/share/CACHEDEV1_DATA/scripts/nzbToMedia/libs/requests/compat.py", line 39, in <module>
    import cookielib
ImportError: No module named cookielib

**Comment by clinton-hall** [comment]
Does Transmission use the optware version of Python?
Try exporting PYTHONPATH to point to the Python qpkg site-packages.

Problem is this might cause issues with Transmission. You may need to edit some other Paths and set to call the Python qpkg etc.

**Comment by Jorman** [comment]
Yep, you're right I edited the new script I exported the pythonpath and the lang code and now works, I don't know why the transmission start/stop script don't export nothing
