### ISSUE TITLE
"no module named core" issue Sabnzbd / Sickrage

### ISSUE THREAD

**Issue by NicoLeOca** [clinton-hall/nzbToMedia#833]
Hi,

I use Sickrage for some time and I got to move from autoprocesstv to nzbtomedia.
Quite happy with it as you seem to be working hard improving it everyday.

However I got an issue here:
           Traceback (most recent call last):
  File "/usr/local/sickbeard-custom/var/SickBeard/contrib/nzbToMedia/nzbToSickBeard.py", line 249, in <module>
    import nzbToMedia
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/contrib/nzbToMedia/nzbToMedia.py", line 503, in <module>
    import core
ImportError: No module named core

           

I use sabnzbd installed on synology.
nzbtomedia was installed automatically by sickrage.

Can you help me to get the postprocess working please?

**Comment by NicoLeOca** [comment]
@neoatomic
As you've worked on some issues with the change to Nzbtomedia with Sickrage on Synology, could you help me here please?

**Comment by NicoLeOca** [comment]
Please close it.
It was due to a wrong configuration.
