### ISSUE TITLE
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'"

### ISSUE THREAD

**Issue by nvenayak** [clinton-hall/nzbToMedia#848]
I'm getting the following error upon executing the NZBtoSickBeard.py script, I've installed Python 2.7.

I noticed a similar post previously, and upon trying to install PyWin32 I noticed that it wouldn't install since no valid Python install was found (it was installed automatically with the SickRage installer). I installed a new 64-bit installation in C: and then install PyWin on this installation. I adjust the path to only include this installation (though SickRage may still use it's own).

Here is the full error:
Traceback (most recent call last):
File "C:\SickRage\SickRage\nzbToMedia\nzbToSickBeard.py", line 252, in 
result = nzbToMedia.main(sys.argv, section)
File "C:\SickRage\SickRage\nzbToMedia\nzbToMedia.py", line 626, in main
core.initialize(section)
File "C:\SickRage\SickRage\nzbToMedia\core__init__.py", line 228, in initialize
MYAPP = RunningProcess()
File "C:\SickRage\SickRage\nzbToMedia\core\nzbToMediaUtil.py", line 1129, in init
self.process = WindowsProcess()
File "C:\SickRage\SickRage\nzbToMedia\core\nzbToMediaUtil.py", line 1144, in init
from win32event import CreateMutex
ImportError: No module named win32event
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'" in > ignored

**Comment by nvenayak** [comment]
I'm now getting the following error, not sure if it is related

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\SickRage\SickRage\nzbToMedia>python nzbToSickBeard.py
Traceback (most recent call last):
  File "nzbToSickBeard.py", line 249, in <module>
    import nzbToMedia
  File "C:\SickRage\SickRage\nzbToMedia\nzbToMedia.py", line 503, in <module>
    import core
  File "C:\SickRage\SickRage\nzbToMedia\core\__init__.py", line 28, in <module>
    from core.autoProcess.autoProcessComics import autoProcessComics
  File "C:\SickRage\SickRage\nzbToMedia\core\autoProcess\autoProcessComics.py",
line 6, in <module>
    from core.nzbToMediaUtil import convert_to_ascii, remoteDir, server_respondi
ng
  File "C:\SickRage\SickRage\nzbToMedia\core\nzbToMediaUtil.py", line 19, in <mo
dule>
    from core.linktastic import linktastic
  File "C:\SickRage\SickRage\nzbToMedia\core\linktastic\linktastic.py", line 30,
 in <module>
    info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

**Comment by nvenayak** [comment]
Installed Python 2.7.1 and the problem was solved. I think the subprocess module must have been updated between 2.7 and 2.7.1
