### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Jonnehs** [clinton-hall/nzbToMedia#877]
Logs below

[12:55:22] [INFO]::MAIN: Loading config from [C:\nzbToMedia\autoProcessMedia.cfg]
[12:55:22] [INFO]::MAIN: Checking database structure...
[12:55:22] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[12:55:22] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[12:55:22] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[12:55:23] [DEBUG]::MAIN: InitialSchema upgrade not required
[12:55:23] [DEBUG]::MAIN: Checking if we can use git commands: git version
[12:55:23] [DEBUG]::MAIN: Executing git version with your shell in C:\nzbToMedia
[12:55:23] [DEBUG]::MAIN: git version : returned successful
[12:55:23] [DEBUG]::MAIN: Using: git
[12:55:23] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in C:\nzbToMedia
[12:55:23] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[12:55:23] [INFO]::MAIN: Checking if git needs an update
[12:55:23] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in C:\nzbToMedia
[12:55:23] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[12:55:23] [DEBUG]::MAIN: Executing git fetch origin with your shell in C:\nzbToMedia
[12:55:25] [DEBUG]::MAIN: git fetch origin : returned successful
[12:55:25] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\nzbToMedia
[12:55:25] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[12:55:25] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\nzbToMedia
[12:55:25] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[12:55:25] [DEBUG]::MAIN: cur_commit = 1cd64053b0da1d351bb6af392e1ebb904c6b6ce2 % (newest_commit)= 1cd64053b0da1d351bb6af392e1ebb904c6b6ce2, num_commits_behind = 0, num_commits_ahead = 0
[12:55:25] [INFO]::MAIN: No update needed
[12:55:25] [INFO]::MAIN: nzbToMedia Version:1cd64053b0da1d351bb6af392e1ebb904c6b6ce2 Branch:master (Windows 2012Server)
[12:55:25] [INFO]::MAIN: #########################################################
[12:55:25] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[12:55:25] [INFO]::MAIN: #########################################################
[12:55:25] [DEBUG]::MAIN: Options passed into nzbToMedia: ['C:\nzbToMedia\nzbToCouchPotato.py', 'C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)', 'Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb', 'Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)', '', 'movies', 'alt.binaries.bloaf', '0']
[12:55:25] [INFO]::MAIN: Script triggered from SABnzbd
[12:55:25] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[12:55:25] [WARNING]::MAIN: Data from SABnzbd could not be parsed
[12:55:25] [DEBUG]::MAIN: Adding NZB download info for directory C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673) to database
[12:55:25] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 735911, u'None', u'None', u'Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb', u'C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)']
[12:55:25] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735911, u'None', u'None', u'Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb', u'C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)']
[12:55:25] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
[12:55:25] [DEBUG]::MAIN: Checking for archives to extract in directory: C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)
[12:55:25] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[12:55:27] [INFO]::MAIN: Attemping imdbID lookup for Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb
[12:55:27] [INFO]::MAIN: Searching folder and file names for imdbID ...
[12:55:27] [INFO]::MAIN: Found imdbID [tt2096673]
[12:55:27] [DEBUG]::MAIN: Opening URL: https://localhost:5050/api/59ca2830e9a84a0ebe388dc7e7fe1aa8/media.get with PARAMS: {'id': 'tt2096673'}
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[12:55:28] [ERROR]::MAIN: CouchPotato returned the following non-json data
[12:55:28] [ERROR]::MAIN: 
[12:55:28] [ERROR]::MAIN: <!doctype html>
[12:55:28] [ERROR]::MAIN: <html class="">
[12:55:28] [ERROR]::MAIN: <head>
[12:55:28] [ERROR]::MAIN: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
[12:55:28] [ERROR]::MAIN: <meta name="apple-mobile-web-app-capable" content="yes">
[12:55:28] [ERROR]::MAIN: <meta name="mobile-web-app-capable" content="yes">
[12:55:28] [ERROR]::MAIN: <meta http-equiv="X-UA-Compatible" content="IE=edge" />
[12:55:28] [ERROR]::MAIN: <meta name="robots" content="noindex, nofollow" />
[12:55:28] [ERROR]::MAIN: 
[12:55:28] [ERROR]::MAIN: <link data-url="static/style/combined.min.css?1441054462" rel="stylesheet" href="/static/style/combined.min.css?1441054462" type="text/css">
[12:55:28] [ERROR]::MAIN: 
[12:55:28] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.vendor.min.js?1441054380"></script>
[12:55:28] [ERROR]::MAIN: <script type="text/javascript" src="/static/scripts/combined.base.min.js?1441054380"></script>
[12:55:28] [ERROR]::MAIN: <link href="/static/images/favicon.ico" rel="icon" type="image/x-icon" />
[12:55:28] [ERROR]::MAIN: <link rel="apple-touch-icon" href="/static/images/homescreen.png" />
[12:55:28] [ERROR]::MAIN: 
[12:55:28] [ERROR]::MAIN: <title>CouchPotato</title>
[12:55:28] [ERROR]::MAIN: </head>
[12:55:28] [ERROR]::MAIN: <body class="page login">
[12:55:28] [ERROR]::MAIN: <form action="" method="post">
[12:55:28] [ERROR]::MAIN: <h1>CouchPotato</h1>
[12:55:28] [ERROR]::MAIN: <div class="ctrlHolder"><input class="username" name="username" type="text" placeholder="Username" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[12:55:28] [ERROR]::MAIN: <div class="ctrlHolder"><input class="password" name="password" type="password" placeholder="Password" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" /></div>
[12:55:28] [ERROR]::MAIN: <div class="ctrlHolder">
[12:55:28] [ERROR]::MAIN: <label class="remember_me" title="for 30 days"><input id="remember_me" name="remember_me" type="checkbox" value="1" checked="checked" /> Remember me</label>
[12:55:28] [ERROR]::MAIN: <input class="button" name="submit" type="submit" value="Login" />
[12:55:28] [ERROR]::MAIN: </div>
[12:55:28] [ERROR]::MAIN: </form>
[12:55:28] [ERROR]::MAIN: </body>
[12:55:28] [ERROR]::MAIN: </html>
[12:55:28] [DEBUG]::EXCEPTION: Replacing file name edl2HOqfPldOiNc8Qmq0XXGT36mfsp5PyiVfupQiGUMOlkouuoRe7hl0 with directory name Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)
[12:55:28] [DEBUG]::EXCEPTION: Replacing file name C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)\edl2HOqfPldOiNc8Qmq0XXGT36mfsp5PyiVfupQiGUMOlkouuoRe7hl0.mkv with download name C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).mkv
[12:55:28] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\nzbToMedia\tests\test.mp4
[12:55:29] [INFO]::TRANSCODER: Checking [Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).mkv] for corruption, please stand by ...
[12:55:29] [DEBUG]::MAIN: calling command: C:\ffmpeg\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -show_error C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).mkv
[12:55:29] [INFO]::TRANSCODER: SUCCESS: [Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).mkv] has no corruption.
[12:55:29] [DEBUG]::COUCHPOTATO: Opening URL: https://localhost:5050/api/59ca2830e9a84a0ebe388dc7e7fe1aa8/renamer.scan with PARAMS: {'media_folder': 'C:\Users\Administrator\Documents\Downloads\complete\Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673)'}
[12:55:29] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Inside.Out.2015.720p.BluRay.x264-WiKi.cp(tt2096673).nzb
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
C:\nzbToMedia\libs\requests\packages\urllib3\connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "C:\nzbToMedia\nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\nzbToMedia\nzbToMedia.py", line 712, in main
    download_id='')
  File "C:\nzbToMedia\nzbToMedia.py", line 595, in process
    inputCategory, failureLink)
  File "C:\nzbToMedia\core\autoProcess\autoProcessMovie.py", line 244, in process
    result = r.json()
  File "C:\nzbToMedia\libs\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by clinton-hall** [comment]
Can you try switching to nightly branch?
I believe this error has been fixed, but waiting for this to be confirmed.
