### ISSUE TITLE
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <core.nzbToMediaUtil.WindowsProcess instance at 0x042069B8>> ignored

### ISSUE THREAD

**Issue by Jaerin** [clinton-hall/nzbToMedia#915]
D:\Programs\nzbToMedia>D:\Programs\nzbtomedia\torrenttomedia.py "D:\Torrent\Seeding\tv\The.Great.Holiday.Baking.Show.S01E01.Cookie.Week.720p.HDTV.x264-W4F" "The.Great.Holiday.Baking.Show.S01E01.Cookie.Week.720p.HDTV.x264-W4F" "tv" "134139E55965E77C467D57B270ECFFA6AAEC6EC3"
Traceback (most recent call last):
  File "D:\Programs\nzbtomedia\TorrentToMedia.py", line 345, in <module>
    exit(main(sys.argv))
  File "D:\Programs\nzbtomedia\TorrentToMedia.py", line 260, in main
    core.initialize()
  File "D:\Programs\nzbtomedia\core\__init__.py", line 234, in initialize
    MYAPP = RunningProcess()
  File "D:\Programs\nzbtomedia\core\nzbToMediaUtil.py", line 1140, in __init__
    self.process = WindowsProcess()
  File "D:\Programs\nzbtomedia\core\nzbToMediaUtil.py", line 1155, in __init__
    from win32event import CreateMutex
ImportError: DLL load failed: %1 is not a valid Win32 application.
Exception AttributeError: "WindowsProcess instance has no attribute 'mutex'" in <bound method WindowsProcess.__del__ of <core.nzbToMediaUtil.WindowsProcess instance at 0x042069B8>> ignored

**Comment by Jaerin** [comment]
Figured it out.  Turns out that something must have broken my pywin32 install.

The post-install script for pywin32 failed, which should copy pythoncom26.dll, pythoncomloader26.dll, and pywintypes26.dll, among other things. I ran it by hand and my installation was fixed.

python scripts\pywin32_postinstall.py -install

Ran the command above to rerun the postinstall and it fixed the issues.
