### ISSUE TITLE
Error returned in SABnzbd after update

### ISSUE THREAD

**Issue by WGSLLC** [clinton-hall/nzbToMedia#919]
I'm getting this error when the script runs after download. Any idea?

```
[05:27:10] [INFO]::MAIN: Loading config from [C:\nzbToMedia\autoProcessMedia.cfg]
[05:27:10] [INFO]::MAIN: Checking database structure...
[05:27:10] [INFO]::MAIN: Checking if git needs an update
[05:27:11] [INFO]::MAIN: No update needed
[05:27:11] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Windows 7)
Traceback (most recent call last):
  File "C:\nzbToMedia\nzbToCouchPotato.py", line 249, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "C:\nzbToMedia\nzbToMedia.py", line 626, in main
    core.initialize(section)
  File "C:\nzbToMedia\core\__init__.py", line 348, in initialize
    TORRENT_CHMOD_DIRECTORY = int(CFG["Torrent"]["chmodDirecotry"], 8)
TypeError: int() can't convert non-string with explicit base
```

**Comment by miigotu** [comment]
@clinton-hall `Directory` is mistyped, likely the cause of this bug.
From
```python
TORRENT_CHMOD_DIRECTORY = int(CFG["Torrent"]["chmodDirecotry"], 8)
```
to
```python
TORRENT_CHMOD_DIRECTORY = int(CFG["Torrent"]["chmodDirectory"], 8)
```

**Comment by WGSLLC** [comment]
Hi. Thanks! So do I need to do anything, or just wait until it's pushed and then update?

**Comment by miigotu** [comment]
@WGSLLC for now you could edit your `autoProcessMedia.cfg` and intentionally misspell `chmodDirectory` as `chmodDirecotry`, under the `Torrent` domain, maybe set it to 0. 
That should fix this error until it is updated.

**Comment by WGSLLC** [comment]
Thank you @miigotu. This is a big help as I wanted to impress my bro in from out of town w/ my baller automated wizard machine ;-). Really appreciate the time you guys spend on this script.

**Comment by clinton-hall** [comment]
Hopefully working in latest nightly branch...

**Comment by thesatman** [comment]
Hello Clinton (and all others ...). I'm taking the plunge and moving away from SABnzbd+ and SickRageTV to NZBget and SickRage. Testing my NzbtoMedia scripts. Looks like the typo is still there ?

Clinton: typo !! TORRENT_CHMOD_DIRECTORY = int(CFG["Torrent"] ******>>>["chmodDirecotry"]<<<*********** , 8) . 

I edited the file \nzbToMedia\core\__init__.py and this error is cleared :)

[19:58:27] [DEBUG]::MAIN: cur_commit = 3e4861e87c543a4d2debd8997feb16bda3ef5339 % (newest_commit)= 3e4861e87c543a4d2debd
8997feb16bda3ef5339, num_commits_behind = 0, num_commits_ahead = 0
[19:58:27] [INFO]::MAIN: No update needed
[19:58:27] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Windows 7)
Traceback (most recent call last):
File "C:\nzbToMedia-GIT\nzbToMedia\TorrentToMedia.py", line 345, in <module>
exit(main(sys.argv))
File "C:\nzbToMedia-GIT\nzbToMedia\TorrentToMedia.py", line 260, in main
core.initialize()
File "C:\nzbToMedia-GIT\nzbToMedia\core\__init__.py", line 348, in initialize
TORRENT_CHMOD_DIRECTORY = int(CFG["Torrent"]["chmodDirecotry"], 8)
TypeError: int() can't convert non-string with explicit base

**Comment by miigotu** [comment]
The default value of `CFG["Torrent"]["chmodDirecotry"]` is already an int =P

This should make it work either way:
`TORRENT_CHMOD_DIRECTORY = int(str(CFG["Torrent"]["chmodDirecotry"]), 8)`

**Comment by clinton-hall** [comment]
This was changed in nightly branch 27 days ago.

If nightly is working I can look to merge up.
