### ISSUE TITLE
CouchPotato: Read timed out. (read timeout=60)

### ISSUE THREAD

**Issue by pven** [clinton-hall/nzbToMedia#950]
I am confused: in autoprocess I configured 'wait_for = 5', when I am right that is five minutes. But when I check the logging, it gives a timeout after 60 seconds: 'Read timed out. (read timeout=60)'

autoProcessMedia.cfg (I only paste the couchpotato-part)
```
[CouchPotato]
    #### autoProcessing for Movies
    #### movie - category that gets called for post-processing with CPS
    [[movies]]
        enabled = 1
        apikey = fddbc9999d084e5ead9357a3a80f528f
        host = localhost
        port = 5053
        ssl = 0
        web_root = ""
        Torrent_NoLink = 0
        keep_archive = 1
        method = renamer
        delete_failed = 0
        wait_for = 5
        extract = 1
        minSize = 0
        delete_ignored = 0
        remote_path = 0
        watch_dir = ""
```

The logging:
```
[13:41:46] [INFO]::MAIN: Loading config from [/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/autoProcessMedia.cfg]
 [13:41:46] [INFO]::ENVIRONMENT: LANG: en_US.utf8
 [13:41:46] [INFO]::ENVIRONMENT: TERM: cons25
 [13:41:46] [INFO]::ENVIRONMENT: SHELL: /bin/sh
 [13:41:46] [INFO]::ENVIRONMENT: CLASSPATH: .:/volume1/@appstore/java8/ejdk1.8.0_06/linux_ppc_e500v2/jre/lib
 [13:41:46] [INFO]::ENVIRONMENT: PGDATA: /var/services/pgsql
 [13:41:46] [INFO]::ENVIRONMENT: PWD: /volume1/@appstore/sabnzbd/share/SABnzbd
 [13:41:46] [INFO]::ENVIRONMENT: LOGNAME: sabnzbd
 [13:41:46] [INFO]::ENVIRONMENT: USER: sabnzbd
 [13:41:46] [INFO]::ENVIRONMENT: TERMINFO: /usr/share/terminfo
 [13:41:46] [INFO]::ENVIRONMENT: PATH: /usr/local/sabnzbd/bin:/usr/local/sabnzbd/env/bin:/usr/local/python/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin
 [13:41:46] [INFO]::ENVIRONMENT: HOME: /usr/local/sabnzbd/var
 [13:41:46] [INFO]::ENVIRONMENT: JAVA_HOME: /volume1/@appstore/java8/ejdk1.8.0_06/linux_ppc_e500v2/jre
 [13:41:46] [INFO]::ENVIRONMENT: PAGER: more
 [13:41:46] [INFO]::ENVIRONMENT: LC_ALL: en_US.utf8
 [13:41:46] [INFO]::MAIN: Checking database structure...
 [13:41:46] [DEBUG]::MAIN: Checking Initial Schema database upgrade
 [13:41:46] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
 [13:41:46] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
 [13:41:46] [DEBUG]::MAIN: InitialSchema upgrade not required
 [13:41:46] [DEBUG]::MAIN: Checking if we can use git commands: "/opt/libexec/git-core/git" version
 [13:41:46] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" version with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:47] [DEBUG]::MAIN: "/opt/libexec/git-core/git" version : returned successful
 [13:41:47] [DEBUG]::MAIN: Using: "/opt/libexec/git-core/git"
 [13:41:47] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" symbolic-ref -q HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:47] [DEBUG]::MAIN: "/opt/libexec/git-core/git" symbolic-ref -q HEAD : returned successful
 [13:41:47] [INFO]::MAIN: Checking if git needs an update
 [13:41:47] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" rev-parse HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:47] [DEBUG]::MAIN: "/opt/libexec/git-core/git" rev-parse HEAD : returned successful
 [13:41:47] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" fetch origin with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:50] [DEBUG]::MAIN: "/opt/libexec/git-core/git" fetch origin : returned successful
 [13:41:50] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" rev-parse --verify --quiet "@{upstream}" with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:51] [DEBUG]::MAIN: "/opt/libexec/git-core/git" rev-parse --verify --quiet "@{upstream}" : returned successful
 [13:41:51] [DEBUG]::MAIN: Executing "/opt/libexec/git-core/git" rev-list --left-right "@{upstream}"...HEAD with your shell in /volume1/@appstore/sabnzbd/var/scripts/nzbToMedia
 [13:41:51] [DEBUG]::MAIN: "/opt/libexec/git-core/git" rev-list --left-right "@{upstream}"...HEAD : returned successful
 [13:41:51] [DEBUG]::MAIN: cur_commit = 3e4861e87c543a4d2debd8997feb16bda3ef5339 % (newest_commit)= 3e4861e87c543a4d2debd8997feb16bda3ef5339, num_commits_behind = 0, num_commits_ahead = 0
 [13:41:51] [INFO]::MAIN: No update needed
 [13:41:51] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Linux 2.6.32.12)
 [13:41:52] [INFO]::MAIN: #########################################################
 [13:41:52] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
 [13:41:52] [INFO]::MAIN: #########################################################
 [13:41:52] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py', '/volume1/media/Movies/Nice.Movie.2015.720p.BluRay.x264', 'Nice.Movie.2015.720p.BluRay.x264.nzb', 'Nice.Movie.2015.720p.BluRay.x264', '', 'movies', 'alt.binaries.misc', '0']
 [13:41:52] [INFO]::MAIN: Script triggered from SABnzbd
 [13:41:52] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
 [13:41:54] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/media/Movies/Nice.Movie.2015.720p.BluRay.x264 to database
 [13:41:54] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 735992, u'None', u'None', u'Nice.Movie.2015.720p.BluRay.x264.nzb', u'/volume1/media/Movies/Nice.Movie.2015.720p.BluRay.x264']
 [13:41:54] [DB]::MAIN: nzbtomedia.db: INSERT OR IGNORE INTO downloads (status, client_agent, last_update, input_id, input_hash, input_name, input_directory) VALUES (?, ?, ?, ?, ?, ?, ?) with args [0, u'sabnzbd', 735992, u'None', u'None', u'Nice.Movie.2015.720p.BluRay.x264.nzb', u'/volume1/media/Movies/Nice.Movie.2015.720p.BluRay.x264']
 [13:41:55] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
 [13:41:55] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/media/Movies/Nice.Movie.2015.720p.BluRay.x264
 [13:41:55] [INFO]::MAIN: Calling CouchPotato:movies to post-process:Nice.Movie.2015.720p.BluRay.x264.nzb
 [13:41:57] [INFO]::MAIN: Attemping imdbID lookup for Nice.Movie.2015.720p.BluRay.x264.nzb
 [13:41:57] [INFO]::MAIN: Searching folder and file names for imdbID ...
 [13:41:57] [INFO]::MAIN: Searching IMDB for imdbID ...
 [13:42:08] [DEBUG]::MAIN: Opening URL: http://www.omdbapi.com
 [13:42:08] [WARNING]::MAIN: Unable to find a imdbID for Nice.Movie.2015.720p.BluRay.x264.nzb
 [13:42:08] [DEBUG]::MAIN: Opening URL: http://localhost:5053/api/fddbc9999d084e5ead9357a3a80f528f/media.list with PARAMS: {}
 Traceback (most recent call last):
   File "/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 796, in <module>
     exit(main(sys.argv))
   File "/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 712, in main
     download_id='')
   File "/usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py", line 595, in process
     inputCategory, failureLink)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 138, in process
     release = self.get_release(baseURL, imdbid, download_id)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 30, in get_release
     r = requests.get(url, params=params, verify=False, timeout=(30, 60))
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/libs/requests/api.py", line 69, in get
     return request('get', url, params=params, **kwargs)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/libs/requests/api.py", line 50, in request
     response = session.request(method=method, url=url, **kwargs)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/libs/requests/sessions.py", line 469, in request
     resp = self.send(prep, **send_kwargs)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/libs/requests/sessions.py", line 577, in send
     r = adapter.send(request, **kwargs)
   File "/volume1/@appstore/sabnzbd/var/scripts/nzbToMedia/libs/requests/adapters.py", line 431, in send
     raise ReadTimeout(e, request=request)
 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=5053): Read timed out. (read timeout=60)
 Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x30ae0620>> ignored
```

When I open http://diskstation:5053/api/fddbc9999d084e5ead9357a3a80f528f/media.list manually (on another computer) it gives a reaction (within 20 seconds)

How can I get rid of those errors?

**Comment by clinton-hall** [comment]
the wait_for parameter changes how long (after the URL returns) the script continues to check to see if the movie has changed status in CouchPotato... this does not change the timeout.

The url might return in 20s when not busy, but the issue here is when just finishing download and extraction etc, on a low power system another service (CouchPotato) might take time to respond...
I als0 find SABnzbd, being python, can be CPU intensive and therefore on a slower system I find NZBGet to be more responsive.

if you want to change the timeout:
change
https://github.com/clinton-hall/nzbToMedia/blob/master/core/autoProcess/autoProcessMovie.py#L30

from
`            r = requests.get(url, params=params, verify=False, timeout=(30, 60))`
to
`            r = requests.get(url, params=params, verify=False, timeout=(30, 180))`

**Comment by pven** [comment]
I changed it. Thanks!

Will there be a solution implemented in a future release? I don't like to hack git-code. ;)

**Comment by pven** [comment]
Now I get some kind of timeouts:
```
[13:36:32] [POSTPROCESS]::COUCHPOTATO: SUCCESS: Finished renamer scan for folder /volume1/media/Movies/The Warriors (1979) 1080p mkv
 [13:36:32] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:36:33] [ERROR]::MAIN: no media found for id tt0080120
 [13:37:23] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:37:25] [ERROR]::MAIN: no media found for id tt0080120
 [13:38:15] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:38:17] [ERROR]::MAIN: no media found for id tt0080120
 [13:39:07] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:39:08] [ERROR]::MAIN: no media found for id tt0080120
 [13:39:58] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:39:59] [ERROR]::MAIN: no media found for id tt0080120
 [13:40:49] [POSTPROCESS]::COUCHPOTATO: Checking for status change, please stand by ...
 [13:40:50] [ERROR]::MAIN: no media found for id tt0080120
 [13:41:40] [WARNING]::COUCHPOTATO: The Warriors (1979) 1080p mkv.nzb does not appear to have changed status after 5 minutes, Please check your logs.
 [13:41:41] [ERROR]::MAIN: A problem was reported in the /usr/local/sabnzbd/var/scripts/nzbToMedia/nzbToMedia.py script.
```

I don't really get it. What is going on?

**Comment by clinton-hall** [comment]
Was this movie snatched by CouchPotato?
Did this movie get renamed to your movie folder?
Are there any CouchPotato logs from this same time?

The issue is the script could find any status changes from CP to confirm the rename worked. This doesn't mean there was a problem, just means we can't be sure and need to confirm.

**Comment by pven** [comment]
The movie was not snatched by CP. I guess that explains it all.

Shall we close this issue?
