### ISSUE TITLE
UTF8 error

### ISSUE THREAD

**Issue by mikerohan** [clinton-hall/nzbToMedia#954]
Hi, I'm getting this error when processing files/folders with "special" characters

`/opt/bin/python2.7 /share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py /share/Download/rtorrent/downloads/Elementary - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Español Castellano] Elementary - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Español Castellano]  72A33AF43D37A34100190C92A370388D19738999
[12:14:06] [INFO]::MAIN: Loading config from [/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/autoProcessMedia.cfg]
[12:14:06] [INFO]::ENVIRONMENT: LANG: en_US.UTF-8
[12:14:06] [INFO]::ENVIRONMENT: TERMCAP: /share/CACHEDEV1_DATA/.qpkg/rtorrent/etc/termcap
[12:14:06] [INFO]::ENVIRONMENT: TERM: xterm
[12:14:06] [INFO]::ENVIRONMENT: SHELL: /usr/bin/rtorrent/bin/bash
[12:14:06] [INFO]::ENVIRONMENT: BOOT_IMAGE: /boot/bzImage
[12:14:06] [INFO]::ENVIRONMENT: _DEBUG: 1
[12:14:06] [INFO]::ENVIRONMENT: SHLVL: 13
[12:14:06] [INFO]::ENVIRONMENT: WGETRC: /usr/bin/rtorrent/etc/.wgetrc
[12:14:06] [INFO]::ENVIRONMENT: OPENSSL: /usr/bin/rtorrent/bin/openssl
[12:14:06] [INFO]::ENVIRONMENT: PROGDIR2: /share/CACHEDEV1_DATA/.qpkg/rtorrent
[12:14:06] [INFO]::ENVIRONMENT: PWD: /share/CACHEDEV1_DATA/.qpkg/rtorrent
[12:14:06] [INFO]::ENVIRONMENT: _QUIET: 1
[12:14:06] [INFO]::ENVIRONMENT: LOGNAME: admin
[12:14:06] [INFO]::ENVIRONMENT: USER: admin
[12:14:06] [INFO]::ENVIRONMENT: TERMINFO: /share/CACHEDEV1_DATA/.qpkg/rtorrent/share/terminfo
[12:14:06] [INFO]::ENVIRONMENT: HOME: /usr/bin/rtorrent/root
[12:14:06] [INFO]::ENVIRONMENT: PATH: /usr/bin/rtorrent/bin:/usr/bin/rtorrent/sbin:/usr/bin/rtorrent/usr/bin:/usr/bin/rtorrent/usr/sbin:/usr/bin/rtorrent/perl/bin:/usr/bin/rtorrent/perl/site/bin:/usr/bin/rtorrent/bin:/usr/bin/rtorrent/sbin:/usr/bin/rtorrent/bin:/usr/bin/rtorrent/sbin:/usr/bin/rtorrent/perl/bin:/usr/bin/rtorrent/perl/site/bin:/usr/bin/rtorrent/bin:/usr/bin/rtorrent/sbin:/usr/bin/rtorrent/perl/bin:/usr/bin/rtorrent/perl/site/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/sbin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/perl/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/perl/site/bin:/usr/bin/rtorrent/bin:/usr/bin/rtorrent/sbin:/usr/bin/rtorrent/perl/bin:/usr/bin/rtorrent/perl/site/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/sbin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/perl/bin:/share/CACHEDEV1_DATA/.qpkg/rtorrent/perl/site/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
[12:14:06] [INFO]::ENVIRONMENT: LD_LIBRARY_PATH: /usr/bin/rtorrent/lib
[12:14:06] [INFO]::ENVIRONMENT: _: /usr/bin/rtorrent/bin/rtorrent
[12:14:06] [INFO]::ENVIRONMENT: EDITOR: /bin/vi
[12:14:06] [INFO]::MAIN: Checking database structure...
[12:14:06] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[12:14:06] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[12:14:06] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[12:14:06] [DEBUG]::MAIN: InitialSchema upgrade not required
[12:14:06] [DEBUG]::MAIN: Checking if we can use git commands: git version
[12:14:06] [DEBUG]::MAIN: Executing git version with your shell in /share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia
[12:14:06] [DEBUG]::MAIN: Not using: git
[12:14:06] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
[12:14:06] [DEBUG]::MAIN: No git specified, can't use git commands
[12:14:06] [INFO]::MAIN: Checking if git needs an update
[12:14:06] [DEBUG]::MAIN: No git specified, can't use git commands
[12:14:06] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[12:14:06] [INFO]::MAIN: No update needed
[12:14:06] [INFO]::MAIN: nzbToMedia Version:10.13 Branch:master (Linux 3.12.6)
[12:14:06] [INFO]::MAIN: #########################################################
[12:14:06] [INFO]::MAIN: ## ..::[TorrentToMedia.py]::.. ##
[12:14:06] [INFO]::MAIN: #########################################################
[12:14:06] [DEBUG]::MAIN: Options passed into TorrentToMedia: ['/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py', '/share/Download/rtorrent/downloads/Elementary - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Espa\xc3\xb1ol Castellano]', 'Elementary - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Espa\xc3\xb1ol Castellano]', '', '72A33AF43D37A34100190C92A370388D19738999']
[12:14:06] [DEBUG]::MAIN: Adding TORRENT download info for directory /share/Download/rtorrent/downloads/Elementary - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Español Castellano] to database
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 354, in <module>
    exit(main(sys.argv))
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 291, in main
    result = processTorrent(inputDirectory, inputName, inputCategory, inputHash, inputID, clientAgent)
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 25, in processTorrent
    encoded, inputDirectory1 = CharReplace(inputDirectory)
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/core/nzbToMediaUtil.py", line 394, in CharReplace
    if ((Name[Idx] == '\xC2') | (Name[Idx] == '\xC3')) & ((Name[Idx+1] >= '\xA0') & (Name[Idx+1] <= '\xFF')):
  File "/opt/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x851220>> ignored

--- Error ---`

Any ideas? Thanks

**Comment by mikerohan** [comment]
I've pasted a better formatted log.

**Comment by clinton-hall** [comment]
This isn't a fix for the encoding... but it should prevent these errors and continue. 
I don't know what will happen when trying to handie these paths later...

**Comment by mikerohan** [comment]
New error:

[16:02:57] [DEBUG]::MAIN: Options passed into TorrentToMedia: ['/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py', '/share/Download/rtorrent/downloads/tv/Major Crimes - Temporada 4 [HDTV 720p][Cap.413][AC3 5.1 Espa\xc3\xb1ol Castellano]', 'Major Crimes - Temporada 4 [HDTV 720p][Cap.413][AC3 5.1 Espa\xc3\xb1ol Castellano]', 'tv', '7944A7EEDF62C5724A0094480288DEAB9AAA42F3']
[16:02:57] [DEBUG]::MAIN: Adding TORRENT download info for directory /share/Download/rtorrent/downloads/tv/Major Crimes - Temporada 4 [HDTV 720p][Cap.413][AC3 5.1 Español Castellano] to database
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 357, in <module>
    exit(main(sys.argv))
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 294, in main
    result = processTorrent(inputDirectory, inputName, inputCategory, inputHash, inputID, clientAgent)
  File "/share/CACHEDEV1_DATA/.qpkg/rtorrent/var/nzbToMedia/TorrentToMedia.py", line 31, in processTorrent
    controlValueDict = {"input_directory": unicode(inputDirectory1)}
UnboundLocalError: local variable 'inputDirectory1' referenced before assignment
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x1e2b950>> ignored


but if I change your latest commit to this code it seems to work (just to give you a clue):

        except:
            inputDirectory1 = inputDirectory
            inputName1 = inputName

**Comment by clinton-hall** [comment]
thanks.. I pre-assign these so that we don't revert ant changes that may have been applied before the failure.
i.e. if the failure occurs on inputName, we still want to keep the decoded inputDirectory...

**Comment by mikerohan** [comment]
Great!
That seems to do it. I've imported two episodes from different shows without a failure.

Thanks!
