### ISSUE TITLE
[WARNING]::MAIN: DB error: database is locked

### ISSUE THREAD

**Issue by KingBain** [clinton-hall/nzbToMedia#956]
script doesn't run

- cloned copy of nzbtomedia today
- fresh install
- no changes made to autoProcessMedia.cfg
- manually running nzbToNzbDrone.py fails 
- deleting the nzbtomedia.db and rerunning nzbToNzbDrone.py causes a new empty nzbtomedia.db to be created
- doesn't seem like a permissions issue, account running command has full access to folder and scripts.
- Attached a debug log here [nzbtomedia.log.txt](https://github.com/clinton-hall/nzbToMedia/files/120525/nzbtomedia.log.txt)

Here are the error messages:
`
root@Downloader:/mnt/media/scripts# ./nzbToNzbDrone.py
[01:55:16] [INFO]::MAIN: Loading config from [/mnt/media/scripts/autoProcessMedia.cfg]
[01:55:16] [INFO]::MAIN: Checking database structure...
[01:55:43] [WARNING]::MAIN: DB error: database is locked
[01:55:44] [WARNING]::MAIN: DB error: database is locked
[01:55:45] [WARNING]::MAIN: DB error: database is locked
[01:55:46] [WARNING]::MAIN: DB error: database is locked
[01:55:47] [WARNING]::MAIN: DB error: database is locked
Traceback (most recent call last):
  File "./nzbToNzbDrone.py", line 237, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/mnt/media/scripts/nzbToMedia.py", line 626, in main
    core.initialize(section)
  File "/mnt/media/scripts/core/__init__.py", line 294, in initialize
    nzbToMediaDB.upgradeDatabase(nzbToMediaDB.DBConnection(), mainDB.InitialSchema)
  File "/mnt/media/scripts/core/nzbToMediaDB.py", line 215, in upgradeDatabase
    _processUpgrade(connection, schema)
  File "/mnt/media/scripts/core/nzbToMediaDB.py", line 225, in _processUpgrade
    if not instance.test():
  File "/mnt/media/scripts/core/databases/mainDB.py", line 23, in test
    if self.hasTable("db_version"):
  File "/mnt/media/scripts/core/nzbToMediaDB.py", line 246, in hasTable
    return len(self.connection.action("SELECT 1 FROM sqlite_master WHERE name = ?;", (tableName, )).fetchall()) > 0
AttributeError: 'NoneType' object has no attribute 'fetchall'
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0xb603ab98>> ignored
root@Downloader:/mnt/media/scripts#

`

**Comment by KingBain** [comment]
Output with debug on
`
2016-02-07 02:08:00 INFO    ::MAIN: Loading config from [/mnt/media/scripts/autoProcessMedia.cfg]
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: LESSOPEN: | /usr/bin/lesspipe %s
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: LOGNAME: root
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: USER: root
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: HOME: /root
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: LANG: en_US.UTF-8
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: TERM: linux
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: SHELL: /bin/bash
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: LANGUAGE: en_US.UTF-8
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: SHLVL: 1
2016-02-07 02:08:00 INFO    ::ENVIRONMENT: SUDO_USER: minipc
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: USERNAME: root
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: SUDO_UID: 1000
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: XDG_SESSION_ID: c1
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: _: ./nzbToNzbDrone.py
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: SUDO_COMMAND: /bin/su
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: SUDO_GID: 1000
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: LESSCLOSE: /usr/bin/lesspipe %s %s
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: LC_MESSAGES: POSIX
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: OLDPWD: /root
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: PWD: /mnt/media/scripts
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: MAIL: /var/mail/root
2016-02-07 02:08:01 INFO    ::ENVIRONMENT: LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
2016-02-07 02:08:01 INFO    ::MAIN: Checking database structure...
2016-02-07 02:08:01 DEBUG   ::MAIN: Checking Initial Schema database upgrade
2016-02-07 02:08:01 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2016-02-07 02:08:27 WARNING ::MAIN: DB error: database is locked
2016-02-07 02:08:28 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2016-02-07 02:08:28 WARNING ::MAIN: DB error: database is locked
2016-02-07 02:08:29 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2016-02-07 02:08:29 WARNING ::MAIN: DB error: database is locked
2016-02-07 02:08:30 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2016-02-07 02:08:30 WARNING ::MAIN: DB error: database is locked
2016-02-07 02:08:31 DB      ::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
2016-02-07 02:08:31 WARNING ::MAIN: DB error: database is locked


`

**Comment by KingBain** [comment]
issue was caused by  the scripts folder being mount using NFS without the "nolock" option.

Adding "nolock" to the mount command resolved the issue ...not an issue of nzbtomedia ...more of an issue with nfs and sqlite
