### ISSUE TITLE
NZBget post process script 'terminated with unknown status'

### ISSUE THREAD

**Issue by AndyHazz** [clinton-hall/nzbToMedia#961]
I've been stumped by this for a few days now ... I've seen reports of similar issues but they normally come down to incorrect API keys or mismatched categories which isn't the case here (if it is I'll really kick myself).

I'm using a raspberry pi 2 and running nzbget and couchpotato behind nginx, with SSL configured in nginx reverse proxy. The couchpotato and nzbget port settings are left as default, and SSL = 0 in the settings (as that's all handled by nginx) with a URL bases of /couchpotato and /nzbget. All of the downloaded files are stored on a NAS, mounted on the Pi using nfs. I mention this as although I can't be the only one running it like this, it probably isn't the norm.

I also have sonarr configured in exactly the same way using nzbToNZBDrone and that appears to be post processing without any issues.

Although the movie is marked as pp-failure, if I set CP to force renamer scan every x hours, it will eventually pick the movie up and process it on its own.

Heres a log with debug enabled - post processing seems to go fine until hitting the renamer scan.

```
INFO	2016-02-15 18:05:26	ResetDateTime: Script triggered from NZBGet Version 16.4.
INFO	2016-02-15 18:05:26	ResetDateTime: reseting datetime for file /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.mkv
INFO	2016-02-15 18:05:26	ResetDateTime: reseting datetime for file /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/153597.jpg
INFO	2016-02-15 18:05:26	ResetDateTime: reseting datetime for file /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/153597.srr
INFO	2016-02-15 18:05:26	ResetDateTime: reseting datetime for file /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/cartel.land.2015.rerip.limited.dvdrip.x264-taste.proof.jpg
INFO	2016-02-15 18:05:26	ResetDateTime: reseting datetime for file /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/cartel.land.2015.rerip.limited.dvdrip.x264-taste.sample.mkv
INFO	2016-02-15 18:05:26	Post-process-script GetScripts/ResetDateTime.py for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304) successful
INFO	2016-02-15 18:05:26	Executing post-process-script nzbToMedia/nzbToCouchPotato.py for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [INFO]::MAIN: Checking database structure...
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Checking Initial Schema database upgrade
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: InitialSchema upgrade not required
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Checking if we can use git commands: git version
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Executing git version with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: git version : returned successful
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Using: git
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [INFO]::MAIN: Checking if git needs an update
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
INFO	2016-02-15 18:05:33	nzbToCouchPotato: [18:05:33] [DEBUG]::MAIN: Executing git fetch origin with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: git fetch origin : returned successful
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/nzbget/scripts/nzbToMedia
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [DEBUG]::MAIN: cur_commit = 3e4861e87c543a4d2debd8997feb16bda3ef5339 % (newest_commit)= 3e4861e87c543a4d2debd8997feb16bda3ef5339, num_commits_behind = 0, num_commits_ahead = 0
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [INFO]::MAIN: No update needed
INFO	2016-02-15 18:05:34	nzbToCouchPotato: [18:05:34] [INFO]::MAIN: nzbToMedia Version:3e4861e87c543a4d2debd8997feb16bda3ef5339 Branch:master (Linux 4.1.17-v7+)
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [INFO]::MAIN: #########################################################
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [INFO]::MAIN: #########################################################
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/opt/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py']
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
INFO	2016-02-15 18:05:35	nzbToCouchPotato: [18:05:35] [DEBUG]::MAIN: Adding NZB download info for directory /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304) to database
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [INFO]::MAIN: Auto-detected SECTION:CouchPotato
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [DEBUG]::MAIN: Checking for archives to extract in directory: /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [INFO]::MAIN: Calling CouchPotato:movie to post-process:Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [INFO]::MAIN: Attemping imdbID lookup for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [INFO]::MAIN: Searching folder and file names for imdbID ...
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [INFO]::MAIN: Found imdbID [tt4126304]
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [DEBUG]::MAIN: Opening URL: https://heres.mydomain.net:/couchpotato/api/APIKEYREMOVED/media.get with PARAMS: {'id': 'tt4126304'}
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [DEBUG]::EXCEPTION: Replacing file name 153597 with directory name Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [DEBUG]::EXCEPTION: Replacing file name /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/153597.jpg with download name /home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304).jpg
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [DEBUG]::COUCHPOTATO: Opening URL: https://heres.mydomain.net:/couchpotato/api/APIKEYREMOVED/renamer.scan with PARAMS: {'download_id': u'e7e71c0ac04ebd8d2a87455eab97de0f', 'media_folder': '/home/pi/nfs/temp/nzbget/_couchpotato/Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)', 'downloader': u'NZBGet'}
INFO	2016-02-15 18:05:38	nzbToCouchPotato: [18:05:38] [POSTPROCESS]::COUCHPOTATO: Starting renamer scan for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
INFO	2016-02-15 18:06:39	nzbToCouchPotato: Traceback (most recent call last):
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/nzbToCouchPotato.py", line 249, in <module>
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     result = nzbToMedia.main(sys.argv, section)
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 698, in main
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     failureLink=failureLink)
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 595, in process
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     inputCategory, failureLink)
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/core/autoProcess/autoProcessMovie.py", line 245, in process
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     result = r.json()
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/opt/nzbget/scripts/nzbToMedia/libs/requests/models.py", line 805, in json
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     return complexjson.loads(self.text, **kwargs)
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     return _default_decoder.decode(s)
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
INFO	2016-02-15 18:06:39	nzbToCouchPotato:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
INFO	2016-02-15 18:06:39	nzbToCouchPotato:     raise ValueError("No JSON object could be decoded")
INFO	2016-02-15 18:06:39	nzbToCouchPotato: ValueError: No JSON object could be decoded
ERROR	2016-02-15 18:06:39	Post-process-script nzbToMedia/nzbToCouchPotato.py for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304) failed (terminated with unknown status)
INFO	2016-02-15 18:06:39	Executing post-process-script Logger.py for Cartel.Land.2015.RERiP.LiMiTED.DVDRiP.X264-TASTE.cp(tt4126304)
```

**Comment by AndyHazz** [comment]
p.s. on posting this I spotted the port was missing in the log's API request, as I hadn't entered any thinking nginx will deal with that. I have just tested setting 443 as the port (though I'm sure I've tried this before) and the logs are identical, other than the url above then has the port number in it.

For what it's worth, if I go to 'https://heres.mydomain.net:443/couchpotato/api/APIKEYREMOVED/renamer.scan'  or /media.get in my browser nginx redirects to strip out the port number and I get a 504 Gateway timeout error.

**Comment by AndyHazz** [comment]
I've set fastcgi_read_timeout 900s; in the nginx config. Now I don't get a 504 when manually calling renamer.scan any more, but that still hasn't fixed the script failure ...

The traceback always starts 60 seconds after renamer.scan is called - is there another timeout being set somewhere? Running the scan manually takes 25 seconds so this might have nothing to do with it.

**Comment by AndyHazz** [comment]
All sorted. The way my nfs mounts are setup from the raspberry pi to the NAS means that a rename.scan has to move files from one mount to another, which can take a while.

Putting these lines in the nginx config helped:

proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;

**Comment by clinton-hall** [comment]
thanks for reporting your fix. Sorry I didn't get to see this until you had already solved.
