### ISSUE TITLE
Error while post processing

### ISSUE THREAD

**Issue by iamcagn** [clinton-hall/nzbToMedia#989]
Hello,

Recently after I upgraded my Mac mini to 10.11 and SABnzbd to 1.0.0 I had errors post processing. Originally I had issues where it couldn't find python, I resolved that switching to the OSX branch but now I get an error after the script runs for a moment.

"Exit(1) Exception TypeError: "'NoneType' object is not callable"

Any hints?

**Comment by clinton-hall** [comment]
Can you show the whole log?

**Comment by iamcagn** [comment]
[20:01:30] [INFO]::MAIN: Loading config from [/Users/Mini/nzbToMedia/autoProcessMedia.cfg]
[20:01:30] [INFO]::MAIN: Checking database structure...
[20:01:30] [INFO]::MAIN: Checking if git needs an update
[20:01:31] [INFO]::MAIN: No update needed
[20:01:31] [INFO]::MAIN: nzbToMedia Version:d8b2755aa699d1a88866402037d52988318d45ac Branch:OSX (Darwin 15.3.0)
[20:01:31] [WARNING]::MAIN: Failed to locate 7zip. Transcosing of disk images and extraction of .7z files will not be possible!
[20:01:31] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
[20:01:31] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[20:01:31] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[20:01:31] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[20:01:31] [INFO]::MAIN: #########################################################
[20:01:31] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[20:01:31] [INFO]::MAIN: #########################################################
[20:01:31] [INFO]::MAIN: Script triggered from SABnzbd
Traceback (most recent call last):
  File "/Users/Mini/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/Users/Mini/nzbToMedia/nzbToMedia.py", line 719, in main
    download_id='')
  File "/Users/Mini/nzbToMedia/nzbToMedia.py", line 522, in process
    download_id = get_nzoid(inputName) 
  File "/Users/Mini/nzbToMedia/core/nzbToMediaUtil.py", line 867, in get_nzoid
    r = requests.get(url, params=params, verify=False, timeout=(30, 120))
  File "/Users/Mini/nzbToMedia/libs/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/Mini/nzbToMedia/libs/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/Mini/nzbToMedia/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Mini/nzbToMedia/libs/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Mini/nzbToMedia/libs/requests/adapters.py", line 431, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=120)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x110ccdef0>> ignored

**Comment by iamcagn** [comment]
Well I may be getting further...

After changing the SABnzbd address from http://localhost to https://10.0.0.10 I now get


Traceback (most recent call last):
  File "/Users/Mini/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
    result = nzbToMedia.main(sys.argv, section)
  File "/Users/Mini/nzbToMedia/nzbToMedia.py", line 633, in main
    core.initialize(section)
  File "/Users/Mini/nzbToMedia/core/__init__.py", line 268, in initialize
    if not config.migrate():
  File "/Users/Mini/nzbToMedia/core/nzbToMediaConfig.py", line 233, in migrate
    CFG_OLD.write()
  File "/Users/Mini/nzbToMedia/libs/configobj/configobj.py", line 2123, in write
    'ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1028-1029: ordinal not in range(128)
Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x10518eef0>> ignored

**Comment by iamcagn** [comment]
Actually no, I realise it's trying to rebuild the config due to the IP address... bah.

**Comment by clinton-hall** [comment]
Try Changing the SABnzbd address to `https://localhost` if you are using https. Then also check the port... usually https is on `9090` not `8080`.

**Comment by iamcagn** [comment]
I've swapped the ports to 8080 for https for reasons, but updating the config to https://localhost resolved it. Oddly I've been using https on 8080 for awhile now, not sure what changed in SABnzbd 1.0.0 to break it.

Cheers, resolved.
