### ISSUE TITLE
nzbtosickbeard stops at flatten 

### ISSUE THREAD

**Issue by hassanm12** [clinton-hall/nzbToMedia#991]
```
info	Sat Mar 26 2016 17:06:44	nzbToSickBeard: [17:06:44] [INFO]::MAIN: FLATTEN: Flattening directory: /volume1/Synology/downloads/dst/tv/Happy.Valley.S02E01.720p.HDTV.x264-ORGANiC
info	Sat Mar 26 2016 17:06:43	nzbToSickBeard: [17:06:43] [INFO]::MAIN: SickBeard:tv fork set to custom
info	Sat Mar 26 2016 17:06:43	nzbToSickBeard: [17:06:43] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'force': None, 'delete_on': None, 'process_method': None, 'dir': None}
info	Sat Mar 26 2016 17:06:38	nzbToSickBeard: [17:06:38] [INFO]::MAIN: Attempting to auto-detect tv fork
info	Sat Mar 26 2016 17:06:10	nzbToSickBeard: [17:06:10] [INFO]::MAIN: Calling SickBeard:tv to post-process:Happy.Valley.S02E01.720p.HDTV.x264-ORGANiC
info	Sat Mar 26 2016 17:06:09	nzbToSickBeard: [17:06:09] [INFO]::MAIN: Auto-detected SECTION:SickBeard
info	Sat Mar 26 2016 17:06:07	nzbToSickBeard: [17:06:07] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
info	Sat Mar 26 2016 17:06:07	nzbToSickBeard: [17:06:07] [INFO]::MAIN: #########################################################
info	Sat Mar 26 2016 17:06:07	nzbToSickBeard: [17:06:07] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
info	Sat Mar 26 2016 17:06:07	nzbToSickBeard: [17:06:07] [INFO]::MAIN: #########################################################
info	Sat Mar 26 2016 17:06:06	nzbToSickBeard: [17:06:06] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
info	Sat Mar 26 2016 17:06:06	nzbToSickBeard: [17:06:06] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
info	Sat Mar 26 2016 17:06:02	nzbToSickBeard: [17:06:02] [INFO]::MAIN: nzbToMedia Version:10.13 Branch:master (Linux 2.6.32.12)
info	Sat Mar 26 2016 17:06:02	nzbToSickBeard: [17:06:02] [INFO]::MAIN: No update needed
info	Sat Mar 26 2016 17:06:02	nzbToSickBeard: [17:06:02] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
info	Sat Mar 26 2016 17:06:02	nzbToSickBeard: [17:06:02] [INFO]::MAIN: Checking if git needs an update
info	Sat Mar 26 2016 17:06:00	nzbToSickBeard: [17:06:00] [INFO]::MAIN: Checking database structure...
info	Sat Mar 26 2016 17:05:03	CouchPotato connected to check status
info	Sat Mar 26 2016 17:04:45	Executing post-process-script nzbToMedia/nzbToSickBeard.py for Happy.Valley.S02E01.720p.HDTV.x264-ORGANiC
```

Trying to process this file, after updating my software sickbeard, etc ran into permission issues, I've worked it out again and all the packages, nzbget, sickrage, couchpotato, etc run in the same group and couchpotato is working with nzbget perfectly with nzbtocouchpotato.

However, with sickrage, when it gets to the part in the script to flatten the directories, it just stops. No error messages, or warnings, it just hangs there.

**Comment by hassanm12** [comment]
It took about 30 minutes to go to the next step, which is nzbToSickBeard: [17:40:03] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request

**Comment by clinton-hall** [comment]
It shouldn't take 30 minutes to flatten a directory that should only have 1 video in it.

Can you please cancel post-processing, then enable debug logging
edit autoProcessMedia.cfg
```
[General]
    log_debug =1
```
then try to post process again and check the logs on completion.

**Comment by hassanm12** [comment]
Ok, this was the debug log for another download

`Sun Mar 27 2016 12:49:48	Post-process-script nzbToMedia/nzbToSickBeard.py for Grimm.S05E14.720p.HDTV.x264-AVS failed (terminated with unknown status)
info	Sun Mar 27 2016 12:49:43	nzbToSickBeard: Exception TypeError: "'NoneType' object is not callable" in <bound method PosixProcess.__del__ of <core.nzbToMediaUtil.PosixProcess instance at 0x413f6120>> ignored
info	Sun Mar 27 2016 12:47:36	nzbToSickBeard: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8083): Read timed out. (read timeout=60)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: raise ReadTimeout(e, request=request)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/adapters.py", line 431, in send
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: r = adapter.send(request, **kwargs)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/sessions.py", line 577, in send
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: resp = self.send(prep, **send_kwargs)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/sessions.py", line 469, in request
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: return self.request('POST', url, data=data, json=json, **kwargs)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/libs/requests/sessions.py", line 512, in post
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: s.post(login, data=login_params, stream=True, verify=False, timeout=(30, 60))
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/core/autoProcess/autoProcessTV.py", line 272, in processEpisode
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: download_id, inputCategory, failureLink)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 598, in process
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: failureLink=failureLink)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia/nzbToMedia.py", line 698, in main
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: result = nzbToMedia.main(sys.argv, section)
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: File "/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py", line 252, in <module>
info	Sun Mar 27 2016 12:47:35	nzbToSickBeard: Traceback (most recent call last):
info	Sun Mar 27 2016 12:46:32	nzbToSickBeard: [12:46:32] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8083/home/postprocess/processEpisode with params: {'nzbName': 'Grimm.S05E14.720p.HDTV.x264-AVS', 'quiet': 1, 'process_method': 'move', 'dir': '/volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS'}
info	Sun Mar 27 2016 12:46:32	nzbToSickBeard: [12:46:32] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
info	Sun Mar 27 2016 12:21:47	nzbToSickBeard: [12:21:47] [DEBUG]::SUBTITLES: Attempting to download subtitles for /volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS/Grimm.S05E14.720p.HDTV.x264-AVS.mkv
info	Sun Mar 27 2016 12:21:46	nzbToSickBeard: [12:21:46] [DEBUG]::MAIN: Checking for empty folders in:/volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS
info	Sun Mar 27 2016 12:21:46	nzbToSickBeard: [12:21:46] [INFO]::MAIN: FLATTEN: Flattening directory: /volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS
info	Sun Mar 27 2016 12:21:45	nzbToSickBeard: [12:21:45] [INFO]::MAIN: SickBeard:tv fork set to custom
info	Sun Mar 27 2016 12:21:45	nzbToSickBeard: [12:21:45] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'force': None, 'delete_on': None, 'process_method': None, 'dir': None}
info	Sun Mar 27 2016 12:21:42	nzbToSickBeard: [12:21:42] [INFO]::MAIN: Attempting to auto-detect tv fork
info	Sun Mar 27 2016 12:21:16	nzbToSickBeard: [12:21:16] [INFO]::MAIN: Calling SickBeard:tv to post-process:Grimm.S05E14.720p.HDTV.x264-AVS
info	Sun Mar 27 2016 12:21:16	nzbToSickBeard: [12:21:16] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS
info	Sun Mar 27 2016 12:21:16	nzbToSickBeard: [12:21:16] [INFO]::MAIN: Auto-detected SECTION:SickBeard
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [DEBUG]::MAIN: Adding NZB download info for directory /volume1/Synology/downloads/dst/tv/Grimm.S05E14.720p.HDTV.x264-AVS to database
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [INFO]::MAIN: Script triggered from NZBGet Version 16.4.
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/usr/local/nzbget/share/nzbget/scripts/nzbToMedia/nzbToSickBeard.py']
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [INFO]::MAIN: #########################################################
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [INFO]::MAIN: #########################################################
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
info	Sun Mar 27 2016 12:21:14	nzbToSickBeard: [12:21:14] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [INFO]::MAIN: nzbToMedia Version:10.13 Branch:master (Linux 2.6.32.12)
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [INFO]::MAIN: No update needed
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [DEBUG]::MAIN: No git specified, can't use git commands
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [INFO]::MAIN: Checking if git needs an update
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [DEBUG]::MAIN: No git specified, can't use git commands
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
info	Sun Mar 27 2016 12:21:08	nzbToSickBeard: [12:21:08] [DEBUG]::MAIN: Not using: git
info	Sun Mar 27 2016 12:21:07	nzbToSickBeard: [12:21:07] [DEBUG]::MAIN: Executing git version with your shell in /volume1/@appstore/nzbget/share/nzbget/scripts/nzbToMedia
info	Sun Mar 27 2016 12:21:07	nzbToSickBeard: [12:21:07] [DEBUG]::MAIN: Checking if we can use git commands: git version
info	Sun Mar 27 2016 12:21:07	nzbToSickBeard: [12:21:07] [DEBUG]::MAIN: InitialSchema upgrade not required
info	Sun Mar 27 2016 12:21:07`

it looks like it takes long because sickrage is looking for subtitles for the tv show. 

I'm not sure why this one failed, need to check my sickrage logs
