### ISSUE TITLE
nzbToHeadPhones.py - headphones server returned status 500!

### ISSUE THREAD

**Issue by nickwaring** [clinton-hall/nzbToMedia#996]
Hi,

I'm having problems with post processing & headphones using the nzbToHeadPhones.py script method. Does anyone have any experience of using this and is able to off advice.

Thanks

Nick

```
[18:40:37] [INFO]::MAIN: Loading config from [/volume1/git/nzbToMedia/autoProcessMedia.cfg]
[18:40:37] [INFO]::ENVIRONMENT: LANG: en_US.utf8
[18:40:37] [INFO]::ENVIRONMENT: TERM: xterm
[18:40:37] [INFO]::ENVIRONMENT: SHELL: /bin/ash
[18:40:37] [INFO]::ENVIRONMENT: SHLVL: 1
[18:40:37] [INFO]::ENVIRONMENT: OLDPWD: /volume1/git/nzbToMedia/logs
[18:40:37] [INFO]::ENVIRONMENT: CLASSPATH: .:/volume1/@appstore/java8/ejdk1.8.0_77/linux_i586/jre/lib
[18:40:37] [INFO]::ENVIRONMENT: PGDATA: /var/services/pgsql
[18:40:37] [INFO]::ENVIRONMENT: PWD: /volume1/git/nzbToMedia
[18:40:37] [INFO]::ENVIRONMENT: LOGNAME: root
[18:40:37] [INFO]::ENVIRONMENT: USER: root
[18:40:37] [INFO]::ENVIRONMENT: TERMINFO: /usr/share/terminfo
[18:40:37] [INFO]::ENVIRONMENT: PATH: /opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin:/volume1/@appstore/java8/ejdk1.8.0_77/linux_i586/jre/bin:/usr/local/python3/bin:/usr/local/git/bin:/volume1/@appstore/java8/ejdk1.8.0_77/linux_i586/jre/bin
[18:40:37] [INFO]::ENVIRONMENT: HOME: /root
[18:40:37] [INFO]::ENVIRONMENT: LC_ALL: en_US.utf8
[18:40:37] [INFO]::ENVIRONMENT: JAVA_HOME: /volume1/@appstore/java8/ejdk1.8.0_77/linux_i586/jre
[18:40:37] [INFO]::ENVIRONMENT: PAGER: more
[18:40:37] [INFO]::ENVIRONMENT: _: /bin/python
[18:40:37] [INFO]::MAIN: Checking database structure...
[18:40:37] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[18:40:37] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[18:40:37] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[18:40:37] [DEBUG]::MAIN: InitialSchema upgrade not required
[18:40:37] [DEBUG]::MAIN: Checking if we can use git commands: "/usr/bin/git/bin/git" version
[18:40:37] [DEBUG]::MAIN: Executing "/usr/bin/git/bin/git" version with your shell in /volume1/git/nzbToMedia
[18:40:37] [DEBUG]::MAIN: Not using: "/usr/bin/git/bin/git"
[18:40:37] [DEBUG]::MAIN: Unable to find your git executable - Set git_path in your autoProcessMedia.cfg OR delete your .git folder and run from source to enable updates.
[18:40:37] [DEBUG]::MAIN: No git specified, can't use git commands
[18:40:37] [INFO]::MAIN: Checking if git needs an update
[18:40:37] [DEBUG]::MAIN: No git specified, can't use git commands
[18:40:37] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[18:40:37] [INFO]::MAIN: No update needed
[18:40:37] [INFO]::MAIN: nzbToMedia Version:10.14 Branch:master (Linux 3.10.77)
[18:40:37] [INFO]::MAIN: #########################################################
[18:40:37] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[18:40:37] [INFO]::MAIN: #########################################################
[18:40:37] [DEBUG]::MAIN: Options passed into nzbToMedia: ['nzbToHeadPhones.py']
[18:40:37] [WARNING]::MAIN: Invalid number of arguments received from client, Switching to manual run mode ...
[18:40:37] [INFO]::MAIN: Searching /volume1/download/music for mediafiles to post-process ...
[18:40:37] [INFO]::MAIN: Starting manual run for HeadPhones:music - Folder:/volume1/download/music/VA - Now That's What I Call Disney (iTunes Edition) (2011)
[18:40:37] [INFO]::MAIN: Checking database for download info for VA - Now That's What I Call Disney (iTunes Edition) (2011) ...
[18:40:37] [DB]::DB: Getting download info for VA - Now That's What I Call Disney (iTunes Edition) (2011) from the DB
[18:40:37] [DB]::MAIN: nzbtomedia.db: SELECT * FROM downloads WHERE input_name=? AND status=? with args [u"VA - Now That's What I Call Disney (iTunes Edition) (2011)", 0]
[18:40:37] [INFO]::MAIN: Unable to locate download info for VA - Now That's What I Call Disney (iTunes Edition) (2011), continuing to try and process this release ...
[18:40:37] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
[18:40:37] [DEBUG]::MAIN: Checking for archives to extract in directory: /volume1/download/music/VA - Now That's What I Call Disney (iTunes Edition) (2011)
[18:40:37] [INFO]::MAIN: Calling HeadPhones:music to post-process:VA - Now That's What I Call Disney (iTunes Edition) (2011)
[18:40:37] [WARNING]::EXCEPTION: No name replacement determined for folder
[18:40:37] [DEBUG]::EXCEPTION: Replacing file name /volume1/download/music/VA - Now That's What I Call Disney (iTunes Edition) (2011)/folder.jpg with download name /volume1/download/music/VA - Now That's What I Call Disney (iTunes Edition) (2011)/VA - Now That's What I Call Disney (iTunes Edition) (2011).jpg
[18:40:37] [DEBUG]::MAIN: Attempting to get current status for release:VA - Now That's What I Call Disney (iTunes Edition) (2011)
[18:40:37] [DEBUG]::MAIN: Opening URL: http://192.168.1.2:8084/api with PARAMS: {'cmd': 'getHistory', 'apikey': '4088ebc169f0ac10d101ddebd9ff30a0'}
[18:40:38] [DEBUG]::HEADPHONES: Opening URL: http://192.168.1.2:8084/api with PARAMS: {'cmd': 'forceProcess', 'apikey': '4088ebc169f0ac10d101ddebd9ff30a0', 'dir': '/volume1/download/music'}
[18:41:10] [DEBUG]::HEADPHONES: Result: <!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/volume1/git/headphones/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/git/headphones/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/git/headphones/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/git/headphones/headphones/webserve.py", line 1605, in api
    return a.fetchData()
  File "/volume1/git/headphones/headphones/api.py", line 87, in fetchData
    methodToCall(**self.kwargs)
  File "/volume1/git/headphones/headphones/api.py", line 341, in _forceProcess
    postprocessor.forcePostProcess(self.dir)
  File "/volume1/git/headphones/headphones/postprocessor.py", line 1290, in forcePostProcess
    keep_original_folder=keep_original_folder)
  File "/volume1/git/headphones/headphones/postprocessor.py", line 264, in verify
    keep_original_folder)
  File "/volume1/git/headphones/headphones/postprocessor.py", line 429, in doPostProcessing
    renameFiles(albumpath, downloaded_track_list, release)
  File "/volume1/git/headphones/headphones/postprocessor.py", line 1075, in renameFiles
    year = date[:4]
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>

[18:41:10] [ERROR]::HEADPHONES: Server returned status 500
[18:41:10] [ERROR]::MAIN: A problem was reported when trying to perform a manual run for HeadPhones:music.
[18:41:10] [ERROR]::MAIN: A problem was reported in the nzbToHeadPhones.py script.
HeadPhones: Failed to post-process - Server returned status 500!
```

**Comment by clinton-hall** [comment]
this is an internal error in HeadPhones... you could try asking at HeadPhones what this means. It may be a bug, or it may be that this script has sent invalid data via the api request... but I need to know what before I can change anything.

**Comment by nickwaring** [comment]
thanks... I did suspect this may be the case and have an question posted on the headphones page too. Once I get a response I'll provide an update

**Comment by ikkeenjij36** [comment]
hi there i have the same probs.
I don't think it's a hp problem?
`    [19:31:49] [INFO]::MAIN: Loading config from [/volume1/scripts1/nzbToMedia-master/autoProcessMedia.cfg]
[19:31:49] [INFO]::MAIN: Checking database structure...
[19:31:49] [DB]::MAIN: nzbtomedia.db: SELECT 1 FROM sqlite_master WHERE name = ?; with args ('db_version',)
[19:31:49] [DB]::MAIN: nzbtomedia.db: SELECT db_version FROM db_version
[19:31:49] [INFO]::MAIN: Checking if source needs an update
[19:31:49] [ERROR]::MAIN: Unknown current version number, don't know if we should update or not
[19:31:49] [INFO]::MAIN: nzbToMedia Version:10.14 Branch:master (Linux 3.10.35)
[19:31:49] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[19:31:49] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[19:31:50] [INFO]::MAIN: #########################################################
[19:31:50] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[19:31:50] [INFO]::MAIN: #########################################################
[19:31:50] [INFO]::MAIN: Script triggered from SABnzbd
[19:31:50] [DB]::MAIN: nzbtomedia.db: UPDATE downloads SET status = ?, client_agent = ?, last_update = ?, input_id = ?, input_hash = ?, input_name = ? WHERE input_directory = ? with args [0, u'sabnzbd', 736057, u'SABnzbd_nzo_tQ4noh', u'SABnzbd_nzo_tQ4noh', u'xxxxxxxxxxx-CD-FLAC-2015-NBFLAC.nzb', u'/volume1/downloads/complete/muziek/xxxxxxxxxx-CD-FLAC-2015-NBFLAC']
[19:31:50] [INFO]::MAIN: Auto-detected SECTION:HeadPhones
[19:31:50] [INFO]::MAIN: Calling HeadPhones:muziek to post-process:James Bay-Chaos And The Calm-CD-FLAC-2015-NBFLAC.nzb
[19:31:51] [ERROR]::HEADPHONES: Server returned status 500
[19:31:51] [ERROR]::MAIN: A problem was reported in the /volume1/scripts1/nzbToMedia-master/nzbToMedia.py script.
HeadPhones: Failed to post-process - Server returned status 500!
`
Anyone a solution?
This happened to me after updating.

**Comment by nickwaring** [comment]
Interesting... having looked at my original error I get a similar "Server returned status 500" for my sickrage downloads

**Comment by ikkeenjij36** [comment]
Ok well i am getting this only after updating the nzbtomediamaster folder from github.
Headphones is the only process where it's getting this error,sonarr couchpotato is all going right.

**Comment by ikkeenjij36** [comment]
no one who could please help me with this please?
